import { NextResponse } from "next/server"
import { auth } from "@/lib/auth"
import { prisma } from "@/lib/prisma"
import { createHash } from "crypto"
import { Prisma } from "@/lib/generated/prisma/client"

async function requireAdmin() {
  const session = await auth()
  if (!session?.user?.isAdmin) return null
  return session
}

const MAT = "PO"
const FONTE = "1ª AE — PO — CFO 2025"
const MOD = "1AE"

type Alt = { id: string; texto: string }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const CTX1 = "1º Quesito (1ª AE — PO — CFO 2025) — Dentro do conteúdo ministrado sobre as funcionalidades do Boletim de Ocorrência eletrônico Policial Militar - Geração 2, marque verdadeiro (V) ou falso (F) para as assertivas."
const CTX2 = "2º Quesito (1ª AE — PO — CFO 2025) — No que diz respeito às imunidades, assinale com (V) as sentenças verdadeiras e com (F) as sentenças falsas."
const CTX3 = "3º Quesito (1ª AE — PO — CFO 2025) — Considerando as instruções ministradas sobre GRUPOS VULNERÁVEIS, marque (V) verdadeiro ou (F) falso."

const QS = [
  // 1º QUESITO — BOEPM Geração 2
  { tipo: "certo_errado", contexto: CTX1, enunciado: "O aplicativo BOEPM Geração 2 foi desenvolvido exclusivamente por empresas privadas, sem a participação de policiais da ativa.", gabarito: "errado", explicacao: "Errado. O aplicativo foi desenvolvido pela GTI/SDS, com o processo conduzido por policiais da ativa e execução por empresa privada de software." },
  { tipo: "certo_errado", contexto: CTX1, enunciado: "O aplicativo BOEPM Geração 2, em relação ao boletim de papel, tem a vantagem da velocidade e da integração ao sistema.", gabarito: "certo", explicacao: "Correto. A geração eletrônica proporciona velocidade, integração direta ao sistema e padronização das informações." },
  { tipo: "certo_errado", contexto: CTX1, enunciado: "O aplicativo BOEPM Geração 2 requer smartphones de alta tecnologia para funcionar.", gabarito: "errado", explicacao: "Errado. O aplicativo foi concebido para funcionar em smartphones comuns, sem dependência de equipamentos especiais." },
  { tipo: "certo_errado", contexto: CTX1, enunciado: "O login no BOEPM Geração 2 não é feito com usuário e senha do Expresso/SEI, sendo necessário um cadastramento específico realizado pela empresa privada desenvolvedora do aplicativo.", gabarito: "errado", explicacao: "Errado. O acesso é feito com usuário e senha do Expresso/SEI, aproveitando as credenciais já conhecidas." },
  { tipo: "certo_errado", contexto: CTX1, enunciado: "O BOEPM Geração 2 simplifica o acesso utilizando informações de fácil memorização.", gabarito: "certo", explicacao: "Correto. O login com credenciais do Expresso/SEI simplifica o acesso e elimina necessidade de novo cadastro." },

  // 2º QUESITO — Imunidades
  { tipo: "certo_errado", contexto: CTX2, enunciado: "Nas ocorrências com autoridades diplomáticas na condição de acusados, a Polícia Militar não poderá prendê-los, ainda que em flagrante delito, exceto nos crimes hediondos.", gabarito: "errado", explicacao: "Errado. Diplomatas gozam de imunidade absoluta (Convenção de Viena); a PM não pode prendê-los nem em flagrante de crime hediondo." },
  { tipo: "certo_errado", contexto: CTX2, enunciado: "Deputados e Senadores gozam de imunidade absoluta decorrente do exercício do cargo eletivo, e a prisão só poderá ocorrer em flagrante de crime inafiançável, como racismo, tortura, tráfico de drogas, terrorismo e crimes hediondos.", gabarito: "errado", explicacao: "Errado. A imunidade parlamentar NÃO é absoluta — é formal (de prisão). O enunciado erra ao chamá-la de 'absoluta'." },
  { tipo: "certo_errado", contexto: CTX2, enunciado: "Magistrados e membros do Ministério Público só poderão ser presos no caso de flagrantes de crime inafiançável, e devem ser conduzidos para Delegacias Especializadas, sendo vedada a apresentação em Delegacia Comum.", gabarito: "errado", explicacao: "Errado. Membros do MP devem ser apresentados ao PGJ; magistrados, ao Presidente do Tribunal. Não há vedação absoluta à delegacia comum." },
  { tipo: "certo_errado", contexto: CTX2, enunciado: "Oficiais das Forças Armadas, Polícias e Bombeiros Militares, bem como Delegados de Polícia Federal e Civil gozam da Imunidade Relativa.", gabarito: "errado", explicacao: "Errado. Esses profissionais não gozam de 'imunidade relativa' — possuem prerrogativas de foro previstas em seus estatutos." },
  { tipo: "certo_errado", contexto: CTX2, enunciado: "O repasse de informações para a Imprensa, acerca de ocorrências que envolvam autoridades, deverá ser centralizado na Assessoria de Comunicação Social da Corporação.", gabarito: "certo", explicacao: "Correto. O POP nº 0020 determina que informações à imprensa sejam centralizadas na Assessoria de Comunicação Social (5ª EMG)." },

  // 3º QUESITO — Grupos Vulneráveis
  { tipo: "certo_errado", contexto: CTX3, enunciado: "A conduta descrita como crime ou contravenção penal não é considerada ato infracional quando praticada por criança ou adolescente.", gabarito: "errado", explicacao: "Errado. O ECA (art. 103) estabelece que a conduta descrita como crime ou contravenção penal, praticada por criança ou adolescente, É ato infracional." },
  { tipo: "certo_errado", contexto: CTX3, enunciado: "Pessoas com deficiência devem ser abordadas de forma rápida e direta, sem considerar suas limitações físicas e cognitivas.", gabarito: "errado", explicacao: "Errado. A abordagem exige sensibilidade e adaptação às limitações físicas e cognitivas, com comunicação acessível e tempo adequado de resposta." },
  { tipo: "certo_errado", contexto: CTX3, enunciado: "O atendimento de ocorrências com idosos deve ser prioritário, sendo que, em alguns casos, o mais importante é garantir a segurança do policiamento em detrimento das necessidades específicas dos idosos.", gabarito: "errado", explicacao: "Errado. O atendimento deve considerar as necessidades e limitações do idoso — a segurança do policiamento não se sobrepõe à proteção do vulnerável." },
  { tipo: "certo_errado", contexto: CTX3, enunciado: "A escuta ativa e respeitosa é um dos pilares do atendimento a ocorrências envolvendo mulheres. Confirmada a situação de violência, o protocolo determina que a vítima e o agressor sejam conduzidos à Delegacia da Mulher, ou, na ausência desta, à delegacia comum mais próxima.", gabarito: "certo", explicacao: "Correto. Escuta ativa e empatia são pilares do atendimento (POP 0016). O protocolo determina encaminhamento à Delegacia da Mulher ou à mais próxima." },
  { tipo: "certo_errado", contexto: CTX3, enunciado: "Para os homens transexuais, a recomendação é para que a abordagem seja realizada por policiais femininas. Caso o homem transexual manifeste explicitamente sua identidade de gênero, solicitando ser abordado por policial masculino, essa preferência deve ser atendida em sua plenitude.", gabarito: "errado", explicacao: "Errado. O POP 005 orienta que a busca em homem transexual seja realizada por policial masculino. A premissa do enunciado (indicar PM feminina como padrão) é incorreta." },

  // 4º QUESITO — BOEPM múltipla
  { tipo: "multipla", contexto: "4º Quesito (1ª AE — PO — CFO 2025) — No que concerne ao Preenchimento do BOEPM, assinale a única alternativa VERDADEIRA.", enunciado: "Assinale a única alternativa VERDADEIRA sobre o preenchimento do BOEPM.", alternativas: A("O BOEPM é um documento importante para registrar apenas a ocorrência de crimes.", "Em face de sua fragilidade, e por conter apenas a versão do Policial Militar, o BOEPM não pode ser considerado como prova em processo judicial.", "Considerando que para cada natureza demanda o preenchimento de um BOEPM, a nova versão do aplicativo permite vincular vários BOEPM para uma mesma ocorrência.", "Não será possível a geração de um novo BOEPM no aplicativo caso haja BOEPM ainda com preenchimento em andamento.", "O BOEPM foi totalmente desenvolvido por Policiais Militares da Ativa, integrantes da Diretoria de Tecnologia e Inovação da Corporação."), gabarito: "D", explicacao: "D é a única verdadeira. O sistema impede novo BO enquanto houver um em andamento. (A) Errado: registra qualquer ocorrência. (B) Errado: pode ser prova judicial. (C) Errado: vincula naturezas, não múltiplos BOEPM. (E) Errado: desenvolvido pela GTI/SDS com empresa privada." },

  // 5º QUESITO — Sinistro de trânsito múltipla INCORRETA
  { tipo: "multipla", contexto: "5º Quesito (1ª AE — PO — CFO 2025) — Dentro do conteúdo ministrado em relação à preservação de local de sinistro de trânsito com vítima ou sem vítima, foi verificado que é essencial a preservação da vida e da integridade física, bem como a fluidez viária. Face às providências a serem adotadas em local de acidente de trânsito, marque a alternativa INCORRETA.", enunciado: "Assinale a alternativa INCORRETA sobre as providências em local de acidente de trânsito.", alternativas: A("A legislação autoriza a remoção de veículos do leito da via pública quando sua permanência comprometer o tráfego, independentemente de exame pericial já ter sido realizado.", "O uso de luvas e materiais descartáveis, por parte dos policiais responsáveis pelo atendimento da ocorrência, não é obrigatório.", "A identificação de produtos perigosos nos veículos envolvidos em acidentes de trânsito é feita por meio dos painéis de segurança e rótulos de risco.", "A confecção do Boletim de Ocorrência de Acidente de Trânsito (BOAT) é exclusiva dos agentes da autoridade de trânsito.", "Caso a viatura envolvida seja de patrimônio público ou locada, aplica-se a Portaria Normativa nº 018/2013 do Comando Geral da PMPE, que determina a abertura de processo sumário ou inquérito técnico, conforme o caso."), gabarito: "B", explicacao: "B é a incorreta. O uso de luvas e materiais descartáveis É obrigatório. (A) Correto: Lei 5.970/73 autoriza remoção. (C) Correto: painéis e rótulos identificam produtos perigosos. (D) Correto: BOAT é da autoridade de trânsito. (E) Correto: Portaria 018/2013 aplica-se a viaturas da corporação." },

  // 6º QUESITO — Morte de integrante múltipla ERRADA
  { tipo: "multipla", contexto: "6º Quesito (1ª AE — PO — CFO 2025) — Considere as afirmações abaixo, tendo em vista a morte de um integrante da Corporação numa ocorrência, e assinale a única alternativa ERRADA.", enunciado: "Assinale a única alternativa ERRADA sobre os procedimentos em ocorrência de morte de policial militar.", alternativas: A("Sendo um Policial Militar de uma Unidade Especializada, o Diretor Integrado Especializado, via de regra, designará um Oficial da mesma Unidade da vítima para acompanhar as diligências na área do Batalhão onde se deram os fatos.", "Caso os fatos tenham ocorrido na Capital ou RMR, o Diretor de Planejamento Operacional determinará a instalação de um Gabinete de Controle de Crise (GCC/DPO).", "Caso o Oficial responsável pelas ações no terreno identifique, visualmente, a participação de Policiais Militares de folga nas diligências, deverá imediatamente identificá-los formalmente e relacionar seus dados, buscando manter o total controle do efetivo participante, conforme POP específico.", "A instalação do GCC será sempre de responsabilidade do Batalhão responsável pela área dos fatos.", "Cabe ao Despachante da área, onde se deram os fatos, permitir que apenas as viaturas e guarnições autorizadas pelo COPOM se desloquem ou permaneçam no local da ocorrência."), gabarito: "D", explicacao: "D é a errada. A instalação do GCC/DPO é determinada pelo DPO — não é responsabilidade exclusiva do Batalhão da área." },

  // 7º QUESITO — Isolamento múltipla VERDADEIRA
  { tipo: "multipla", contexto: "7º Quesito (1ª AE — PO — CFO 2025) — Quanto ao Isolamento de Locais de Crime, marque a única afirmativa VERDADEIRA.", enunciado: "Assinale a única afirmativa VERDADEIRA sobre o isolamento de locais de crime.", alternativas: A("Nada pode ser removido ou retirado do local de crime, exceto após o registro do Policial Militar encarregado do isolamento.", "Em um isolamento de local de crime, a equipe policial deve delimitar a área, controlar o acesso, estabelecer a vigilância e realizar o registro das ações.", "Em acidentes de trânsito com vítima, nada substitui o BOAT.", "Os materiais destinados ao isolamento de locais de crime são específicos, como cones, cavaletes e fitas, sendo descartada a utilização de outros meios de improviso.", "No caso de acidentes de trânsito, ainda que com vítimas, o acordo entre os condutores isenta o policiamento de efetuar o encaminhamento para a Delegacia."), gabarito: "B", explicacao: "B é a verdadeira. Isolar exige delimitar, controlar acesso, vigiar e registrar. (A) Errado: remoções para socorro são permitidas com registro. (C) Errado: BOAT não é obrigatório em todos os casos. (D) Errado: materiais de improviso são admitidos. (E) Errado: acordo entre condutores não isenta o registro." },

  // 8º QUESITO — Dissertativa
  { tipo: "dissertativa", contexto: "8º Quesito (1ª AE — PO — CFO 2025) — Dissertativa (mínimo 10 e máximo 15 linhas).", enunciado: "Discorra sobre os procedimentos básicos que uma guarnição deve adotar em local de um crime de homicídio.", modelo: { estrutura: "Segurança → socorro → isolamento → preservação → comunicação → registro.", criterios: ["Garantir segurança da equipe antes de adentrar", "Socorro às vítimas com sinais vitais (SAMU)", "Isolar e delimitar a área controlando acesso", "Preservar vestígios sem tocar ou mover", "Comunicar ao COPOM/CIODS, acionar perícia e DPC", "Registrar alterações com horário e justificativa", "Confeccionar BOEPM com informações precisas"], resposta: "Ao chegar ao local, a guarnição garante sua segurança verificando riscos residuais. Se houver vítima com sinais vitais, aciona o SAMU. Isola a área com fitas ou viaturas, controlando o acesso de curiosos e imprensa. Preserva vestígios (posição de corpos, armas, cápsulas), evitando tocar ou mover qualquer evidência. Toda alteração para socorro é registrada com horário e justificativa. Comunica ao COPOM/CIODS, aciona a perícia criminal e a Polícia Civil. Identifica testemunhas mantendo-as no local até a chegada da investigação. Ao final, preenche o BOEPM com informações precisas, imparciais e detalhadas." } },

  // 9º QUESITO — Dissertativa LGBTQIAPN+
  { tipo: "dissertativa", contexto: "9º Quesito (1ª AE — PO — CFO 2025) — A abordagem a grupos vulneráveis requer sensibilidade, respeito e conhecimento das necessidades específicas de cada grupo. Para o caso das Pessoas LGBTQIAPN+, a Polícia Militar de Pernambuco editou e publicou o Procedimento Operacional Padrão (POP) de n.º 005. Estando você no comando do Policiamento Externo do Classic Hall, onde ocorre o Show de um artista nacional, na condição de Oficial de Operações do 1º BPM, dispondo de Patrulhas integradas por Policiais Militares Masculinos e Femininos, informe quais seriam as medidas a serem adotadas durante a realização de buscas pessoais (não minuciosa), baseadas em fundadas suspeitas, nas seguintes situações: a) Pessoa identificada como GAY; b) Pessoa identificada como TRAVESTI que se apresenta como mulher de nome social Sônia; c) Transexual que se utiliza de vestes masculinas, mas exige ser abordada por uma policial feminina; d) Pessoa identificada como TRAVESTI que se apresenta como mulher de nome social Sônia, contudo, todas as Policiais Femininas presentes alegam constrangimento e não desejam efetuar a abordagem pessoal. (Mínimo 07 e máximo 15 linhas.)", enunciado: "Com base no POP nº 005 da PMPE, discorra sobre os procedimentos de busca pessoal (não minuciosa) nas quatro situações descritas envolvendo pessoas LGBTQIAPN+.", modelo: { estrutura: "POP 005 → a) gay → b) travesti nome social → c) transexual masc. pedindo PM feminina → d) sem PM feminina disponível.", criterios: ["a) Gay: busca por PM do mesmo sexo biológico (masculino), com respeito", "b) Travesti nome social Sônia: busca por PM feminina, respeitando identidade de gênero", "c) Transexual masc. que solicita PM feminina: preferência atendida — PM feminina realiza a busca", "d) Sem PM feminina: PM masculino acompanhado de testemunha civil, com registro no BOEPM"], resposta: "O POP 005 orienta abordagem com respeito, sigilo e uso do nome social. a) GAY: busca por PM masculino (mesmo sexo biológico), postura respeitosa. b) TRAVESTI (Sônia): busca por PM feminina, respeitando identidade de gênero e nome social. c) Transexual masculino que solicita PM feminina: preferência atendida, PM feminina realiza a busca. d) TRAVESTI (Sônia) sem PM feminina disponível: PM masculino realiza a busca acompanhado de testemunha civil, registrando no BOEPM para garantir rastreabilidade." } },

  // 10º QUESITO — Dissertativa Violência doméstica
  { tipo: "dissertativa", contexto: "10º Quesito (1ª AE — PO — CFO 2025) — Durante o evento Galo da Madrugada, ocorrido no dia 14 de fevereiro de 2026, por volta das 14h00, o efetivo do BPChoque, escalado na Operação Galo da Madrugada, foi acionado por populares que informaram sobre uma agressão acontecendo em uma embarcação atracada em frente à plataforma 3, na Rua do Sol. O imputado, Sr. R.P.O.F., mordeu e agrediu fisicamente a sua esposa, a Sra. V.M.O., deixando-a com uma lesão no lábio inferior e no supercílio esquerdo. A Sra. V.M.O. não quis prestar queixa-crime formal contra o seu marido.", enunciado: "Discorra sobre as diretrizes para o atendimento da ocorrência descrita, envolvendo mulher em situação de vulnerabilidade. Aborde as providências do policiamento, a rede de apoio à mulher, a escuta ativa e a ação penal relativa à ocorrência. (Mínimo 10 e máximo 15 linhas.)", modelo: { estrutura: "Atendimento humanizado → providências imediatas → ação penal incondicionada → rede de apoio.", criterios: ["Escuta ativa, empatia, sem revitimização", "Registro BOEPM com descrição das lesões", "Prisão em flagrante do agressor (lesão corporal doméstica)", "Ação penal pública incondicionada — vítima não pode impedir (Lei 11.340/2006)", "Encaminhamento à Delegacia da Mulher", "Medidas protetivas de urgência", "Rede de apoio: CREAS, CRAM, abrigos, saúde"], resposta: "O atendimento deve ser conduzido com escuta ativa, empatia e respeito, sem culpabilizar a vítima. As lesões são registradas no BOEPM com detalhes. A vítima é encaminhada para atendimento médico. O agressor deve ser preso em flagrante — configura lesão corporal doméstica (art. 129, §9º CP). A vontade da vítima de não representar NÃO impede a prisão nem a ação penal, pois trata-se de ação penal pública incondicionada (Lei Maria da Penha). O efetivo conduz o agressor à Delegacia da Mulher e informa à vítima sobre medidas protetivas de urgência. A PMPE aciona a rede de apoio: CREAS, CRAM, abrigos e serviços de saúde." } },
]

export async function POST() {
  const s = await requireAdmin()
  if (!s) return NextResponse.json({ error: "Não autorizado" }, { status: 403 })

  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) return NextResponse.json({ error: `Disciplina ${MAT} não existe` }, { status: 400 })

  let criadas = 0, atualizadas = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${MOD}|${q.enunciado}`).digest("hex")
    const base = {
      materia: MAT,
      modulo: MOD,
      tipo: q.tipo,
      contexto: q.contexto ?? null,
      enunciado: q.enunciado,
      alternativas: q.tipo === "multipla" ? (q as { alternativas: Alt[] }).alternativas : [],
      gabarito: q.tipo !== "dissertativa" ? (q as { gabarito: string }).gabarito : "",
      explicacao: q.tipo !== "dissertativa" ? (q as { explicacao: string }).explicacao : null,
      modelo: q.tipo === "dissertativa" ? (q as { modelo: object }).modelo : Prisma.DbNull,
      fonte: FONTE,
      hash,
    }
    const existing = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    if (existing) atualizadas++; else criadas++
  }

  return NextResponse.json({ ok: true, criadas, atualizadas, total: QS.length })
}
