// Títulos dos módulos do banco de questões, por matéria.
// O campo `modulo` da tabela Questao guarda só o identificador ("1", "SIM",
// "AE1-2025"); o título fica aqui para situar o aluno na tela de /questoes.
// Módulo sem título cai no rótulo genérico ("Módulo 4").

export const TITULOS_MODULO: Record<string, Record<string, string>> = {
  IG: {
    "1": "Continência individual e sinais de respeito",
    "2": "Apresentação individual e continência da tropa",
    "3": "Culto à Bandeira e hasteamento",
    "4": "Bandeiras-insígnias e honras de recepção/despedida",
    "5": "Guarda-Bandeira",
    "6": "Compromisso e promoção ao primeiro posto",
    "7": "Solenidades e passagem de comando",
    "8": "Honras fúnebres e condecorações",
    "9": "Atribuições do Comandante de OME",
    "10": "Atribuições do Subcomandante de OME",
    "11": "Atribuições do Ajudante-Secretário",
    "12": "Atribuições do P1",
    "13": "Atribuições do P3",
    "14": "Atribuições do SEI (Ensino e Instrução)",
    "15": "Atribuições do P4",
    "16": "Do Boletim Interno (BI)",
    "17": "Trabalhos diários, instrução e faxinas",
    "18": "Do Adjunto de Comando",
    "19": "Manual Básico de Comunicação Social da PMPE",
    "20": "Do Expediente",
    "21": "Das Escalas de Serviço",
    "22": "Do Serviço Interno",
    "23": "Do Oficial de Dia (de Operações)",
    "24": "Do Adjunto ao Oficial de Dia (Graduado de Operações)",
    "25": "Do Serviço de Guarda do Quartel",
    "26": "Do Comandante da Guarda do Quartel",
    "27": "Do Plantão",
    "28": "Das Formaturas",
    "AE1-2025": "Prova antiga — 1ª AE de IG (11/07/2025)",
    "AE2-2025": "Prova antiga — 2ª AE de Instrução Geral (25/08/2025)",
  },
  APHT: {
    "1": "Histórico do APH-Tático, normas e legislações",
    "2": "Atendimento sob confronto armado (1ª fase)",
    "3": "M.A.R.C.H. — letra M (hemorragias)",
    "4": "M.A.R.C.H. — letras A e R (vias aéreas e respiração)",
    "5": "M.A.R.C.H. — letras C e H (choque e hipotermia)",
    "6": "Atendimento em evacuação tática (3ª fase)",
    SIM: "Simulado — formato da prova (10,0 pontos)",
  },
  GC: {
    "1": "Gestão de conflitos e de crises",
    "2": "Histórico da doutrina de gerenciamento de crises",
    "3": "Incidentes com reféns e modalidades de ocorrências",
    "4": "Incidentes estáticos e dinâmicos",
    "5": "Conceito de crise, características e binômio",
    "6": "Aspectos legais, objetivos e critérios de ação",
    "7": "Inteligência e fases do gerenciamento",
    "8": "Tipologia dos CEC, perímetros e posto de comando",
    "9": "Primeira intervenção em crises policiais",
    "10": "Alternativas táticas no gerenciamento estático",
    "11": "Nova ambiência: sistema dinâmico e agressor ativo",
    "12": "Decreto nº 33.782/2009 (GCRISES)",
    "13": "POP nº 0054 (agressor ativo em ataque massivo)",
    SIM: "Simulado — formato da prova (10,0 pontos)",
  },
  POE: {
    "1": "Conceitos básicos do policiamento ostensivo",
    "2": "Características do policiamento ostensivo",
    "3": "Princípios do policiamento ostensivo",
    "4": "Variáveis do policiamento ostensivo",
    "5": "Órgãos do sistema de segurança pública",
    "6": "Desdobramento da PMPE: DPO e diretorias territoriais",
    "7": "DIRESP, DASDH e programas institucionais",
    "8": "3ª EMG: Estado-Maior Geral e suas seções",
    "9": "Planejamento operacional na PMPE",
    "10": "Documentos de planejamento da PMPE",
    "11": "Ciclo PDCA",
    "12": "Juntos pela Segurança e Gestão por Resultados",
    SIM: "Simulado — formato da prova (10,0 pontos)",
  },
  AP: {
    "1": "Fundamentação legal da busca pessoal (CPP)",
    "2": "Fundada suspeita e Tribunais Superiores",
    "3": "Grupos vulneráveis",
    "4": "Conceito e finalidades da abordagem policial",
    "5": "Princípios da abordagem policial",
    "6": "Processos da abordagem: planejamento e execução",
    "7": "Posturas de segurança",
    "8": "Tipos de busca",
    "9": "Posições de busca pessoal",
    "10": "Sequência da abordagem a pessoas",
    "11": "Busca veicular e busca domiciliar",
    "12": "Técnicas de algemamento",
    "13": "Abordagem a veículos e motocicletas",
    "14": "Ponto de bloqueio, ônibus e veículos de carga",
    "15": "Abordagem à edificação",
    SIM: "Simulado — formato da prova (10,0 pontos)",
  },
  INTSISP: {
    "1": "Fundamentos históricos da inteligência no Brasil",
    "2": "Sistema Brasileiro de Inteligência (SISBIN / ABIN)",
    "3": "Sistema Estadual de Inteligência (SEINSP / CIIDS / SIPOM)",
    "4": "Fundamentos doutrinários e ética",
    "5": "Princípios e valores",
    "6": "Ramo Inteligência e classificações",
    "7": "Ciclo de Inteligência",
    "8": "Contrainteligência",
    "9": "Elemento de análise: dado × informação × conhecimento",
    "10": "Ciclo de análise, MPC e técnicas de apoio",
    "11": "POI e Inteligência × Investigação policial",
    SIM: "Simulado — formato da prova (10,0 pontos)",
  },
  GPGA: {
    "01": "Administração e gestão — conceitos básicos",
    "02": "Evolução da administração pública (patrimonialismo à gestão)",
    "03": "Princípios do art. 37 da CF/1988",
    "04": "Administração direta, indireta e terceiro setor",
    "05": "Planejamento e orçamento público (PPA, LDO e LOA)",
    "06": "Licitações e contratos (Lei nº 14.133/2021)",
    "07": "Ciclo das políticas públicas",
    "08": "Controle da administração pública",
    "09": "Ferramentas gerenciais aplicadas à gestão pública",
    "10": "Estrutura, comportamento e cultura organizacional",
    "11": "Qualidade e gestão pública de excelência",
    SIM: "Simulado",
  },
  PO: {
    "01": "Ocorrências com armas de fogo e arma branca (POP nº 0017)",
    "02": "Lei de Drogas — usuário × traficante",
    "03": "Perturbação do sossego e poluição sonora",
    "04": "Infrações de trânsito e crimes ambientais",
    "05": "Escolta de presos",
    "06": "Operações de repressão qualificada",
    "07": "Manifestações e uso diferenciado da força",
    "08": "Rebeliões, assaltos a instituições financeiras e crises",
    "SIM-2AE": "Simulado — 2ª AE",
  },
  TCEM: {
    "02": "Histórico do Estado-Maior",
    "03": "Inteligências múltiplas e inteligência emocional",
    "04": "Estilos de comando",
    "05": "Atribuições e atividades do Estado-Maior",
    "06": "Lei de Organização Básica (LOB) e competências da PM",
    "SIM-1VA": "Simulado — 1ª VA",
    APOSTILA: "Questões da apostila",
  },
  GRAPP: {
    "1": "Ciclo de políticas públicas e modelos de decisão",
    "2": "Gestão por Resultados (GpR) — conceito e componentes",
    "3": "GpR na Administração Pública brasileira",
    "4": "Marcos normativos da GpR em Pernambuco",
    "5": "Juntos pela Segurança — base legal e o Pacto pela Vida",
    "6": "Indicadores do JPS (MVI, CVP e RFV)",
    "7": "Atores e governança do JPS (NGR-SDS e SEPLAG)",
    "8": "Análise SWOT do Juntos pela Segurança",
    "Simulado 1": "Simulado 1", "Simulado 2": "Simulado 2",
    "Simulado 3": "Simulado 3", "Simulado 4": "Simulado 4",
  },
  ACE: {
    "1": "Histórico da análise criminal (UCR, Vollmer, CompStat)",
    "2": "Análise criminal na segurança pública e a GACE",
    "3": "Teorias do crime (escolha racional e padrão criminal)",
    "4": "Avaliação de políticas e fontes das estatísticas criminais",
    "5": "Estatística aplicada (séries, medidas e gráficos)",
    "6": "Geoprocessamento e SIG",
    "7": "Ferramentas de BI, Excel e o SACE",
    "Exercícios — Ten Vicente": "Exercícios — Ten Vicente",
    Gaivotas: "Gaivotas — questões da turma",
  },
  AM: {
    "1": "Classificação das armas de fogo",
    "2": "Revólver, pistola e submetralhadora — funcionamento",
    "3": "Normas de segurança com armas de fogo",
    "4": "Segurança e conduta no estande de tiro",
    "5": "Posições de tiro (Isósceles, Weaver e deitado)",
    "6": "Empunhadura",
    "7": "Aparelho de pontaria, visada e plano focal",
    "8": "Condicionamento mental, saque e apresentação",
    "9": "Recargas, follow through e Double Tap",
    "10": "Panes e sua correção",
    "11": "Balística (interna, de transição, externa e terminal)",
  },
  DADM: {
    "1": "Direito Administrativo Disciplinar Militar — noções e base legal",
    "2": "Transgressão disciplinar e investigação preliminar",
    "3": "Espécies de PADM (SAD, PADS, CJ e CD)",
    "4": "Competência para aplicar penas (art. 10 do CDMEPE)",
    "5": "Apuração dos inativos e Corregedoria-Geral da SDS",
    "6": "Penas disciplinares (art. 28) e advertência",
    "7": "Recursos: reconsideração, queixa e afastamento preventivo",
    "8": "Prazos de conclusão dos processos",
  },
  ECRI: {
    "1": "Ética e filosofia moral (de Sócrates a Kant)",
    "2": "Deontologia, valores e deveres",
    "3": "Cidadania: direitos civis, políticos e sociais",
    "4": "Direitos Humanos e Código de Conduta da ONU",
    "5": "Desvios éticos: violência, corrupção e disfunção",
    "6": "Liderança, comunicação e inteligência emocional",
  },
  FPC: {
    "1": "Conceito e premissas da Polícia Comunitária",
    "2": "Princípios da Polícia Comunitária",
    "3": "Estratégias de policiamento",
    "4": "O que NÃO é Policiamento Comunitário",
    "5": "Os seis grandes grupos do policiamento comunitário",
    "6": "Experiências: NUSEP, Sistema Koban e Patrulha do Bairro",
    "7": "Senasp e os planos nacionais de segurança pública",
  },
  HPMPE: {
    "1": "Criação do Corpo de Polícia de Pernambuco (1825)",
    "2": "Denominações e a Brigada Militar (1825–1900)",
    "3": "Quartel do Derby e o Mercado Coelho Cintra",
    "4": "Tropas Volantes e o combate ao cangaço",
    "5": "História militar: conceitos e Nova História Militar",
  },
  LPMO: {
    "1": "Lei Orgânica Nacional (Lei nº 14.751/2023) e competências",
    "2": "Hierarquia: postos e graduações",
    "3": "Deveres policiais-militares",
    "4": "Direitos, estabilidade e recursos administrativos",
    "5": "Prerrogativas do policial-militar",
    "6": "Agregação",
    "7": "Desligamento, reserva e reforma",
    "8": "Remuneração: soldo, gratificações e indenizações",
    "9": "Promoções — critérios",
    "10": "Licenças",
    "11": "Registro e porte de arma (CRAF)",
    "12": "Tempo de serviço, quadro de acesso e readaptação",
  },
  PA: {
    "1": "Perfil psicológico e socialização policial",
    "2": "Assertividade e trabalho em equipe",
    "3": "Estresse e Síndrome de Burnout",
    "4": "Comportamento coletivo e multidões",
    "5": "Comunicação Não Violenta (CNV)",
    "6": "Primeiros Socorros Psicológicos (PSP)",
  },
  SMQV: {
    "1": "Saúde mental e qualidade de vida — conceitos",
    "2": "Saúde mental no ambiente de trabalho",
    "3": "Estresse, suas fases e o TEPT",
    "4": "Estigma em saúde mental",
    "5": "Vitimização policial",
    "6": "Rede de apoio e o papel do oficial-líder",
  },
  SSP: {
    "1": "Ordem pública e segurança pública — conceitos",
    "2": "Art. 144 da CF e os órgãos de segurança pública",
    "3": "Competências das polícias",
    "4": "Guardas municipais, Forças Armadas e atores complementares",
    "5": "Sistema Único de Segurança Pública (SUSP)",
    "6": "Cooperação federativa e sistema de justiça criminal",
  },
  TGA: {
    "1": "Conceitos básicos: eficiência, eficácia e efetividade",
    "2": "A administração como ciência, técnica e arte",
    "3": "Administração Científica (Taylor)",
    "4": "Teoria Clássica (Fayol)",
    "5": "Burocracia (Weber) e suas disfunções",
    "6": "Relações Humanas (Mayo e Hawthorne)",
    "7": "Teoria Neoclássica e APO",
    "8": "Hierarquia das necessidades (Maslow)",
    "9": "Abordagens sistêmica e contingencial",
    "10": "Modelos de gestão contemporâneos",
  },
  TIC: {
    "1": "Pirâmide do Conhecimento (DIKW) e níveis de decisão",
    "2": "Sistemas de Informação × Tecnologia da Informação",
    "3": "Sistemas da SDS/PE (GGTI, senha unificada e CIODS)",
    "4": "Polícia Ágil e sistemas nacionais (SINESP e SISDEPEN)",
    "5": "Radiocomunicação P25, PM Conectado e reconhecimento facial",
    "6": "SEI, Expresso e sistemas administrativos",
    "7": "Código Q e alfabeto fonético",
  },
}

/** Rótulo completo do módulo: "Módulo 3 — Culto à Bandeira". */
export function moduloLabel(materia: string, modulo: string): string {
  if (!modulo) return "Sem módulo"
  const titulo = TITULOS_MODULO[materia]?.[modulo]
  if (!/^\d+$/.test(modulo)) return titulo || modulo
  return titulo ? `Módulo ${Number(modulo)} — ${titulo}` : `Módulo ${Number(modulo)}`
}

/** Rótulo curto para as etiquetas de questão: "Mód. 3 — Culto à Bandeira". */
export function moduloLabelCurto(materia: string, modulo: string): string {
  if (!modulo) return ""
  const titulo = TITULOS_MODULO[materia]?.[modulo]
  if (!/^\d+$/.test(modulo)) return titulo || modulo
  return titulo ? `Mód. ${Number(modulo)} — ${titulo}` : `Mód. ${Number(modulo)}`
}
