import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "AP"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ── Módulo 1 — Fundamentação jurídica ──
  { modulo: "1", tipo: "multipla", enunciado: "A busca pessoal encontra fundamento no Código de Processo Penal, especialmente nos artigos:", alternativas: A("240, §2º, 244 e 249", "5º, 121 e 157", "301, 302 e 303", "144, 155 e 156", "33, 34 e 35"), gabarito: "A", explicacao: "A busca pessoal funda-se nos arts. 240, §2º, 244 e 249 do CPP." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Nos termos do art. 244 do CPP, a busca pessoal independe de mandado no caso de prisão, quando houver fundada suspeita de posse de arma proibida ou de objetos que constituam corpo de delito, ou no curso de busca domiciliar.", gabarito: "certo", explicacao: "Correto. O art. 244 dispensa o mandado nessas hipóteses." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Segundo o art. 249 do CPP, a busca em mulher será sempre feita por outra mulher, sem qualquer exceção.", gabarito: "errado", explicacao: "Errado. A busca em mulher é feita por outra mulher, SALVO se isso importar retardamento ou prejuízo da diligência." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O policial deve fundamentar no boletim de ocorrência o motivo prévio (fundada suspeita) e a urgência que justificaram a busca pessoal.", gabarito: "certo", explicacao: "Correto. O registro escrito dos elementos concretos é exigência para legitimar a medida." },
  { modulo: "1", tipo: "multipla", enunciado: "A busca pessoal corresponde a:", alternativas: A("uma revista no corpo do indivíduo para encontrar arma proibida ou objetos/papéis que constituam corpo de delito", "a entrada e vistoria em imóveis", "a inspeção de automóveis", "a verificação do entorno da abordagem", "a coleta de depoimentos de testemunhas"), gabarito: "A", explicacao: "A busca pessoal é a revista no corpo do sujeito em busca de armas, drogas, objetos ou papéis que constituam corpo de delito." },

  // ── Módulo 2 — Fundada suspeita e jurisprudência ──
  { modulo: "2", tipo: "certo_errado", enunciado: "A fundada suspeita exige elementos objetivos e indícios significativos, não podendo basear-se apenas em pressentimento, achismo ou tirocínio policial.", gabarito: "certo", explicacao: "Correto. A fundada suspeita demanda elementos concretos, não meramente subjetivos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Conforme entendimento do STJ, a denúncia anônima, por si só e sem outros elementos, é suficiente para configurar a fundada suspeita e legitimar a busca pessoal.", gabarito: "errado", explicacao: "Errado. O STJ (AgRg no HC 734.263/RS) firmou que a denúncia anônima isolada não justifica a busca pessoal." },
  { modulo: "2", tipo: "multipla", enunciado: "Segundo o STJ (RHC 158.580/BA), é ILEGAL a busca pessoal pautada, EXCETO:", alternativas: A("em elementos concretos e indícios objetivos de posse de arma proibida ou corpo de delito", "em critérios unicamente subjetivos", "no nervosismo do abordado", "unicamente em denúncia anônima", "tão somente em atitude suspeita"), gabarito: "A", explicacao: "A busca é legal justamente quando há elementos concretos/objetivos; as demais hipóteses caracterizam ilegalidade." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O STF (HC 208.240) firmou que a busca pessoal não é lícita quando realizada com base na raça, sexo, orientação sexual ou cor da pele.", gabarito: "certo", explicacao: "Correto. A busca deve fundar-se em elementos indiciários objetivos, vedada a discriminação." },
  { modulo: "2", tipo: "multipla", enunciado: "No HC 81.305, o STF entendeu que NÃO basta para a fundada suspeita a alegação de que o abordado:", alternativas: A("trajava um 'blusão' suscetível de esconder uma arma", "portava ostensivamente uma arma de fogo", "confessou o crime espontaneamente", "estava em cumprimento de mandado de prisão", "foi flagrado em ato de tráfico"), gabarito: "A", explicacao: "O STF reputou insuficiente o argumento do 'blusão' — parâmetro subjetivo, sem elementos concretos." },

  // ── Módulo 3 — Grupos vulneráveis ──
  { modulo: "3", tipo: "certo_errado", enunciado: "A Lei nº 12.764/2012 considera a pessoa com Transtorno do Espectro Autista (TEA) como pessoa com deficiência para todos os efeitos legais.", gabarito: "certo", explicacao: "Correto. O autista é equiparado a PCD (Lei 12.764/2012); há o POP 0053 para ocorrências envolvendo TEA." },
  { modulo: "3", tipo: "multipla", enunciado: "No atendimento à mulher vítima de violência, o principal documento orientador da PMPE é o:", alternativas: A("POP 0016", "POP 0029", "POP 0053", "POP 0001", "Decreto 30.051/2010"), gabarito: "A", explicacao: "O POP 0016 trata do atendimento à mulher vítima de violência doméstica, familiar, sexual, psicológica, moral ou patrimonial." },
  { modulo: "3", tipo: "certo_errado", enunciado: "No trato com a população LGBTQIAPN+, deve-se respeitar o uso do nome social, conforme o Decreto Estadual nº 30.051/2010.", gabarito: "certo", explicacao: "Correto. O decreto dispõe sobre o uso do nome social de travestis e transexuais nos serviços públicos estaduais." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Na abordagem à pessoa idosa devem ser consideradas as peculiaridades e limitações da idade avançada, evitando expô-la a situação que não suporte.", gabarito: "certo", explicacao: "Correto. O atendimento ao idoso exige atenção às suas limitações." },
  { modulo: "3", tipo: "multipla", enunciado: "Na abordagem à pessoa em situação de rua, após a busca e breve entrevista, o policial deverá notificar, para fins de reintegração:", alternativas: A("o CRAS e o CREAS", "apenas o Ministério Público", "somente a Defensoria Pública", "o Conselho Tutelar exclusivamente", "a Receita Federal"), gabarito: "A", explicacao: "A notificação ao CRAS/CREAS visa a integração e ressocialização da pessoa em vulnerabilidade." },

  // ── Módulo 4 — Conceito e técnicas ──
  { modulo: "4", tipo: "certo_errado", enunciado: "A abordagem policial é uma ação operacional do policiamento ostensivo, executada de forma técnica e fundamentada em princípios legais e éticos.", gabarito: "certo", explicacao: "Correto. É a definição de abordagem policial." },
  { modulo: "4", tipo: "multipla", enunciado: "São finalidades da abordagem policial, EXCETO:", alternativas: A("julgar e condenar o abordado", "orientar ou assistir", "interpelar ou advertir", "realizar busca e identificar", "deter em flagrante ou por mandado"), gabarito: "A", explicacao: "Julgar/condenar é função jurisdicional. A abordagem visa orientar, interpelar, buscar, identificar e deter." },
  { modulo: "4", tipo: "multipla", enunciado: "A verificação da área onde foi realizada a abordagem, para checar se há material ilícito escondido, é a busca:", alternativas: A("no perímetro", "pessoal", "em veículos", "em edificações", "ocular"), gabarito: "A", explicacao: "A busca no perímetro checa o entorno da abordagem." },

  // ── Módulo 5 — Princípios ──
  { modulo: "5", tipo: "multipla", enunciado: "São princípios da abordagem policial:", alternativas: A("segurança, surpresa, rapidez, ação vigorosa e unidade de comando", "legalidade, impessoalidade, moralidade, publicidade e eficiência", "necessidade, proporcionalidade, moderação e conveniência", "hierarquia, disciplina, lealdade e camaradagem", "prevenção, repressão, ostensividade e dissuasão"), gabarito: "A", explicacao: "Os 5 princípios da abordagem: segurança, surpresa, rapidez, ação vigorosa e unidade de comando." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A ação vigorosa consiste em postura firme e resoluta do agente, podendo confundir-se com o uso arbitrário da força quando a situação exigir.", gabarito: "errado", explicacao: "Errado. A ação vigorosa NÃO se confunde com arbítrio ou violência; respeita a legalidade e os direitos humanos." },
  { modulo: "5", tipo: "multipla", enunciado: "O princípio que estabelece que todas as ordens devem emanar de uma única autoridade, evitando conflito de decisões durante a abordagem, é o da:", alternativas: A("unidade de comando", "surpresa", "rapidez", "segurança", "ação vigorosa"), gabarito: "A", explicacao: "A unidade de comando garante linha de comando única, evitando conflito de ordens." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O princípio da surpresa consiste em agir de maneira inesperada ou não previsível, minimizando as chances de reação ou resistência do abordado.", gabarito: "certo", explicacao: "Correto. A surpresa cria vantagem tática e aumenta a segurança." },

  // ── Módulo 6 — Processos ──
  { modulo: "6", tipo: "multipla", enunciado: "No planejamento mental da abordagem, o policial faz as indagações: o que faremos? para que? quem? e onde? Já no plano de ação, suscitam-se:", alternativas: A("como faremos (modus operandi) e quando faremos (melhor momento)", "quanto custará e quem pagará", "quem julgará e quando", "qual a pena e o regime", "onde guardar as provas e por quanto tempo"), gabarito: "A", explicacao: "O plano de ação define o 'como' (modus operandi) e o 'quando' (melhor momento)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A execução é a fase em que se aplica, na prática, aquilo que foi previamente planejado, conforme a sequência de ações da abordagem.", gabarito: "certo", explicacao: "Correto. Execução = prática do que foi planejado." },

  // ── Módulo 7 — Posturas de segurança ──
  { modulo: "7", tipo: "multipla", enunciado: "A postura de segurança recomendada para cenários de ações educativas/informativas (ex.: prestar informação a transeunte), com arma de porte no coldre, é a:", alternativas: A("postura 1 (básica)", "postura 2 modificada", "postura 3 modificada", "postura 3 pronto", "postura 4 tática"), gabarito: "A", explicacao: "A postura 1 (básica) é usada em ações educativas/informativas, com a arma no coldre." },
  { modulo: "7", tipo: "multipla", enunciado: "A arma engajada em plenas condições de disparo (postura 3 'pronto') é recomendada:", alternativas: A("somente em situações de confronto, atual ou iminente, com risco de vida", "em qualquer abordagem de rotina", "ao prestar informações a transeuntes", "apenas em formaturas e solenidades", "exclusivamente em revistas prisionais"), gabarito: "A", explicacao: "A postura 3 'pronto' restringe-se a confronto atual ou iminente, com risco de vida." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Na postura 3 modificada, a massa de mira fica levemente abaixo da linha de visada, com o intuito de ampliar a visão periférica do policial, sendo adotada no primeiro contato e verbalização com o abordado.", gabarito: "certo", explicacao: "Correto. É a postura do primeiro contato/verbalização." },

  // ── Módulo 8 — Tipos de busca ──
  { modulo: "8", tipo: "multipla", enunciado: "A busca preventiva, sem contato físico, em que o policial avalia a distância o comportamento do indivíduo e o ambiente, é a busca:", alternativas: A("visual/ocular", "rápida", "minuciosa", "completa", "domiciliar"), gabarito: "A", explicacao: "A busca visual/ocular é não invasiva, feita a distância segura." },
  { modulo: "8", tipo: "multipla", enunciado: "A busca em que, em situações extremas, são verificadas inclusive as cavidades do corpo do abordado, executada em cenários de revistas prisionais, é a busca:", alternativas: A("completa", "minuciosa", "rápida", "visual", "no perímetro"), gabarito: "A", explicacao: "A busca completa inclui as cavidades e restringe-se a situações extremas (revista prisional)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A busca rápida é uma técnica direta para localizar objetos perigosos sem revista minuciosa, comum no acesso a eventos (ex.: partidas de futebol) e em patrulhamento a pé.", gabarito: "certo", explicacao: "Correto. A busca rápida prioriza segurança e agilidade." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A busca minuciosa é mais superficial que a busca rápida, sendo aplicada quando não há tempo para uma inspeção detalhada.", gabarito: "errado", explicacao: "Errado. A minuciosa é mais aprofundada e sistemática que a rápida; usa-se quando a verificação rápida não basta." },

  // ── Módulo 9 — Posições e zona de segurança ──
  { modulo: "9", tipo: "multipla", enunciado: "A posição de busca pessoal indicada para suspeita confirmada e alto nível de periculosidade, com o abordado em decúbito ventral, pernas afastadas e mãos na nuca, é a posição:", alternativas: A("deitado", "em pé", "ajoelhado", "sentado", "agachado"), gabarito: "A", explicacao: "A posição deitado (decúbito ventral) é a de maior controle, para alta periculosidade/suspeita confirmada." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Após a busca nas posições ajoelhado ou deitado, o abordado deve ser colocado de pé e submetido a nova busca pessoal, visando maior segurança do procedimento.", gabarito: "certo", explicacao: "Correto. A nova busca em pé é medida de segurança prevista no manual." },
  { modulo: "9", tipo: "multipla", enunciado: "O perímetro de segurança da abordagem é descrito como '540º' porque corresponde a:", alternativas: A("360º na horizontal somados a 180º na vertical (inclui pontos altos)", "uma volta e meia completa apenas no plano do chão", "três quadrantes de 180º", "a soma de quatro ângulos retos", "o dobro de um círculo"), gabarito: "A", explicacao: "O perímetro 540º = 360º horizontal + 180º vertical, abrangendo inclusive pontos altos de edificações." },
  { modulo: "9", tipo: "multipla", enunciado: "O local onde o policiamento posiciona o abordado, já verificado que não representa risco, sob custódia direta de um ou mais policiais, é a:", alternativas: A("área de custódia", "área de busca", "área de alcance", "área de fuga", "área de triagem"), gabarito: "A", explicacao: "A área de custódia recebe o abordado após a busca, sem risco; a área de busca é onde se realiza a revista." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A área de alcance é o espaço em que os policiais podem ser atingidos numa possível reação por parte dos abordados.", gabarito: "certo", explicacao: "Correto. É a definição de área de alcance na zona de segurança." },

  // ── Módulo 10 — Sequência da abordagem ──
  { modulo: "10", tipo: "multipla", enunciado: "A sequência correta da abordagem a pessoas é:", alternativas: A("aproximação → verbalização → posicionamento → busca → desfecho", "verbalização → aproximação → busca → posicionamento → desfecho", "busca → aproximação → verbalização → desfecho → posicionamento", "posicionamento → busca → aproximação → verbalização → desfecho", "aproximação → busca → verbalização → desfecho → posicionamento"), gabarito: "A", explicacao: "A sequência é: aproximação, verbalização, posicionamento, busca e desfecho." },
  { modulo: "10", tipo: "certo_errado", enunciado: "Na aproximação, o policiamento desloca-se em triangulação (com o abordado no vértice), mantendo cerca de 2 m entre os policiais e de 1 a 3 m destes para o abordado.", gabarito: "certo", explicacao: "Correto. São as distâncias e a formação previstas para a aproximação." },
  { modulo: "10", tipo: "certo_errado", enunciado: "No desfecho, caso nenhum ilícito seja verificado, o policiamento deverá liberar o(s) abordado(s).", gabarito: "certo", explicacao: "Correto. Sem flagrante/ilícito, libera-se o abordado (com urbanidade); havendo flagrante, conduz-se o preso." },
  { modulo: "10", tipo: "multipla", enunciado: "Ao executar a busca pessoal, o Homem-Busca deve manter:", alternativas: A("a arma de porte no coldre e a portátil travada, evitando deixá-la à frente do corpo", "a arma de porte sempre apontada para o abordado", "ambas as armas guardadas na viatura", "a arma portátil engatilhada à frente do corpo", "a arma de porte na mão durante toda a revista"), gabarito: "A", explicacao: "O Homem-Busca realiza a revista com a arma de porte no coldre e a portátil travada, enquanto o Segurança de Busca dá cobertura." },

  // ── Dissertativas ──
  { modulo: "2", tipo: "dissertativa", enunciado: "Conceitue 'fundada suspeita' e indique, com base na jurisprudência, situações que NÃO a caracterizam.", modelo: { estrutura: "Conceito → base legal → situações ilegais (jurisprudência) → conclusão.", criterios: ["Definir fundada suspeita com elementos objetivos/indícios concretos", "Citar a base legal (arts. 240, §2º e 244 do CPP)", "Indicar hipóteses que não a caracterizam (subjetividade, rotina, nervosismo, denúncia anônima isolada, tirocínio, atitude suspeita)"], resposta: "A fundada suspeita é o requisito essencial e indispensável da busca pessoal, previsto nos arts. 240, §2º, e 244 do CPP, consistente na existência, no caso concreto, de elementos objetivos e indícios significativos de que a pessoa esteja na posse de arma proibida ou de objetos/papéis que constituam corpo de delito. Não basta a intuição ou o pressentimento do agente. Conforme a jurisprudência do STF (HC 81.305 e HC 208.240) e do STJ (RHC 158.580/BA; AgRg no HC 734.263/RS), NÃO caracterizam fundada suspeita: critérios unicamente subjetivos; abordagens de rotina; o mero nervosismo do abordado; a denúncia anônima isolada; o tirocínio policial isolado; e a simples 'atitude suspeita'. Também é ilícita a busca baseada em raça, sexo, orientação sexual ou cor da pele." } },
  { modulo: "7", tipo: "dissertativa", enunciado: "Descreva as posturas de segurança que o policial militar pode adotar na abordagem, conforme o nível de ameaça.", modelo: { estrutura: "Introdução → postura 1 → postura 2 → postura 3 (modificada e pronto) → conclusão.", criterios: ["Relacionar as posturas ao nível de ameaça", "Descrever a postura 1 (básica/educativa)", "Descrever as posturas 2 e 3 (segurança e confronto)"], resposta: "As posturas de segurança variam conforme o nível de ameaça. Na postura 1 (básica), a arma de porte permanece no coldre e a portátil em bandoleira apontada para baixo, sendo recomendada para ações educativas/informativas, como prestar informações a transeuntes. Na postura 2 modificada, a arma fica engajada a 45º para baixo ou em pronto alto (posição de segurança), adotada pelo policial responsável pela segurança, custódia dos abordados ou perímetro. Na postura 3 modificada, a arma está engajada e pronta, com a massa de mira levemente abaixo da linha de visada para ampliar a visão periférica, usada no primeiro contato e na verbalização; já na postura 3 'pronto', a arma fica em plenas condições de disparo, recomendada somente em situações de confronto atual ou iminente, com risco de vida ao policiamento ou a terceiros." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tq = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`AP: questoes ${c} criadas/${u} atualizadas (total ${tq}).`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
