import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "DADM"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 5 — Corregedoria, Inativos e Justiça ════════
  { modulo: "5", tipo: "certo_errado", enunciado: "A Corregedoria-Geral da SDS, criada pela Lei nº 11.929/2001, é o órgão superior de controle disciplinar interno.", gabarito: "certo", explicacao: "Correto. A Lei nº 11.929/2001 institui a Corregedoria-Geral da SDS como órgão superior de controle disciplinar interno." },
  { modulo: "5", tipo: "certo_errado", enunciado: "As requisições da Corregedoria-Geral da SDS devem ser atendidas no prazo máximo de 15 dias.", gabarito: "certo", explicacao: "Correto. O parágrafo único do art. 2º da Lei 11.929/2001 fixa o prazo de 15 dias." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Compete à Justiça Militar estadual processar e julgar as ações judiciais contra atos disciplinares militares (art. 125, §4º, da CF).", gabarito: "certo", explicacao: "Correto. O art. 125, §4º, da CF (EC 45/2004) atribui essa competência à Justiça Militar estadual." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Nas ações contra atos disciplinares militares, o julgamento é feito por Conselho de Justiça, e não pelo juiz de forma singular.", gabarito: "errado", explicacao: "Errado. O juiz de direito do juízo militar julga de forma singular os atos disciplinares militares." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A apuração disciplinar dos inativos compete ao Comandante-Geral, conforme o art. 73 do CDMEPE.", gabarito: "certo", explicacao: "Correto. O art. 73 atribui às autoridades dos incisos I e II do art. 10 (Comandante-Geral) a penalização dos inativos." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Diretoria de Polícia Judiciária Militar (DPJM) e a Diretoria de Inativos e Pensionistas (DIP) foram criadas pela Lei Complementar nº 483/2022.", gabarito: "certo", explicacao: "Correto. A LC nº 483/2022 criou a DPJM e a DIP na PMPE." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Corregedoria-Geral da SDS pode instaurar e acompanhar sindicâncias e processos administrativos disciplinares.", gabarito: "certo", explicacao: "Correto. É atribuição da Corregedoria (art. 2º da Lei 11.929/2001)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A competência disciplinar da Corregedoria-Geral da SDS confunde-se com as competências de polícia judiciária militar das autoridades federais.", gabarito: "errado", explicacao: "Errado. A competência disciplinar da Corregedoria (normas estaduais) não se confunde com a de polícia judiciária militar (CPM/CPPM)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A delegação ao DPJM e ao DIP para aplicar reprimenda aos inativos foi feita pela Portaria do Comando-Geral nº 399/2022.", gabarito: "certo", explicacao: "Correto. A Portaria CG nº 399/2022 delegou essa atribuição ao DPJM e ao DIP." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A apreciação do ato disciplinar pela Justiça Militar pode abranger as consequências civis do ato, como indenizações e reparações.", gabarito: "certo", explicacao: "Correto. Segundo Assis, a apreciação jurisdicional pode abranger as consequências do ato, incluindo ações de responsabilidade civil." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Corregedoria-Geral da SDS pode requisitar a instauração de Conselhos de Disciplina e de Justificação.", gabarito: "certo", explicacao: "Correto. É atribuição prevista no art. 2º, V, da Lei 11.929/2001." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A lei não pode excluir da apreciação do Poder Judiciário lesão ou ameaça a direito, inclusive em matéria disciplinar militar.", gabarito: "certo", explicacao: "Correto. É o princípio da inafastabilidade da jurisdição (art. 5º, XXXV, da CF)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O controle jurisdicional do ato disciplinar é, em regra, limitado à ocorrência de nulidade no processo de sancionamento.", gabarito: "certo", explicacao: "Correto. A doutrina aponta a limitação do controle à ocorrência de nulidade (pas de nullité sans grief)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Corregedoria-Geral da SDS foi criada pelo próprio CDMEPE (Lei 11.817/2000).", gabarito: "errado", explicacao: "Errado. A Corregedoria-Geral da SDS foi criada pela Lei nº 11.929/2001, e não pelo CDMEPE." },
  { modulo: "5", tipo: "certo_errado", enunciado: "É pacífico que não se declara nulidade de ato processual se dele não tiver decorrido prejuízo ao interessado.", gabarito: "certo", explicacao: "Correto. Aplica-se o princípio 'pas de nullité sans grief' (não há nulidade sem prejuízo)." },

  { modulo: "5", tipo: "multipla", enunciado: "A Corregedoria-Geral da Secretaria de Defesa Social foi criada por qual norma?", alternativas: A("Lei nº 11.929/2001", "Lei nº 11.817/2000", "Lei Complementar nº 483/2022", "Decreto nº 3.639/1975", "Lei nº 6.783/1974"), gabarito: "A", explicacao: "A Corregedoria-Geral da SDS é instituída pela Lei nº 11.929/2001." },
  { modulo: "5", tipo: "multipla", enunciado: "Nas ações contra atos disciplinares militares estaduais (art. 125, §4º, CF), o julgamento cabe:", alternativas: A("ao juiz de direito do juízo militar, de forma singular", "ao Conselho de Justiça", "ao Tribunal do Júri", "ao STF", "ao Ministério Público Militar"), gabarito: "A", explicacao: "O juiz julga de forma singular os atos disciplinares militares (sem Conselho de Justiça)." },
  { modulo: "5", tipo: "multipla", enunciado: "A apuração disciplinar dos militares inativos compete, em regra, a:", alternativas: A("Comandante-Geral (art. 73), com delegação ao DPJM e DIP", "qualquer comandante de companhia", "Ministério Público", "Justiça Comum", "Tribunal de Contas"), gabarito: "A", explicacao: "O art. 73 atribui ao Comandante-Geral; houve delegação ao DPJM e ao DIP (Portaria CG 399/2022)." },
  { modulo: "5", tipo: "multipla", enunciado: "A DPJM e a DIP foram criadas por qual norma?", alternativas: A("Lei Complementar nº 483/2022", "Lei nº 11.929/2001", "Lei nº 11.817/2000", "Portaria CG nº 399/2022", "Decreto nº 39.336/2013"), gabarito: "A", explicacao: "A LC nº 483/2022 criou a Diretoria de Polícia Judiciária Militar e a Diretoria de Inativos e Pensionistas." },
  { modulo: "5", tipo: "multipla", enunciado: "O prazo máximo para atendimento das requisições da Corregedoria-Geral da SDS é de:", alternativas: A("15 dias", "5 dias", "30 dias", "48 horas", "60 dias"), gabarito: "A", explicacao: "O parágrafo único do art. 2º da Lei 11.929/2001 fixa o prazo de 15 dias." },

  { modulo: "5", tipo: "dissertativa", enunciado: "Disserte sobre a Corregedoria-Geral da SDS: norma de criação, natureza e principais atribuições no controle disciplinar.", modelo: { estrutura: "Norma de criação → natureza → atribuições → prazo de requisição.", criterios: ["Citar a Lei nº 11.929/2001", "Definir como órgão superior de controle disciplinar interno", "Listar atribuições (instaurar/acompanhar sindicâncias e PADs; requisitar Conselhos)", "Mencionar o prazo de 15 dias para atendimento das requisições"], resposta: "A Corregedoria-Geral da SDS foi criada pela Lei nº 11.929/2001 e é o órgão superior de controle disciplinar interno dos órgãos e agentes vinculados à Secretaria de Defesa Social. Entre suas atribuições estão instaurar, proceder e acompanhar sindicâncias e processos administrativos disciplinares, requisitar a instauração de Conselhos de Disciplina e de Justificação e expedir provimentos correicionais. Suas requisições devem ser atendidas no prazo máximo de 15 dias." } },
  { modulo: "5", tipo: "dissertativa", enunciado: "Explique como se dá a apreciação do ato disciplinar militar pelo Poder Judiciário, conforme o art. 125, §4º, da CF.", modelo: { estrutura: "Inafastabilidade da jurisdição → competência da JME → julgamento singular → limites.", criterios: ["Citar o art. 5º, XXXV (inafastabilidade)", "Citar o art. 125, §4º, da CF (competência da Justiça Militar estadual)", "Afirmar o julgamento singular pelo juiz", "Mencionar a limitação do controle a nulidades (sem prejuízo, sem nulidade)"], resposta: "Pela inafastabilidade da jurisdição (art. 5º, XXXV, da CF), o ato disciplinar militar pode ser apreciado pelo Judiciário. O art. 125, §4º, da CF atribui à Justiça Militar estadual a competência para processar e julgar as ações contra atos disciplinares militares, sendo o julgamento feito pelo juiz de forma singular (sem Conselho de Justiça). O controle costuma limitar-se à ocorrência de nulidade no processo de sancionamento, observado o princípio de que não há nulidade sem prejuízo (pas de nullité sans grief)." } },

  // ════════ MÓDULO 6 — Penas Disciplinares ════════
  { modulo: "6", tipo: "certo_errado", enunciado: "São penas disciplinares do CDMEPE (art. 28): repreensão, detenção, prisão, licenciamento a bem da disciplina e exclusão a bem da disciplina.", gabarito: "certo", explicacao: "Correto. É o rol do art. 28 do CDMEPE." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Embora prevista no rol do art. 28, a pena de repreensão é inaplicável atualmente, por ausência de previsão de conduta/forma de uso.", gabarito: "certo", explicacao: "Correto. A apostila aponta o vazio legal que torna a repreensão inaplicável atualmente." },
  { modulo: "6", tipo: "certo_errado", enunciado: "As penas de prisão e detenção podem ultrapassar 30 dias, a critério da autoridade.", gabarito: "errado", explicacao: "Errado. O §4º do art. 28 limita prisão e detenção a, no máximo, 30 dias." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A prisão disciplinar implica privação absoluta da liberdade (confinamento), enquanto a detenção implica privação relativa.", gabarito: "certo", explicacao: "Correto. O §4º do art. 28: prisão = privação absoluta; detenção = privação relativa." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O licenciamento a bem da disciplina aplica-se às praças sem estabilidade (menos de 10 anos de efetivo serviço).", gabarito: "certo", explicacao: "Correto. O licenciamento a bem da disciplina destina-se às praças sem estabilidade." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A exclusão a bem da disciplina aplica-se ao Aspirante a Oficial e às praças com estabilidade assegurada.", gabarito: "certo", explicacao: "Correto. É o público da exclusão a bem da disciplina." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A pena de caráter demissório aplicável ao oficial é a 'demissão ex-officio'.", gabarito: "certo", explicacao: "Correto. Conforme a Lei Estadual 6.783/1974, o desligamento do oficial é a demissão ex-officio." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A advertência prevista no §3º do art. 28 é uma espécie de pena disciplinar registrada na ficha do militar.", gabarito: "errado", explicacao: "Errado. A advertência é orientação verbal, SEM registro na ficha, e não é pena nem recurso em sentido estrito." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Podem ser aplicadas, alternativa ou cumulativamente às penas, medidas administrativas como movimentação de OME e suspensão de folga.", gabarito: "certo", explicacao: "Correto. É o §1º do art. 28 (medidas administrativas)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Todas as penas disciplinares aplicadas devem ser registradas na ficha disciplinar do transgressor.", gabarito: "certo", explicacao: "Correto. É o §2º do art. 28 (registro para apuração de comportamento/conceito)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A detenção implica recolhimento em dependência da OME designada para esse fim.", gabarito: "certo", explicacao: "Correto. O §4º, I, do art. 28: na detenção, o recolhimento se dá em dependência da OME." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A pena disciplinar tem por objetivo apenas a punição do transgressor, sem qualquer caráter reeducativo.", gabarito: "errado", explicacao: "Errado. O art. 27 estabelece a finalidade de fortalecer a disciplina e reeducar o transgressor e a coletividade." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A advertência pode ser adotada, em regra, quando se tratar da primeira penalidade aplicada ao transgressor.", gabarito: "certo", explicacao: "Correto. O §3º do art. 28 admite a advertência na primeira penalidade ou quando os antecedentes recomendarem." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Detenção e prisão são penas aplicáveis às transgressões disciplinares simples, nos termos da Parte Especial do CDMEPE.", gabarito: "certo", explicacao: "Correto. A apostila indica que detenção e prisão se aplicam às transgressões simples." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O cumprimento da pena de prisão deve sempre implicar prejuízo às atividades de instrução a que o transgressor deva comparecer.", gabarito: "errado", explicacao: "Errado. O §8º do art. 28: em princípio, a prisão não deve prejudicar as atividades de instrução; havendo prejuízo, isso deve ser declarado em boletim." },

  { modulo: "6", tipo: "multipla", enunciado: "Qual das penas do art. 28 do CDMEPE é considerada inaplicável atualmente?", alternativas: A("Repreensão", "Detenção", "Prisão", "Licenciamento a bem da disciplina", "Exclusão a bem da disciplina"), gabarito: "A", explicacao: "A repreensão, embora prevista, é inaplicável por ausência de previsão de conduta/forma de uso." },
  { modulo: "6", tipo: "multipla", enunciado: "As penas de prisão e detenção não podem ultrapassar:", alternativas: A("30 dias", "15 dias", "60 dias", "90 dias", "10 dias"), gabarito: "A", explicacao: "O §4º do art. 28 limita prisão e detenção a 30 dias." },
  { modulo: "6", tipo: "multipla", enunciado: "A exclusão a bem da disciplina aplica-se a:", alternativas: A("Aspirante a Oficial e praças com estabilidade assegurada", "praças sem estabilidade", "apenas oficiais superiores", "civis contratados", "alunos do CFO"), gabarito: "A", explicacao: "A exclusão a bem da disciplina destina-se ao Aspirante a Oficial e às praças com estabilidade." },
  { modulo: "6", tipo: "multipla", enunciado: "Sobre a advertência (§3º do art. 28), é correto afirmar:", alternativas: A("é orientação verbal, sem registro na ficha, e não é pena nem recurso em sentido estrito", "é a pena disciplinar mais grave", "é um recurso disciplinar do art. 51", "deve sempre ser registrada na ficha", "só pode ser aplicada a oficiais"), gabarito: "A", explicacao: "A advertência é orientação verbal sem registro; não é pena nem recurso em sentido estrito." },
  { modulo: "6", tipo: "multipla", enunciado: "A pena de caráter demissório aplicável ao oficial denomina-se:", alternativas: A("demissão ex-officio", "exclusão a bem da disciplina", "licenciamento a bem da disciplina", "repreensão", "reforma compulsória"), gabarito: "A", explicacao: "O desligamento do oficial das fileiras é a 'demissão ex-officio' (Lei 6.783/1974)." },

  { modulo: "6", tipo: "dissertativa", enunciado: "Apresente o rol de penas disciplinares do art. 28 do CDMEPE e explique a aplicabilidade de cada uma (repreensão, detenção, prisão, licenciamento e exclusão).", modelo: { estrutura: "Rol → aplicabilidade de cada pena → oficial (demissão ex-officio) → conclusão.", criterios: ["Listar as cinco penas do art. 28", "Apontar a inaplicabilidade da repreensão", "Detenção/prisão para transgressões simples (máx. 30 dias)", "Licenciamento (praça sem estabilidade) e exclusão (aspirante e praça com estabilidade)", "Citar a demissão ex-officio do oficial"], resposta: "O art. 28 prevê: I – repreensão; II – detenção; III – prisão; IV – licenciamento a bem da disciplina; V – exclusão a bem da disciplina. A repreensão, apesar de prevista, é inaplicável atualmente. Detenção e prisão aplicam-se às transgressões simples e não podem ultrapassar 30 dias (prisão = privação absoluta; detenção = relativa). O licenciamento a bem da disciplina destina-se às praças sem estabilidade (menos de 10 anos), e a exclusão a bem da disciplina ao Aspirante a Oficial e às praças com estabilidade. Ao oficial, o desligamento se dá pela demissão ex-officio (Lei 6.783/1974)." } },
  { modulo: "6", tipo: "dissertativa", enunciado: "Explique a natureza jurídica da advertência (§3º do art. 28) e diferencie-a da pena disciplinar e do recurso.", modelo: { estrutura: "Conceito de advertência → natureza → diferença para pena e recurso → conclusão.", criterios: ["Definir a advertência como orientação verbal sem registro", "Apontar o cabimento na primeira penalidade", "Diferenciar de pena (não há registro/sanção) e de recurso (não ataca decisão)"], resposta: "A advertência, prevista no §3º do art. 28, é uma orientação verbal ao transgressor, sem registro na ficha disciplinar, podendo a autoridade fixar-se nela quando se tratar da primeira penalidade ou quando os antecedentes recomendarem. Não é pena disciplinar em sentido estrito (pois não gera registro nem sanção formal) nem recurso (que é instrumento para atacar decisão). Trata-se de instrumento processual substitutivo de caráter educativo." } },

  // ════════ MÓDULO 7 — Recursos e Medidas Cautelares ════════
  { modulo: "7", tipo: "certo_errado", enunciado: "Os recursos disciplinares do CDMEPE são: reconsideração de ato, queixa, representação e revisão disciplinar.", gabarito: "certo", explicacao: "Correto. É o rol taxativo do art. 51 do CDMEPE." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Todos os recursos disciplinares têm efeito suspensivo, sobrestando o recolhimento do militar até o julgamento.", gabarito: "certo", explicacao: "Correto. O §1º do art. 51 confere efeito suspensivo aos recursos disciplinares." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A tramitação dos recursos disciplinares tem caráter urgente, não podendo exceder 15 dias.", gabarito: "certo", explicacao: "Correto. O §3º do art. 51 fixa o prazo de 15 dias para a tramitação." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A Reconsideração de Ato é dirigida ao superior imediato da autoridade que praticou o ato.", gabarito: "errado", explicacao: "Errado. A Reconsideração de Ato é dirigida à PRÓPRIA autoridade que praticou o ato (art. 52). À queixa é que se dirige ao superior imediato." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O pedido de reconsideração de ato deve ser apresentado no prazo máximo de 2 dias úteis.", gabarito: "certo", explicacao: "Correto. O §2º do art. 52: prazo de 2 dias úteis para apresentar a reconsideração." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A autoridade deve despachar o pedido de reconsideração de ato no prazo máximo de 4 dias úteis.", gabarito: "certo", explicacao: "Correto. O §3º do art. 52 fixa 4 dias úteis para o despacho." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A Queixa é dirigida ao superior imediato da autoridade contra quem é apresentada.", gabarito: "certo", explicacao: "Correto. O art. 53 prevê que a queixa é dirigida ao superior imediato da autoridade." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A queixa é cabível antes mesmo da publicação da solução do pedido de reconsideração.", gabarito: "errado", explicacao: "Errado. A queixa só é cabível APÓS a publicação da solução da reconsideração (§1º do art. 53)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O prazo para apresentação da queixa é de 5 dias úteis, a contar da publicação da solução da reconsideração.", gabarito: "certo", explicacao: "Correto. O §2º do art. 53 fixa o prazo de 5 dias úteis." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O afastamento preventivo das funções é determinado pelo Secretário de Defesa Social, ouvido o Corregedor-Geral.", gabarito: "certo", explicacao: "Correto. É o art. 14 da Lei nº 11.929/2001." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O afastamento preventivo das funções implica perda da remuneração do servidor.", gabarito: "errado", explicacao: "Errado. O afastamento preventivo ocorre SEM prejuízo da remuneração (art. 14 da Lei 11.929/2001)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O afastamento preventivo perdura por até 120 dias, prorrogável uma única vez por igual período.", gabarito: "certo", explicacao: "Correto. O §3º do art. 14 da Lei 11.929/2001 prevê até 120 dias, prorrogável uma vez por igual período." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O afastamento preventivo ocorre quando necessário à garantia da ordem pública, à instrução regular do procedimento e à correta aplicação da sanção.", gabarito: "certo", explicacao: "Correto. É o §2º do art. 14 da Lei 11.929/2001." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A revisão disciplinar não consta do rol de recursos do art. 51 do CDMEPE.", gabarito: "errado", explicacao: "Errado. A revisão disciplinar é um dos quatro recursos do art. 51 (ao lado de reconsideração, queixa e representação)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Findo o prazo do afastamento preventivo sem conclusão do processo, o servidor retorna às atividades meramente administrativas.", gabarito: "certo", explicacao: "Correto. É o §6º do art. 14 da Lei 11.929/2001." },

  { modulo: "7", tipo: "multipla", enunciado: "São recursos disciplinares previstos no art. 51 do CDMEPE:", alternativas: A("reconsideração de ato, queixa, representação e revisão disciplinar", "apelação, agravo, embargos e recurso especial", "advertência, repreensão e queixa", "habeas corpus e mandado de segurança", "pedido de reconsideração e apelação"), gabarito: "A", explicacao: "O art. 51 lista reconsideração de ato, queixa, representação e revisão disciplinar." },
  { modulo: "7", tipo: "multipla", enunciado: "A Reconsideração de Ato deve ser apresentada no prazo de:", alternativas: A("2 dias úteis", "5 dias úteis", "15 dias", "120 dias", "30 dias"), gabarito: "A", explicacao: "O §2º do art. 52 fixa 2 dias úteis para a reconsideração (e 4 dias úteis para o despacho da autoridade)." },
  { modulo: "7", tipo: "multipla", enunciado: "A Queixa é dirigida a quem e em que prazo?", alternativas: A("ao superior imediato da autoridade, em 5 dias úteis após a solução da reconsideração", "à própria autoridade, em 2 dias úteis", "ao Governador, em 15 dias", "ao juiz militar, em 120 dias", "ao Corregedor, a qualquer tempo"), gabarito: "A", explicacao: "A queixa (art. 53) vai ao superior imediato, em 5 dias úteis, após a publicação da solução da reconsideração." },
  { modulo: "7", tipo: "multipla", enunciado: "O afastamento preventivo das funções (art. 14 da Lei 11.929/2001):", alternativas: A("é determinado pelo Secretário de Defesa Social, sem prejuízo da remuneração, por até 120 dias prorrogáveis uma vez", "implica perda total da remuneração", "é vitalício", "é decidido pelo juiz militar", "dura no máximo 30 dias improrrogáveis"), gabarito: "A", explicacao: "É determinado pelo Secretário de Defesa Social (ouvido o Corregedor), sem prejuízo da remuneração, por até 120 dias prorrogáveis uma vez." },
  { modulo: "7", tipo: "multipla", enunciado: "Qual característica é comum a todos os recursos disciplinares do CDMEPE?", alternativas: A("possuem efeito suspensivo e tramitação em até 15 dias", "não têm prazo de tramitação", "dispensam motivação", "só cabem para oficiais", "são julgados pela Justiça Comum"), gabarito: "A", explicacao: "Todos têm efeito suspensivo (§1º) e tramitação que não excede 15 dias (§3º do art. 51)." },

  { modulo: "7", tipo: "dissertativa", enunciado: "Apresente os recursos disciplinares do CDMEPE e detalhe a Reconsideração de Ato e a Queixa (destinatário e prazos).", modelo: { estrutura: "Rol do art. 51 → reconsideração (destinatário/prazos) → queixa (destinatário/prazo) → efeito suspensivo.", criterios: ["Listar os quatro recursos do art. 51", "Reconsideração: à própria autoridade; 2 dias úteis (e 4 para despacho)", "Queixa: ao superior imediato; 5 dias úteis após a solução da reconsideração", "Mencionar efeito suspensivo e tramitação em 15 dias"], resposta: "Os recursos disciplinares (art. 51) são: reconsideração de ato, queixa, representação e revisão disciplinar, todos com efeito suspensivo e tramitação que não excede 15 dias. A Reconsideração de Ato (art. 52) é dirigida à própria autoridade que praticou o ato, no prazo de 2 dias úteis, devendo a autoridade despachá-la em até 4 dias úteis. A Queixa (art. 53) é dirigida ao superior imediato da autoridade contra quem se queixa, cabível apenas após a publicação da solução da reconsideração, no prazo de 5 dias úteis." } },
  { modulo: "7", tipo: "dissertativa", enunciado: "Disserte sobre a medida cautelar de afastamento preventivo das funções (art. 14 da Lei 11.929/2001): competência, finalidade, remuneração e prazo.", modelo: { estrutura: "Competência → finalidade → remuneração → prazo → conclusão.", criterios: ["Citar competência do Secretário de Defesa Social, ouvido o Corregedor", "Apontar finalidades (ordem pública, instrução, correta aplicação da sanção)", "Afirmar que é sem prejuízo da remuneração", "Indicar prazo de até 120 dias, prorrogável uma vez"], resposta: "O afastamento preventivo das funções (art. 14 da Lei 11.929/2001) é determinado, por portaria, pelo Secretário de Defesa Social, ouvido o Corregedor-Geral, em desfavor de servidor submetido a procedimento disciplinar por ato incompatível com a função. Ocorre sem prejuízo da remuneração e quando necessário à garantia da ordem pública, à instrução regular do procedimento e à correta aplicação da sanção. Perdura por até 120 dias, prorrogável uma única vez por igual período; findo o prazo sem conclusão, o servidor retorna a atividades meramente administrativas." } },

  // ════════ MÓDULO 8 — Prazos das Espécies de PADM ════════
  { modulo: "8", tipo: "certo_errado", enunciado: "O Conselho de Justificação tem 30 dias para conclusão, a contar da nomeação, prorrogáveis por mais 20 dias.", gabarito: "certo", explicacao: "Correto. CJ: 30 dias + 20 (Lei 5.836/1972), conforme o Provimento Correicional 003/2018." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O Conselho de Disciplina tem 30 dias para conclusão, a contar da nomeação, prorrogáveis por mais 20 dias.", gabarito: "certo", explicacao: "Correto. CD: 30 dias + 20 (Decreto 3.639/1975)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A Sindicância Administrativa Disciplinar (SAD) tem prazo de 30 dias para conclusão, prorrogável por até igual período.", gabarito: "certo", explicacao: "Correto. SAD: 30 dias, prorrogável por igual período (IN 02/17)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O Processo de Licenciamento a Bem da Disciplina (PL) tem 40 dias corridos para conclusão, não podendo o prazo de apuração ultrapassar 90 dias.", gabarito: "certo", explicacao: "Correto. PL: 40 dias corridos, máximo de 90 com prorrogação." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O PAD e o PAD Especial (PADE) têm 60 dias para conclusão, prorrogáveis por até igual período.", gabarito: "certo", explicacao: "Correto. PAD/PADE: 60 dias + igual período (art. 220 da Lei 6.123/1968)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A Sindicância (do gênero PAD) tem prazo de 20 dias para conclusão, prorrogável por até igual período.", gabarito: "certo", explicacao: "Correto. Sindicância: 20 dias, prorrogável por igual período (art. 217 da Lei 6.123/1968)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Os prazos dos PADM são peremptórios, de modo que o seu descumprimento gera a extinção do processo por decadência.", gabarito: "errado", explicacao: "Errado. Os prazos são meramente referenciais/impróprios; o descumprimento não gera perempção, prescrição ou decadência." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O descumprimento dos prazos processuais do PADM não serve de fundamento para extinguir o processo por excesso de prazo.", gabarito: "certo", explicacao: "Correto. Por serem prazos impróprios, o excesso não extingue o processo (art. 4º do Provimento 003/2018)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O prazo do Conselho de Justificação conta-se a partir do trânsito em julgado da sentença penal.", gabarito: "errado", explicacao: "Errado. O prazo do CJ (30 dias) conta-se a partir da data da nomeação do conselho." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A SAD conta seu prazo a partir do primeiro dia útil da publicação da portaria de instauração.", gabarito: "certo", explicacao: "Correto. O prazo da SAD começa no 1º dia útil da publicação da portaria de instauração." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O Provimento Correicional nº 003/2018 resume os prazos dos processos administrativos disciplinares vigentes.", gabarito: "certo", explicacao: "Correto. É o normativo que sistematiza os prazos das espécies de PADM/PAD." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Tanto o Conselho de Justificação quanto o Conselho de Disciplina têm a mesma prorrogação de 20 dias.", gabarito: "certo", explicacao: "Correto. Ambos: 30 dias + prorrogação de 20 dias." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O prazo de conclusão do PAD/PADE é de 90 dias, prorrogável por mais 90.", gabarito: "errado", explicacao: "Errado. O PAD/PADE tem 60 dias, prorrogáveis por igual período (60). 90 dias é o teto do Processo de Licenciamento." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A autoridade processante é aquela designada para proceder à apuração dos fatos, dando impulso oficial ao processo.", gabarito: "certo", explicacao: "Correto. É a definição de autoridade processante no Provimento 003/2018." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A Sindicância e a Sindicância Administrativa Disciplinar (SAD) possuem exatamente o mesmo prazo de conclusão.", gabarito: "errado", explicacao: "Errado. A SAD tem 30 dias; a Sindicância (gênero PAD) tem 20 dias — prazos distintos." },

  { modulo: "8", tipo: "multipla", enunciado: "Qual o prazo de conclusão do Conselho de Disciplina (CD), a contar da nomeação?", alternativas: A("30 dias, prorrogável por mais 20", "60 dias, prorrogável por igual período", "40 dias, máximo de 90", "20 dias, prorrogável por igual período", "15 dias improrrogáveis"), gabarito: "A", explicacao: "O CD tem 30 dias para conclusão (da nomeação), prorrogável por mais 20 (Decreto 3.639/1975)." },
  { modulo: "8", tipo: "multipla", enunciado: "O Processo de Licenciamento a Bem da Disciplina (PL) tem prazo de:", alternativas: A("40 dias corridos, com teto de 90 dias na prorrogação", "30 dias + 20", "60 dias + 60", "20 dias + 20", "15 dias"), gabarito: "A", explicacao: "O PL tem 40 dias corridos, não podendo ultrapassar 90 dias com prorrogação." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre a natureza dos prazos do PADM, é correto afirmar:", alternativas: A("são referenciais/impróprios; o descumprimento não extingue o processo", "são peremptórios e geram decadência", "geram prescrição automática", "são todos de 15 dias", "não existem prazos no PADM"), gabarito: "A", explicacao: "Os prazos são impróprios/referenciais; o excesso não gera perempção, prescrição ou decadência." },
  { modulo: "8", tipo: "multipla", enunciado: "O PAD e o PAD Especial (PADE) têm prazo de conclusão de:", alternativas: A("60 dias, prorrogável por igual período", "30 dias + 20", "40 dias, máx. 90", "20 dias + 20", "120 dias"), gabarito: "A", explicacao: "PAD/PADE: 60 dias, prorrogável por igual período (art. 220 da Lei 6.123/1968)." },
  { modulo: "8", tipo: "multipla", enunciado: "A Sindicância (gênero PAD) tem prazo de conclusão de:", alternativas: A("20 dias, prorrogável por igual período", "30 dias + 20", "60 dias + 60", "40 dias, máx. 90", "15 dias"), gabarito: "A", explicacao: "A Sindicância tem 20 dias, prorrogável por igual período (art. 217 da Lei 6.123/1968)." },

  { modulo: "8", tipo: "dissertativa", enunciado: "Apresente os prazos de conclusão das principais espécies de PADM/PAD (CJ, CD, SAD, PL, PAD/PADE e Sindicância), conforme o Provimento Correicional nº 003/2018.", modelo: { estrutura: "Listar cada espécie com prazo e prorrogação.", criterios: ["CJ e CD: 30 + 20 dias", "SAD: 30 dias + igual período", "PL: 40 dias (máx. 90)", "PAD/PADE: 60 + 60", "Sindicância: 20 + 20"], resposta: "Conforme o Provimento Correicional nº 003/2018: o Conselho de Justificação (CJ) e o Conselho de Disciplina (CD) têm 30 dias para conclusão, a contar da nomeação, prorrogáveis por mais 20 dias; a Sindicância Administrativa Disciplinar (SAD) tem 30 dias, prorrogável por igual período; o Processo de Licenciamento a Bem da Disciplina (PL) tem 40 dias corridos, com teto de 90 dias; o PAD e o PADE têm 60 dias, prorrogáveis por igual período; e a Sindicância tem 20 dias, prorrogável por igual período." } },
  { modulo: "8", tipo: "dissertativa", enunciado: "Explique a natureza dos prazos processuais do PADM e a consequência do seu descumprimento.", modelo: { estrutura: "Natureza dos prazos → fundamento → consequência → conclusão.", criterios: ["Afirmar que são prazos referenciais/impróprios", "Explicar que não há previsão legal de perempção/prescrição/decadência por excesso", "Concluir que o descumprimento não extingue o processo"], resposta: "Os prazos processuais previstos para os PADM e PAD, destinados às autoridades competentes para instaurar, instruir e julgar, são meramente referenciais ou impróprios, porque não há disposição legal que discipline o seu descumprimento como causa de perempção, prescrição ou decadência. Por isso, o excesso de prazo não serve de fundamento para extinguir o processo, embora possa ensejar responsabilização do agente que lhe der causa." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`DADM (mods 5-8): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
