import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "DADM"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }

const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 1 — Introdução, Princípios e Distinção ════════
  { modulo: "1", tipo: "certo_errado", enunciado: "A principal norma que rege o Direito Administrativo Disciplinar Militar na PMPE é a Lei nº 11.817/2000 — Código Disciplinar dos Militares do Estado de Pernambuco (CDMEPE).", gabarito: "certo", explicacao: "Correto. A Lei nº 11.817, de 24/07/2000 (CDMEPE), é a norma principal do DADM em Pernambuco." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O Direito Administrativo Disciplinar Militar é o campo especial do Direito que capitula os crimes militares.", gabarito: "errado", explicacao: "Errado. Quem capitula os crimes militares é o Direito Penal Militar. O DADM regula as relações entre o Estado e seus servidores (transgressões disciplinares)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A doutrina da 'verdade sabida' foi superada pelos princípios do devido processo legal, do contraditório, da ampla defesa e da possibilidade recursal.", gabarito: "certo", explicacao: "Correto. A 'verdade sabida' (punição imediata sem processo) foi superada pelas garantias do devido processo legal, contraditório e ampla defesa." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O Direito Administrativo Disciplinar Militar e o Direito Penal Militar tratam exatamente da mesma matéria, sendo expressões sinônimas.", gabarito: "errado", explicacao: "Errado. São campos distintos: o DADM trata das transgressões disciplinares (relação Estado-servidor); o Direito Penal Militar trata dos crimes militares." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os atos administrativos disciplinares militares gozam de presunção de legitimidade e veracidade.", gabarito: "certo", explicacao: "Correto. O ato sancionador militar tem presunção (relativa) de legitimidade e veracidade, reforçada pelos princípios da hierarquia e disciplina." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os princípios da legalidade, impessoalidade, moralidade, publicidade e eficiência (art. 37 da CF) não se aplicam ao Direito Administrativo Disciplinar Militar.", gabarito: "errado", explicacao: "Errado. Os princípios do art. 37 da CF aplicam-se à atuação disciplinar, ao lado do devido processo legal, contraditório e ampla defesa." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Uma mesma conduta pode estar tipificada simultaneamente como crime no Código Penal Militar e como transgressão disciplinar no CDMEPE.", gabarito: "certo", explicacao: "Correto. A apostila exemplifica condutas que figuram tanto como crime no CPM quanto como infração administrativa no CDMEPE (esferas independentes)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Para Miguel Reale, princípios são verdades ou juízos fundamentais que servem de alicerce a um conjunto de juízos ordenados em sistema.", gabarito: "certo", explicacao: "Correto. É a definição de princípio adotada na apostila (Miguel Reale)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O Direito Penal Militar é regido por normas estaduais, enquanto o Direito Administrativo Disciplinar Militar decorre de normas exclusivamente federais.", gabarito: "errado", explicacao: "Errado. O Direito Penal Militar é federal (CPM); o DADM, em PE, é regido por norma estadual (Lei 11.817/2000), além de normativos da SDS/PMPE." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O DADM regula as relações jurídicas entre o Estado e seus administrados, neles incluídos os próprios servidores.", gabarito: "certo", explicacao: "Correto. É a definição de Direito Administrativo Disciplinar adotada na apostila." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A aplicação de uma transgressão disciplinar prescinde de motivação, bastando a constatação do fato pela autoridade.", gabarito: "errado", explicacao: "Errado. A aplicação deve ser necessariamente motivada, considerando a natureza e a gravidade da infração (art. 13, parágrafo único, do CDMEPE)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A finalidade da pena disciplinar inclui o fortalecimento da disciplina e a reeducação do transgressor e da coletividade.", gabarito: "certo", explicacao: "Correto. É o objetivo previsto no art. 27 do CDMEPE." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O CDMEPE foi instituído pela Lei nº 11.929/2001.", gabarito: "errado", explicacao: "Errado. O CDMEPE é a Lei nº 11.817/2000. A Lei nº 11.929/2001 dispõe sobre a Corregedoria-Geral da SDS." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A moralidade administrativa está ligada à conduta do bom administrador, que busca o melhor e o mais útil ao interesse público.", gabarito: "certo", explicacao: "Correto. A moralidade impõe atuação conforme os princípios morais e a conduta do bom administrador." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O princípio da legalidade permite ao gestor público militar fazer tudo o que a lei não proíba expressamente.", gabarito: "errado", explicacao: "Errado. Na Administração Pública, a legalidade significa só fazer o que a lei autoriza/prevê — diferentemente do particular, que pode fazer o que a lei não proíbe." },

  { modulo: "1", tipo: "multipla", enunciado: "Qual norma é a principal referência do Direito Administrativo Disciplinar Militar na PMPE?", alternativas: A("Lei nº 11.817/2000 (CDMEPE)", "Lei nº 11.929/2001", "Decreto-Lei nº 1.001/1969 (CPM)", "Lei nº 6.783/1974 (Estatuto)", "Lei nº 14.751/2023"), gabarito: "A", explicacao: "A Lei nº 11.817/2000 é o Código Disciplinar dos Militares do Estado de Pernambuco, norma principal do DADM." },
  { modulo: "1", tipo: "multipla", enunciado: "A distinção essencial entre o Direito Administrativo Disciplinar Militar e o Direito Penal Militar é que:", alternativas: A("o DADM trata de transgressões disciplinares e o DPM, de crimes militares", "ambos tratam exclusivamente de crimes", "o DADM é federal e o DPM é estadual", "apenas o DPM admite contraditório", "não há distinção entre eles"), gabarito: "A", explicacao: "O DADM cuida das transgressões disciplinares (relação Estado-servidor); o Direito Penal Militar capitula os crimes militares." },
  { modulo: "1", tipo: "multipla", enunciado: "Assinale a alternativa que NÃO corresponde a um princípio expresso no art. 37 da CF aplicável à atuação administrativa:", alternativas: A("Insignificância", "Legalidade", "Impessoalidade", "Moralidade", "Publicidade"), gabarito: "A", explicacao: "Os princípios do art. 37 são legalidade, impessoalidade, moralidade, publicidade e eficiência. 'Insignificância' é princípio do Direito Penal, não do art. 37." },
  { modulo: "1", tipo: "multipla", enunciado: "Sobre os atos disciplinares militares, é correto afirmar que:", alternativas: A("gozam de presunção (relativa) de legitimidade e veracidade", "não admitem qualquer controle judicial", "dispensam motivação", "só podem ser aplicados a oficiais", "são regidos pelo Código de Processo Penal comum"), gabarito: "A", explicacao: "O ato disciplinar militar tem presunção relativa de legitimidade e veracidade, mas é motivado e sujeito a controle." },
  { modulo: "1", tipo: "multipla", enunciado: "A superação da doutrina da 'verdade sabida' decorre da consagração:", alternativas: A("do devido processo legal, do contraditório e da ampla defesa", "do princípio da insignificância", "da hierarquia absoluta", "da reserva legal penal", "do princípio da anterioridade tributária"), gabarito: "A", explicacao: "A 'verdade sabida' foi superada pelos princípios do devido processo legal, contraditório, ampla defesa e possibilidade recursal." },

  { modulo: "1", tipo: "dissertativa", enunciado: "Diferencie o Direito Administrativo Disciplinar Militar do Direito Penal Militar, apontando o objeto de cada um e a norma de regência do DADM na PMPE.", modelo: { estrutura: "Conceito de DADM → conceito de DPM → norma de regência → conclusão.", criterios: ["Definir o DADM como regulador das relações Estado-servidor (transgressões disciplinares)", "Definir o DPM como o campo que capitula os crimes militares", "Citar a Lei 11.817/2000 (CDMEPE) como norma principal do DADM em PE", "Mencionar a independência das esferas"], resposta: "O Direito Administrativo Disciplinar Militar regula as relações jurídicas entre o Estado e seus servidores militares, tratando das transgressões disciplinares — ações ou omissões que violam a ética e os valores militares sem se tipificarem como crime. Já o Direito Penal Militar é o campo especial que capitula os crimes militares. Em Pernambuco, o DADM tem como norma principal a Lei nº 11.817/2000 (CDMEPE). As esferas são independentes, podendo um mesmo fato repercutir tanto na disciplinar quanto na penal militar." } },
  { modulo: "1", tipo: "dissertativa", enunciado: "Explique por que a doutrina da 'verdade sabida' foi superada no Direito Administrativo Disciplinar Militar e quais princípios passaram a reger o sancionamento.", modelo: { estrutura: "Conceito da verdade sabida → razão da superação → princípios atuais → conclusão.", criterios: ["Explicar a 'verdade sabida' como punição imediata sem processo", "Apontar a incompatibilidade com as garantias constitucionais", "Citar devido processo legal, contraditório, ampla defesa e possibilidade recursal"], resposta: "A 'verdade sabida' permitia punir o transgressor de imediato, com base no conhecimento direto do fato pela autoridade, sem processo. Essa doutrina foi superada por ser incompatível com as garantias constitucionais. Atualmente, o sancionamento disciplinar deve observar o devido processo legal, o contraditório, a ampla defesa e a possibilidade recursal, assegurando legitimidade à punição." } },

  // ════════ MÓDULO 2 — Transgressão e Submissão ao Regime ════════
  { modulo: "2", tipo: "certo_errado", enunciado: "Transgressão disciplinar militar é toda ação ou omissão que viole os preceitos da ética e os valores militares, ou contrarie os deveres e obrigações, em manifestações que não possam ser tipificadas como crime ou contravenção.", gabarito: "certo", explicacao: "Correto. É a definição do art. 13 do CDMEPE." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Estão sujeitos ao regime disciplinar do CDMEPE apenas os militares da ativa.", gabarito: "errado", explicacao: "Errado. O art. 8º sujeita ao regime disciplinar os militares da ativa, da reserva remunerada e os reformados." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Os alunos de cursos militares também estão sujeitos às normas específicas previstas no regulamento da OME em que estejam matriculados.", gabarito: "certo", explicacao: "Correto. O §2º do art. 8º do CDMEPE prevê essa sujeição dos alunos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A apuração de transgressão disciplinar de militar inativo compete ao Comandante-Geral.", gabarito: "certo", explicacao: "Correto. O art. 73 atribui à competência das autoridades dos incisos I e II do art. 10 (entre elas o Comandante-Geral) a penalização dos inativos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Uma conduta tipificada como crime militar deve ser tratada, prioritariamente, como transgressão disciplinar simples.", gabarito: "errado", explicacao: "Errado. A transgressão disciplinar abrange manifestações que NÃO possam ser tipificadas como crime ou contravenção. Havendo crime, aplica-se a esfera penal." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A aplicação da pena por transgressão disciplinar deve considerar a natureza e a gravidade da infração.", gabarito: "certo", explicacao: "Correto. O parágrafo único do art. 13 exige motivação e consideração da natureza e gravidade." },
  { modulo: "2", tipo: "certo_errado", enunciado: "As transgressões disciplinares militares estão previstas apenas na Parte Geral do CDMEPE.", gabarito: "errado", explicacao: "Errado. Estão previstas na Parte Especial do Código, sem prejuízo de outras definidas em lei ou regulamento." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Os oficiais nomeados juízes da Justiça Militar são regidos por legislação específica quanto ao regime disciplinar.", gabarito: "certo", explicacao: "Correto. O §1º do art. 8º ressalva que esses oficiais são regidos por legislação específica." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A transgressão disciplinar pode consistir tanto em uma ação quanto em uma omissão do militar.", gabarito: "certo", explicacao: "Correto. O art. 13 define a transgressão como 'ação ou omissão'." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O Inquérito Policial Militar (IPM) é uma das espécies de Processo Administrativo Disciplinar Militar.", gabarito: "errado", explicacao: "Errado. O IPM é procedimento de polícia judiciária militar, não é peça do Direito Administrativo Disciplinar Militar." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A reserva remunerada e os reformados não respondem por transgressão disciplinar, pois não estão mais na ativa.", gabarito: "errado", explicacao: "Errado. Reserva remunerada e reformados sujeitam-se ao regime disciplinar (art. 8º), e os inativos são penalizados pelo Comandante-Geral (art. 73)." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A transgressão disciplinar viola preceitos da ética e valores militares, ou deveres e obrigações a que o militar está submetido.", gabarito: "certo", explicacao: "Correto. Reproduz o núcleo do art. 13 do CDMEPE." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A Investigação Preliminar visa a enfrentar dúvidas de autoria ou de materialidade.", gabarito: "certo", explicacao: "Correto. A Investigação Preliminar é procedimento que enfrenta dúvidas de autoria/materialidade." },
  { modulo: "2", tipo: "certo_errado", enunciado: "As transgressões disciplinares constituem manifestações elementares e simples, distintas dos crimes e contravenções.", gabarito: "certo", explicacao: "Correto. O art. 13 caracteriza a transgressão como manifestação elementar e simples não tipificável como crime/contravenção." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A competência para penalizar os inativos por transgressão pode ser delegada, conforme o inciso IX do art. 10 do CDMEPE.", gabarito: "certo", explicacao: "Correto. Com base no inciso IX do art. 10, a competência foi delegada (Portaria CG 399/2022) ao DPJM e ao DIP." },

  { modulo: "2", tipo: "multipla", enunciado: "Segundo o art. 13 do CDMEPE, transgressão disciplinar militar é:", alternativas: A("ação ou omissão que viole a ética/valores militares ou deveres, não tipificável como crime ou contravenção", "qualquer crime militar de menor potencial ofensivo", "apenas a omissão de socorro a superior", "a conduta que gere dano ao erário", "o descumprimento de ordem manifestamente ilegal"), gabarito: "A", explicacao: "É a definição literal do art. 13: ação ou omissão que viola ética/valores ou deveres, em manifestações não tipificáveis como crime ou contravenção." },
  { modulo: "2", tipo: "multipla", enunciado: "Estão sujeitos ao regime disciplinar do CDMEPE:", alternativas: A("militares da ativa, da reserva remunerada e reformados", "apenas os militares da ativa", "somente os oficiais", "apenas praças sem estabilidade", "exclusivamente os alunos de cursos militares"), gabarito: "A", explicacao: "O art. 8º sujeita ativa, reserva remunerada e reformados; os alunos também, por norma específica da OME." },
  { modulo: "2", tipo: "multipla", enunciado: "A apuração disciplinar do militar inativo compete a:", alternativas: A("Comandante-Geral (e autoridades dos incisos I e II do art. 10), podendo haver delegação", "qualquer comandante de OME", "exclusivamente ao Governador", "ao juiz de direito da Justiça Militar", "ao Ministério Público Militar"), gabarito: "A", explicacao: "O art. 73 atribui a competência às autoridades dos incisos I e II do art. 10 (Comandante-Geral incluído); houve delegação ao DPJM e DIP." },
  { modulo: "2", tipo: "multipla", enunciado: "Onde estão previstas as transgressões disciplinares militares?", alternativas: A("Na Parte Especial do CDMEPE, sem prejuízo de outras em lei/regulamento", "Apenas no Código Penal Militar", "Somente em portarias da Corregedoria", "Na Constituição Estadual", "Exclusivamente no Estatuto dos Militares"), gabarito: "A", explicacao: "O parágrafo único do art. 13 indica a Parte Especial do Código, sem prejuízo de outras definidas em lei ou regulamento." },
  { modulo: "2", tipo: "multipla", enunciado: "Assinale o que NÃO é peça do Direito Administrativo Disciplinar Militar:", alternativas: A("Inquérito Policial Militar (IPM)", "Sindicância Administrativa Disciplinar", "Conselho de Disciplina", "Conselho de Justificação", "Processo Apuratório Disciplinar Sumário"), gabarito: "A", explicacao: "O IPM é procedimento de polícia judiciária militar, e não peça do DADM." },

  { modulo: "2", tipo: "dissertativa", enunciado: "Conceitue transgressão disciplinar militar segundo o art. 13 do CDMEPE e indique quem está sujeito ao regime disciplinar.", modelo: { estrutura: "Conceito (art. 13) → elementos → sujeitos (art. 8º) → conclusão.", criterios: ["Definir transgressão como ação/omissão que viola ética/valores ou deveres", "Destacar que não pode ser tipificada como crime/contravenção", "Citar a sujeição de ativa, reserva remunerada e reformados (art. 8º)", "Mencionar os alunos de cursos militares"], resposta: "Transgressão disciplinar militar é toda ação ou omissão do militar que viole os preceitos da ética e os valores militares, ou contrarie deveres e obrigações, constituindo manifestações elementares e simples que não possam ser tipificadas como crime ou contravenção (art. 13 do CDMEPE). Sua aplicação deve ser motivada, considerando a natureza e a gravidade. Sujeitam-se ao regime disciplinar os militares da ativa, da reserva remunerada e os reformados (art. 8º), além dos alunos de cursos militares, conforme normas da OME." } },
  { modulo: "2", tipo: "dissertativa", enunciado: "Diferencie a Investigação Preliminar do Inquérito Policial Militar, esclarecendo se integram ou não o Direito Administrativo Disciplinar Militar.", modelo: { estrutura: "Investigação Preliminar → IPM → enquadramento → conclusão.", criterios: ["Definir a Investigação Preliminar (dúvidas de autoria/materialidade)", "Definir o IPM como procedimento de polícia judiciária militar", "Esclarecer que o IPM não é peça do DADM"], resposta: "A Investigação Preliminar é procedimento administrativo que visa enfrentar dúvidas de autoria ou de materialidade, podendo subsidiar a instauração de um PADM. O Inquérito Policial Militar (IPM), por sua vez, é procedimento de polícia judiciária militar, regido pelo Código de Processo Penal Militar, destinado à apuração de crimes militares — não integra o Direito Administrativo Disciplinar Militar, embora muitas vezes seja com ele confundido." } },

  // ════════ MÓDULO 3 — Processo, Procedimento e Espécies de PADM ════════
  { modulo: "3", tipo: "certo_errado", enunciado: "A Sindicância Administrativa Disciplinar (SAD) destina-se a apurar transgressões simples que necessitem de instrução probatória.", gabarito: "certo", explicacao: "Correto. A SAD (IN 002/2017) apura transgressões simples que exigem instrução probante." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Processo Apuratório Disciplinar Sumário (PADS) destina-se a transgressões simples que NÃO necessitam de instrução probatória.", gabarito: "certo", explicacao: "Correto. O PADS (Provimento Correicional 14/2019) trata de transgressões simples sem necessidade de instrução probatória." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Conselho de Justificação é o PADM de caráter demissório aplicável às praças com e sem estabilidade.", gabarito: "errado", explicacao: "Errado. O Conselho de Justificação destina-se aos oficiais. Às praças aplica-se o Conselho de Disciplina." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Conselho de Disciplina é destinado às praças (com e sem estabilidade) e tem previsão no Decreto nº 3.639/1975.", gabarito: "certo", explicacao: "Correto. O Conselho de Disciplina aplica-se às praças e está previsto no Decreto nº 3.639/1975." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Processo e procedimento são expressões absolutamente sinônimas no estudo do PADM.", gabarito: "errado", explicacao: "Errado. Processo é a concatenação de atos; procedimento é a forma de organizar os atos (ou o ato unitário). Um processo compõe-se de vários procedimentos." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Os PADMs de caráter demissório têm processamento exclusivo na Corregedoria-Geral da SDS.", gabarito: "certo", explicacao: "Correto. Os processos demissórios (Conselhos de Disciplina e de Justificação) tramitam exclusivamente na Corregedoria-Geral da SDS." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Conselho de Justificação destinado aos oficiais tem fundamento na Lei Federal nº 5.836/1972.", gabarito: "certo", explicacao: "Correto. O Conselho de Justificação tem base na Lei Federal nº 5.836/1972 (e Lei Estadual nº 6.957/1975)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A SAD e o PADS são exemplos de PADM de caráter apuratório.", gabarito: "certo", explicacao: "Correto. SAD e PADS são espécies apuratórias; Conselhos de Disciplina e de Justificação são demissórios." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Um processo é composto, em regra, por um único procedimento indivisível.", gabarito: "errado", explicacao: "Errado. Um processo pode ser composto de diversos procedimentos (atos organizados)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Processo de Licenciamento a Bem da Disciplina foi extinto e transformado em Conselho de Disciplina, mas a sanção de licenciamento às praças sem estabilidade continua a existir.", gabarito: "certo", explicacao: "Correto. A apostila registra a extinção do processo de licenciamento e a manutenção da respectiva sanção às praças sem estabilidade." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O procedimento, em uma de suas acepções, significa a maneira pela qual os atos são organizados dentro de um processo.", gabarito: "certo", explicacao: "Correto. Procedimento tem dupla acepção: a organização dos atos no processo ou o próprio ato unitário." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A Sindicância Administrativa Disciplinar destina-se exclusivamente a apurar crimes militares.", gabarito: "errado", explicacao: "Errado. A SAD apura transgressões disciplinares simples que necessitem de instrução probatória, e não crimes militares." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Conselho de Disciplina pode resultar em licenciamento ou exclusão a bem da disciplina, conforme o caso.", gabarito: "certo", explicacao: "Correto. Como PADM demissório aplicável às praças, pode levar a licenciamento (sem estabilidade) ou exclusão (com estabilidade)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O PADS exige, em todos os casos, ampla dilação probatória com produção de perícias.", gabarito: "errado", explicacao: "Errado. O PADS destina-se justamente às transgressões simples que NÃO necessitam de instrução probatória." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A Lei Estadual nº 6.957/1975 também fundamenta o Conselho de Justificação dos oficiais.", gabarito: "certo", explicacao: "Correto. O Conselho de Justificação baseia-se na Lei Federal nº 5.836/1972 e na Lei Estadual nº 6.957/1975." },

  { modulo: "3", tipo: "multipla", enunciado: "Qual espécie de PADM, de caráter demissório, é aplicável aos OFICIAIS?", alternativas: A("Conselho de Justificação", "Conselho de Disciplina", "Sindicância Administrativa Disciplinar", "Processo Apuratório Disciplinar Sumário", "Inquérito Policial Militar"), gabarito: "A", explicacao: "O Conselho de Justificação destina-se aos oficiais (Lei 5.836/72); o Conselho de Disciplina, às praças." },
  { modulo: "3", tipo: "multipla", enunciado: "A diferença entre a SAD e o PADS está em que:", alternativas: A("a SAD apura transgressões simples que necessitam de instrução probatória; o PADS, as que não necessitam", "a SAD é para oficiais e o PADS para praças", "a SAD é demissória e o PADS apuratório", "o PADS apura crimes e a SAD transgressões", "não há diferença entre eles"), gabarito: "A", explicacao: "Ambos são apuratórios de transgressões simples; a SAD exige instrução probante, o PADS dispensa-a." },
  { modulo: "3", tipo: "multipla", enunciado: "Assinale a espécie de PADM de caráter demissório aplicável às praças:", alternativas: A("Conselho de Disciplina (Decreto 3.639/1975)", "Conselho de Justificação (Lei 5.836/1972)", "Sindicância Administrativa Disciplinar", "PADS", "Investigação Preliminar"), gabarito: "A", explicacao: "O Conselho de Disciplina é o PADM demissório das praças, com base no Decreto nº 3.639/1975." },
  { modulo: "3", tipo: "multipla", enunciado: "Sobre processo e procedimento, é correto afirmar:", alternativas: A("o processo é a concatenação de atos e pode ser composto de vários procedimentos", "procedimento e processo são sinônimos perfeitos", "o procedimento sempre engloba vários processos", "o processo é o ato unitário e o procedimento, o conjunto", "ambos são peças de polícia judiciária"), gabarito: "A", explicacao: "Processo é a concatenação de atos; procedimento é a forma de organizá-los (ou o ato unitário). Um processo compõe-se de vários procedimentos." },
  { modulo: "3", tipo: "multipla", enunciado: "Os processos de caráter demissório (Conselhos de Disciplina e de Justificação) têm processamento:", alternativas: A("exclusivo na Corregedoria-Geral da SDS", "em qualquer OME", "no Ministério Público Militar", "na Justiça Militar estadual", "na Diretoria de Ensino"), gabarito: "A", explicacao: "O processamento dos PADMs demissórios é exclusivo da Corregedoria-Geral da SDS." },

  { modulo: "3", tipo: "dissertativa", enunciado: "Diferencie as espécies de PADM de caráter apuratório (SAD e PADS) das de caráter demissório (Conselho de Disciplina e Conselho de Justificação), indicando o público de cada conselho.", modelo: { estrutura: "Apuratórios (SAD/PADS) → demissórios (Conselhos) → público → conclusão.", criterios: ["Definir SAD (instrução probante) e PADS (sem instrução probante)", "Definir os conselhos como demissórios", "Indicar Conselho de Disciplina = praças; Conselho de Justificação = oficiais", "Citar o processamento na Corregedoria"], resposta: "Os PADMs apuratórios destinam-se a transgressões simples: a Sindicância Administrativa Disciplinar (SAD) quando há necessidade de instrução probatória, e o Processo Apuratório Disciplinar Sumário (PADS) quando essa instrução é dispensável. Os PADMs demissórios visam ao desligamento: o Conselho de Disciplina aplica-se às praças (com e sem estabilidade), e o Conselho de Justificação, aos oficiais. Os processos demissórios têm processamento exclusivo na Corregedoria-Geral da SDS." } },
  { modulo: "3", tipo: "dissertativa", enunciado: "Explique a distinção entre processo e procedimento no âmbito do PADM.", modelo: { estrutura: "Conceito de processo → conceito de procedimento → relação → conclusão.", criterios: ["Definir processo como concatenação de atos", "Apontar a dupla acepção de procedimento", "Afirmar que um processo é composto de vários procedimentos"], resposta: "Processo é a concatenação de atos voltada a alterar a natureza ou a forma de determinada situação. Procedimento tem dupla acepção: pode significar a maneira como os atos são organizados dentro de um processo ou o próprio ato unitário. Disso decorre que um processo pode ser composto de diversos procedimentos — sendo, portanto, conceitos relacionados, mas não sinônimos." } },

  // ════════ MÓDULO 4 — Poder Disciplinar e Competência ════════
  { modulo: "4", tipo: "certo_errado", enunciado: "A competência para aplicar penas disciplinares é inerente ao cargo ou função ocupada, e não ao grau hierárquico.", gabarito: "certo", explicacao: "Correto. O art. 10 do CDMEPE vincula a competência ao cargo/função, não ao grau hierárquico." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O Governador do Estado e o Secretário de Defesa Social têm competência disciplinar em relação a todos os integrantes das Corporações Militares Estaduais.", gabarito: "certo", explicacao: "Correto. É o inciso I do art. 10 do CDMEPE." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Pela Teoria dos Poderes Implícitos, quem recebe da Constituição uma função recebe também, implicitamente, os meios necessários para executá-la.", gabarito: "certo", explicacao: "Correto. É a definição da Teoria dos Poderes Implícitos, que fundamenta a competência para instaurar o PADM (RE 593.727)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A competência para aplicar penas disciplinares pertence sempre ao militar de maior grau hierárquico presente, independentemente do cargo.", gabarito: "errado", explicacao: "Errado. A competência é inerente ao cargo ou função, e não ao grau hierárquico (art. 10)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A Teoria dos Poderes Implícitos tem origem norte-americana e foi invocada no julgamento do RE 593.727 pelo STF.", gabarito: "certo", explicacao: "Correto. A teoria tem origem norte-americana (McCulloch v. Maryland) e foi referida no RE 593.727/MG." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Os Comandantes-Gerais têm competência disciplinar apenas sobre os oficiais de suas Corporações.", gabarito: "errado", explicacao: "Errado. O inciso II do art. 10 dá competência aos Comandantes-Gerais sobre todos os integrantes de suas respectivas Corporações." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Autoridade que, em razão do cargo ou função, receba delegação específica de autoridade superior competente pode aplicar penas disciplinares.", gabarito: "certo", explicacao: "Correto. É a hipótese do inciso IX do art. 10 do CDMEPE." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O Corregedor-Geral da SDS recebeu delegação do Secretário de Defesa Social para instaurar Conselho de Disciplina e PADS.", gabarito: "certo", explicacao: "Correto. A Portaria SDS nº 3642/2018 delegou ao Corregedor-Geral tais atribuições." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A competência disciplinar é intransferível e não admite qualquer espécie de delegação.", gabarito: "errado", explicacao: "Errado. O inciso IX do art. 10 admite delegação específica por autoridade competente superior." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O Chefe da Casa Militar do Governo do Estado tem competência disciplinar em relação aos que servem sob sua chefia.", gabarito: "certo", explicacao: "Correto. É o inciso III do art. 10 do CDMEPE." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A delegação da competência disciplinar aos Diretores (DPJM e DIP) para os inativos baseou-se no inciso IX do art. 10 do CDMEPE.", gabarito: "certo", explicacao: "Correto. A Portaria CG 399/2022 delegou ao DPJM e DIP com base no inciso IX do art. 10." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Comandantes de OME com autonomia administrativa têm competência disciplinar sobre os que servem sob seus comandos.", gabarito: "certo", explicacao: "Correto. É o inciso VII do art. 10 do CDMEPE." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A Teoria dos Poderes Implícitos não tem qualquer relação com a competência para instaurar PADM.", gabarito: "errado", explicacao: "Errado. É justamente a teoria que fundamenta a competência implícita para instaurar o PADM." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Os Comandantes de OME que exerçam atividades de ensino têm competência disciplinar inclusive sobre os alunos matriculados naquelas OME.", gabarito: "certo", explicacao: "Correto. É o inciso VIII do art. 10 do CDMEPE." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O poder disciplinar visa exclusivamente a punir, sem qualquer finalidade educativa ou de preservação da disciplina coletiva.", gabarito: "errado", explicacao: "Errado. A pena disciplinar tem finalidade de reeducação do transgressor e da coletividade (art. 27), não sendo meramente punitiva." },

  { modulo: "4", tipo: "multipla", enunciado: "Segundo o art. 10 do CDMEPE, a competência para aplicar penas disciplinares é inerente:", alternativas: A("ao cargo ou função ocupada", "ao grau hierárquico", "ao tempo de serviço", "à antiguidade na corporação", "à lotação na capital"), gabarito: "A", explicacao: "A competência é inerente ao cargo/função, e não ao grau hierárquico." },
  { modulo: "4", tipo: "multipla", enunciado: "A Teoria dos Poderes Implícitos sustenta que:", alternativas: A("quem recebe uma função recebe, implicitamente, os meios para executá-la", "todo poder deve estar expresso em lei, sem exceção", "a competência decorre apenas da hierarquia", "o silêncio da lei impede qualquer ação estatal", "os poderes são sempre exclusivos da União"), gabarito: "A", explicacao: "A teoria (origem norte-americana) fundamenta a competência para instaurar o PADM: concedida a função, conferem-se os meios necessários." },
  { modulo: "4", tipo: "multipla", enunciado: "Quem possui competência disciplinar sobre TODOS os integrantes das Corporações Militares Estaduais?", alternativas: A("O Governador e o Secretário de Defesa Social", "Apenas os comandantes de batalhão", "Somente o Corregedor-Geral", "Os comandantes de companhia", "O juiz da Justiça Militar"), gabarito: "A", explicacao: "Inciso I do art. 10: Governador e Secretário de Defesa Social, em relação a todos os integrantes." },
  { modulo: "4", tipo: "multipla", enunciado: "A aplicação de penas a militares inativos foi delegada (Portaria CG 399/2022) com base no inciso IX do art. 10 a quais autoridades?", alternativas: A("Diretor de Polícia Judiciária Militar (DPJM) e Diretor de Inativos e Pensionistas (DIP)", "Comandantes de OME apenas", "Corregedor-Geral apenas", "Governador e Vice", "Chefe da Casa Militar"), gabarito: "A", explicacao: "A delegação para reprimenda dos inativos foi feita ao DPJM e ao DIP." },
  { modulo: "4", tipo: "multipla", enunciado: "Sobre a competência disciplinar, é correto afirmar que:", alternativas: A("admite delegação específica por autoridade competente superior (art. 10, IX)", "jamais pode ser delegada", "pertence ao militar mais antigo", "depende do grau hierárquico", "é exclusiva do Poder Judiciário"), gabarito: "A", explicacao: "O inciso IX do art. 10 admite delegação específica proveniente de autoridade competente superior." },

  { modulo: "4", tipo: "dissertativa", enunciado: "Explique a regra de competência para aplicação de penas disciplinares no CDMEPE (art. 10) e como a Teoria dos Poderes Implícitos fundamenta a instauração do PADM.", modelo: { estrutura: "Regra do art. 10 (cargo/função) → autoridades → Teoria dos Poderes Implícitos → conclusão.", criterios: ["Afirmar que a competência é inerente ao cargo/função, não ao grau hierárquico", "Citar autoridades (Governador, Secretário, Comandantes-Gerais etc.)", "Explicar a Teoria dos Poderes Implícitos", "Relacionar com a competência para instaurar PADM"], resposta: "Pelo art. 10 do CDMEPE, a competência para aplicar penas disciplinares é inerente ao cargo ou função ocupada, e não ao grau hierárquico. São competentes, entre outros, o Governador e o Secretário de Defesa Social (todos os integrantes), os Comandantes-Gerais, o Chefe da Casa Militar e quem receba delegação específica (inciso IX). A Teoria dos Poderes Implícitos, de origem norte-americana, sustenta que, ao conceder uma função a um órgão, a Constituição lhe confere implicitamente os meios necessários para executá-la — fundamento da competência para instaurar o PADM (RE 593.727)." } },
  { modulo: "4", tipo: "dissertativa", enunciado: "Disserte sobre a possibilidade de delegação da competência disciplinar no CDMEPE, citando exemplo concreto ocorrido na PMPE.", modelo: { estrutura: "Regra → previsão de delegação (art. 10, IX) → exemplo → conclusão.", criterios: ["Afirmar que a competência decorre do cargo/função", "Citar o inciso IX do art. 10 (delegação específica)", "Exemplificar com a delegação ao DPJM/DIP (inativos) ou ao Corregedor-Geral"], resposta: "A competência disciplinar decorre do cargo ou função (art. 10), mas admite delegação específica por autoridade competente superior, nos termos do inciso IX do mesmo artigo. Exemplos concretos na PMPE: a Portaria SDS nº 3642/2018, que delegou ao Corregedor-Geral atribuições para instaurar Conselho de Disciplina e PADS; e a Portaria CG nº 399/2022, que delegou ao Diretor de Polícia Judiciária Militar e ao Diretor de Inativos e Pensionistas a aplicação de reprimenda disciplinar aos militares inativos." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`DADM (mods 1-4): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
