import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "GPGA"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 6 — Políticas Públicas ════════
  { modulo: "6", tipo: "certo_errado", enunciado: "Política pública pode ser entendida como um fluxo de decisões públicas voltado a manter o equilíbrio social ou a modificar a realidade.", gabarito: "certo", explicacao: "Correto. É a definição (Saravia) adotada na apostila." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Uma das características das políticas públicas é ser 'institucional', pois o governo as institui em seus programas.", gabarito: "certo", explicacao: "Correto. A característica institucional indica que o governo institui as políticas em seus programas." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A característica 'causal' das políticas públicas significa que, quando implementadas, promovem impactos na sociedade.", gabarito: "certo", explicacao: "Correto. A política pública é causal: gera impactos sociais (positivos ou negativos)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O ciclo das políticas públicas inicia-se pela avaliação e termina na construção da agenda.", gabarito: "errado", explicacao: "Errado. O ciclo inicia na construção da agenda e termina na avaliação." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A 'construção da agenda' parte da identificação de um problema social e da vontade de discuti-lo, colocando-o em pauta.", gabarito: "certo", explicacao: "Correto. A construção da agenda identifica o problema e o coloca em pauta para o governo." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Na fase de 'formulação', define-se um planejamento e elencam-se alternativas de solução para o problema detectado.", gabarito: "certo", explicacao: "Correto. A formulação elabora o planejamento e as alternativas de solução." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Na fase de implementação, as ações começam a acontecer e o problema passa a ser enfrentado no mundo real.", gabarito: "certo", explicacao: "Correto. A implementação concretiza as ações planejadas." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A avaliação é dispensável quando a política pública foi bem formulada.", gabarito: "errado", explicacao: "Errado. A avaliação é fase essencial: verifica eficiência/eficácia e permite ajustar a política." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A característica 'comportamental' das políticas públicas relaciona-se à 'vontade de fazer'.", gabarito: "certo", explicacao: "Correto. A característica comportamental traduz a 'vontade de fazer' necessária à política." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O processo decisório define as responsabilidades e os métodos para o enfrentamento do problema.", gabarito: "certo", explicacao: "Correto. A tomada de decisão define responsabilidades e métodos de enfrentamento." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A segurança pública é um tema de política pública permanente para os governos.", gabarito: "certo", explicacao: "Correto. A apostila destaca a segurança pública como tema eterno das políticas públicas." },
  { modulo: "6", tipo: "certo_errado", enunciado: "São fases do ciclo de políticas públicas: construção da agenda, formulação, processo decisório, implementação e avaliação.", gabarito: "certo", explicacao: "Correto. São as cinco fases do ciclo adotado na apostila." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A característica 'decisória' indica que a política prescinde de qualquer cadeia de decisões para ser eficaz.", gabarito: "errado", explicacao: "Errado. A característica decisória indica que a política NECESSITA de uma cadeia competente de decisões para lograr eficácia." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Caso a avaliação aponte falhas, cabe ao gestor ajustar a política implementada ou em implementação.", gabarito: "certo", explicacao: "Correto. A avaliação permite o ajuste da política, se necessário." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A formulação de política pública é a etapa em que as ações já estão sendo executadas no mundo real.", gabarito: "errado", explicacao: "Errado. A execução real ocorre na implementação; a formulação é o planejamento e a definição de alternativas." },

  { modulo: "6", tipo: "multipla", enunciado: "As fases do ciclo de políticas públicas, na ordem, são:", alternativas: A("agenda → formulação → decisão → implementação → avaliação", "avaliação → agenda → decisão → formulação → implementação", "formulação → agenda → implementação → decisão → avaliação", "decisão → agenda → formulação → avaliação → implementação", "implementação → avaliação → agenda → formulação → decisão"), gabarito: "A", explicacao: "O ciclo: construção da agenda, formulação, processo decisório, implementação e avaliação." },
  { modulo: "6", tipo: "multipla", enunciado: "São características das políticas públicas, EXCETO:", alternativas: A("aleatoriedade", "institucional", "decisória", "comportamental", "causal"), gabarito: "A", explicacao: "As características são institucional, decisória, comportamental e causal. 'Aleatoriedade' não é característica." },
  { modulo: "6", tipo: "multipla", enunciado: "A fase em que se identifica um problema social e ele é colocado em pauta para o governo é a:", alternativas: A("construção da agenda", "formulação", "implementação", "avaliação", "processo decisório"), gabarito: "A", explicacao: "A construção da agenda parte da identificação do problema e o coloca em pauta." },
  { modulo: "6", tipo: "multipla", enunciado: "A característica que traduz a 'vontade de fazer' é a:", alternativas: A("comportamental", "institucional", "causal", "decisória", "aleatória"), gabarito: "A", explicacao: "A característica comportamental refere-se à 'vontade de fazer'." },
  { modulo: "6", tipo: "multipla", enunciado: "A fase que verifica se a política foi eficiente/eficaz e permite ajustes é a:", alternativas: A("avaliação", "formulação", "agenda", "implementação", "decisão"), gabarito: "A", explicacao: "A avaliação afere eficiência/eficácia e permite ajustar a política." },

  { modulo: "6", tipo: "dissertativa", enunciado: "Descreva as cinco fases do ciclo de políticas públicas.", modelo: { estrutura: "Listar e explicar agenda, formulação, decisão, implementação e avaliação.", criterios: ["Construção da agenda: identificar e pautar o problema", "Formulação: planejar e elencar alternativas", "Processo decisório: definir responsabilidades e métodos", "Implementação: executar as ações", "Avaliação: aferir resultados e ajustar"], resposta: "O ciclo de políticas públicas tem cinco fases: 1) Construção da agenda — identifica-se um problema social e a vontade de discuti-lo, colocando-o em pauta; 2) Formulação — define-se o planejamento e elencam-se alternativas de solução; 3) Processo decisório — definem-se as responsabilidades e os métodos de enfrentamento; 4) Implementação — as ações começam a acontecer e o problema é enfrentado no mundo real; 5) Avaliação — afere-se a eficiência e a eficácia e, se necessário, ajusta-se a política implementada ou em implementação." } },
  { modulo: "6", tipo: "dissertativa", enunciado: "Conceitue política pública e apresente suas características predominantes.", modelo: { estrutura: "Conceito → características (institucional, decisória, comportamental, causal).", criterios: ["Definir política pública (fluxo de decisões públicas)", "Listar e explicar as 4 características"], resposta: "Política pública é um fluxo de decisões públicas orientado a manter o equilíbrio social ou a introduzir mudanças na realidade, condicionado pelos valores e visões dos que decidem. Suas características predominantes são: institucional (o governo a institui em seus programas), decisória (necessita de uma cadeia competente de decisões para ser eficaz), comportamental (depende da 'vontade de fazer') e causal (quando implementada, promove impactos sociais, positivos ou negativos)." } },

  // ════════ MÓDULO 7 — Controle da Administração Pública ════════
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle interno é exercido dentro de cada poder, para fiscalizar seus próprios atos.", gabarito: "certo", explicacao: "Correto. O controle interno ocorre dentro do próprio poder (ex.: CGU)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle externo é exercido pelo próprio poder controlado sobre seus atos.", gabarito: "errado", explicacao: "Errado. O controle externo é exercido FORA do poder controlado (ex.: TCU/Congresso, MP, controle social)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Quanto ao momento, o controle pode ser prévio/preventivo, concomitante e posterior/corretivo.", gabarito: "certo", explicacao: "Correto. São as três classificações quanto ao momento." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle quanto ao aspecto pode ser de legalidade (conformidade) e de mérito (conveniência e oportunidade).", gabarito: "certo", explicacao: "Correto. O controle de legalidade afere conformidade; o de mérito, conveniência/oportunidade." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O art. 70 da CF prevê a fiscalização contábil, financeira, orçamentária, operacional e patrimonial por controle externo e interno.", gabarito: "certo", explicacao: "Correto. É o caput do art. 70 da CF." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle hierárquico é exercido por órgãos superiores sobre os inferiores.", gabarito: "certo", explicacao: "Correto. O controle hierárquico (quanto à amplitude) é dos superiores sobre os inferiores." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle finalístico é exercido pela Administração indireta sobre a Administração direta.", gabarito: "errado", explicacao: "Errado. O controle finalístico é da Administração DIRETA sobre a INDIRETA (limitado pela autonomia desta)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O principal cerne do controle da Administração Pública é a legalidade dos atos.", gabarito: "certo", explicacao: "Correto. A apostila aponta a legalidade como o principal (mas não único) cerne do controle." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A CGU é citada como exemplo de controle interno no âmbito federal.", gabarito: "certo", explicacao: "Correto. A CGU exemplifica o controle interno federal." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle de mérito analisa apenas a conformidade do ato com a lei.", gabarito: "errado", explicacao: "Errado. A conformidade com a lei é o controle de LEGALIDADE; o de mérito analisa conveniência, eficiência e oportunidade." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Quanto aos órgãos, o controle pode ser administrativo, legislativo ou judicial.", gabarito: "certo", explicacao: "Correto. É a classificação quanto aos órgãos que exercem o controle." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle social (ONGs, conselhos, mídia) é considerado, por parte da doutrina, uma forma de controle externo.", gabarito: "certo", explicacao: "Correto. A apostila inclui o controle social entre as formas de controle externo." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle concomitante ocorre após a consumação do ato administrativo.", gabarito: "errado", explicacao: "Errado. O concomitante ocorre DURANTE a execução do ato; o posterior/corretivo é que ocorre após a consumação." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Não há gestão sem controle, sendo o controle a última das funções administrativas (após planejar, organizar e dirigir).", gabarito: "certo", explicacao: "Correto. O controle é a última função administrativa, conforme Chiavenato citado na apostila." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O controle prévio/preventivo ocorre antes da construção do ato administrativo.", gabarito: "certo", explicacao: "Correto. O controle prévio/preventivo antecede o ato (fase de preparação)." },

  { modulo: "7", tipo: "multipla", enunciado: "Quanto à ORIGEM, o controle classifica-se em:", alternativas: A("interno e externo", "prévio e posterior", "legalidade e mérito", "hierárquico e finalístico", "administrativo e judicial"), gabarito: "A", explicacao: "Quanto à origem: interno (dentro do poder) e externo (fora do poder controlado)." },
  { modulo: "7", tipo: "multipla", enunciado: "O controle exercido DURANTE a execução do ato administrativo é:", alternativas: A("concomitante", "prévio", "posterior", "finalístico", "hierárquico"), gabarito: "A", explicacao: "O controle concomitante ocorre durante a execução do ato." },
  { modulo: "7", tipo: "multipla", enunciado: "O controle que analisa a conveniência, a eficiência e a oportunidade do ato é o de:", alternativas: A("mérito", "legalidade", "origem", "amplitude", "órgãos"), gabarito: "A", explicacao: "O controle de mérito analisa conveniência/eficiência/oportunidade; o de legalidade, a conformidade." },
  { modulo: "7", tipo: "multipla", enunciado: "O controle exercido pela Administração direta sobre a indireta é o:", alternativas: A("finalístico", "hierárquico", "interno", "concomitante", "social"), gabarito: "A", explicacao: "O controle finalístico é da Administração direta sobre a indireta." },
  { modulo: "7", tipo: "multipla", enunciado: "O fundamento constitucional da fiscalização contábil, financeira e orçamentária (controle externo + interno) é o:", alternativas: A("art. 70 da CF", "art. 37 da CF", "art. 165 da CF", "art. 144 da CF", "art. 5º da CF"), gabarito: "A", explicacao: "O art. 70 da CF trata da fiscalização por controle externo (Congresso) e interno de cada poder." },

  { modulo: "7", tipo: "dissertativa", enunciado: "Classifique o controle da Administração Pública quanto à origem, ao momento e ao aspecto.", modelo: { estrutura: "Origem → momento → aspecto.", criterios: ["Origem: interno e externo", "Momento: prévio, concomitante, posterior", "Aspecto: legalidade e mérito"], resposta: "Quanto à origem, o controle é interno (exercido dentro do próprio poder, ex.: CGU) ou externo (exercido fora do poder controlado, ex.: TCU/Congresso, MP, controle social). Quanto ao momento, é prévio/preventivo (antes do ato), concomitante (durante a execução) ou posterior/corretivo (após a consumação). Quanto ao aspecto, é de legalidade (verifica a conformidade do ato com a lei) ou de mérito (analisa a conveniência, a eficiência e a oportunidade do ato)." } },
  { modulo: "7", tipo: "dissertativa", enunciado: "Explique a diferença entre controle hierárquico e controle finalístico e cite o fundamento constitucional do controle (art. 70).", modelo: { estrutura: "Hierárquico → finalístico → art. 70 → conclusão.", criterios: ["Hierárquico: superior sobre inferior", "Finalístico: direta sobre indireta", "Citar o art. 70 da CF (controle externo + interno)"], resposta: "Quanto à amplitude, o controle hierárquico é exercido por órgãos superiores sobre os inferiores, dentro da mesma estrutura. O controle finalístico é exercido pela Administração direta sobre a indireta, limitado pela autonomia desta e dependente de previsão legal. O fundamento constitucional do controle está no art. 70 da CF, que prevê a fiscalização contábil, financeira, orçamentária, operacional e patrimonial por controle externo (Congresso) e pelo sistema de controle interno de cada Poder, tendo a legalidade como principal cerne." } },

  // ════════ MÓDULO 8 — Ferramentas Gerenciais ════════
  { modulo: "8", tipo: "certo_errado", enunciado: "Benchmarking é o ato de comparar a própria atividade/produto com uma referência ou concorrente, buscando boas práticas.", gabarito: "certo", explicacao: "Correto. Benchmarking (de 'benchmark', referência) busca boas práticas pela comparação." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O ciclo PDCA corresponde às etapas Plan, Do, Check e Action.", gabarito: "certo", explicacao: "Correto. PDCA = Plan (planejar), Do (executar), Check (verificar), Action (agir)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O PDCA também é conhecido como ciclo de Pareto.", gabarito: "errado", explicacao: "Errado. O PDCA é conhecido como ciclo de Deming. Pareto está associado ao Diagrama de Pareto (80/20)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O Diagrama de Pareto baseia-se na premissa de que 80% dos problemas decorrem de 20% das causas.", gabarito: "certo", explicacao: "Correto. É o princípio 80/20 do Diagrama de Pareto." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Kaizen é uma técnica de melhoria contínua, com envolvimento permanente das pessoas.", gabarito: "certo", explicacao: "Correto. Kaizen significa melhoria contínua, com participação das pessoas." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O orçamento participativo busca distribuir responsabilidades na alocação de recursos com os stakeholders.", gabarito: "certo", explicacao: "Correto. O orçamento participativo envolve os interessados na decisão sobre alocação de recursos." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O ciclo PDCA tem origem nos anos 1950.", gabarito: "certo", explicacao: "Correto. A apostila situa a origem do PDCA em meados dos anos 1950." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O Diagrama de Pareto recebeu esse nome em homenagem ao economista italiano Vilfredo Pareto.", gabarito: "certo", explicacao: "Correto. O nome homenageia o economista Vilfredo Pareto." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O benchmarking consiste em ignorar as práticas dos concorrentes e inovar isoladamente.", gabarito: "errado", explicacao: "Errado. O benchmarking justamente compara com referências/concorrentes para adotar boas práticas." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Brainstorming, Ishikawa, 5S e BSC são exemplos de ferramentas gerenciais aplicáveis à gestão pública.", gabarito: "certo", explicacao: "Correto. A apostila cita essas ferramentas entre as aplicáveis à gestão pública." },
  { modulo: "8", tipo: "certo_errado", enunciado: "No ciclo PDCA, a etapa 'Check' corresponde ao planejamento inicial.", gabarito: "errado", explicacao: "Errado. 'Check' é a verificação; o planejamento é a etapa 'Plan'." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A ferramenta Kaizen propõe identificar problemas, discutir com a equipe, aplicar soluções e rever resultados de forma permanente.", gabarito: "certo", explicacao: "Correto. É o processo de melhoria contínua (Kaizen) descrito na apostila." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Segundo o princípio de Pareto, deve-se focar primeiro nos problemas/causas prioritários (os mais danosos).", gabarito: "certo", explicacao: "Correto. O Diagrama de Pareto orienta a focar nos poucos vitais (20%) que causam a maioria dos problemas." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Downsizing é sinônimo de aumento da estrutura organizacional.", gabarito: "errado", explicacao: "Errado. Downsizing significa enxugamento (redução) da estrutura, não aumento." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O aprimoramento constante é um dever do gestor público que busca a excelência.", gabarito: "certo", explicacao: "Correto. A apostila destaca o aprimoramento contínuo como dever do gestor de excelência." },

  { modulo: "8", tipo: "multipla", enunciado: "As etapas do ciclo PDCA são:", alternativas: A("Plan, Do, Check, Action", "Plan, Define, Control, Act", "Prepare, Do, Choose, Act", "Plan, Deliver, Check, Adjust", "Predict, Do, Compare, Apply"), gabarito: "A", explicacao: "PDCA = Plan (planejar), Do (executar), Check (verificar), Action (agir) — ciclo de Deming." },
  { modulo: "8", tipo: "multipla", enunciado: "A ferramenta baseada na premissa de que 80% dos problemas decorrem de 20% das causas é:", alternativas: A("Diagrama de Pareto", "Benchmarking", "PDCA", "Kaizen", "Orçamento participativo"), gabarito: "A", explicacao: "É o Diagrama de Pareto (princípio 80/20)." },
  { modulo: "8", tipo: "multipla", enunciado: "A comparação da própria atividade com uma referência/concorrente para adotar boas práticas é o:", alternativas: A("benchmarking", "downsizing", "brainstorming", "kaizen", "5S"), gabarito: "A", explicacao: "Benchmarking é a comparação com referências para melhoria." },
  { modulo: "8", tipo: "multipla", enunciado: "A técnica de melhoria contínua com envolvimento permanente das pessoas é o:", alternativas: A("Kaizen", "Pareto", "Benchmarking", "Downsizing", "BSC"), gabarito: "A", explicacao: "Kaizen é a melhoria contínua, com participação das pessoas." },
  { modulo: "8", tipo: "multipla", enunciado: "O ciclo PDCA também é conhecido como ciclo de:", alternativas: A("Deming", "Pareto", "Ishikawa", "Maslow", "Taylor"), gabarito: "A", explicacao: "O PDCA é também chamado de ciclo de Deming." },

  { modulo: "8", tipo: "dissertativa", enunciado: "Explique o ciclo PDCA e o Diagrama de Pareto como ferramentas gerenciais.", modelo: { estrutura: "PDCA (etapas) → Pareto (80/20) → utilidade.", criterios: ["Detalhar Plan/Do/Check/Action (ciclo de Deming)", "Explicar o princípio 80/20 do Pareto", "Apontar a utilidade de cada uma"], resposta: "O PDCA (ciclo de Deming) é um ciclo contínuo de melhoria composto por quatro etapas: Plan (planejar), Do (executar), Check (verificar) e Action (agir/corrigir), buscando maior efetividade na produção do serviço/produto. O Diagrama de Pareto baseia-se na premissa de que cerca de 80% dos problemas decorrem de apenas 20% das causas; por isso, estratificam-se os problemas em um histograma e foca-se nos prioritários (os poucos vitais), otimizando o esforço de melhoria." } },
  { modulo: "8", tipo: "dissertativa", enunciado: "Conceitue benchmarking, kaizen e orçamento participativo.", modelo: { estrutura: "Benchmarking → kaizen → orçamento participativo.", criterios: ["Benchmarking: comparação com referência", "Kaizen: melhoria contínua", "Orçamento participativo: distribuir responsabilidade com stakeholders"], resposta: "Benchmarking é o ato de comparar a própria atividade ou produto com uma referência ou concorrente, na busca por boas práticas e melhoria constante. Kaizen significa melhoria contínua: insere na organização o princípio permanente de envolvimento das pessoas para evoluir as tarefas no dia a dia (identificar problemas, propor e aplicar soluções, rever resultados). O orçamento participativo visa distribuir responsabilidades na decisão de alocação de recursos com os stakeholders, ampliando a participação da sociedade na gestão." } },

  // ════════ MÓDULO 9 — Estrutura organizacional e excelência ════════
  { modulo: "9", tipo: "certo_errado", enunciado: "A estrutura organizacional corresponde ao modo pelo qual a autoridade é distribuída, as atividades são divididas e a comunicação é estabelecida.", gabarito: "certo", explicacao: "Correto. É o conceito de estrutura organizacional adotado na apostila." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O organograma representa graficamente a estrutura da organização.", gabarito: "certo", explicacao: "Correto. O organograma é a representação gráfica da estrutura." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Organizar a Administração significa organizar seu aparato: estrutura, recursos, órgãos, agentes, serviços e competências.", gabarito: "certo", explicacao: "Correto. É a noção de organização administrativa apresentada na apostila." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A gestão pública de excelência mede eficiência/eficácia apenas pelo aumento de receitas, como na iniciativa privada.", gabarito: "errado", explicacao: "Errado. Na esfera pública, mede-se pelo cumprimento da missão e pelo atendimento de qualidade ao cidadão (não por receitas)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A gestão de excelência busca a qualidade contínua no serviço público.", gabarito: "certo", explicacao: "Correto. A excelência associa-se à busca contínua pela qualidade." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A cultura organizacional não tem qualquer relação com o comportamento dos integrantes da organização.", gabarito: "errado", explicacao: "Errado. A cultura e o comportamento organizacional influenciam diretamente o funcionamento da instituição." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A eficiência e a eficácia das entidades públicas medem-se também pelo cumprimento de sua missão e pelo atendimento de qualidade às demandas do cidadão.", gabarito: "certo", explicacao: "Correto. É o critério de aferição no setor público (diferente da lógica privada de receitas)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A estrutura organizacional é irrelevante para o sistema de comunicação da instituição.", gabarito: "errado", explicacao: "Errado. A estrutura define como a comunicação é estabelecida na organização." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Cada Estado possui uma Lei de Organização Básica; em Pernambuco é a Lei nº 11.328/1996.", gabarito: "certo", explicacao: "Correto. A Lei de Organização Básica da PMPE é a Lei nº 11.328/1996." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A distribuição da autoridade e a divisão das atividades fazem parte da definição de estrutura organizacional.", gabarito: "certo", explicacao: "Correto. Ambas integram o conceito de estrutura organizacional." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A busca pela excelência dispensa o aprimoramento constante do gestor.", gabarito: "errado", explicacao: "Errado. A excelência exige aprimoramento constante do gestor." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A escola estruturalista da administração contribui para a compreensão da estrutura organizacional.", gabarito: "certo", explicacao: "Correto. A apostila remete à escola estruturalista ao tratar da estrutura organizacional." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Organograma e cultura organizacional são exatamente a mesma coisa.", gabarito: "errado", explicacao: "Errado. O organograma é a representação gráfica da estrutura; a cultura organizacional é o conjunto de valores e comportamentos." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A gestão de qualidade no serviço público volta-se ao atendimento das necessidades e demandas do cidadão e da sociedade.", gabarito: "certo", explicacao: "Correto. A qualidade no setor público centra-se no atendimento ao cidadão." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Organizar a Administração não envolve a definição de competências dos órgãos.", gabarito: "errado", explicacao: "Errado. Organizar a Administração envolve, sim, a definição de competências, além de estrutura, recursos, órgãos e serviços." },

  { modulo: "9", tipo: "multipla", enunciado: "A representação gráfica da estrutura de uma organização é o:", alternativas: A("organograma", "fluxograma", "histograma", "cronograma", "diagrama de Pareto"), gabarito: "A", explicacao: "O organograma representa graficamente a estrutura organizacional." },
  { modulo: "9", tipo: "multipla", enunciado: "A estrutura organizacional corresponde ao modo pelo qual:", alternativas: A("a autoridade é distribuída, as atividades são divididas e a comunicação é estabelecida", "as receitas são estimadas e as despesas fixadas", "os crimes militares são apurados", "as políticas públicas são avaliadas", "os contratos são licitados"), gabarito: "A", explicacao: "É o conceito de estrutura organizacional: distribuição de autoridade, divisão de atividades e comunicação." },
  { modulo: "9", tipo: "multipla", enunciado: "No setor público, a eficiência e a eficácia medem-se principalmente pelo:", alternativas: A("cumprimento da missão e atendimento de qualidade ao cidadão", "aumento das receitas e expansão de mercado", "lucro líquido do exercício", "número de filiais abertas", "valor das ações"), gabarito: "A", explicacao: "No setor público, mede-se pelo cumprimento da missão e pela qualidade no atendimento ao cidadão." },
  { modulo: "9", tipo: "multipla", enunciado: "A Lei de Organização Básica da PMPE é a:", alternativas: A("Lei nº 11.328/1996", "Lei nº 11.817/2000", "Lei nº 14.133/2021", "Lei nº 6.783/1974", "Lei nº 11.929/2001"), gabarito: "A", explicacao: "A Lei de Organização Básica da PMPE é a Lei nº 11.328/1996." },
  { modulo: "9", tipo: "multipla", enunciado: "A gestão pública de excelência caracteriza-se pela:", alternativas: A("busca contínua pela qualidade e aprimoramento constante", "ausência de controle", "priorização do lucro", "informalidade dos processos", "centralização absoluta das decisões"), gabarito: "A", explicacao: "A excelência associa-se à busca contínua de qualidade e ao aprimoramento constante." },

  { modulo: "9", tipo: "dissertativa", enunciado: "Defina estrutura organizacional e explique o papel do organograma.", modelo: { estrutura: "Conceito de estrutura → organograma → relação.", criterios: ["Definir estrutura (autoridade, atividades, comunicação)", "Apontar o organograma como representação gráfica", "Relacionar organização do aparato e competências"], resposta: "Estrutura organizacional é o modo pelo qual a autoridade é distribuída, as atividades são divididas e organizadas e o sistema de comunicação é estabelecido. Organizar a Administração significa organizar todo o seu aparato — estrutura, recursos, órgãos, agentes, serviços e competências. O organograma é a representação gráfica dessa estrutura, evidenciando os níveis de autoridade e as relações entre as unidades." } },
  { modulo: "9", tipo: "dissertativa", enunciado: "Explique como se medem a eficiência e a eficácia na gestão pública de excelência, diferenciando da lógica privada.", modelo: { estrutura: "Critério público → critério privado → conclusão.", criterios: ["Público: cumprimento da missão e atendimento de qualidade ao cidadão", "Privado: receitas, redução de gastos, expansão de mercado", "Concluir pela busca de qualidade contínua"], resposta: "Na gestão pública de excelência, a eficiência e a eficácia medem-se não apenas pela correta utilização dos recursos, mas principalmente pelo cumprimento da missão institucional e pelo atendimento, com qualidade, das necessidades e demandas do cidadão e da sociedade. Difere-se da lógica privada, em que tais medidas se dão pelo aumento de receitas, pela redução de gastos ou pela expansão de mercado. A excelência, portanto, associa-se à busca contínua pela qualidade e ao aprimoramento constante do gestor." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`GPGA (mods 6-9): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
