import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "GPGA"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 1 — Conceitos gerais ════════
  { modulo: "1", tipo: "certo_errado", enunciado: "O Estado é permanente e intangível (ente moral), enquanto o Governo é transitório e tangível.", gabarito: "certo", explicacao: "Correto. O Estado é permanente/intangível; o Governo é transitório/tangível e exerce o poder do Estado." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Governo e Estado são expressões idênticas, não havendo distinção entre eles.", gabarito: "errado", explicacao: "Errado. O Estado exerce seu poder por meio do Governo, mas não se confunde com ele (Estado permanente × Governo transitório)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A Administração compreende todo o aparato (estrutura, órgãos, agentes, serviços) à disposição do Governo para realizar os fins do Estado.", gabarito: "certo", explicacao: "Correto. É o conceito de Administração adotado na apostila." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Administração e gestão são termos antagônicos e incompatíveis.", gabarito: "errado", explicacao: "Errado. São sinônimos; 'gestão' é a denominação mais moderna, que incorpora medidas gerenciais mais efetivas." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A Administração Pública tem como objetivo maior o bem-estar da coletividade, enquanto a iniciativa privada visa primordialmente ao lucro.", gabarito: "certo", explicacao: "Correto. É a distinção central entre gestão pública e privada." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Eficácia é a relação entre os resultados alcançados e os recursos empregados.", gabarito: "errado", explicacao: "Errado. Essa é a definição de eficiência. Eficácia é o alcance dos objetivos (o que se pretendia × o que se conseguiu)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Efetividade é o resultado que une ações eficientes ao alcance de máximos resultados.", gabarito: "certo", explicacao: "Correto. É a definição de efetividade na apostila." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Na centralização, as decisões são delegadas aos níveis mais baixos da estrutura.", gabarito: "errado", explicacao: "Errado. Na centralização as decisões ficam no topo; é a descentralização que delega aos níveis mais baixos." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A desconcentração administrativa é a distribuição de competências dentro da mesma pessoa jurídica, mantendo-se a hierarquia.", gabarito: "certo", explicacao: "Correto. A desconcentração ocorre dentro da mesma pessoa jurídica (Administração direta), preservando a hierarquia." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Governabilidade é a capacidade financeira e administrativa de um governo implementar políticas públicas.", gabarito: "errado", explicacao: "Errado. Essa é a governança. Governabilidade é a capacidade POLÍTICA de governar (legitimidade e apoio)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Governança pública é a capacidade financeira e administrativa de implementar políticas que atendam às necessidades da população.", gabarito: "certo", explicacao: "Correto. É a definição de governança (Bresser-Pereira) adotada na apostila." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Accountability é a capacidade/obrigação de prestar contas das responsabilidades outorgadas.", gabarito: "certo", explicacao: "Correto. Accountability é a obrigação de responder por uma responsabilidade outorgada (prestação de contas)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Compliance significa conformidade — governança baseada no cumprimento de padrões normativos e legais.", gabarito: "certo", explicacao: "Correto. Compliance (de 'to comply') é conformidade com os parâmetros normativos." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Cargo e função são exatamente a mesma coisa na PMPE.", gabarito: "errado", explicacao: "Errado. Cargo é a posição na estrutura organizacional; função é o conjunto de tarefas/responsabilidades do cargo." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A palavra 'Estado' foi utilizada pela primeira vez na obra 'O Príncipe', de Maquiavel, em 1513.", gabarito: "certo", explicacao: "Correto. A apostila registra que o termo 'Estado' surge em 'O Príncipe', de Maquiavel (1513)." },

  { modulo: "1", tipo: "multipla", enunciado: "Assinale a alternativa correta sobre a distinção entre Estado e Governo:", alternativas: A("o Estado é permanente e intangível; o Governo é transitório e tangível", "ambos são transitórios", "o Governo é permanente e o Estado, transitório", "são sinônimos perfeitos", "o Estado é tangível e o Governo, moral"), gabarito: "A", explicacao: "O Estado é permanente/intangível (ente moral); o Governo é transitório/tangível e exerce o poder." },
  { modulo: "1", tipo: "multipla", enunciado: "A relação entre RESULTADOS alcançados e RECURSOS empregados define:", alternativas: A("eficiência", "eficácia", "efetividade", "economicidade", "produtividade absoluta"), gabarito: "A", explicacao: "Eficiência = relação entre resultados e recursos (uso econômico/produtivo)." },
  { modulo: "1", tipo: "multipla", enunciado: "A transferência de competências dos órgãos superiores para os inferiores, dentro da mesma pessoa jurídica, denomina-se:", alternativas: A("desconcentração", "descentralização", "concentração", "centralização", "delegação externa"), gabarito: "A", explicacao: "Desconcentração = distribuição de competências dentro da mesma pessoa jurídica (mantém hierarquia)." },
  { modulo: "1", tipo: "multipla", enunciado: "A capacidade POLÍTICA de governar, derivada da legitimidade e do apoio da sociedade, é a:", alternativas: A("governabilidade", "governança", "accountability", "compliance", "eficiência"), gabarito: "A", explicacao: "Governabilidade é a capacidade política de governar; governança é a capacidade financeira/administrativa." },
  { modulo: "1", tipo: "multipla", enunciado: "O termo que significa 'conformidade' — cumprimento de padrões normativos e legais — é:", alternativas: A("compliance", "accountability", "benchmarking", "governabilidade", "downsizing"), gabarito: "A", explicacao: "Compliance (de 'to comply') é conformidade com os parâmetros normativos e legais." },

  { modulo: "1", tipo: "dissertativa", enunciado: "Diferencie Estado, Governo e Administração Pública.", modelo: { estrutura: "Estado → Governo → Administração → relação entre eles.", criterios: ["Estado: organização político-jurídica permanente/intangível", "Governo: parte política transitória/tangível que conduz a coisa pública", "Administração: aparato para realizar os fins do Estado", "Relacionar os três"], resposta: "O Estado é a organização político-jurídica de uma nação, permanente e intangível (ente moral), detentora do poder. O Governo é a parte política, transitória e tangível, que conduz a coisa pública e define os objetivos nacionais, exercendo o poder do Estado. A Administração é todo o aparato (estrutura, órgãos, agentes e serviços) à disposição do Governo para realizar os fins do Estado, especialmente o bem comum. Assim, o Estado exerce seu poder por meio do Governo, e este se vale da Administração para concretizar suas decisões." } },
  { modulo: "1", tipo: "dissertativa", enunciado: "Conceitue eficiência, eficácia e efetividade na gestão pública.", modelo: { estrutura: "Eficácia → eficiência → efetividade → exemplo/conclusão.", criterios: ["Eficácia: alcance dos objetivos", "Eficiência: relação resultados × recursos", "Efetividade: une eficiência ao alcance de máximos resultados"], resposta: "Eficácia é o alcance dos objetivos: compara o que se pretendia fazer com o que efetivamente se conseguiu. Eficiência é a relação entre os resultados alcançados e os recursos empregados, indicando uso econômico/produtivo. Efetividade é o resultado que une ações eficientes ao alcance de máximos resultados — ou seja, fazer a coisa certa (eficácia), do modo certo (eficiência) e gerando impacto real (efetividade)." } },

  // ════════ MÓDULO 2 — Evolução histórica e Princípios ════════
  { modulo: "2", tipo: "certo_errado", enunciado: "Durante a maior parte da história do Brasil (colônia e império), a principal característica da gestão pública foi o patrimonialismo.", gabarito: "certo", explicacao: "Correto. O patrimonialismo predominou na colônia e no império." },
  { modulo: "2", tipo: "certo_errado", enunciado: "No patrimonialismo, há clara separação entre o que é público e o que é privado.", gabarito: "errado", explicacao: "Errado. No patrimonialismo a governança se confunde com a pessoalidade do governante; não há separação entre público e privado." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Os princípios expressos no art. 37 da CF são legalidade, impessoalidade, moralidade, publicidade e eficiência (LIMPE).", gabarito: "certo", explicacao: "Correto. São os cinco princípios expressos do art. 37 (LIMPE)." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Pelo princípio da legalidade, a Administração só pode fazer o que a lei autoriza/prevê.", gabarito: "certo", explicacao: "Correto. A legalidade vincula a Administração aos mandamentos da lei, sob pena de invalidade e responsabilização." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O princípio da impessoalidade admite favorecimentos e discriminações conforme a conveniência do gestor.", gabarito: "errado", explicacao: "Errado. A impessoalidade exige atuação dirigida a todos, sem discriminação ou favorecimento." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A publicidade torna obrigatória a divulgação dos atos da Administração, em regra por meio dos Diários Oficiais.", gabarito: "certo", explicacao: "Correto. A publicidade impõe a divulgação dos atos (Diário Oficial) para conhecimento, controle e produção de efeitos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A eficiência liga-se à conduta do bom administrador no campo dos valores morais.", gabarito: "errado", explicacao: "Errado. Essa noção é da moralidade. A eficiência preza pela racionalidade, presteza e qualidade do serviço." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A moralidade administrativa relaciona-se ao conceito de bom administrador, que busca o mais útil ao interesse público.", gabarito: "certo", explicacao: "Correto. A moralidade liga-se à conduta do bom administrador." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O princípio da eficiência foi inserido no art. 37 da CF pela Emenda Constitucional nº 19/1998.", gabarito: "certo", explicacao: "Correto. A eficiência foi acrescentada ao caput do art. 37 pela EC nº 19/1998." },
  { modulo: "2", tipo: "certo_errado", enunciado: "No patrimonialismo, a expressão 'O Estado sou eu' bem ilustra a confusão entre o público e a pessoa do governante.", gabarito: "certo", explicacao: "Correto. A apostila usa essa expressão para caracterizar o patrimonialismo." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Com o início da República, a gestão pública brasileira passou, ainda que de forma incipiente, a ser mais técnica.", gabarito: "certo", explicacao: "Correto. A apostila aponta que, com a República, iniciou-se uma gestão mais técnica." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A violação do princípio da legalidade pode acarretar a invalidade do ato e a responsabilização do seu autor.", gabarito: "certo", explicacao: "Correto. A legalidade impõe que o afastamento da lei gere invalidade do ato e responsabilização." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Os princípios do art. 37 da CF aplicam-se apenas à Administração direta, não alcançando a indireta.", gabarito: "errado", explicacao: "Errado. O art. 37 alcança a Administração direta e indireta de qualquer dos Poderes da União, Estados, DF e Municípios." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O instrumento oficial de publicidade dos atos administrativos é, em geral, o Diário Oficial.", gabarito: "certo", explicacao: "Correto. Em regra utilizam-se os Diários Oficiais para a publicação dos atos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A divisão da história da gestão pública em paradigmas é de caráter absoluto, sem exceções pontuais.", gabarito: "errado", explicacao: "Errado. A apostila ressalva que a divisão paradigmática é geral, admitindo casos pontuais divergentes." },

  { modulo: "2", tipo: "multipla", enunciado: "Os princípios expressos no caput do art. 37 da CF são:", alternativas: A("legalidade, impessoalidade, moralidade, publicidade e eficiência", "legalidade, economicidade, moralidade, celeridade e eficácia", "legalidade, impessoalidade, motivação, publicidade e proporcionalidade", "moralidade, eficiência, razoabilidade e segurança jurídica", "supremacia, indisponibilidade, legalidade e eficiência"), gabarito: "A", explicacao: "São os cinco princípios expressos (LIMPE): legalidade, impessoalidade, moralidade, publicidade e eficiência." },
  { modulo: "2", tipo: "multipla", enunciado: "A característica predominante da gestão pública brasileira na colônia e no império foi o:", alternativas: A("patrimonialismo", "gerencialismo", "burocratismo weberiano", "neoliberalismo", "republicanismo técnico"), gabarito: "A", explicacao: "Predominou o patrimonialismo (confusão entre público e privado)." },
  { modulo: "2", tipo: "multipla", enunciado: "O princípio que obriga a divulgação dos atos administrativos é o da:", alternativas: A("publicidade", "moralidade", "eficiência", "impessoalidade", "legalidade"), gabarito: "A", explicacao: "A publicidade impõe a divulgação dos atos (em regra, no Diário Oficial)." },
  { modulo: "2", tipo: "multipla", enunciado: "A inserção do princípio da eficiência no art. 37 da CF deu-se pela:", alternativas: A("Emenda Constitucional nº 19/1998", "Emenda Constitucional nº 45/2004", "Emenda Constitucional nº 103/2019", "Lei nº 14.133/2021", "Constituição de 1988 (texto originário)"), gabarito: "A", explicacao: "A eficiência foi acrescentada pela EC nº 19/1998." },
  { modulo: "2", tipo: "multipla", enunciado: "O princípio que veda discriminações e favorecimentos, exigindo atuação dirigida a todos, é o da:", alternativas: A("impessoalidade", "moralidade", "publicidade", "eficiência", "legalidade"), gabarito: "A", explicacao: "A impessoalidade impõe atuação sem discriminação ou favorecimento." },

  { modulo: "2", tipo: "dissertativa", enunciado: "Explique os cinco princípios expressos do art. 37 da CF (LIMPE) aplicáveis à Administração Pública.", modelo: { estrutura: "Listar e conceituar legalidade, impessoalidade, moralidade, publicidade e eficiência.", criterios: ["Legalidade: só fazer o previsto em lei", "Impessoalidade: sem discriminação/favorecimento", "Moralidade: bom administrador", "Publicidade: divulgação dos atos", "Eficiência: racionalidade/qualidade"], resposta: "Os princípios do art. 37 (LIMPE) são: Legalidade — a Administração só faz o que a lei autoriza, sob pena de invalidade e responsabilização; Impessoalidade — atuação dirigida a todos, sem discriminação ou favorecimento; Moralidade — atuação conforme os princípios morais e a conduta do bom administrador; Publicidade — divulgação obrigatória dos atos (em regra, no Diário Oficial), para conhecimento, controle e produção de efeitos; e Eficiência — presteza, racionalidade e qualidade na prestação do serviço público (inserida pela EC 19/1998)." } },
  { modulo: "2", tipo: "dissertativa", enunciado: "Caracterize o patrimonialismo como paradigma histórico da gestão pública brasileira.", modelo: { estrutura: "Conceito → período → características → conclusão.", criterios: ["Definir patrimonialismo (confusão público/privado)", "Situar na colônia/império", "Citar a pessoalidade do governante ('O Estado sou eu')"], resposta: "O patrimonialismo é o paradigma em que a governança se confunde com a pessoalidade do governante, não havendo separação entre o que é público e o que é privado — o gestor apropria-se, como seu, daquilo que é de toda a sociedade ('O Estado sou eu'). Predominou na maior parte da história brasileira (colônia e império). Com o advento da República, iniciou-se, ainda que de forma incipiente, uma gestão pública mais técnica." } },

  // ════════ MÓDULO 3 — Organização da Administração Pública ════════
  { modulo: "3", tipo: "certo_errado", enunciado: "Os órgãos da Administração direta não possuem personalidade jurídica própria.", gabarito: "certo", explicacao: "Correto. Os órgãos da Administração direta são centros de competências despersonalizados, sem personalidade jurídica própria." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As autarquias e fundações, em regra, prestam serviços públicos; as empresas públicas e sociedades de economia mista exploram atividade econômica.", gabarito: "certo", explicacao: "Correto. É a distinção típica das entidades da Administração indireta." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A Administração indireta é composta por órgãos sem personalidade jurídica, ligados diretamente ao ente central.", gabarito: "errado", explicacao: "Errado. Isso descreve a Administração direta. A indireta é composta por pessoas jurídicas descentralizadas e autônomas." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O terceiro setor é composto por entes privados que atuam em atividades de interesse público, sem fins lucrativos.", gabarito: "certo", explicacao: "Correto. O terceiro setor é figura híbrida/paraestatal, sem fins lucrativos, que colabora com o Estado." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As entidades da Administração indireta são vinculadas (e não subordinadas) aos órgãos da Administração direta.", gabarito: "certo", explicacao: "Correto. A indireta é vinculada à direta, exercendo de forma descentralizada as atividades; há controle finalístico, não hierárquico." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Organizações sociais (OS) e OSCIP integram a Administração direta.", gabarito: "errado", explicacao: "Errado. OS e OSCIP integram o terceiro setor (entes privados de interesse público), não a Administração direta." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As empresas públicas e as sociedades de economia mista são entidades da Administração indireta.", gabarito: "certo", explicacao: "Correto. Ambas integram a Administração indireta (exploração de atividade econômica)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Os serviços sociais autônomos (Sistema S) são exemplos de entidades do terceiro setor.", gabarito: "certo", explicacao: "Correto. Serviços sociais autônomos compõem o terceiro setor, ao lado de OS, OSCIP e ONGs." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A Administração direta atua através de seus órgãos e agentes, que expressam a vontade da pessoa jurídica a que estão ligados.", gabarito: "certo", explicacao: "Correto. Os órgãos despersonalizados atuam imputando sua conduta à entidade estatal a que pertencem." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O terceiro setor é assim chamado por ser composto exclusivamente por órgãos estatais.", gabarito: "errado", explicacao: "Errado. O primeiro setor é o estatal; o segundo, o privado; o terceiro é a figura híbrida (privados de interesse público sem fins lucrativos)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As entidades da Administração indireta são submetidas aos princípios da Administração Pública.", gabarito: "certo", explicacao: "Correto. Mesmo descentralizadas e autônomas, submetem-se aos princípios da Administração Pública e ao controle do Estado." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Os órgãos da Administração direta possuem capacidade jurídica e constituem pessoa jurídica própria.", gabarito: "errado", explicacao: "Errado. Os órgãos não têm personalidade/capacidade jurídica própria — são centros de competências despersonalizados." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Agências executivas e agências reguladoras são, segundo a apostila, derivações das administrações indiretas tradicionais.", gabarito: "certo", explicacao: "Correto. A apostila trata essas figuras como derivações das entidades da Administração indireta." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A Administração indireta exerce de forma centralizada todas as atividades do ente central.", gabarito: "errado", explicacao: "Errado. A Administração indireta exerce as atividades de forma DESCENTRALIZADA." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As entidades do terceiro setor não almejam lucro e colaboram com o Estado em atividades de interesse público.", gabarito: "certo", explicacao: "Correto. O terceiro setor não busca lucro e atua em colaboração com o Estado." },

  { modulo: "3", tipo: "multipla", enunciado: "São entidades da Administração indireta:", alternativas: A("autarquias, fundações, empresas públicas e sociedades de economia mista", "ministérios e secretarias", "organizações sociais e ONGs", "órgãos despersonalizados do ente central", "serviços sociais autônomos"), gabarito: "A", explicacao: "A Administração indireta compõe-se de autarquias, fundações, empresas públicas e sociedades de economia mista." },
  { modulo: "3", tipo: "multipla", enunciado: "A principal característica dos órgãos da Administração direta é:", alternativas: A("não possuírem personalidade jurídica própria", "serem pessoas jurídicas autônomas", "explorarem atividade econômica", "pertencerem ao terceiro setor", "terem fins lucrativos"), gabarito: "A", explicacao: "Os órgãos da Administração direta são centros de competências despersonalizados, sem personalidade jurídica própria." },
  { modulo: "3", tipo: "multipla", enunciado: "Organizações sociais (OS), OSCIP, serviços sociais autônomos e ONGs compõem:", alternativas: A("o terceiro setor", "a Administração direta", "a Administração indireta", "o Poder Legislativo", "as agências reguladoras"), gabarito: "A", explicacao: "São entidades do terceiro setor (privados de interesse público, sem fins lucrativos)." },
  { modulo: "3", tipo: "multipla", enunciado: "Entidades que exploram atividade econômica na Administração indireta são:", alternativas: A("empresas públicas e sociedades de economia mista", "autarquias e fundações", "OS e OSCIP", "ministérios", "serviços sociais autônomos"), gabarito: "A", explicacao: "Empresas públicas e sociedades de economia mista exploram atividade econômica." },
  { modulo: "3", tipo: "multipla", enunciado: "Assinale a afirmação correta sobre a Administração indireta:", alternativas: A("é composta por pessoas jurídicas descentralizadas e autônomas, vinculadas à direta", "não se submete aos princípios da Administração Pública", "é formada por órgãos sem personalidade jurídica", "pertence ao terceiro setor", "não sofre controle do Estado"), gabarito: "A", explicacao: "A indireta é composta por pessoas jurídicas descentralizadas e autônomas, vinculadas à direta e submetidas aos princípios e ao controle estatal." },

  { modulo: "3", tipo: "dissertativa", enunciado: "Diferencie a Administração direta da indireta e situe o terceiro setor.", modelo: { estrutura: "Direta → indireta → terceiro setor → conclusão.", criterios: ["Direta: órgãos sem personalidade própria, ligados ao ente central", "Indireta: pessoas jurídicas descentralizadas (autarquias, fundações, EP, SEM)", "Terceiro setor: privados de interesse público, sem fins lucrativos"], resposta: "A Administração direta é composta por órgãos ligados diretamente ao ente central de cada poder e esfera, sem personalidade jurídica própria (centros de competências despersonalizados). A Administração indireta é composta por pessoas jurídicas criadas para fins específicos, descentralizadas e autônomas, vinculadas à direta: autarquias e fundações (serviços públicos) e empresas públicas e sociedades de economia mista (atividade econômica). O terceiro setor é figura híbrida/paraestatal, formada por entes privados que atuam em atividades de interesse público sem fins lucrativos (serviços sociais autônomos, OS, OSCIP, ONGs), colaborando com o Estado." } },
  { modulo: "3", tipo: "dissertativa", enunciado: "Explique por que os órgãos da Administração direta são chamados de 'centros de competências despersonalizados'.", modelo: { estrutura: "Conceito de órgão → ausência de personalidade → imputação à entidade → conclusão.", criterios: ["Afirmar que órgãos não têm personalidade jurídica própria", "Explicar que possuem apenas competências", "Indicar que a atuação dos agentes é imputada à entidade estatal"], resposta: "Os órgãos da Administração direta não constituem pessoa jurídica nem têm capacidade jurídica própria; possuem apenas competências. Por isso são chamados de 'centros de competências despersonalizados': atuam por meio de seus agentes, cuja conduta é imputada à entidade estatal (União, Estado ou Município) a que pertencem. Eles expressam a vontade política da pessoa jurídica à qual estão ligados, mas não respondem como sujeito de direito autônomo." } },

  // ════════ MÓDULO 4 — PPA, LDO e LOA ════════
  { modulo: "4", tipo: "certo_errado", enunciado: "O Plano Plurianual (PPA) estabelece objetivos, diretrizes e metas da gestão para um período de 4 anos.", gabarito: "certo", explicacao: "Correto. O PPA (art. 165 da CF) tem horizonte de 4 anos." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A Lei Orçamentária Anual (LOA) estima as receitas e fixa as despesas para o ano subsequente.", gabarito: "certo", explicacao: "Correto. A LOA estima receitas e fixa despesas, conforme o PPA e a LDO." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A LDO tem por objetivo detalhar as metas e prioridades da administração e orientar a elaboração da LOA.", gabarito: "certo", explicacao: "Correto. A LDO (anual) detalha metas/prioridades e orienta a confecção da LOA." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O PPA é elaborado anualmente, assim como a LDO e a LOA.", gabarito: "errado", explicacao: "Errado. O PPA é plurianual (4 anos); LDO e LOA é que são anuais." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O PPA tem previsão constitucional no art. 165.", gabarito: "certo", explicacao: "Correto. O PPA tem previsão no art. 165 da CF." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O PPA, a LDO e a LOA compõem o chamado ciclo de gestão (orçamentário) da Administração Pública.", gabarito: "certo", explicacao: "Correto. Os três instrumentos compõem o ciclo de gestão/orçamentário." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Entre as características do PPA estão dar transparência ao uso dos recursos e fomentar a continuidade administrativa.", gabarito: "certo", explicacao: "Correto. São características do PPA citadas na apostila." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A LDO deve ser encaminhada ao Legislativo até 31 de agosto.", gabarito: "errado", explicacao: "Errado. A LDO é encaminhada até 15 de abril; até 31 de agosto vão o PPA (1º ano) e a LOA." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O orçamento (LOA) é o mecanismo que indica a alocação de recursos para os programas estabelecidos no planejamento.", gabarito: "certo", explicacao: "Correto. A LOA materializa a alocação de recursos aos programas planejados." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A LDO orienta a confecção do PPA.", gabarito: "errado", explicacao: "Errado. A LDO orienta a confecção da LOA; o PPA é o planejamento de mais longo prazo (4 anos)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O PPA deve ser enviado ao Legislativo até 31 de agosto do primeiro ano do mandato e devolvido até 22 de dezembro.", gabarito: "certo", explicacao: "Correto. São os prazos do PPA indicados na apostila (com base na ADCT)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A boa governança independe de um uso otimizado dos recursos públicos.", gabarito: "errado", explicacao: "Errado. A boa governança requer otimização dos recursos para prover bons serviços, daí a importância de PPA/LDO/LOA." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A LOA deve ser enviada ao Legislativo até 31 de agosto e devolvida até 22 de dezembro.", gabarito: "certo", explicacao: "Correto. São os prazos da LOA indicados na apostila." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A LDO é encaminhada até 15 de abril e devolvida até 17 de julho.", gabarito: "certo", explicacao: "Correto. São os prazos da LDO indicados na apostila." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O PPA estima receitas e fixa despesas, sendo o instrumento de execução anual do orçamento.", gabarito: "errado", explicacao: "Errado. Quem estima receitas e fixa despesas é a LOA; o PPA é o planejamento de 4 anos." },

  { modulo: "4", tipo: "multipla", enunciado: "Qual instrumento estabelece objetivos, diretrizes e metas por 4 anos?", alternativas: A("PPA — Plano Plurianual", "LDO — Lei de Diretrizes Orçamentárias", "LOA — Lei Orçamentária Anual", "LRF — Lei de Responsabilidade Fiscal", "ADCT"), gabarito: "A", explicacao: "O PPA (art. 165 da CF) fixa objetivos, diretrizes e metas por 4 anos." },
  { modulo: "4", tipo: "multipla", enunciado: "O instrumento que estima receitas e fixa despesas do ano subsequente é a:", alternativas: A("LOA", "LDO", "PPA", "LRF", "Lei nº 14.133/2021"), gabarito: "A", explicacao: "A LOA estima receitas e fixa despesas, conforme o PPA e a LDO." },
  { modulo: "4", tipo: "multipla", enunciado: "A função de detalhar metas e prioridades e orientar a LOA cabe à:", alternativas: A("LDO", "LOA", "PPA", "Constituição", "ADCT"), gabarito: "A", explicacao: "A LDO detalha metas/prioridades e orienta a confecção da LOA." },
  { modulo: "4", tipo: "multipla", enunciado: "O PPA deve ser enviado ao Legislativo até:", alternativas: A("31 de agosto do 1º ano do mandato", "15 de abril", "17 de julho", "30 de novembro", "31 de dezembro"), gabarito: "A", explicacao: "O PPA é enviado até 31/ago do 1º ano do mandato e devolvido até 22/dez." },
  { modulo: "4", tipo: "multipla", enunciado: "Os prazos de envio da LDO são:", alternativas: A("envio até 15/abr e devolução até 17/jul", "envio até 31/ago e devolução até 22/dez", "envio até 30/jun e devolução até 30/set", "envio até 1º/jan e devolução até 30/jun", "não há prazos definidos"), gabarito: "A", explicacao: "A LDO é encaminhada até 15/abr e devolvida até 17/jul." },

  { modulo: "4", tipo: "dissertativa", enunciado: "Explique os três instrumentos do ciclo de gestão orçamentária (PPA, LDO e LOA) e a função de cada um.", modelo: { estrutura: "PPA → LDO → LOA → integração.", criterios: ["PPA: objetivos/diretrizes/metas, 4 anos (art. 165)", "LDO: anual, detalha metas e orienta a LOA", "LOA: estima receitas e fixa despesas", "Relacionar os três"], resposta: "O ciclo de gestão orçamentária compõe-se de três instrumentos. O Plano Plurianual (PPA), previsto no art. 165 da CF, estabelece objetivos, diretrizes e metas por 4 anos, dando transparência e continuidade administrativa. A Lei de Diretrizes Orçamentárias (LDO) é anual, detalha as metas e prioridades e orienta a elaboração da LOA. A Lei Orçamentária Anual (LOA) estima as receitas e fixa as despesas para o ano subsequente, conforme o PPA e a LDO, materializando a alocação de recursos aos programas planejados." } },
  { modulo: "4", tipo: "dissertativa", enunciado: "Indique os prazos de envio e devolução do PPA, da LDO e da LOA conforme a apostila.", modelo: { estrutura: "PPA → LDO → LOA (prazos).", criterios: ["PPA: envio 31/ago (1º ano), devolução 22/dez", "LDO: envio 15/abr, devolução 17/jul", "LOA: envio 31/ago, devolução 22/dez"], resposta: "Conforme a apostila (com base na ADCT): o PPA deve ser enviado ao Legislativo até 31 de agosto do primeiro ano do mandato e devolvido até 22 de dezembro; a LDO é encaminhada até 15 de abril e devolvida até 17 de julho; e a LOA é enviada até 31 de agosto e devolvida até 22 de dezembro." } },

  // ════════ MÓDULO 5 — Licitações e Contratos ════════
  { modulo: "5", tipo: "certo_errado", enunciado: "A Lei nº 14.133/2021 estabelece as normas gerais de licitação e contratos para a Administração Pública.", gabarito: "certo", explicacao: "Correto. A Lei nº 14.133/2021 é a atual lei geral de licitações e contratos." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Licitação é o procedimento legal para selecionar propostas de possíveis contratos com a Administração.", gabarito: "certo", explicacao: "Correto. É a definição de licitação adotada na apostila." },
  { modulo: "5", tipo: "certo_errado", enunciado: "São modalidades de licitação na Lei nº 14.133/2021: concorrência, concurso, leilão, pregão e diálogo competitivo.", gabarito: "certo", explicacao: "Correto. São as cinco modalidades previstas na nova lei." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A tomada de preços e o convite continuam previstos como modalidades na Lei nº 14.133/2021.", gabarito: "errado", explicacao: "Errado. A Lei 14.133/2021 não traz tomada de preços nem convite; as modalidades são concorrência, concurso, leilão, pregão e diálogo competitivo." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Em casos especiais, a contratação pode dispensar a licitação ou ser caso de inexigibilidade.", gabarito: "certo", explicacao: "Correto. A apostila menciona as hipóteses de dispensa e inexigibilidade." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Contrato administrativo é o ajuste entre órgãos da Administração e particulares para dispor serviços/produtos, com cláusulas que vinculam as partes.", gabarito: "certo", explicacao: "Correto. É a definição de contrato público adotada na apostila." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O 'diálogo competitivo' é uma das modalidades introduzidas pela Lei nº 14.133/2021.", gabarito: "certo", explicacao: "Correto. O diálogo competitivo é modalidade da nova lei de licitações." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O pregão deixou de existir como modalidade após a Lei nº 14.133/2021.", gabarito: "errado", explicacao: "Errado. O pregão permanece como uma das cinco modalidades da Lei 14.133/2021." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Lei nº 14.133/2021 aplica-se às Administrações diretas, autárquicas e fundacionais da União, Estados, DF e Municípios.", gabarito: "certo", explicacao: "Correto. É o âmbito de aplicação do art. 1º da Lei 14.133/2021." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Os contratos decorrentes de dispensa ou inexigibilidade não precisam atender aos termos do ato que os autorizou.", gabarito: "errado", explicacao: "Errado. Tais contratos devem atender aos termos do ato autorizador e da respectiva proposta." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A licitação respeita os princípios constitucionais que regem a Administração Pública.", gabarito: "certo", explicacao: "Correto. A licitação observa os ditames legais e os princípios basilares da Administração." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O leilão é modalidade prevista na Lei nº 14.133/2021.", gabarito: "certo", explicacao: "Correto. O leilão é uma das cinco modalidades da nova lei." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Os contratos administrativos devem estabelecer com clareza as condições de execução, direitos, obrigações e responsabilidades das partes.", gabarito: "certo", explicacao: "Correto. É a orientação citada na apostila (Chiavenato) sobre contratos." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A Lei nº 14.133/2021 prevê três modalidades de licitação.", gabarito: "errado", explicacao: "Errado. São cinco modalidades: concorrência, concurso, leilão, pregão e diálogo competitivo." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O concurso é uma das modalidades de licitação da Lei nº 14.133/2021.", gabarito: "certo", explicacao: "Correto. O concurso é uma das cinco modalidades." },

  { modulo: "5", tipo: "multipla", enunciado: "A atual lei geral de licitações e contratos é a:", alternativas: A("Lei nº 14.133/2021", "Lei nº 8.666/1993", "Lei nº 10.520/2002", "Lei nº 14.751/2023", "Lei nº 11.817/2000"), gabarito: "A", explicacao: "A Lei nº 14.133/2021 é a atual lei geral de licitações e contratos." },
  { modulo: "5", tipo: "multipla", enunciado: "São modalidades de licitação na Lei nº 14.133/2021:", alternativas: A("concorrência, concurso, leilão, pregão e diálogo competitivo", "concorrência, tomada de preços, convite, concurso e leilão", "pregão, convite e tomada de preços", "concorrência e convite apenas", "leilão, concurso e tomada de preços"), gabarito: "A", explicacao: "As cinco modalidades são concorrência, concurso, leilão, pregão e diálogo competitivo." },
  { modulo: "5", tipo: "multipla", enunciado: "A modalidade INTRODUZIDA pela Lei nº 14.133/2021 é o(a):", alternativas: A("diálogo competitivo", "tomada de preços", "convite", "pregão", "concorrência"), gabarito: "A", explicacao: "O diálogo competitivo é a novidade da Lei 14.133/2021 (tomada de preços e convite foram extintos)." },
  { modulo: "5", tipo: "multipla", enunciado: "Quando a Administração contrata sem licitação por inviabilidade de competição, trata-se de:", alternativas: A("inexigibilidade", "concorrência", "pregão", "diálogo competitivo", "leilão"), gabarito: "A", explicacao: "A inexigibilidade ocorre quando há inviabilidade de competição; a dispensa, em casos legalmente previstos." },
  { modulo: "5", tipo: "multipla", enunciado: "Licitação pode ser definida como:", alternativas: A("o procedimento legal para selecionar a proposta mais vantajosa para a Administração", "qualquer compra direta sem formalidade", "um contrato firmado entre particulares", "a fixação de despesas no orçamento", "a fiscalização contábil do Estado"), gabarito: "A", explicacao: "Licitação é o procedimento para selecionar propostas/contratos com a Administração, respeitados os princípios." },

  { modulo: "5", tipo: "dissertativa", enunciado: "Conceitue licitação e contrato administrativo e indique as modalidades de licitação previstas na Lei nº 14.133/2021.", modelo: { estrutura: "Licitação → contrato → modalidades → dispensa/inexigibilidade.", criterios: ["Definir licitação (selecionar proposta)", "Definir contrato administrativo", "Listar as 5 modalidades", "Mencionar dispensa e inexigibilidade"], resposta: "Licitação é o procedimento legal para selecionar a proposta mais vantajosa entre as oferecidas por particulares para contratar com a Administração, observados os princípios constitucionais. Contrato administrativo é o ajuste entre órgãos da Administração e particulares para dispor serviços ou produtos, com cláusulas que definem direitos, obrigações e responsabilidades. A Lei nº 14.133/2021 prevê cinco modalidades: concorrência, concurso, leilão, pregão e diálogo competitivo. Em casos especiais, a contratação pode ocorrer por dispensa ou inexigibilidade de licitação." } },
  { modulo: "5", tipo: "dissertativa", enunciado: "Comente as principais mudanças trazidas pela Lei nº 14.133/2021 quanto às modalidades de licitação.", modelo: { estrutura: "Lei nova → modalidades atuais → extinção de tomada de preços/convite → diálogo competitivo.", criterios: ["Citar a Lei 14.133/2021 como nova lei geral", "Listar as 5 modalidades atuais", "Apontar a extinção de tomada de preços e convite", "Destacar o diálogo competitivo como novidade"], resposta: "A Lei nº 14.133/2021 substituiu o regime anterior e passou a prever cinco modalidades de licitação: concorrência, concurso, leilão, pregão e diálogo competitivo. Em relação ao modelo anterior, extinguiram-se as modalidades tomada de preços e convite, e introduziu-se o diálogo competitivo, voltado a contratações de maior complexidade, em que a Administração dialoga com licitantes previamente selecionados para desenvolver soluções. Permanecem possíveis as contratações diretas por dispensa e inexigibilidade." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`GPGA (mods 1-5): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
