import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "HPMPE"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

// Complemento p/ ~22 questoes/modulo.
const QS: Q[] = [
  // ── M1 ──
  { modulo: "1", tipo: "certo_errado", enunciado: "A origem da futura Polícia Militar de Pernambuco vincula-se à criação da Intendência Geral de Polícia, no Rio de Janeiro, após a vinda da Família Real em 1808.", gabarito: "certo", explicacao: "Correto. A Intendência Geral de Polícia (1808) tinha por função principal a manutenção do sossego público." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A partir de 1830, o recrutamento para o Corpo de Polícia passou a ser voluntário, com contrato de dois anos renovável.", gabarito: "certo", explicacao: "Correto. Ainda assim, nunca se conseguiu preencher as vagas, por resistência à profissão e deserção." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O efetivo inicial do Corpo de Polícia era plenamente suficiente para o policiamento do Recife.", gabarito: "errado", explicacao: "Errado. O efetivo era ínfimo (cerca de 259 soldados) para uma cidade de mais de 25.000 habitantes." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Em dezembro de 1825, o Governo da Província uniformizou e armou o efetivo, com jaqueta azul, calças, capote e sapatos.", gabarito: "certo", explicacao: "Correto. Ainda assim, policiais vendiam armas e peças, sobretudo capotes." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os códigos disciplinares de 1845 e 1853 previam prisão disciplinar para quem vendesse peças do fardamento ou usasse uniforme em desalinho.", gabarito: "certo", explicacao: "Correto. Eram medidas contra a venda de equipamentos e o desleixo no uniforme." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O primeiro Comandante-Geral, em 1825, já contava com quartel próprio e efetivo completo de 320 homens.", gabarito: "errado", explicacao: "Errado. Em 1825 havia apenas 6 oficiais, 35 soldados e 11 recrutas, sem quartel, embora o quadro previsto fosse de 320." },
  { modulo: "1", tipo: "multipla", enunciado: "A data formal de criação do Corpo de Polícia de Pernambuco é:", alternativas: A("11 de junho de 1825", "7 de setembro de 1822", "15 de novembro de 1889", "28 de junho de 1900", "24 de julho de 2000"), gabarito: "A", explicacao: "11/06/1825 é a data de criação (aniversário da instituição)." },
  { modulo: "1", tipo: "multipla", enunciado: "O efetivo inicial de 259 soldados dividia-se aproximadamente em:", alternativas: A("182 de infantaria e 77 de cavalaria", "100 de infantaria e 159 de cavalaria", "259 exclusivamente de cavalaria", "metade infantaria e metade marinha", "200 de artilharia e 59 de infantaria"), gabarito: "A", explicacao: "Eram 182 de infantaria e 77 de cavalaria." },
  { modulo: "1", tipo: "multipla", enunciado: "Em 1827, na organização policial mais regular, o comando coube a:", alternativas: A("Francisco Jacinto Pereira", "Antônio Maria da Silva Torres", "Manuel Cavalcante de Albuquerque", "Antero José Ferreira", "Delmiro Gouveia"), gabarito: "A", explicacao: "Em 1827, com 320 praças em 3 companhias, o comando foi de Francisco Jacinto Pereira." },
  { modulo: "1", tipo: "multipla", enunciado: "Sobre a condição social do militar nos primórdios da corporação, é correto afirmar:", alternativas: A("o soldo era muito baixo e ser militar não mudava o status social", "o militar gozava de alto prestígio e bons salários", "todos eram voluntários da elite local", "havia excesso de candidatos às vagas", "o serviço garantia ascensão social imediata"), gabarito: "A", explicacao: "O soldo era ínfimo; muitos eram vítimas de recrutamento forçado e o status social não mudava." },
  { modulo: "1", tipo: "multipla", enunciado: "O nome do Comandante-Geral foi definitivamente definido em janeiro de 1832 na pessoa de:", alternativas: A("TC Manuel Cavalcante de Albuquerque", "CEL Antônio Maria da Silva Torres", "Francisco Jacinto Pereira", "Sérgio Loreto", "Roberto Magalhães"), gabarito: "A", explicacao: "Em jan/1832 definiu-se o nome do Cmt-Geral: TC Manuel Cavalcante de Albuquerque." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A finalidade da criação do Corpo de Polícia, em 1825, incluía manter a segurança no Recife e prevenir levantes e insurreições.", gabarito: "certo", explicacao: "Correto. O contexto era de instabilidade e necessidade de conter revoltas." },
  { modulo: "1", tipo: "multipla", enunciado: "O primeiro Comandante-Geral do Corpo de Polícia Provisório (1825) foi:", alternativas: A("CEL Antônio Maria da Silva Torres", "TC Manuel Cavalcante de Albuquerque", "Francisco Jacinto Pereira", "Antero José Ferreira", "Henrique de Lucena"), gabarito: "A", explicacao: "Silva Torres foi o 1º Cmt-Geral, em 1825." },

  // ── M2 ──
  { modulo: "2", tipo: "certo_errado", enunciado: "A Guarda Nacional foi criada em agosto de 1831, e as Guardas Municipais Permanentes em outubro do mesmo ano.", gabarito: "certo", explicacao: "Correto. Ambas surgem em 1831, no período regencial." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A Setembrada e a Novembrada (1831) foram movimentos marcados por forte sentimento anti-lusitano.", gabarito: "certo", explicacao: "Correto. Ocorreram em torno da abdicação de D. Pedro I." },
  { modulo: "2", tipo: "certo_errado", enunciado: "No levante das praças de 1831, no Recife, houve ampla liderança e apoio dos oficiais.", gabarito: "errado", explicacao: "Errado. O movimento foi quase acéfalo (praticamente sem oficiais); o grupo legalista prevaleceu." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Os rios Beberibe e Capibaribe funcionavam como 'estradas' e dificultavam o trabalho de fiscalização policial no Recife.", gabarito: "certo", explicacao: "Correto. A geografia fluvial dificultava o policiamento." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Pela Lei nº 473, de 28/06/1900, a corporação passou a ser denominada Brigada Militar de Pernambuco.", gabarito: "certo", explicacao: "Correto. Com efetivo de cerca de 1.000 praças." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Entre 1825 e 1900 a corporação mudou de nome três vezes.", gabarito: "errado", explicacao: "Errado. Mudou de nome SETE vezes nesse período." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Durante o Estado Novo, sob Agamenon Magalhães, terreiros de umbanda e maracatus foram vigiados e combatidos.", gabarito: "certo", explicacao: "Correto. Em 1938, militares foram excluídos por dançar maracatu no quartel." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A tese central da disciplina é que a PMPE sempre esteve mais ligada ao combate à criminalidade do que à ordem pública.", gabarito: "errado", explicacao: "Errado. A ênfase histórica é a ordem pública e a administração; o foco no crime só se estreita no século XX." },
  { modulo: "2", tipo: "multipla", enunciado: "A malha urbana do Recife, no século XIX, compreendia basicamente três bairros:", alternativas: A("Recife, Santo Amaro e Boa Vista", "Boa Viagem, Pina e Afogados", "Casa Forte, Derby e Madalena", "Olinda, Jaboatão e Paulista", "Várzea, Iputinga e Torre"), gabarito: "A", explicacao: "Eram os bairros do Recife, Santo Amaro e Boa Vista." },
  { modulo: "2", tipo: "multipla", enunciado: "A 'polícia de moleque', no século XIX, tinha como alvo determinado:", alternativas: A("quem não podia resistir — escravos e 'pobres sem patrão'", "os grandes comerciantes da elite", "os oficiais da Guarda Nacional", "os fazendeiros do interior", "os clérigos e religiosos"), gabarito: "A", explicacao: "A violência recaía sobre os mais vulneráveis, no contexto de controle da escravaria urbana." },
  { modulo: "2", tipo: "multipla", enunciado: "Em 1870, em meio à disputa entre Henrique de Lucena e o liberal José Mariano, as Forças foram usadas como:", alternativas: A("polícia de choque", "guarda de fronteira", "corpo de bombeiros", "tropa de elite antidrogas", "milícia eleitoral rural"), gabarito: "A", explicacao: "Foram empregadas como polícia de choque na disputa política." },
  { modulo: "2", tipo: "multipla", enunciado: "Assinale o que NÃO figura entre os principais problemas de segurança do Recife na 1ª metade do séc. XIX:", alternativas: A("tráfico de armas automáticas", "abastecimento de água", "fluxo de marinheiros", "escravos fugidos", "dinheiro falso em circulação"), gabarito: "A", explicacao: "Os problemas eram água, quarentena de escravos, marinheiros, chafarizes, escravos fugidos, enchentes e dinheiro falso." },
  { modulo: "2", tipo: "multipla", enunciado: "As 'batidas' policiais, como prática de repressão, ganham destaque a partir de:", alternativas: A("1913, com a preocupação sobre o proletariado urbano (mocambos)", "1650, na expulsão dos holandeses", "1822, na Independência", "2000, com o CDMEPE", "1985, com a Patrulha do Bairro"), gabarito: "A", explicacao: "Em 1913, a repressão aos mocambos/proletariado urbano consolida as 'batidas'." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Foi somente no século XX que as instituições policiais estreitaram seu campo de ação, da ordem pública para o combate ao crime.", gabarito: "certo", explicacao: "Correto. É uma das conclusões centrais da disciplina." },
  { modulo: "2", tipo: "multipla", enunciado: "A reforma remunerada de 1850 teve como efeito:", alternativas: A("melhorar a condição do policial e aproximar o efetivo do previsto em lei", "extinguir a cavalaria", "criar a Brigada Militar", "abolir o recrutamento forçado em todo o país", "transferir a polícia para o controle municipal"), gabarito: "A", explicacao: "A reforma de 1850 melhorou a remuneração e a condição do policial." },

  // ── M3 ──
  { modulo: "3", tipo: "certo_errado", enunciado: "O Mercado Coelho Cintra, idealizado por Delmiro Gouveia, inspirou-se na Exposição Mundial de Chicago de 1893.", gabarito: "certo", explicacao: "Correto. Delmiro idealizou um grande centro comercial inspirado na feira de Chicago." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Mercado Coelho Cintra foi inaugurado em 1898 e é considerado precursor dos shopping centers no Brasil.", gabarito: "certo", explicacao: "Correto. Tinha mais de 200 boxes e era a única edificação com luz elétrica no fim do séc. XIX." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Em 1897, Delmiro Gouveia adquiriu em leilão as instalações do Prado da Estância.", gabarito: "certo", explicacao: "Correto. Foi a base física do futuro Mercado Coelho Cintra." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O incêndio do Mercado Coelho Cintra, em 1900, foi um acidente sem qualquer relação com disputas políticas.", gabarito: "errado", explicacao: "Errado. O incêndio foi provocado por policiais a mando do governo, no conflito político entre Delmiro e o grupo de Rosa e Silva." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Quartel do Derby foi erguido sobre as bases do antigo Mercado Coelho Cintra, para o 2º Batalhão da Força Pública.", gabarito: "certo", explicacao: "Correto. No governo Sérgio Loreto, pelo Ato nº 376/1923." },
  { modulo: "3", tipo: "multipla", enunciado: "O Quartel do Derby foi parcialmente inaugurado em:", alternativas: A("18 de outubro de 1924", "11 de junho de 1825", "28 de junho de 1900", "1º de janeiro de 1900", "7 de setembro de 1922"), gabarito: "A", explicacao: "18/10/1924, no 2º ano do governo Loreto e centenário da Confederação do Equador." },
  { modulo: "3", tipo: "multipla", enunciado: "A cessão dos terrenos do Derby deu-se pelo Ato nº 376, de 04/07/1923, no governo de:", alternativas: A("Sérgio Loreto", "Roberto Magalhães", "Agamenon Magalhães", "Henrique de Lucena", "Esmeraldino Bandeira"), gabarito: "A", explicacao: "Foi no governo de Sérgio Loreto." },
  { modulo: "3", tipo: "multipla", enunciado: "Antes de se tornar quartel, e após anos de abandono, o prédio do antigo mercado abrigou:", alternativas: A("a Escola de Aprendizes de Artífices", "a Faculdade de Direito do Recife", "o Palácio do Governo", "a Santa Casa de Misericórdia", "o Teatro de Santa Isabel"), gabarito: "A", explicacao: "Até 1909 ficou abandonado; depois abrigou a Escola de Aprendizes de Artífices." },
  { modulo: "3", tipo: "multipla", enunciado: "O conflito que levou à perseguição a Delmiro Gouveia opunha-o ao grupo político de:", alternativas: A("Rosa e Silva", "Sérgio Loreto", "Agamenon Magalhães", "Manuel Cavalcante", "Antero Ferreira"), gabarito: "A", explicacao: "Delmiro entrou em choque com o grupo de Rosa e Silva (prefeito Esmeraldino Bandeira incentivava a repressão)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Após a destruição do mercado, Delmiro Gouveia arrendou o Derby e partiu para a Europa.", gabarito: "certo", explicacao: "Correto. Delmiro deixou o Recife após o episódio." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O Quartel do Derby ganhou ares renascentistas e tornou-se a edificação secular representativa da PMPE.", gabarito: "certo", explicacao: "Correto. É um marco arquitetônico e simbólico da corporação." },
  { modulo: "3", tipo: "multipla", enunciado: "A inauguração parcial do Quartel do Derby coincidiu com o centenário de qual evento histórico?", alternativas: A("Confederação do Equador (1824)", "Independência do Brasil (1822)", "Proclamação da República (1889)", "Abolição da Escravatura (1888)", "Revolução Praieira (1848)"), gabarito: "A", explicacao: "1924 marcou o centenário da Confederação do Equador (1824)." },

  // ── M4 ──
  { modulo: "4", tipo: "certo_errado", enunciado: "As Tropas Volantes foram a solução possível encontrada pelo Estado para enfrentar o cangaço, incorporando saberes regionais.", gabarito: "certo", explicacao: "Correto. Uniam o conhecimento do sertão à estrutura militar." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O termo 'volante', no contexto urbano original, referia-se ao policial que rondava.", gabarito: "certo", explicacao: "Correto. Entre 1878-1888 o corpo volante tinha 850 policiais; com a República o termo caiu em desuso." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O modus operandi de Lampião (extorsão, incêndios, sequestros e deslocamento rápido) expôs a incapacidade do aparato policial.", gabarito: "certo", explicacao: "Correto. Levou à inserção de tropas de deslocamento (20 a 40 homens)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A 'negaça' de Lampião era considerada covardia pelos sertanejos.", gabarito: "errado", explicacao: "Errado. A negaça (evitar o combate, preferir emboscadas) era vista como prudência — 'arte da guerra no mundo sertanejo'." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A indumentária, as armas e as táticas das volantes e dos cangaceiros tornaram-se quase idênticas.", gabarito: "certo", explicacao: "Correto. Daí a expressão 'inimigos fraternos' e 'para exterminar o inimigo foi necessário se tornar muito parecido com ele'." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O coiteiro era o policial mais experiente da tropa volante.", gabarito: "errado", explicacao: "Errado. O coiteiro era o sertanejo que dava asilo/proteção aos cangaceiros (por simpatia ou coação)." },
  { modulo: "4", tipo: "multipla", enunciado: "A estratégia do 'chocalho', no cangaço, consistia em:", alternativas: A("dividir o bando em rumos diferentes e reagrupá-lo adiante por som de chocalho de bode", "tocar o sino da igreja para reunir os homens", "usar explosivos para abrir caminho", "marcar o gado dos coiteiros", "anunciar a chegada às vilas"), gabarito: "A", explicacao: "O bando se separava e se reagrupava guiado pelo som do chocalho." },
  { modulo: "4", tipo: "multipla", enunciado: "Os 'três olhares' do rastejador eram:", alternativas: A("para baixo (pegadas), para cima (urubus/carcarás) e 'com o nariz' (café e perfume)", "norte, sul e oeste", "o do guia, o do soldado e o do coiteiro", "manhã, tarde e noite", "vista, audição e tato"), gabarito: "A", explicacao: "Pegadas no chão; aves de rapina sobre acampamentos; odor de café e perfume." },
  { modulo: "4", tipo: "multipla", enunciado: "O único detalhe que, na prática, diferenciava as volantes dos cangaceiros era que a volante:", alternativas: A("agia em nome das autoridades e das leis", "usava farda azul-marinho", "andava sempre a cavalo", "não usava armas de fogo", "atuava apenas à noite"), gabarito: "A", explicacao: "A legitimidade legal era a diferença essencial; o resto era quase idêntico." },
  { modulo: "4", tipo: "multipla", enunciado: "A estratégia de 'desaparecimento', no cangaço, consistia em:", alternativas: A("fugir por terreno pedregoso (lajes) sem deixar pegadas", "esconder-se em igrejas", "render-se às volantes", "subornar os rastejadores", "incendiar a própria trilha"), gabarito: "A", explicacao: "Fugiam por pedras/lajes para não deixar rastros." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A rede de apoio ao cangaço, entre 1922 e 1926, chegou a ser maior que a da Força Pública.", gabarito: "certo", explicacao: "Correto. O silêncio do sertanejo dificultava muito a atuação das volantes." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Os 'Nazarenos' (Nazaré, entre Floresta e Vila Bela) tornaram-se marco de resistência ao cangaço.", gabarito: "certo", explicacao: "Correto. 'A inimizade local vestiu a farda' — exemplo de resistência regional." },
  { modulo: "4", tipo: "multipla", enunciado: "Os contratos das tropas volantes tinham duração de:", alternativas: A("3 anos, com salários baixos pagos a cada 2 meses", "10 anos, com soldo elevado", "1 ano, sem remuneração", "6 meses renováveis automaticamente", "tempo indeterminado e estável"), gabarito: "A", explicacao: "Eram contratos de 3 anos, com salários baixos pagos a cada 2 meses." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Permanecer em combate prolongado convinha aos cangaceiros, pois aumentava o butim.", gabarito: "errado", explicacao: "Errado. Permanecer em combate significava mais baixas e mais gasto bélico, sem butim — por isso evitavam." },

  // ── M5 ──
  { modulo: "5", tipo: "certo_errado", enunciado: "A 'Nova História Militar' supera a abordagem factual e heroica, estudando a instituição em relação com a sociedade, a cultura e a administração.", gabarito: "certo", explicacao: "Correto. Trata a corporação como ator social." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Para Clausewitz, a guerra é a continuação da política por outros meios.", gabarito: "certo", explicacao: "Correto. É a máxima central de 'Da Guerra'." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Sun Tzu, em 'A Arte da Guerra', valoriza vencer sem combater e o conhecimento do terreno e do inimigo.", gabarito: "certo", explicacao: "Correto. Dialoga com a 'negaça' do cangaço." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A apostila trata o 'cangaceirismo moderno' (assaltos a banco, roubo a coletivo) como fenômeno idêntico ao cangaço histórico.", gabarito: "errado", explicacao: "Errado. São lidos como continuidades/semelhanças, não como fenômenos idênticos." },
  { modulo: "5", tipo: "multipla", enunciado: "A leitura de conexão sobre 'cangaceirismo moderno' aproxima o cangaço de:", alternativas: A("assaltos a banco e roubo a coletivo", "crimes cibernéticos", "contravenções de trânsito", "crimes ambientais", "infrações administrativas militares"), gabarito: "A", explicacao: "A apostila relaciona o cangaço a assaltos a banco e ao roubo a coletivo (mobilidade, intimidação, apoio social)." },
  { modulo: "5", tipo: "multipla", enunciado: "A 'História Policial Militar', segundo a abordagem da disciplina, estuda a corporação:", alternativas: A("como ator social, e não apenas militar", "apenas pelas suas batalhas e heróis", "somente por sua estrutura jurídica atual", "exclusivamente pelos seus uniformes", "apenas por dados estatísticos de crimes"), gabarito: "A", explicacao: "É a perspectiva da Nova História Militar: a corporação como ator social." },
  { modulo: "5", tipo: "multipla", enunciado: "A obra 'Da Guerra', referência conceitual da disciplina, é de:", alternativas: A("Karl von Clausewitz", "Sun Tzu", "Gustave Le Bon", "André Carneiro", "Michel Foucault"), gabarito: "A", explicacao: "Clausewitz é o autor de 'Da Guerra'." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A reflexão sobre a 'derrota clausewitziana' e o atrito da guerra integra os conceitos de História Militar da apostila.", gabarito: "certo", explicacao: "Correto. São conceitos clausewitzianos abordados na leitura de base." },
]

async function main() {
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const all = await prisma.questao.findMany({ where: { materia: MAT }, select: { modulo: true } })
  const mods = new Set(all.map(x => x.modulo))
  console.log(`HPMPE complemento: ${c} criadas/${u} atualizadas. Total ${all.length} (~${(all.length/mods.size).toFixed(1)}/modulo).`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
