import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "LPMO"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 6 — Sistema de Proteção Social ════════
  { modulo: "6", tipo: "certo_errado", enunciado: "O Sistema de Proteção Social dos Militares de Pernambuco (SPSMPE) foi criado pela Lei Complementar nº 460/2021.", gabarito: "certo", explicacao: "Correto. O SPSMPE foi acrescido pela LC nº 460/2021." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O SPSMPE assegura remuneração, inatividade e pensão militar aos integrantes da PMPE/CBMPE e seus dependentes.", gabarito: "certo", explicacao: "Correto. É a finalidade do SPSMPE (art. 74-A)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A gestão do SPSMPE, a partir de 1º de janeiro de 2022, cabe à FUNAPE.", gabarito: "certo", explicacao: "Correto. A FUNAPE gere o SPSMPE desde 01/01/2022." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O Sistema de Proteção Social dos Militares é gerido por empresa privada de previdência complementar.", gabarito: "errado", explicacao: "Errado. A gestão é da FUNAPE (Fundação de Aposentadorias e Pensões dos Servidores do Estado de PE)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O SPSMPE é um conjunto integrado de direitos, ações permanentes e serviços.", gabarito: "certo", explicacao: "Correto. É a definição do art. 74-A." },
  { modulo: "6", tipo: "certo_errado", enunciado: "As regras do Sistema de Proteção Social tratam de matéria previdenciária aplicável aos militares.", gabarito: "certo", explicacao: "Correto. O SPSMPE contém as regras previdenciárias dos militares estaduais." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A FUNAPE cuida da concessão, manutenção e gestão dos benefícios de inatividade e das pensões militares.", gabarito: "certo", explicacao: "Correto. É a competência da FUNAPE no SPSMPE." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O SPSMPE abrange tanto a PMPE quanto o CBMPE.", gabarito: "certo", explicacao: "Correto. O sistema abrange os integrantes da PMPE e do CBMPE e seus dependentes." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A LC nº 460/2021 não tem relação com o Sistema de Proteção Social dos Militares de PE.", gabarito: "errado", explicacao: "Errado. A LC nº 460/2021 é justamente a norma que criou o SPSMPE." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A inatividade e a pensão militar estão entre os objetos assegurados pelo SPSMPE.", gabarito: "certo", explicacao: "Correto. O SPSMPE assegura remuneração, inatividade e pensão." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A gestão do SPSMPE pela FUNAPE iniciou-se em 2030.", gabarito: "errado", explicacao: "Errado. A gestão pela FUNAPE iniciou-se em 1º de janeiro de 2022." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Os dependentes dos militares também são beneficiários do Sistema de Proteção Social.", gabarito: "certo", explicacao: "Correto. O art. 74-A inclui os dependentes." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O Sistema de Proteção Social não inclui a remuneração entre seus objetos.", gabarito: "errado", explicacao: "Errado. O SPSMPE assegura a remuneração, a inatividade e a pensão militar." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A sigla FUNAPE corresponde à Fundação de Aposentadorias e Pensões dos Servidores do Estado de Pernambuco.", gabarito: "certo", explicacao: "Correto. É o significado de FUNAPE." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O SPSMPE é regido exclusivamente por normas federais, sem qualquer base estadual.", gabarito: "errado", explicacao: "Errado. O SPSMPE foi instituído por lei complementar estadual (LC 460/2021)." },

  { modulo: "6", tipo: "multipla", enunciado: "O Sistema de Proteção Social dos Militares de PE (SPSMPE) foi criado pela:", alternativas: A("Lei Complementar nº 460/2021", "Lei nº 6.783/1974", "Lei nº 14.751/2023", "Lei nº 11.328/1996", "Lei nº 11.929/2001"), gabarito: "A", explicacao: "O SPSMPE foi criado pela LC nº 460/2021." },
  { modulo: "6", tipo: "multipla", enunciado: "A gestão do SPSMPE, a partir de 01/01/2022, cabe à:", alternativas: A("FUNAPE", "PMPE", "SEPLAG", "Corregedoria-Geral", "Casa Militar"), gabarito: "A", explicacao: "A FUNAPE gere o SPSMPE desde 01/01/2022." },
  { modulo: "6", tipo: "multipla", enunciado: "O SPSMPE assegura aos militares e dependentes:", alternativas: A("remuneração, inatividade e pensão militar", "apenas a remuneração", "somente a pensão", "apenas planos de saúde", "exclusivamente férias"), gabarito: "A", explicacao: "O art. 74-A assegura remuneração, inatividade e pensão militar." },
  { modulo: "6", tipo: "multipla", enunciado: "O SPSMPE abrange os integrantes:", alternativas: A("da PMPE e do CBMPE e seus dependentes", "apenas da PMPE", "apenas do CBMPE", "de todos os servidores civis", "somente dos oficiais"), gabarito: "A", explicacao: "Abrange PMPE, CBMPE e dependentes." },
  { modulo: "6", tipo: "multipla", enunciado: "As regras do Sistema de Proteção Social dos Militares tratam essencialmente de matéria:", alternativas: A("previdenciária", "tributária", "penal", "eleitoral", "ambiental"), gabarito: "A", explicacao: "O SPSMPE concentra as regras previdenciárias dos militares estaduais." },

  { modulo: "6", tipo: "dissertativa", enunciado: "Discorra sobre o Sistema de Proteção Social dos Militares de PE (SPSMPE): norma de criação, finalidade, abrangência e gestão.", modelo: { estrutura: "Criação (LC 460/2021) → finalidade → abrangência → gestão (FUNAPE).", criterios: ["Citar a LC nº 460/2021", "Apontar a finalidade (remuneração, inatividade e pensão)", "Indicar abrangência (PMPE/CBMPE e dependentes)", "Citar a gestão pela FUNAPE desde 01/01/2022"], resposta: "O Sistema de Proteção Social dos Militares do Estado de Pernambuco (SPSMPE), criado pela Lei Complementar nº 460/2021 (art. 74-A), é o conjunto integrado de direitos, ações permanentes e serviços destinados a assegurar a remuneração, a inatividade e a pensão militar dos integrantes da PMPE e do CBMPE e de seus dependentes. Concentra as regras previdenciárias dos militares estaduais e é gerido, a partir de 1º de janeiro de 2022, pela FUNAPE (Fundação de Aposentadorias e Pensões dos Servidores do Estado de Pernambuco)." } },
  { modulo: "6", tipo: "dissertativa", enunciado: "Explique o papel da FUNAPE no Sistema de Proteção Social dos Militares de PE.", modelo: { estrutura: "Quem é a FUNAPE → competência → início → conclusão.", criterios: ["Identificar a FUNAPE", "Apontar a gestão dos benefícios de inatividade e pensões", "Citar o marco de 01/01/2022"], resposta: "A FUNAPE (Fundação de Aposentadorias e Pensões dos Servidores do Estado de Pernambuco) é a entidade responsável, a partir de 1º de janeiro de 2022, pela gestão do SPSMPE no que se refere à concessão, manutenção e gestão orçamentária e financeira dos benefícios de inatividade dos militares estaduais e das pensões militares de seus dependentes, mantendo os registros segregados das receitas e dos recursos necessários a essas despesas." } },

  // ════════ MÓDULO 7 — Situações Especiais ════════
  { modulo: "7", tipo: "certo_errado", enunciado: "A agregação é a situação na qual o militar da ativa permanece sem número na sua escala hierárquica.", gabarito: "certo", explicacao: "Correto. É o conceito do art. 75 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A agregação abre vaga, inclusive para efeito de promoção.", gabarito: "errado", explicacao: "Errado. A agregação NÃO abre vaga, inclusive para efeito de promoção (art. 75)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A agregação faz-se por ato do Governador do Estado ou de autoridade com poderes delegados.", gabarito: "certo", explicacao: "Correto. É o art. 77 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Reversão é o ato pelo qual o militar agregado retorna ao respectivo quadro quando cessa o motivo da agregação.", gabarito: "certo", explicacao: "Correto. É o art. 78 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O excedente é uma situação permanente e definitiva do militar.", gabarito: "errado", explicacao: "Errado. O excedente é situação TRANSITÓRIA (art. 80)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O militar promovido por bravura sem haver vaga passa, automaticamente, à situação de excedente.", gabarito: "certo", explicacao: "Correto. É hipótese do art. 80 (excedente), ocupando a primeira vaga que surgir." },
  { modulo: "7", tipo: "certo_errado", enunciado: "É considerado ausente o militar que, por mais de 24 horas consecutivas, deixar de comparecer à OME sem comunicar.", gabarito: "certo", explicacao: "Correto. É o art. 81 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O desertor é caracterizado a partir da primeira hora de ausência do militar.", gabarito: "errado", explicacao: "Errado. A deserção configura-se quando esgotado o prazo previsto no Código Penal Militar (após a ausência)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O militar agregado fica adido, para efeito de alterações e remuneração, à OME que lhe for designada.", gabarito: "certo", explicacao: "Correto. É o art. 76 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O militar na situação de excedente é considerado em efetivo serviço e concorre à promoção.", gabarito: "certo", explicacao: "Correto. O §2º do art. 80 considera o excedente em efetivo serviço, concorrendo a cargo e promoção." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A reversão é efetuada por ato do Governador ou de autoridade com poderes delegados.", gabarito: "certo", explicacao: "Correto. É o art. 79 da Lei 6.783/1974." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Aguardar transferência ex-officio para a reserva é uma das hipóteses de agregação.", gabarito: "certo", explicacao: "Correto. É a alínea 'b' do §1º do art. 75." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O excedente recebe a abreviatura 'Ag' em seu registro.", gabarito: "errado", explicacao: "Errado. O excedente recebe a abreviatura 'Excd'; 'Ag' é do agregado (art. 76)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O militar candidato a cargo eletivo, com 5 anos ou mais de serviço, é uma das hipóteses de agregação.", gabarito: "certo", explicacao: "Correto. É hipótese de agregação prevista no art. 75 (a partir do registro até a diplomação/regresso)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A agregação retira do militar a condição de estar em serviço ativo em todas as hipóteses.", gabarito: "errado", explicacao: "Errado. Em hipóteses como nomeação para cargo PM e aguardo de reserva (alíneas a e b), o agregado continua, para todos os efeitos, em serviço ativo (§2º)." },

  { modulo: "7", tipo: "multipla", enunciado: "A situação em que o militar da ativa permanece SEM número na escala hierárquica é a:", alternativas: A("agregação", "reversão", "reforma", "reserva", "excedência"), gabarito: "A", explicacao: "É a agregação (art. 75)." },
  { modulo: "7", tipo: "multipla", enunciado: "O retorno do militar agregado ao seu quadro, quando cessa o motivo da agregação, é a:", alternativas: A("reversão", "reforma", "reserva", "agregação", "excedência"), gabarito: "A", explicacao: "É a reversão (art. 78)." },
  { modulo: "7", tipo: "multipla", enunciado: "É considerado AUSENTE o militar que deixa de comparecer à OME, sem comunicar, por mais de:", alternativas: A("24 horas consecutivas", "8 horas", "48 horas", "72 horas", "12 horas"), gabarito: "A", explicacao: "É o art. 81: mais de 24 horas consecutivas." },
  { modulo: "7", tipo: "multipla", enunciado: "Sobre a agregação, é correto afirmar que:", alternativas: A("não abre vaga, inclusive para promoção, e é feita por ato do Governador", "abre vaga automaticamente", "é decidida pelo comandante de pelotão", "é situação definitiva", "exclui o militar da corporação"), gabarito: "A", explicacao: "A agregação não abre vaga (art. 75) e faz-se por ato do Governador (art. 77)." },
  { modulo: "7", tipo: "multipla", enunciado: "O militar promovido por bravura sem haver vaga passa à situação de:", alternativas: A("excedente", "agregado", "reformado", "reserva", "ausente"), gabarito: "A", explicacao: "É hipótese de excedente (art. 80), que ocupará a primeira vaga." },

  { modulo: "7", tipo: "dissertativa", enunciado: "Conceitue agregação e reversão, indicando a autoridade competente e o efeito da agregação sobre a vaga.", modelo: { estrutura: "Agregação (art. 75) → não abre vaga → autoridade → reversão (art. 78).", criterios: ["Definir agregação (sem número na escala)", "Apontar que não abre vaga (nem p/ promoção)", "Citar ato do Governador", "Definir reversão como retorno ao quadro"], resposta: "Agregação é a situação na qual o militar da ativa permanece sem número na sua escala hierárquica; nos termos da Constituição Estadual, ela não abre vaga, inclusive para efeito de promoção. Faz-se por ato do Governador (ou autoridade delegada) e ocorre em hipóteses como nomeação para cargo civil, aguardo de transferência ex-officio para a reserva e licenças prolongadas. A reversão, por sua vez, é o ato pelo qual o militar agregado retorna ao respectivo quadro, tão logo cesse o motivo que determinou a agregação, voltando a ocupar seu lugar na escala numérica." } },
  { modulo: "7", tipo: "dissertativa", enunciado: "Diferencie o 'excedente', o 'ausente' e o 'desertor' no Estatuto dos Militares de PE.", modelo: { estrutura: "Excedente (art. 80) → ausente (art. 81) → desertor → conclusão.", criterios: ["Excedente: situação transitória (ex.: promoção por bravura sem vaga)", "Ausente: falta por +24h sem comunicar", "Desertor: esgotado o prazo da deserção (CPM)"], resposta: "Excedente é a situação transitória do militar que, por exemplo, é promovido por bravura sem haver vaga; ele ocupa a primeira vaga que surgir e é considerado em efetivo serviço, concorrendo a cargo e promoção. Ausente é o militar que, por mais de 24 horas consecutivas, deixa de comparecer à sua OME sem comunicar. Já o desertor é aquele em relação ao qual se esgotou o prazo que caracteriza o crime de deserção, previsto no Código Penal Militar. São, portanto, situações distintas quanto à causa e aos efeitos." } },

  // ════════ MÓDULO 8 — Desligamento (reserva e reforma) ════════
  { modulo: "8", tipo: "certo_errado", enunciado: "A transferência para a reserva remunerada pode ocorrer a pedido ou ex-officio.", gabarito: "certo", explicacao: "Correto. A reserva remunerada efetua-se a pedido (art. 89) ou ex-officio (art. 90)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A transferência para a reserva ex-officio por idade ocorre aos 67 anos para oficiais e 63 anos para praças.", gabarito: "certo", explicacao: "Correto. O art. 90 fixa 67 anos (oficiais) e 63 anos (praças)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A reforma é a fase da inatividade em que ainda existe possibilidade de retorno ao serviço ativo.", gabarito: "errado", explicacao: "Errado. Na reforma inexiste definitivamente a possibilidade de retorno ao serviço ativo." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A reforma ocorre sempre de ofício.", gabarito: "certo", explicacao: "Correto. O art. 93 estabelece que a reforma ocorre sempre de ofício." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A idade-limite para a reforma é de 70 anos.", gabarito: "certo", explicacao: "Correto. O art. 94, I, fixa a reforma por atingir a idade-limite de 70 anos." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A incapacidade definitiva para o serviço ativo, quando inviável a readaptação, é hipótese de reforma.", gabarito: "certo", explicacao: "Correto. É o art. 94, II, da Lei 6.783/1974." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A perda do posto e da patente do oficial conduz à demissão ex-officio.", gabarito: "certo", explicacao: "Correto. O oficial que perde o posto e a patente é demitido ex-officio (art. 106 da Lei 6.783/1974)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A reserva remunerada por idade dos oficiais ocorre aos 70 anos.", gabarito: "errado", explicacao: "Errado. A reserva ex-officio por idade dos oficiais é aos 67 anos; 70 anos é a idade-limite da REFORMA." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O militar agregado por mais de 2 anos, por incapacidade temporária homologada pela Junta de Saúde, pode ser reformado.", gabarito: "certo", explicacao: "Correto. É hipótese de reforma do art. 94, III." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A perda do posto e da patente do oficial decorre de decisão do Tribunal de Justiça do Estado de Pernambuco.", gabarito: "certo", explicacao: "Correto. O art. 107 prevê a perda mediante decisão do TJPE (indignidade/incompatibilidade)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A transferência para a reserva ex-officio por idade das praças ocorre aos 63 anos.", gabarito: "certo", explicacao: "Correto. O art. 90 fixa 63 anos para as praças." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A condenação à pena de reforma prevista no CPM, por sentença transitada em julgado, é hipótese de reforma.", gabarito: "certo", explicacao: "Correto. É o art. 94, IV, da Lei 6.783/1974." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A reforma admite retorno do militar ao serviço ativo a qualquer tempo, a critério do comando.", gabarito: "errado", explicacao: "Errado. Na reforma inexiste definitivamente a possibilidade de retorno ao serviço ativo." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A transferência para a reserva e a reforma não isentam o militar de certas obrigações (como responder por fatos pretéritos).", gabarito: "certo", explicacao: "Correto. O art. 86 dispõe que a transferência para a reserva ou a reforma não isentam o militar dessas obrigações." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A transferência para a reserva a pedido independe de qualquer requisito de tempo de serviço.", gabarito: "errado", explicacao: "Errado. A reserva a pedido (art. 89) submete-se a requisitos (tempo de serviço/regras conforme data de ingresso), não sendo incondicionada." },

  { modulo: "8", tipo: "multipla", enunciado: "A transferência para a reserva remunerada ex-officio por idade ocorre aos:", alternativas: A("67 anos (oficiais) e 63 anos (praças)", "70 anos para todos", "65 anos para todos", "60 anos (oficiais) e 55 (praças)", "75 anos (oficiais) e 70 (praças)"), gabarito: "A", explicacao: "O art. 90 fixa 67 anos (oficiais) e 63 anos (praças)." },
  { modulo: "8", tipo: "multipla", enunciado: "A idade-limite para a REFORMA é de:", alternativas: A("70 anos", "63 anos", "67 anos", "75 anos", "65 anos"), gabarito: "A", explicacao: "O art. 94, I, fixa a reforma por atingir 70 anos." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre a reforma, é correto afirmar que:", alternativas: A("inexiste definitivamente a possibilidade de retorno ao ativo e ocorre sempre de ofício", "é sempre a pedido", "permite retorno a qualquer tempo", "depende de concurso", "é situação transitória"), gabarito: "A", explicacao: "A reforma é definitiva e ocorre sempre de ofício (arts. 93-94)." },
  { modulo: "8", tipo: "multipla", enunciado: "A perda do posto e da patente do oficial conduz à:", alternativas: A("demissão ex-officio", "reforma compulsória", "transferência para a reserva a pedido", "exclusão a bem da disciplina", "agregação"), gabarito: "A", explicacao: "O oficial que perde o posto e a patente é demitido ex-officio (art. 106)." },
  { modulo: "8", tipo: "multipla", enunciado: "A transferência para a reserva remunerada efetua-se:", alternativas: A("a pedido (art. 89) ou ex-officio (art. 90)", "apenas a pedido", "apenas ex-officio", "somente por decisão judicial", "exclusivamente por idade"), gabarito: "A", explicacao: "A reserva pode ser a pedido ou ex-officio." },

  { modulo: "8", tipo: "dissertativa", enunciado: "Diferencie a transferência para a reserva remunerada da reforma, indicando idades e caráter (definitividade).", modelo: { estrutura: "Reserva (a pedido/ex-officio; idades) → reforma (definitiva; idade-limite) → conclusão.", criterios: ["Reserva: a pedido (89) ou ex-officio (90); idade 67/63", "Reforma: sempre de ofício; idade-limite 70; definitiva", "Concluir pela distinção de definitividade"], resposta: "A transferência para a reserva remunerada pode ocorrer a pedido (art. 89) ou ex-officio (art. 90); por idade, dá-se aos 67 anos para oficiais e 63 anos para praças, além de hipóteses por tempo no posto e por promoção requerida. A reforma (arts. 93-94) é a fase da inatividade em que inexiste definitivamente a possibilidade de retorno ao serviço ativo, ocorrendo sempre de ofício, e tem como idade-limite os 70 anos (além de incapacidade definitiva, condenação à pena de reforma e decisão do TJPE). A distinção essencial está na definitividade: a reforma é definitiva, enquanto a reserva integra a inatividade remunerada do militar." } },
  { modulo: "8", tipo: "dissertativa", enunciado: "Explique as hipóteses de reforma do militar (art. 94) e a situação do oficial que perde o posto e a patente.", modelo: { estrutura: "Hipóteses de reforma → demissão ex-officio do oficial → conclusão.", criterios: ["Citar idade-limite de 70 anos", "Citar incapacidade definitiva", "Citar agregação por +2 anos / condenação à pena de reforma / decisão do TJPE", "Apontar a demissão ex-officio do oficial que perde posto/patente"], resposta: "A reforma (art. 94) ocorre quando o militar: atinge a idade-limite de 70 anos; é julgado definitivamente incapaz para o serviço ativo (sem possibilidade de readaptação); permanece agregado por mais de 2 anos por incapacidade temporária homologada; é condenado à pena de reforma do CPM por sentença transitada em julgado; ou, sendo oficial, tem a reforma determinada pelo TJPE em Conselho de Justificação. Quanto ao oficial que perde o posto e a patente (por declaração de indignidade/incompatibilidade pelo TJPE), o desligamento se dá pela demissão ex-officio (art. 106), sem direito a remuneração ou indenização." } },

  // ════════ MÓDULO 9 — Remuneração, Promoção e Afastamentos ════════
  { modulo: "9", tipo: "certo_errado", enunciado: "A remuneração do militar é composta por soldo (e quotas de soldo), gratificações e indenizações.", gabarito: "certo", explicacao: "Correto. A apostila estrutura a remuneração em soldo, gratificações e indenizações." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A GLE corresponde à Gratificação de Localidade Especial.", gabarito: "certo", explicacao: "Correto. GLE = Gratificação de Localidade Especial." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Vale-refeição, auxílio-uniforme, ajuda de custo e diárias são exemplos de indenizações.", gabarito: "certo", explicacao: "Correto. São indenizações citadas na apostila." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção é um ato administrativo formal de ascensão na carreira, baseado em mérito e antiguidade.", gabarito: "certo", explicacao: "Correto. A promoção é ato formal de ascensão por mérito/antiguidade." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Súmula Vinculante nº 43 do STF admite o provimento derivado que permita ascender, sem concurso, a cargo de carreira diversa.", gabarito: "errado", explicacao: "Errado. A SV 43 VEDA o provimento que permita investir-se, sem concurso, em cargo de carreira diversa." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A GSE corresponde à Gratificação de Serviço Extraordinário.", gabarito: "certo", explicacao: "Correto. GSE = Gratificação de Serviço Extraordinário." },
  { modulo: "9", tipo: "certo_errado", enunciado: "São direitos do militar as férias, os afastamentos temporários e as licenças.", gabarito: "certo", explicacao: "Correto. Constam do rol de direitos do Estatuto." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A licença-maternidade e a licença-paternidade estão entre as licenças tratadas na disciplina.", gabarito: "certo", explicacao: "Correto. A apostila trata da licença-maternidade e da licença-paternidade." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O soldo é uma indenização paga eventualmente ao militar.", gabarito: "errado", explicacao: "Errado. O soldo é a base da remuneração do militar, não uma indenização eventual." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A GOEPM é a Gratificação de Operações Especiais.", gabarito: "certo", explicacao: "Correto. GOEPM = Gratificação de Operações Especiais." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção pode ocorrer pelos critérios de antiguidade e merecimento.", gabarito: "certo", explicacao: "Correto. A promoção combina os critérios de mérito e antiguidade." },
  { modulo: "9", tipo: "certo_errado", enunciado: "As gratificações integram a remuneração do militar.", gabarito: "certo", explicacao: "Correto. As gratificações compõem a remuneração, ao lado do soldo e das indenizações." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Súmula Vinculante nº 43 do STF trata da inconstitucionalidade de provimento sem concurso em cargo de carreira diversa.", gabarito: "certo", explicacao: "Correto. É o teor da SV 43." },
  { modulo: "9", tipo: "certo_errado", enunciado: "As diárias são uma espécie de gratificação permanente incorporada ao soldo.", gabarito: "errado", explicacao: "Errado. As diárias são indenizações (eventuais), não gratificações permanentes incorporadas." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Gratificação por exercício na atividade de inteligência (GEAI) é uma das gratificações previstas.", gabarito: "certo", explicacao: "Correto. A GEAI consta entre as gratificações citadas na apostila." },

  { modulo: "9", tipo: "multipla", enunciado: "A remuneração do militar compõe-se, essencialmente, de:", alternativas: A("soldo, gratificações e indenizações", "apenas soldo", "salário-mínimo e comissões", "lucro e dividendos", "honorários e diárias apenas"), gabarito: "A", explicacao: "A remuneração estrutura-se em soldo, gratificações e indenizações." },
  { modulo: "9", tipo: "multipla", enunciado: "São exemplos de INDENIZAÇÕES:", alternativas: A("vale-refeição, auxílio-uniforme, ajuda de custo e diárias", "GLE e GSE", "soldo e quotas de soldo", "promoção e estabilidade", "férias e licenças"), gabarito: "A", explicacao: "Vale-refeição, auxílio-uniforme, ajuda de custo e diárias são indenizações." },
  { modulo: "9", tipo: "multipla", enunciado: "A promoção do militar é:", alternativas: A("ato administrativo formal de ascensão, por mérito e antiguidade", "ato discricionário sem critérios", "decisão exclusiva do próprio militar", "consequência automática do tempo de farda sem requisitos", "ato privativo do Judiciário"), gabarito: "A", explicacao: "A promoção é ato formal de ascensão, baseado em mérito e antiguidade." },
  { modulo: "9", tipo: "multipla", enunciado: "A Súmula Vinculante nº 43 do STF:", alternativas: A("veda provimento que permita investir-se, sem concurso, em cargo de carreira diversa", "autoriza qualquer ascensão funcional", "trata de porte de armas", "regula licenças-maternidade", "fixa a idade da reforma"), gabarito: "A", explicacao: "A SV 43 veda o provimento derivado sem concurso para cargo de carreira diversa." },
  { modulo: "9", tipo: "multipla", enunciado: "A sigla GLE refere-se à:", alternativas: A("Gratificação de Localidade Especial", "Gratificação de Localização Estadual", "Gratificação Legal Extraordinária", "Garantia de Lotação Especial", "Gratificação de Logística Específica"), gabarito: "A", explicacao: "GLE = Gratificação de Localidade Especial." },

  { modulo: "9", tipo: "dissertativa", enunciado: "Explique a composição da remuneração do militar (soldo, gratificações e indenizações), com exemplos.", modelo: { estrutura: "Soldo → gratificações → indenizações → exemplos.", criterios: ["Definir o soldo como base", "Citar gratificações (GLE, GSE, GOEPM etc.)", "Citar indenizações (vale-refeição, auxílio-uniforme, ajuda de custo, diárias)"], resposta: "A remuneração do militar compõe-se do soldo (e quotas de soldo), que é a base, somado às gratificações e às indenizações. As gratificações remuneram condições específicas do serviço — por exemplo, GLE (Localidade Especial), GSE (Serviço Extraordinário), GOEPM (Operações Especiais), gratificações de risco de plantão, de perigo laboral e de atividade de inteligência (GEAI). As indenizações ressarcem despesas — como vale-refeição, auxílio-uniforme, ajuda de custo e diárias." } },
  { modulo: "9", tipo: "dissertativa", enunciado: "Conceitue a promoção do militar e relacione-a com a Súmula Vinculante nº 43 do STF.", modelo: { estrutura: "Conceito de promoção → critérios → SV 43 → conclusão.", criterios: ["Definir promoção (ascensão formal na carreira)", "Citar mérito e antiguidade", "Explicar a SV 43 (vedação de provimento sem concurso em carreira diversa)"], resposta: "A promoção é o ato administrativo formal que permite ao militar ascender dentro da carreira a que se submeteu mediante concurso público, com base nos critérios de mérito e antiguidade. Relaciona-se com a Súmula Vinculante nº 43 do STF, que declara inconstitucional toda modalidade de provimento que permita ao servidor investir-se, sem prévia aprovação em concurso público destinado ao respectivo provimento, em cargo que não integra a carreira na qual anteriormente investido — ou seja, a promoção é progressão dentro da mesma carreira, não podendo servir de via transversa para outra." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`LPMO (mods 6-9): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
