import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

// LPMO — Assunto 2 (banco por tema + simulado da 2ª Avaliação).
// Módulos 6 a 11 = os 6 temas do memento "MEMENTO LPMO 2"; módulo 12 = simulado da turma.
// Substitui o conteúdo antigo dos módulos 6-9: questões desses módulos que não
// estejam neste arquivo são REMOVIDAS (junto com as respostas já dadas nelas).

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "LPMO"
const MODULOS = ["6", "7", "8", "9", "10", "11", "12"]

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string; fonte?: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string; fonte?: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string }; fonte?: string }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [

  // ════════ MÓDULO 6 — Tema 1 — Situações especiais ════════
  // Lei 6.783/74, arts. 75 a 84 (agregação, reversão, excedente, ausente/desertor, desaparecido e extravio)
  { modulo: "6", tipo: "certo_errado", enunciado: "A agregação é a situação na qual o policial-militar da ativa permanece sem número na sua escala hierárquica.", gabarito: "certo", explicacao: "Art. 75, caput, Lei 6.783/74." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Nos termos da Constituição Estadual, a agregação abre vaga para efeito de promoção.", gabarito: "errado", explicacao: "Art. 75, caput: a agregação NÃO abre vaga, inclusive para efeito de promoção." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O policial-militar agregado por nomeação para cargo de natureza PM não previsto nos quadros continua considerado, para todos os efeitos, em serviço ativo.", gabarito: "certo", explicacao: "Art. 75, §2º (alíneas 'a' e 'b')." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A agregação por aguardar transferência ex officio para a reserva é contada a partir do primeiro dia após o respectivo prazo.", gabarito: "errado", explicacao: "Art. 75, §5º: nessa hipótese (alínea 'b') conta-se da data indicada no ato que torna público o evento." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A agregação se faz por ato do Governador do Estado de Pernambuco ou de autoridade a qual tenham sido delegados poderes para isso.", gabarito: "certo", explicacao: "Art. 77, Lei 6.783/74." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O militar agregado poderá concorrer às promoções pelos critérios de antiguidade e de merecimento.", gabarito: "errado", explicacao: "Art. 76, §1º: o agregado só concorre à promoção pelo princípio da ANTIGUIDADE." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O policial-militar agregado fica adido, para efeito de alterações e remuneração, à OPM que lhe for designada, com a abreviatura 'Ag'.", gabarito: "certo", explicacao: "Art. 76, caput." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A reversão é o ato pelo qual o agregado retorna ao respectivo quadro tão logo cesse o motivo que determinou a agregação.", gabarito: "certo", explicacao: "Art. 78, caput." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A reversão do agregado pode ser determinada a qualquer tempo, sem qualquer exceção prevista em lei.", gabarito: "errado", explicacao: "Art. 78, par. único: há exceções (incisos I, II, III, VI, VII, VIII, XI, XIV e XV da alínea 'c' do §1º do Art. 75)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Excedente é a situação transitória a que, automaticamente, passa o policial-militar promovido por bravura sem haver vaga.", gabarito: "certo", explicacao: "Art. 80, I." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O policial-militar excedente perde a antiguidade que possuía e não concorre a promoções enquanto durar a situação.", gabarito: "errado", explicacao: "Art. 80, §§1º e 2º: mantém a antiguidade (abrev. 'Excd') e concorre a promoção sem restrição." },
  { modulo: "6", tipo: "certo_errado", enunciado: "É considerado ausente o policial-militar que, por mais de 24 horas consecutivas, deixar de comparecer à OPM sem comunicar impedimento.", gabarito: "certo", explicacao: "Art. 81, I." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O policial-militar é considerado desertor nos casos previstos na legislação penal militar.", gabarito: "certo", explicacao: "Art. 82." },
  { modulo: "6", tipo: "certo_errado", enunciado: "É considerado desaparecido o militar da ativa que, no desempenho de serviço, tiver paradeiro ignorado por mais de 15 dias.", gabarito: "errado", explicacao: "Art. 83: o prazo é de mais de 8 (oito) dias." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O policial-militar que permanecer desaparecido por mais de 30 dias será oficialmente considerado extraviado.", gabarito: "certo", explicacao: "Art. 84." },

  { modulo: "6", tipo: "multipla", enunciado: "Sobre a agregação (Lei 6.783/74), assinale a alternativa CORRETA:", alternativas: A("Abre vaga para efeito de promoção, desde que o agregado conte mais de 10 anos de serviço.", "É concedida exclusivamente aos oficiais, não se aplicando às praças.", "Se faz por ato do Governador do Estado ou de autoridade a qual tenham sido delegados poderes.", "Impede, em qualquer hipótese, que o militar seja considerado em serviço ativo.", "É sempre contada a partir da publicação do ato, qualquer que seja a hipótese."), gabarito: "C", explicacao: "Art. 77. Não abre vaga (Art. 75); aplica-se a praças; nas alíneas 'a'/'b' segue em serviço ativo (§2º); a contagem varia conforme a hipótese (§§3º a 6º)." },
  { modulo: "6", tipo: "multipla", enunciado: "Quanto à situação de excedente, é correto afirmar que:", alternativas: A("O excedente perde a antiguidade na escala hierárquica.", "O excedente não pode concorrer a promoções.", "O promovido por bravura sem vaga ocupará a primeira vaga aberta, deslocando o princípio de promoção para a vaga seguinte.", "A situação de excedente é permanente.", "O excedente recebe a abreviatura 'Ag'."), gabarito: "C", explicacao: "Art. 80, §3º. Mantém antiguidade (§1º), concorre a promoção (§2º), é transitória e usa a abreviatura 'Excd'." },
  { modulo: "6", tipo: "multipla", enunciado: "A reversão do policial-militar agregado (Art. 78):", alternativas: A("É efetuada por ato do Comandante-Geral, exclusivamente.", "Ocorre quando cessa o motivo que determinou a agregação, voltando o militar a ocupar seu lugar na escala numérica.", "Abre vaga no respectivo quadro.", "Independe de qualquer exceção legal.", "Só é possível para oficiais."), gabarito: "B", explicacao: "Art. 78, caput. É efetuada por ato do Governador (Art. 79) e comporta exceções (par. único)." },
  { modulo: "6", tipo: "multipla", enunciado: "Assinale a alternativa que apresenta corretamente um prazo do Tema:", alternativas: A("Ausente: mais de 48 horas.", "Desaparecido: mais de 30 dias.", "Extraviado: mais de 8 dias.", "Desaparecido: mais de 8 dias; extraviado: mais de 30 dias.", "Ausente: mais de 12 horas."), gabarito: "D", explicacao: "Arts. 81 (ausente: +24h), 83 (desaparecido: +8 dias) e 84 (extraviado: +30 dias)." },
  { modulo: "6", tipo: "multipla", enunciado: "Sobre os efeitos da agregação, assinale a INCORRETA:", alternativas: A("O agregado fica sujeito às obrigações disciplinares com PMs e autoridades civis.", "Órgão que tiver PM à disposição arca integral e exclusivamente com a remuneração, salvo Assistência PM/Civil.", "O agregado permanece sem número na escala hierárquica.", "O agregado, em regra, concorre a promoção por antiguidade e merecimento.", "A agregação não abre vaga."), gabarito: "D", explicacao: "Art. 76, §1º: o agregado concorre apenas por antiguidade — por isso a assertiva 'd' é a incorreta." },

  { modulo: "6", tipo: "dissertativa", enunciado: "Disserte sobre a AGREGAÇÃO: conceito, efeito quanto à vaga, competência e critério de promoção do agregado. (mín. 5, máx. 12 linhas)", modelo: { estrutura: "Conceito → Vaga → Competência → Promoção → Complemento.", criterios: ["Conceito: PM da ativa permanece SEM NÚMERO na escala hierárquica (Art. 75, caput).", "Vaga: não abre vaga, inclusive para promoção (Art. 75, caput, c/ Constituição Estadual).", "Competência: ato do Governador ou autoridade delegada (Art. 77).", "Promoção: o agregado só concorre por ANTIGUIDADE (Art. 76, §1º).", "Complemento: nas alíneas 'a'/'b' do §1º segue em serviço ativo (§2º); fica adido com a abreviatura 'Ag' (Art. 76)."], resposta: "Conceito: PM da ativa permanece SEM NÚMERO na escala hierárquica (Art. 75, caput). Vaga: não abre vaga, inclusive para promoção (Art. 75, caput, c/ Constituição Estadual). Competência: ato do Governador ou autoridade delegada (Art. 77). Promoção: o agregado só concorre por ANTIGUIDADE (Art. 76, §1º). Complemento: nas alíneas 'a'/'b' do §1º segue em serviço ativo (§2º); fica adido com a abreviatura 'Ag' (Art. 76)." } },
  { modulo: "6", tipo: "dissertativa", enunciado: "Diferencie AUSENTE, DESAPARECIDO e EXTRAVIADO, indicando os respectivos prazos. (mín. 4, máx. 10 linhas)", modelo: { estrutura: "Ausente (Art. 81) → Desaparecido (Art. 83) → Extraviado (Art. 84) → Observação → Desertor (Art. 82).", criterios: ["Ausente (Art. 81): mais de 24h consecutivas sem comparecer/comunicar impedimento, ou ausência sem licença.", "Desaparecido (Art. 83): paradeiro ignorado por mais de 8 dias, em serviço/viagem/operação/calamidade, sem indício de deserção.", "Extraviado (Art. 84): desaparecido por mais de 30 dias.", "Observação: a situação de desaparecido só se considera quando não houver indício de deserção (Art. 83, par. único).", "Desertor (Art. 82): nos casos da legislação penal militar."], resposta: "Ausente (Art. 81): mais de 24h consecutivas sem comparecer/comunicar impedimento, ou ausência sem licença. Desaparecido (Art. 83): paradeiro ignorado por mais de 8 dias, em serviço/viagem/operação/calamidade, sem indício de deserção. Extraviado (Art. 84): desaparecido por mais de 30 dias. Observação: a situação de desaparecido só se considera quando não houver indício de deserção (Art. 83, par. único). Desertor (Art. 82): nos casos da legislação penal militar." } },

  // ════════ MÓDULO 7 — Tema 2 — Desligamento/exclusão do serviço ativo ════════
  // Lei 6.783/74, arts. 85 a 111; LC 460/2021 (reserva, reforma, readaptação, demissão/perda de posto, licenciamento)
  { modulo: "7", tipo: "certo_errado", enunciado: "São hipóteses de desligamento/exclusão do serviço ativo, entre outras, a reserva remunerada, a reforma, a demissão, o licenciamento, a deserção, o falecimento e o extravio.", gabarito: "certo", explicacao: "Art. 85, incisos I a IX." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A agregação é hipótese de desligamento ou exclusão do serviço ativo prevista no art. 85.", gabarito: "errado", explicacao: "A agregação é situação especial (Art. 75); não consta do rol do Art. 85." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A transferência para a reserva ou a reforma isenta o militar de indenizar prejuízos causados à Fazenda estadual.", gabarito: "errado", explicacao: "Art. 86: reserva/reforma NÃO isentam da indenização nem das pensões judiciais." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O desligamento da OPM não pode exceder 45 dias da data da primeira publicação oficial do ato.", gabarito: "certo", explicacao: "Art. 87, par. único." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Para quem ingressou a partir de 1º/01/2022, a reserva a pedido com proventos integrais exige 35 anos de serviço, dos quais no mínimo 30 de atividade militar em PE.", gabarito: "certo", explicacao: "Art. 89, Lei 6.783/74." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Não será concedida reserva a pedido a quem esteja respondendo inquérito/processo em qualquer jurisdição ou cumprindo pena de qualquer natureza.", gabarito: "certo", explicacao: "Art. 89, 'a' e 'b'." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A transferência ex officio por idade ocorre aos 63 anos para oficiais e aos 67 anos para praças.", gabarito: "errado", explicacao: "Art. 90: oficiais 67 anos; praças 63 anos (a assertiva inverteu)." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A reforma do militar do Estado ocorre sempre de ofício.", gabarito: "certo", explicacao: "Art. 93, Lei 6.783/74." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A reforma ocorre quando o militar atinge a idade-limite de 70 anos.", gabarito: "certo", explicacao: "Art. 94, I." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A reforma ocorre quando o militar estiver agregado por mais de 2 anos por ter sido julgado incapaz temporariamente, mediante homologação da Junta de Saúde.", gabarito: "certo", explicacao: "Art. 94, III." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Na readaptação real, se o tempo reformado não ultrapassar 5 anos, o militar retorna ao serviço ativo.", gabarito: "certo", explicacao: "Art. 100, §1º." },
  { modulo: "7", tipo: "certo_errado", enunciado: "Na readaptação prospectiva, o militar permanece no serviço ativo em atividade administrativa, no mesmo posto/graduação, independentemente de ser julgado apto pela Junta.", gabarito: "errado", explicacao: "Art. 93, §1º: depende de ser julgado APTO pela Junta Militar de Saúde." },
  { modulo: "7", tipo: "certo_errado", enunciado: "A demissão da Polícia Militar aplica-se exclusivamente aos oficiais.", gabarito: "certo", explicacao: "Art. 103, caput." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O oficial demissionário a pedido mantém o direito a remuneração proporcional ao tempo de serviço prestado.", gabarito: "errado", explicacao: "Art. 104, §3º: o demissionário a pedido não tem direito a qualquer remuneração." },
  { modulo: "7", tipo: "certo_errado", enunciado: "O licenciamento do serviço ativo aplica-se somente às praças.", gabarito: "certo", explicacao: "Art. 109, caput." },

  { modulo: "7", tipo: "multipla", enunciado: "Nos termos do art. 85 da Lei 6.783/74, é INCORRETO afirmar que constitui hipótese de desligamento/exclusão do serviço ativo:", alternativas: A("A transferência para a reserva remunerada.", "A reforma.", "A demissão.", "A agregação.", "O falecimento."), gabarito: "D", explicacao: "A agregação é situação especial (Art. 75), não hipótese de desligamento (Art. 85)." },
  { modulo: "7", tipo: "multipla", enunciado: "Para o militar que ingressou a partir de 1º/01/2022, a reserva a pedido exige:", alternativas: A("30 anos de serviço, independentemente do tempo de atividade militar.", "35 anos de serviço, sendo no mínimo 30 de atividade de natureza militar em PE.", "35 anos exclusivamente de efetivo serviço militar.", "Apenas idade mínima de 60 anos.", "30 anos de efetivo militar e idade mínima de 55 anos."), gabarito: "B", explicacao: "Art. 89, Lei 6.783/74." },
  { modulo: "7", tipo: "multipla", enunciado: "Assinale a INCORRETA a respeito da reforma do militar do Estado:", alternativas: A("Ocorre sempre de ofício.", "Ocorre quando o militar atinge a idade-limite de 70 anos.", "Ocorre quando julgado incapaz definitivamente, desde que não seja possível a readaptação.", "Ocorre quando agregado por mais de 2 anos por incapacidade temporária, mediante homologação da Junta.", "Pode ser requerida a pedido do próprio militar, a qualquer tempo, independentemente das hipóteses legais."), gabarito: "E", explicacao: "Art. 93: a reforma ocorre SEMPRE de ofício; jamais a pedido." },
  { modulo: "7", tipo: "multipla", enunciado: "Segundo o art. 89, NÃO será concedida reserva a pedido ao policial-militar que:", alternativas: A("Contar com menos de 40 anos de idade.", "For do sexo feminino.", "Estiver respondendo inquérito ou processo em qualquer jurisdição, ou cumprindo pena de qualquer natureza.", "Estiver na ativa há menos de 20 anos.", "Estiver em gozo de férias regulamentares."), gabarito: "C", explicacao: "Art. 89, 'a' e 'b'." },
  { modulo: "7", tipo: "multipla", enunciado: "Sobre demissão, perda de posto e licenciamento, assinale a CORRETA:", alternativas: A("A demissão aplica-se a oficiais e praças indistintamente.", "O oficial com mais de 5 anos de oficialato tem demissão a pedido sem indenizar os cofres públicos.", "O licenciamento aplica-se aos oficiais.", "O demissionário a pedido conserva remuneração proporcional.", "A perda de posto e patente independe de decisão do TJPE."), gabarito: "B", explicacao: "Art. 104, I. Demissão é só de oficiais (Art. 103); licenciamento é só de praças (Art. 109); demissionário a pedido não tem remuneração (Art. 104, §3º); perda de posto depende do TJPE (Art. 107)." },

  { modulo: "7", tipo: "dissertativa", enunciado: "Discorra sobre a RESERVA REMUNERADA A PEDIDO do militar ingresso a partir de 1º/01/2022: tempo exigido e restrições legais. (mín. 5, máx. 10 linhas)", modelo: { estrutura: "Regra (Art. 89) → Natureza militar → Restrição 'a' → Restrição 'b'.", criterios: ["Regra (Art. 89): 35 anos de serviço, mediante requerimento, com proventos integrais.", "Natureza militar: no mínimo 30 desses anos de atividade de natureza militar em Pernambuco.", "Restrição 'a': não concedida a quem responde inquérito/processo em qualquer jurisdição.", "Restrição 'b': não concedida a quem cumpre pena de qualquer natureza."], resposta: "Regra (Art. 89): 35 anos de serviço, mediante requerimento, com proventos integrais. Natureza militar: no mínimo 30 desses anos de atividade de natureza militar em Pernambuco. Restrição 'a': não concedida a quem responde inquérito/processo em qualquer jurisdição. Restrição 'b': não concedida a quem cumpre pena de qualquer natureza." } },
  { modulo: "7", tipo: "dissertativa", enunciado: "Diferencie READAPTAÇÃO PROSPECTIVA e REAL, com os efeitos temporais da real. (mín. 5, máx. 12 linhas)", modelo: { estrutura: "Prospectiva (Art. 93, §1º) → Real (Art. 100) → Real ≤ 5 → Real > 5.", criterios: ["Prospectiva (Art. 93, §1º): militar que incorreria em reforma por incapacidade definitiva na atividade-fim (por deficiência) permanece no serviço ativo em atividade administrativa, mesmo posto/graduação, se apto pela Junta.", "Real (Art. 100): já reformado, julgado apto em recurso/revisão, retorna como apto ou readaptado.", "Real ≤ 5 anos reformado → retorna ao serviço ativo (§1º).", "Real > 5 anos → regride para reserva remunerada, respeitadas idades-limite (§2º)."], resposta: "Prospectiva (Art. 93, §1º): militar que incorreria em reforma por incapacidade definitiva na atividade-fim (por deficiência) permanece no serviço ativo em atividade administrativa, mesmo posto/graduação, se apto pela Junta. Real (Art. 100): já reformado, julgado apto em recurso/revisão, retorna como apto ou readaptado. Real ≤ 5 anos reformado → retorna ao serviço ativo (§1º). Real > 5 anos → regride para reserva remunerada, respeitadas idades-limite (§2º)." } },

  // ════════ MÓDULO 8 — Tema 3 — Remuneração ════════
  // Lei 6.783/74, arts. 52-57; Lei 10.426/90; LC 32/2001; LC 460/2021 (soldo, proventos, gratificações, indenizações, auxílio-invalidez)
  { modulo: "8", tipo: "certo_errado", enunciado: "O soldo é irredutível e não está sujeito a penhora, sequestro ou arresto, exceto nos casos previstos em lei.", gabarito: "certo", explicacao: "Art. 54, Lei 6.783/74." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O valor do soldo é igual para o militar da ativa, da reserva ou reformado de um mesmo grau hierárquico, ressalvadas as exceções legais.", gabarito: "certo", explicacao: "Art. 55." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A integralidade é o direito do inativo perceber a remuneração do posto/graduação que ocupava na ativa, salvo proporcionalidade.", gabarito: "certo", explicacao: "Art. 74-C, VI (LC 460/2021)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A paridade é o direito de o inativo ter a remuneração revista em proporção e data distintas das dos militares ativos.", gabarito: "errado", explicacao: "Art. 74-C, VII: a revisão ocorre na MESMA proporção e data dos ativos." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A Gratificação de Localidade Especial (GLE) mantém atualmente o valor de 15% do soldo do posto ou graduação.", gabarito: "errado", explicacao: "O art. 24 (Lei 10.426/90) foi tacitamente revogado pela LC 32/2001; a GLE passou a ter valor NOMINAL." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A gratificação de motorista teve seu percentual sobre o soldo tacitamente revogado pela LC 32/2001, passando a valor nominal.", gabarito: "certo", explicacao: "LC 32/2001 (vedação de vinculação ao soldo)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A GOEPM, dos integrantes do BEPI e BOPE, pode ser acumulada com qualquer outra gratificação prevista na Lei.", gabarito: "errado", explicacao: "Art. 6º-A da Lei 13.487/08: quem recebe a GOEPM não pode receber qualquer outra gratificação da Lei." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A GAT-4 não pode ser cumulada com a GOEPM nem com a Gratificação por Encargo de Comando (GEC).", gabarito: "certo", explicacao: "Lei 13.487/08 (GAT-4)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A GSE — Gratificação de Serviço Extraordinário foi extinta pela LC 59/2004.", gabarito: "errado", explicacao: "A GSE permanece; foram extintas GCP, GR, GM e GE (LC 59/2004) e a GTS (LC 169/2011)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A ajuda de custo é a indenização de despesas de viagem e de nova instalação, paga ao militar movimentado com mudança de moradia.", gabarito: "certo", explicacao: "Art. 42, Lei 10.426/90." },
  { modulo: "8", tipo: "certo_errado", enunciado: "Diárias destinam-se a atender despesas extraordinárias de alimentação e pousada no afastamento da sede por motivo de serviço.", gabarito: "certo", explicacao: "Art. 36, Lei 10.426/90." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O vale-refeição jamais poderá ser suspenso, por constituir direito adquirido do militar.", gabarito: "errado", explicacao: "Pode ser suspenso, p.ex. quando o militar recebe refeição por conta do Estado (IN CG 635/2025)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O auxílio-uniforme encontra-se definido em valor único para todos os postos e graduações.", gabarito: "certo", explicacao: "Anexo IV-E da LC 32/2001." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O auxílio-invalidez é devido ao militar inválido total e permanente, em valor fixo e nominal, reconhecido por Junta Militar de Saúde.", gabarito: "certo", explicacao: "Art. 92, Lei 10.426/90; art. 11 da Lei 17.713/22." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O auxílio-invalidez pode ser suspenso se o militar exercer atividade remunerada após o recebimento ou se for julgado apto em inspeção.", gabarito: "certo", explicacao: "Art. 92, Lei 10.426/90." },

  { modulo: "8", tipo: "multipla", enunciado: "Sobre soldo e proventos, assinale a CORRETA:", alternativas: A("O soldo pode ser reduzido por ato do Comandante-Geral.", "O soldo é irredutível e não sujeito a penhora/sequestro/arresto, salvo casos previstos em lei.", "O valor do soldo difere entre ativa e reserva de mesmo grau.", "A integralidade e a paridade foram revogadas pela LC 460/2021.", "Os proventos jamais são revistos."), gabarito: "B", explicacao: "Art. 54. O valor é igual (Art. 55); integralidade/paridade são princípios do SPSMPE (Art. 74-C, VI e VII)." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre as gratificações, assinale a CORRETA:", alternativas: A("A GLE mantém o valor de 15% do soldo.", "A GOEPM é cumulável com a GEC.", "A GAT-4 pode ser cumulada com a GOEPM.", "A gratificação de motorista teve o percentual sobre o soldo revogado pela LC 32/2001, passando a valor nominal.", "A GSE foi extinta pela LC 59/2004."), gabarito: "D", explicacao: "LC 32/2001 vedou vinculação ao soldo. GLE virou nominal; GOEPM não acumula; GAT-4 não acumula com GOEPM; GSE permanece." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre as indenizações, assinale a CORRETA:", alternativas: A("A ajuda de custo indeniza despesas extraordinárias de alimentação em viagens.", "A diária integra os proventos da inatividade.", "O vale-refeição jamais pode ser suspenso.", "A ajuda de custo é devida ao militar movimentado com mudança de residência.", "O auxílio-uniforme é percentual do soldo."), gabarito: "D", explicacao: "Art. 42, Lei 10.426/90. Diária indeniza alimentação/pousada em afastamento; vale-refeição pode ser suspenso; auxílio-uniforme tem valor único." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre o auxílio-invalidez (Art. 92, Lei 10.426/90), assinale a CORRETA:", alternativas: A("É devido independentemente de reconhecimento por Junta Militar de Saúde.", "Tem valor variável conforme o soldo.", "É devido ao inválido total e permanente, em valor fixo e nominal, reconhecido por Junta.", "Não pode ser suspenso em nenhuma hipótese.", "É devido a qualquer militar afastado, mesmo sem invalidez."), gabarito: "C", explicacao: "Art. 92: inválido total e permanente, valor fixo (R$ 800,00 — art. 11 da Lei 17.713/22), reconhecido por Junta; suspensível se exercer atividade remunerada ou for julgado apto." },
  { modulo: "8", tipo: "multipla", enunciado: "Sobre a estrutura remuneratória (Art. 52 do Estatuto), assinale a INCORRETA:", alternativas: A("Os ativos percebem mensalmente vencimentos (soldo + gratificações) e indenizações.", "Os inativos percebem proventos e adicional de inatividade.", "O auxílio-invalidez pode ser devido eventualmente aos inativos.", "O salário-família é disciplinado pela Lei 9.348/1983.", "As gratificações extintas (GCP, GR, GM, GE) permanecem em pagamento normal."), gabarito: "E", explicacao: "Art. 16 da Lei 10.426/91: GCP, GR, GM e GE foram extintas (LC 59/2004) — por isso a 'e' é a incorreta." },

  { modulo: "8", tipo: "dissertativa", enunciado: "Explique a vedação de vinculação ao soldo (LC 32/2001) e seus reflexos sobre GLE e gratificação de motorista. (mín. 4, máx. 10 linhas)", modelo: { estrutura: "A LC 32/2001 → GLE → Gratificação de motorista → Fundamento.", criterios: ["A LC 32/2001 (art. 1º) vedou expressamente a vinculação de vantagens, parcelas ou acréscimos pecuniários ao soldo.", "GLE: o art. 24 da Lei 10.426/90 (15% do soldo) foi tacitamente revogado; a GLE passou a ter valor NOMINAL.", "Gratificação de motorista: o percentual sobre o soldo também foi revogado, passando a valor nominal (anexo III-D da LC 32/2001).", "Fundamento: impedir reajuste automático de vantagens atreladas ao soldo."], resposta: "A LC 32/2001 (art. 1º) vedou expressamente a vinculação de vantagens, parcelas ou acréscimos pecuniários ao soldo. GLE: o art. 24 da Lei 10.426/90 (15% do soldo) foi tacitamente revogado; a GLE passou a ter valor NOMINAL. Gratificação de motorista: o percentual sobre o soldo também foi revogado, passando a valor nominal (anexo III-D da LC 32/2001). Fundamento: impedir reajuste automático de vantagens atreladas ao soldo." } },
  { modulo: "8", tipo: "dissertativa", enunciado: "Conceitue INTEGRALIDADE e PARIDADE no SPSMPE (Art. 74-C, VI e VII). (mín. 4, máx. 8 linhas)", modelo: { estrutura: "Integralidade (VI) → Paridade (VII) → Base.", criterios: ["Integralidade (VI): direito do inativo de perceber a remuneração do posto/graduação (ou faixa de soldo) que ocupava na ativa ao passar à inatividade, salvo proporcionalidade.", "Paridade (VII): direito de ter a remuneração da inatividade (e as pensões) revista na mesma proporção e data das alterações dos militares ativos.", "Base: Art. 74-C, incs. VI e VII (LC 460/2021)."], resposta: "Integralidade (VI): direito do inativo de perceber a remuneração do posto/graduação (ou faixa de soldo) que ocupava na ativa ao passar à inatividade, salvo proporcionalidade. Paridade (VII): direito de ter a remuneração da inatividade (e as pensões) revista na mesma proporção e data das alterações dos militares ativos. Base: Art. 74-C, incs. VI e VII (LC 460/2021)." } },

  // ════════ MÓDULO 9 — Tema 4 — Promoção ════════
  // Lei 6.783/74, arts. 58-59 e 71-72; LC 470/2021; Lei 11.328/96 (critérios, quadro de acesso, comissões)
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção é ato administrativo cuja finalidade básica é selecionar policiais-militares para funções do grau hierárquico superior.", gabarito: "certo", explicacao: "Art. 58, §2º, Lei 6.783/74." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Os critérios ordinários de promoção são antiguidade e merecimento.", gabarito: "certo", explicacao: "Art. 4º, LC 470/2021." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Os critérios ordinários de promoção são antiguidade e bravura.", gabarito: "errado", explicacao: "Art. 4º: ordinários são antiguidade e merecimento; bravura é extraordinário (Art. 8º)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção requerida é considerada um critério ordinário de promoção.", gabarito: "errado", explicacao: "Art. 8º, V: a requerida é critério EXTRAORDINÁRIO." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção post mortem e a por invalidez permanente são critérios extraordinários de promoção.", gabarito: "certo", explicacao: "Art. 8º, II e III." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção em ressarcimento de preterição pode ocorrer em casos excepcionais.", gabarito: "certo", explicacao: "Art. 8º, par. único." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Para coronel e tenente-coronel, a proporção é de duas promoções por merecimento e uma por antiguidade.", gabarito: "certo", explicacao: "Art. 7º, I, LC 470/2021." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Para o posto de 2º tenente, a promoção se dá apenas por antiguidade, na ordem de classificação intelectual do CFO/CFOA ou equivalente.", gabarito: "certo", explicacao: "Art. 7º, III." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Para major, capitão e 1º tenente, a proporção é de duas por merecimento e uma por antiguidade.", gabarito: "errado", explicacao: "Art. 7º, II: é uma por merecimento e uma por antiguidade." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Não será promovido post mortem o militar se configurado que na ação houve ofensa à honra, ao pundonor, ao dever ou ao decoro militar.", gabarito: "certo", explicacao: "Art. 10, LC 470/2021." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção por invalidez permanente independe de vaga, interstício ou habilitação em cursos, passando o militar automaticamente à situação de excedente.", gabarito: "certo", explicacao: "Art. 11, §§5º e 8º." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Para ingressar no Quadro de Acesso por merecimento, o militar deve estar entre os 40% mais antigos do posto/graduação.", gabarito: "certo", explicacao: "Art. 18, I." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O interstício para promoção ao posto de Capitão, no QOPM/QOS, é de 3 anos.", gabarito: "errado", explicacao: "Art. 18, II: no QOPM/QOS o interstício de Capitão é de 4 anos (3 anos é no QOA)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Será excluído de qualquer Quadro de Acesso o militar que for promovido, tiver falecido ou passar à inatividade.", gabarito: "certo", explicacao: "Art. 71, §3º." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A promoção por merecimento dos oficiais é de competência do Comandante-Geral, mediante portaria.", gabarito: "errado", explicacao: "Art. 43, LC 470/2021: o merecimento de oficiais é de competência do Chefe do Executivo (Governador)." },

  { modulo: "9", tipo: "multipla", enunciado: "Quanto aos critérios de promoção (LC 470/2021), assinale a CORRETA:", alternativas: A("Para coronel e tenente-coronel: uma por merecimento e uma por antiguidade.", "Para 2º tenente: apenas por antiguidade, na ordem de classificação intelectual do CFO ou equivalente.", "Não há previsão de promoção em ressarcimento de preterição.", "A post mortem independe de o militar estar em serviço ou em razão da função.", "A requerida exige interstício e habilitação em cursos."), gabarito: "B", explicacao: "Art. 7º, III. Cel/TenCel: 2 merecimento/1 antiguidade (I); há ressarcimento (Art. 8º, par. único); post mortem exige serviço/função (Art. 10); requerida independe de interstício/curso (Art. 13)." },
  { modulo: "9", tipo: "multipla", enunciado: "Sobre os critérios extraordinários, assinale a CORRETA:", alternativas: A("A bravura é critério ordinário.", "A promoção por invalidez permanente exige vaga, interstício e habilitação em cursos.", "A promoção por invalidez permanente independe de vaga/interstício/curso e leva o militar à situação de excedente.", "A requerida aplica-se a quem já é Coronel na ativa.", "A post mortem exige que o militar esteja de folga no momento do óbito."), gabarito: "C", explicacao: "Art. 11, §§5º e 8º. Bravura é extraordinário (Art. 8º); requerida não se aplica a Coronel (Art. 89-B, §4º); post mortem exige serviço/função (Art. 10)." },
  { modulo: "9", tipo: "multipla", enunciado: "Sobre o Quadro de Acesso (Art. 18), assinale a CORRETA:", alternativas: A("O militar preso em flagrante pode constar normalmente do QAM.", "Deve estar entre os 40% mais antigos do posto/graduação, exclusivamente para merecimento.", "O interstício de Capitão no QOPM é de 3 anos.", "A licença para interesse particular não impede o ingresso.", "Independe de inspeção de saúde."), gabarito: "B", explicacao: "Art. 18, I. Preso não consta (Art. 71, III); Capitão QOPM = 4 anos (Art. 18, II); licença p/ interesse particular impede (Art. 71, IX); exige inspeção de saúde (Art. 18, III)." },
  { modulo: "9", tipo: "multipla", enunciado: "Sobre as competências de promoção (LC 470/2021 e Lei 11.328/96), assinale a CORRETA:", alternativas: A("O merecimento de oficiais é do Comandante-Geral.", "A antiguidade e decenal de oficiais podem ser feitas por portaria do Cmt-Geral, por delegação.", "A promoção de praças é do Governador.", "A Comissão de Promoção de Praças é subordinada ao Comandante-Geral.", "A requerida é sempre do Governador, sem delegação."), gabarito: "B", explicacao: "Art. 44, LC 470/2021. Merecimento de oficiais é do Chefe do Executivo (Art. 43); praças é do Cmt-Geral (Art. 46); Comissão de Praças é subordinada ao Subcmt-Geral (Lei 11.328/96, Art. 12, II)." },
  { modulo: "9", tipo: "multipla", enunciado: "Assinale a INCORRETA sobre impedimentos ao Quadro de Acesso (Art. 71):", alternativas: A("O militar preso temporariamente/preventivamente/em flagrante não pode constar, enquanto a prisão não for revogada.", "O condenado por crime doloso, enquanto durar a pena, não pode constar.", "O militar em licença para tratar de interesse particular não pode constar.", "O militar promovido permanece automaticamente no Quadro de Acesso.", "O desaparecido, extraviado ou desertor não pode constar."), gabarito: "D", explicacao: "Art. 71, §3º, II: o militar promovido é EXCLUÍDO do Quadro de Acesso — logo a 'd' é a incorreta." },

  { modulo: "9", tipo: "dissertativa", enunciado: "Disserte sobre a PROMOÇÃO REQUERIDA (LC 470/2021 e Lei 6.783/74): destinatário, independência de vaga/interstício, situação do militar e momento do desligamento. (mín. 6, máx. 12 linhas)", modelo: { estrutura: "Destinatário → Imediatidade → Independência → Situação → Desligamento → Observações.", criterios: ["Destinatário: militar ingresso até 31/12/2021 com o tempo exigido para a reserva (Arts. 89-B/89-C).", "Imediatidade: independe do calendário de promoções (Art. 13, I; Art. 89-C, I).", "Independência: independe de vaga (criada e extinta na transf. à reserva), sem interstício ou curso (Art. 13, IV).", "Situação: passa automaticamente a EXCEDENTE, adido como se efetivo fosse.", "Desligamento: após 2 meses consecutivos da remuneração do novo posto (Art. 89-C, VI).", "Observações: julgada em 10 dias úteis, retroage ao protocolo (Art. 89-C, III); irrevogável (Art. 89-E); não se aplica a Coronel (Art. 89-B, §4º)."], resposta: "Destinatário: militar ingresso até 31/12/2021 com o tempo exigido para a reserva (Arts. 89-B/89-C). Imediatidade: independe do calendário de promoções (Art. 13, I; Art. 89-C, I). Independência: independe de vaga (criada e extinta na transf. à reserva), sem interstício ou curso (Art. 13, IV). Situação: passa automaticamente a EXCEDENTE, adido como se efetivo fosse. Desligamento: após 2 meses consecutivos da remuneração do novo posto (Art. 89-C, VI). Observações: julgada em 10 dias úteis, retroage ao protocolo (Art. 89-C, III); irrevogável (Art. 89-E); não se aplica a Coronel (Art. 89-B, §4º)." } },
  { modulo: "9", tipo: "dissertativa", enunciado: "Explique os requisitos do QUADRO DE ACESSO (Art. 18, LC 470/2021). (mín. 5, máx. 10 linhas)", modelo: { estrutura: "I → II → III → IV → V.", criterios: ["I: estar entre os 40% mais antigos do posto/graduação, exclusivamente para merecimento.", "II: possuir o interstício exigido (ex.: Cap QOPM/QOS = 4 anos; Cap QOA = 3 anos).", "III: ser considerado apto em inspeção de saúde.", "IV: requisitos peculiares (cursos e serviço arregimentado).", "V: obter conceito profissional e moral."], resposta: "I: estar entre os 40% mais antigos do posto/graduação, exclusivamente para merecimento. II: possuir o interstício exigido (ex.: Cap QOPM/QOS = 4 anos; Cap QOA = 3 anos). III: ser considerado apto em inspeção de saúde. IV: requisitos peculiares (cursos e serviço arregimentado). V: obter conceito profissional e moral." } },

  // ════════ MÓDULO 10 — Tema 5 — Afastamentos ════════
  // Lei 6.783/74, arts. 61-67; Lei 10.426/90; LC 091/2007; Port. Normativa CG 175/2014 (férias, licenças, maternidade/paternidade)
  { modulo: "10", tipo: "certo_errado", enunciado: "As férias são afastamentos totais do serviço, concedidos anual e obrigatoriamente aos policiais-militares para descanso.", gabarito: "certo", explicacao: "Art. 61, caput." },
  { modulo: "10", tipo: "certo_errado", enunciado: "Compete ao Comandante-Geral da Polícia Militar a regulamentação da concessão das férias anuais.", gabarito: "certo", explicacao: "Art. 61, §1º." },
  { modulo: "10", tipo: "certo_errado", enunciado: "O gozo anterior de licença para tratamento de saúde impede a concessão de férias no período seguinte.", gabarito: "errado", explicacao: "Art. 61, §2º: a concessão de férias NÃO é prejudicada por licença de saúde anterior." },
  { modulo: "10", tipo: "certo_errado", enunciado: "As férias só podem ser interrompidas em casos de Segurança Nacional, manutenção da ordem, extrema necessidade do serviço ou transferência para a inatividade.", gabarito: "certo", explicacao: "Art. 61, §3º." },
  { modulo: "10", tipo: "certo_errado", enunciado: "O período de férias não gozado é computado dia a dia, pelo dobro, na passagem para a inatividade e somente para esse fim.", gabarito: "certo", explicacao: "Art. 61, §4º." },
  { modulo: "10", tipo: "certo_errado", enunciado: "O afastamento por núpcias é de 8 dias, assim como o afastamento por luto.", gabarito: "certo", explicacao: "Art. 62, I e II." },
  { modulo: "10", tipo: "certo_errado", enunciado: "O afastamento por motivo de instalação é de até 30 dias.", gabarito: "errado", explicacao: "Art. 62, III: instalação é até 10 dias; 30 dias é o trânsito (IV)." },
  { modulo: "10", tipo: "certo_errado", enunciado: "As férias e os demais afastamentos do art. 62 não são computados, em nenhuma hipótese, como tempo de efetivo serviço.", gabarito: "errado", explicacao: "Art. 63: são computados como tempo de efetivo serviço para todos os efeitos legais." },
  { modulo: "10", tipo: "certo_errado", enunciado: "Licença é a autorização para o afastamento total do serviço, em caráter temporário, concedida ao policial-militar.", gabarito: "certo", explicacao: "Art. 64, caput." },
  { modulo: "10", tipo: "certo_errado", enunciado: "São modalidades de licença: especial; para tratar de interesse particular; para tratamento de saúde de pessoa da família; e para tratamento de saúde própria.", gabarito: "certo", explicacao: "Art. 64, §1º." },
  { modulo: "10", tipo: "certo_errado", enunciado: "A licença especial tem duração de 6 meses e o período interrompe a contagem do tempo de efetivo serviço.", gabarito: "errado", explicacao: "Art. 65, §2º: o período de licença especial NÃO interrompe a contagem do tempo de efetivo serviço." },
  { modulo: "10", tipo: "certo_errado", enunciado: "A licença para tratar de interesse particular é concedida ao militar com mais de 10 anos de efetivo serviço, com prejuízo da remuneração e da contagem de tempo.", gabarito: "certo", explicacao: "Art. 66, caput e §1º." },
  { modulo: "10", tipo: "certo_errado", enunciado: "A servidora gestante tem direito à licença-maternidade de 180 dias, com vencimento integral.", gabarito: "certo", explicacao: "Art. 126, LC 091/2007." },
  { modulo: "10", tipo: "certo_errado", enunciado: "Pela adoção de criança de até 1 ano, a servidora tem direito a apenas 90 dias de licença-maternidade.", gabarito: "errado", explicacao: "Art. 126-A, I: até 1 ano são 180 dias (90 dias é de 1 a 4 anos)." },
  { modulo: "10", tipo: "certo_errado", enunciado: "O servidor tem direito à licença-paternidade de 20 dias consecutivos, ampliável até 180 dias em caso de falecimento da genitora.", gabarito: "certo", explicacao: "Art. 2º e §1º, LC 471/2021." },

  { modulo: "10", tipo: "multipla", enunciado: "Sobre as férias (Art. 61), assinale a CORRETA:", alternativas: A("A regulamentação compete ao Secretário de Defesa Social.", "O gozo anterior de licença de saúde impede as férias seguintes.", "O período não gozado, na impossibilidade, é computado em dobro na passagem à inatividade, só para esse fim.", "As férias podem ser interrompidas por conveniência pessoal do militar.", "As férias não são obrigatórias."), gabarito: "C", explicacao: "Art. 61, §4º. Regulamentação é do Cmt-Geral (§1º); licença de saúde não impede (§2º); interrupção só nas hipóteses do §3º." },
  { modulo: "10", tipo: "multipla", enunciado: "Sobre os afastamentos do art. 62, assinale a CORRETA:", alternativas: A("Núpcias: 10 dias.", "Luto: 15 dias.", "Instalação: até 10 dias; trânsito: até 30 dias.", "Trânsito: até 10 dias.", "Instalação: até 30 dias."), gabarito: "C", explicacao: "Art. 62, III e IV: instalação até 10 dias; trânsito até 30 dias (núpcias e luto: 8 dias cada)." },
  { modulo: "10", tipo: "multipla", enunciado: "Sobre a licença especial (Art. 65), assinale a CORRETA:", alternativas: A("Duração de 3 meses.", "Tem duração de 6 meses e não interrompe a contagem do tempo de efetivo serviço.", "Não pode ser parcelada.", "Implica restrição à carreira.", "Interrompe a contagem do tempo de efetivo serviço."), gabarito: "B", explicacao: "Art. 65, caput e §2º. Pode ser parcelada em 2/3 meses por ano civil; sem restrição à carreira." },
  { modulo: "10", tipo: "multipla", enunciado: "Sobre a licença-maternidade/paternidade (LC 091/2007), assinale a CORRETA:", alternativas: A("Gestante: 120 dias.", "Adoção de até 1 ano: 90 dias.", "Gestante: 180 dias, com vencimento integral.", "Paternidade: 5 dias.", "Adoção de 4 a 8 anos: 180 dias."), gabarito: "C", explicacao: "Art. 126. Adoção até 1 ano = 180 dias (Art. 126-A, I); paternidade = 20 dias; 4 a 8 anos = 60 dias." },
  { modulo: "10", tipo: "multipla", enunciado: "Assinale a INCORRETA sobre licenças (Arts. 64-67):", alternativas: A("Licença é afastamento total temporário do serviço.", "A licença para interesse particular exige mais de 10 anos de efetivo serviço.", "A licença especial relaciona-se a cada decênio de efetivo serviço.", "A licença especial pode ser interrompida para cumprimento de punição disciplinar.", "A licença para interesse particular é concedida sem prejuízo da remuneração."), gabarito: "E", explicacao: "Art. 66, §1º: a licença para interesse particular é sempre COM prejuízo da remuneração e da contagem de tempo — a 'e' é a incorreta." },

  { modulo: "10", tipo: "dissertativa", enunciado: "Disserte sobre a LICENÇA ESPECIAL (Art. 65): decênio, duração, parcelamento, efeito na contagem de tempo e cômputo em dobro. (mín. 5, máx. 12 linhas)", modelo: { estrutura: "Natureza → Duração → Contagem → Dobro → Efeito.", criterios: ["Natureza: autorização de afastamento total relativa a cada decênio de efetivo serviço, a requerimento, sem restrição à carreira (caput).", "Duração: 6 meses, de uma só vez, podendo ser parcelada em 2 ou 3 meses por ano civil (§1º).", "Contagem: o período de licença especial não interrompe a contagem do tempo de efetivo serviço (§2º).", "Dobro: os períodos não gozados são computados em dobro só para a inatividade (exceto a última, salvo aquiescência) (§3º).", "Efeito: concedida a licença, o militar é exonerado do cargo e fica à disposição do órgão de pessoal (§5º)."], resposta: "Natureza: autorização de afastamento total relativa a cada decênio de efetivo serviço, a requerimento, sem restrição à carreira (caput). Duração: 6 meses, de uma só vez, podendo ser parcelada em 2 ou 3 meses por ano civil (§1º). Contagem: o período de licença especial não interrompe a contagem do tempo de efetivo serviço (§2º). Dobro: os períodos não gozados são computados em dobro só para a inatividade (exceto a última, salvo aquiescência) (§3º). Efeito: concedida a licença, o militar é exonerado do cargo e fica à disposição do órgão de pessoal (§5º)." } },
  { modulo: "10", tipo: "dissertativa", enunciado: "Explique a licença-maternidade por ADOÇÃO (Art. 126-A) e a licença-paternidade (Art. 2º, LC 091/2007). (mín. 5, máx. 10 linhas)", modelo: { estrutura: "Adoção/guarda até 1 ano → Adoção/guarda de 1 a 4 anos → Adoção/guarda de 4 a 8 anos → Paternidade → Ampliação → Aplicável aos militares.", criterios: ["Adoção/guarda até 1 ano: 180 dias (Art. 126-A, I).", "Adoção/guarda de 1 a 4 anos: 90 dias (II).", "Adoção/guarda de 4 a 8 anos: 60 dias (III).", "Paternidade: 20 dias consecutivos (Art. 2º, com redação da LC 471/2021).", "Ampliação: até 180 dias em caso de falecimento da genitora, exceto no falecimento do filho (§1º).", "Aplicável aos militares do Estado (Art. 4º)."], resposta: "Adoção/guarda até 1 ano: 180 dias (Art. 126-A, I). Adoção/guarda de 1 a 4 anos: 90 dias (II). Adoção/guarda de 4 a 8 anos: 60 dias (III). Paternidade: 20 dias consecutivos (Art. 2º, com redação da LC 471/2021). Ampliação: até 180 dias em caso de falecimento da genitora, exceto no falecimento do filho (§1º). Aplicável aos militares do Estado (Art. 4º)." } },

  // ════════ MÓDULO 11 — Tema 6 — Aquisição e porte de armas de fogo ════════
  // Lei 6.783/74, Art. 49; INCG nº 612, de 22MAI2024 (propriedade, CRAF, porte, carga pessoal)
  { modulo: "11", tipo: "certo_errado", enunciado: "O porte de arma é direito originário do oficial, em serviço ativo ou inatividade, salvo inatividade por alienação mental ou condenação por crimes contra a segurança nacional.", gabarito: "certo", explicacao: "Art. 49, IV, 'l', Lei 6.783/74." },
  { modulo: "11", tipo: "certo_errado", enunciado: "O CRAF comprova a propriedade da arma de fogo, mas não confere, por si só, o direito ao porte.", gabarito: "certo", explicacao: "Art. 12, §2º, INCG 612/2024." },
  { modulo: "11", tipo: "certo_errado", enunciado: "O CRAF emitido pela PMPE confere ao proprietário o direito ao porte da arma nele registrada.", gabarito: "errado", explicacao: "Art. 12, §2º: o CRAF NÃO confere o direito ao porte." },
  { modulo: "11", tipo: "certo_errado", enunciado: "As armas adquiridas por policiais militares devem ser registradas no Comando do Exército e cadastradas no SIGMA.", gabarito: "certo", explicacao: "Art. 6º, INCG 612/2024." },
  { modulo: "11", tipo: "certo_errado", enunciado: "O policial militar poderá adquirir arma de fogo ainda que não possua permissão para o porte.", gabarito: "errado", explicacao: "Art. 5º: é vedada a aquisição a quem não tem permissão de porte." },
  { modulo: "11", tipo: "certo_errado", enunciado: "O CRAF do policial militar é válido por prazo indeterminado.", gabarito: "certo", explicacao: "Art. 13, INCG 612/2024." },
  { modulo: "11", tipo: "certo_errado", enunciado: "Em caso de roubo, furto ou extravio, o militar deve registrar BO imediatamente e comunicar à autoridade em até 3 dias.", gabarito: "certo", explicacao: "Art. 15, I e II." },
  { modulo: "11", tipo: "certo_errado", enunciado: "Em caso de inutilização da arma, o militar deve comunicar o fato à autoridade competente no prazo máximo de 15 dias.", gabarito: "errado", explicacao: "Art. 17: o prazo é de até 3 dias, com registro fotográfico e parecer técnico." },
  { modulo: "11", tipo: "certo_errado", enunciado: "No falecimento, interdição ou inatividade por saúde mental, as providências (transferência ou entrega à PF) devem ocorrer em até 90 dias.", gabarito: "certo", explicacao: "Art. 18, §2º." },
  { modulo: "11", tipo: "certo_errado", enunciado: "Perderá o direito ao porte o policial militar sob recomendação médica ou psicológica para não portar arma de fogo.", gabarito: "certo", explicacao: "Art. 21, II." },
  { modulo: "11", tipo: "certo_errado", enunciado: "O procedimento de cassação do CRAF só pode ser instaurado mediante denúncia de terceiros, jamais de ofício.", gabarito: "errado", explicacao: "Art. 14: instaurado de ofício pela autoridade competente ou mediante denúncia." },
  { modulo: "11", tipo: "certo_errado", enunciado: "A carga pessoal provisória autoriza a entrega de arma para determinado serviço, devendo ser devolvida ao término.", gabarito: "certo", explicacao: "Art. 27, INCG 612/2024." },
  { modulo: "11", tipo: "certo_errado", enunciado: "A carga pessoal por acautelamento autoriza a entrega de arma da OME pelo período de um ano.", gabarito: "certo", explicacao: "Art. 28, caput." },
  { modulo: "11", tipo: "certo_errado", enunciado: "É permitida a entrega de arma da instituição desacompanhada de munições.", gabarito: "errado", explicacao: "Art. 26, §1º: é vedada a entrega de arma desacompanhada de munições, e vice-versa." },
  { modulo: "11", tipo: "certo_errado", enunciado: "Não será concedido acautelamento ao militar regularmente matriculado em curso de formação.", gabarito: "certo", explicacao: "Art. 29, III." },

  { modulo: "11", tipo: "multipla", enunciado: "Sobre o CRAF (INCG 612/2024), assinale a CORRETA:", alternativas: A("Confere o direito ao porte da arma registrada.", "Tem validade de 5 anos.", "Comprova a propriedade da arma, mas não confere, por si só, o direito ao porte.", "É assinado pelo Comandante-Geral.", "Só é emitido para oficiais."), gabarito: "C", explicacao: "Art. 12, §2º. Validade indeterminada (Art. 13); assinado pelo Chefe do CSM/MB (§1º)." },
  { modulo: "11", tipo: "multipla", enunciado: "Sobre aquisição e registro (INCG 612/2024), assinale a CORRETA:", alternativas: A("Pode adquirir arma quem não tem permissão de porte.", "As armas são registradas no Exército e cadastradas no SIGMA.", "A aquisição dispensa autorização individual.", "A quantidade de munição é definida pelo Comandante-Geral da PMPE.", "A aquisição só pode ocorrer no comércio."), gabarito: "B", explicacao: "Art. 6º. Vedada aquisição sem porte (Art. 5º); exige autorização individual (Art. 7º); quantidade por Portaria do Comando Logístico do Exército (Art. 4º); aquisição por comércio, convênio ou transferência (Art. 7º)." },
  { modulo: "11", tipo: "multipla", enunciado: "Sobre os prazos da INCG 612/2024, assinale a CORRETA:", alternativas: A("Roubo/furto/extravio: comunicar em até 10 dias.", "Inutilização: comunicar em até 30 dias.", "Roubo/furto/extravio: comunicar em até 3 dias.", "Falecimento/interdição: providências em até 15 dias.", "Acautelamento: prazo de 6 meses."), gabarito: "C", explicacao: "Art. 15, II. Inutilização: 3 dias (Art. 17); falecimento/interdição: 90 dias (Art. 18); acautelamento: 1 ano (Art. 28)." },
  { modulo: "11", tipo: "multipla", enunciado: "Sobre a perda do direito ao porte (Art. 21), assinale a CORRETA:", alternativas: A("A recomendação médica/psicológica para não portar não afeta o porte.", "Perde o porte quem responde por crime cuja natureza desaconselhe ou em que a arma seja meio.", "O afastamento por distúrbio de saúde mental não afeta o porte.", "A embriaguez portando arma não afeta o porte.", "O porte, uma vez perdido, jamais é readmitido."), gabarito: "B", explicacao: "Art. 21, I. Recomendação médica (II), saúde mental (III) e embriaguez (IV) também retiram o porte; readmite-se cessadas as razões (§1º)." },
  { modulo: "11", tipo: "multipla", enunciado: "Sobre a carga pessoal (Arts. 26-30), assinale a INCORRETA:", alternativas: A("A carga provisória autoriza a entrega de arma para determinado serviço.", "A carga por acautelamento tem prazo de um ano.", "É permitida a entrega de arma desacompanhada de munições.", "Não se concede acautelamento a quem está matriculado em curso de formação.", "Vedada a entrega de armas por intermédio de terceiros."), gabarito: "C", explicacao: "Art. 26, §1º: é VEDADA a entrega de arma desacompanhada de munições — logo a 'c' é a incorreta." },

  { modulo: "11", tipo: "dissertativa", enunciado: "Disserte sobre o CRAF (INCG 612/2024): conceito, competência de assinatura, relação com o porte e validade. (mín. 5, máx. 10 linhas)", modelo: { estrutura: "Conceito → Assinatura → Porte → Validade → Registro.", criterios: ["Conceito: documento que atesta a PROPRIEDADE de arma de fogo ao policial militar (Art. 12).", "Assinatura: pelo Chefe do CSM/MB (§1º).", "Porte: o CRAF NÃO confere o direito ao porte (§2º) — propriedade e porte são institutos distintos.", "Validade: prazo indeterminado (Art. 13); em roubo/extravio/deterioração, nova emissão com BO/solução (par. único).", "Registro: armas cadastradas no Exército e no SIGMA (Art. 6º)."], resposta: "Conceito: documento que atesta a PROPRIEDADE de arma de fogo ao policial militar (Art. 12). Assinatura: pelo Chefe do CSM/MB (§1º). Porte: o CRAF NÃO confere o direito ao porte (§2º) — propriedade e porte são institutos distintos. Validade: prazo indeterminado (Art. 13); em roubo/extravio/deterioração, nova emissão com BO/solução (par. único). Registro: armas cadastradas no Exército e no SIGMA (Art. 6º)." } },
  { modulo: "11", tipo: "dissertativa", enunciado: "Diferencie CARGA PESSOAL PROVISÓRIA e POR ACAUTELAMENTO (Arts. 27-29). (mín. 5, máx. 10 linhas)", modelo: { estrutura: "Provisória (Art. 27) → Acautelamento (Art. 28) → Vedações → Restrições ao acautelamento (Art. 29).", criterios: ["Provisória (Art. 27): entrega de arma/munição/PCE para cumprimento de determinado serviço, devolvida ao término; exige escala/ofício + identidade militar.", "Acautelamento (Art. 28): entrega de arma/munição/colete da OME pelo período de 1 ano, deferida pelo comandante, com identidade (c/ porte) e certidões negativas (TJPE, JF, CG/SDS).", "Vedações: entrega de arma sem munição e vice-versa; entrega por terceiros (Art. 26, §§).", "Restrições ao acautelamento (Art. 29): porte suspenso; comportamento 'Mau'/'Insuficiente'; matrícula em curso de formação; apuração de roubo/furto/extravio; entre outras."], resposta: "Provisória (Art. 27): entrega de arma/munição/PCE para cumprimento de determinado serviço, devolvida ao término; exige escala/ofício + identidade militar. Acautelamento (Art. 28): entrega de arma/munição/colete da OME pelo período de 1 ano, deferida pelo comandante, com identidade (c/ porte) e certidões negativas (TJPE, JF, CG/SDS). Vedações: entrega de arma sem munição e vice-versa; entrega por terceiros (Art. 26, §§). Restrições ao acautelamento (Art. 29): porte suspenso; comportamento 'Mau'/'Insuficiente'; matrícula em curso de formação; apuração de roubo/furto/extravio; entre outras." } },

  // ════════ MÓDULO 12 — Simulado da turma (2ª Avaliação) ════════
  // Blocos V/F desmembrados em assertivas individuais + múltiplas escolhas A–E.
  { modulo: "12", tipo: "certo_errado", enunciado: "Para os postos de Coronel e Tenente-Coronel, a proporcionalidade de promoção é de duas vagas por merecimento para uma por antiguidade.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 01 — Critérios ordinários de promoção e quadro de acesso.", fonte: "Simulado 2ª Avaliação — 01 — Critérios ordinários de promoção e quadro de acesso" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção ao posto de 2º Tenente ocorre exclusivamente pelo critério de antiguidade, na ordem de classificação intelectual do CFO, CFOA ou equivalente.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 01 — Critérios ordinários de promoção e quadro de acesso.", fonte: "Simulado 2ª Avaliação — 01 — Critérios ordinários de promoção e quadro de acesso" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Para ingressar no Quadro de Acesso por merecimento, o militar deve estar entre os 40% mais antigos do posto ou graduação.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 01 — Critérios ordinários de promoção e quadro de acesso.", fonte: "Simulado 2ª Avaliação — 01 — Critérios ordinários de promoção e quadro de acesso" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O interstício exigido para promoção ao posto de Capitão, tanto no QOPM/QOS quanto no QOA, é uniformemente de 4 anos.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 01 — Critérios ordinários de promoção e quadro de acesso.", fonte: "Simulado 2ª Avaliação — 01 — Critérios ordinários de promoção e quadro de acesso" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Quando nunca tiver ocorrido promoção em determinado posto/graduação, a primeira promoção deverá ser realizada, obrigatoriamente, pelo critério de antiguidade.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 01 — Critérios ordinários de promoção e quadro de acesso.", fonte: "Simulado 2ª Avaliação — 01 — Critérios ordinários de promoção e quadro de acesso" },
  { modulo: "12", tipo: "multipla", enunciado: "Sobre a agregação (Lei 6.783/74), é correto afirmar que:", alternativas: A("abre vaga para efeito de promoção, desde que o agregado conte mais de 10 anos de serviço.", "é contada, na nomeação para cargo não previsto nos quadros, a partir da publicação do ato até o regresso.", "se faz por ato do Governador do Estado de Pernambuco ou de autoridade a qual tenham sido delegados poderes.", "é concedida exclusivamente aos oficiais, não se aplicando às praças.", "impede, em qualquer hipótese, que o militar seja considerado em serviço ativo."), gabarito: "C", explicacao: "Gabarito oficial do simulado da turma (questão 2).", fonte: "Simulado 2ª Avaliação — questão 02" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Quando agregado, o PM passa a figurar sem número na escala e, em regra, essa situação não gera abertura de vaga, nem para promoção.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 03 — Agregação.", fonte: "Simulado 2ª Avaliação — 03 — Agregação" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Agregado por nomeação para cargo de natureza PM não previsto nos quadros, continua considerado, para todos os efeitos, em serviço ativo.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 03 — Agregação.", fonte: "Simulado 2ª Avaliação — 03 — Agregação" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Cabe unicamente ao Comandante-Geral decidir sobre a agregação, sem que outra autoridade possa exercê-la.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 03 — Agregação.", fonte: "Simulado 2ª Avaliação — 03 — Agregação" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Mesmo agregado, o militar continua sujeito às obrigações disciplinares, exceto quando ocupar cargo com precedência funcional sobre mais graduados/antigos.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 03 — Agregação.", fonte: "Simulado 2ª Avaliação — 03 — Agregação" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Um militar agregado pode disputar promoção tanto por antiguidade quanto por merecimento, como no exercício normal das funções.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 03 — Agregação.", fonte: "Simulado 2ª Avaliação — 03 — Agregação" },
  { modulo: "12", tipo: "multipla", enunciado: "Quanto à situação de excedente, é correto afirmar que:", alternativas: A("o excedente perde a antiguidade que possuía na escala hierárquica.", "o excedente não pode concorrer a promoções enquanto permanecer nessa situação.", "o promovido por bravura, sem haver vaga, ocupará a primeira vaga aberta, deslocando o princípio de promoção para a vaga seguinte.", "a situação de excedente é permanente, não cessando com a abertura de vaga.", "o excedente recebe a abreviatura 'Ag' em seus assentamentos."), gabarito: "C", explicacao: "Gabarito oficial do simulado da turma (questão 4).", fonte: "Simulado 2ª Avaliação — questão 04" },
  { modulo: "12", tipo: "certo_errado", enunciado: "As férias são afastamentos totais do serviço, concedidos anual e obrigatoriamente aos policiais-militares.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 05 — Férias (Art. 61).", fonte: "Simulado 2ª Avaliação — 05 — Férias (Art. 61)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Compete ao Comandante-Geral da Polícia Militar regulamentar a concessão das férias anuais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 05 — Férias (Art. 61).", fonte: "Simulado 2ª Avaliação — 05 — Férias (Art. 61)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O gozo anterior de licença para tratamento de saúde impede a concessão de férias no período seguinte.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 05 — Férias (Art. 61).", fonte: "Simulado 2ª Avaliação — 05 — Férias (Art. 61)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Somente em casos de Segurança Nacional, ordem, extrema necessidade ou transferência para a inatividade as férias podem ser interrompidas ou não gozadas na época prevista.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 05 — Férias (Art. 61).", fonte: "Simulado 2ª Avaliação — 05 — Férias (Art. 61)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Na impossibilidade absoluta de gozo no ano seguinte, o período não gozado será computado em dobro somente na passagem para a inatividade.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 05 — Férias (Art. 61).", fonte: "Simulado 2ª Avaliação — 05 — Férias (Art. 61)" },
  { modulo: "12", tipo: "multipla", enunciado: "Nos termos do art. 85 da Lei 6.783/74, é INCORRETO afirmar que constitui hipótese de desligamento/exclusão do serviço ativo:", alternativas: A("a transferência para a reserva remunerada.", "a reforma.", "a agregação.", "a demissão.", "o falecimento."), gabarito: "C", explicacao: "Gabarito oficial do simulado da turma (questão 6).", fonte: "Simulado 2ª Avaliação — questão 06" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O CRAF comprova a propriedade da arma, mas não confere, por si só, o direito ao porte.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 07 — Aquisição e porte de armas (INCG 612/2024).", fonte: "Simulado 2ª Avaliação — 07 — Aquisição e porte de armas (INCG 612/2024)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "As armas adquiridas por policiais militares devem ser registradas no Comando do Exército e cadastradas no SIGMA.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 07 — Aquisição e porte de armas (INCG 612/2024).", fonte: "Simulado 2ª Avaliação — 07 — Aquisição e porte de armas (INCG 612/2024)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O policial militar poderá adquirir arma de fogo, ainda que não possua permissão para o porte.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 07 — Aquisição e porte de armas (INCG 612/2024).", fonte: "Simulado 2ª Avaliação — 07 — Aquisição e porte de armas (INCG 612/2024)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Em caso de roubo, furto ou extravio, o militar deve comunicar o fato à autoridade competente no prazo máximo de três dias.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 07 — Aquisição e porte de armas (INCG 612/2024).", fonte: "Simulado 2ª Avaliação — 07 — Aquisição e porte de armas (INCG 612/2024)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O CRAF do policial militar possui validade por prazo indeterminado.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 07 — Aquisição e porte de armas (INCG 612/2024).", fonte: "Simulado 2ª Avaliação — 07 — Aquisição e porte de armas (INCG 612/2024)" },
  { modulo: "12", tipo: "multipla", enunciado: "Sobre as indenizações da legislação remuneratória, assinale a alternativa correta:", alternativas: A("A ajuda de custo destina-se ao pagamento de despesas extraordinárias de alimentação durante viagens de serviço.", "A diária possui natureza remuneratória e integra os proventos da inatividade.", "O vale-refeição jamais poderá ser suspenso, por constituir direito adquirido.", "A ajuda de custo é devida ao militar movimentado para cargo ou serviço que importe mudança de residência.", "O auxílio-uniforme é calculado em percentual sobre o soldo."), gabarito: "D", explicacao: "Gabarito oficial do simulado da turma (questão 8).", fonte: "Simulado 2ª Avaliação — questão 08" },
  { modulo: "12", tipo: "multipla", enunciado: "Sobre a transferência compulsória por tempo no posto, para o militar ingresso a partir de 1º/01/2022, sendo Coronel, a transferência ex officio ocorrerá quando:", alternativas: A("ultrapassar 2 anos de permanência no posto, contando 30 anos de efetivo serviço.", "ultrapassar 3 anos de permanência no posto, desde que conte ou venha a contar 35 anos de serviço, dos quais 30 de efetivo serviço militar.", "ultrapassar 5 anos de permanência no posto, independentemente do tempo de serviço.", "cumprir a regra de 'pedágio' do art. 89-A, independentemente do tempo de permanência.", "não há regra de transferência compulsória prevista para o posto de Coronel."), gabarito: "B", explicacao: "Gabarito oficial do simulado da turma (questão 9).", fonte: "Simulado 2ª Avaliação — questão 09" },
  { modulo: "12", tipo: "certo_errado", enunciado: "As férias são afastamentos totais do serviço, concedidos anual e obrigatoriamente para descanso.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 10 — Férias e afastamentos temporários.", fonte: "Simulado 2ª Avaliação — 10 — Férias e afastamentos temporários" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Compete ao Secretário de Defesa Social, e não ao Comandante-Geral, regulamentar a concessão das férias anuais.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 10 — Férias e afastamentos temporários.", fonte: "Simulado 2ª Avaliação — 10 — Férias e afastamentos temporários" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O afastamento por núpcias é de 8 dias, assim como o afastamento por luto.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 10 — Férias e afastamentos temporários.", fonte: "Simulado 2ª Avaliação — 10 — Férias e afastamentos temporários" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O afastamento por motivo de trânsito pode chegar a até 30 dias.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 10 — Férias e afastamentos temporários.", fonte: "Simulado 2ª Avaliação — 10 — Férias e afastamentos temporários" },
  { modulo: "12", tipo: "certo_errado", enunciado: "As férias e os demais afastamentos do art. 62 não são computados, em nenhuma hipótese, como tempo de efetivo serviço.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 10 — Férias e afastamentos temporários.", fonte: "Simulado 2ª Avaliação — 10 — Férias e afastamentos temporários" },
  { modulo: "12", tipo: "multipla", enunciado: "Assinale a alternativa INCORRETA a respeito da reforma do militar do Estado:", alternativas: A("a reforma ocorre sempre de ofício.", "a reforma ocorre quando o militar atingir a idade limite de 70 anos.", "a reforma ocorre quando julgado incapaz definitivamente, desde que não seja possível a readaptação.", "a reforma ocorre quando agregado por mais de 2 anos por incapacidade temporária, mediante homologação da Junta.", "a reforma pode ser requerida a pedido do próprio militar, a qualquer tempo, independentemente das hipóteses legais."), gabarito: "E", explicacao: "Gabarito oficial do simulado da turma (questão 11).", fonte: "Simulado 2ª Avaliação — questão 11" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar inválido, impossibilitado total e permanentemente para qualquer trabalho, faz jus a auxílio-invalidez em valor fixo e nominal.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 12 — Auxílio-invalidez.", fonte: "Simulado 2ª Avaliação — 12 — Auxílio-invalidez" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O auxílio-invalidez independe de reconhecimento por Junta Militar de Saúde.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 12 — Auxílio-invalidez.", fonte: "Simulado 2ª Avaliação — 12 — Auxílio-invalidez" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O auxílio-invalidez pode ser suspenso automaticamente se verificado que o militar exerce ou exerceu, após o recebimento, qualquer atividade remunerada.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 12 — Auxílio-invalidez.", fonte: "Simulado 2ª Avaliação — 12 — Auxílio-invalidez" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O auxílio-invalidez é devido independentemente de o militar necessitar de internação ou de assistência de enfermagem permanente.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 12 — Auxílio-invalidez.", fonte: "Simulado 2ª Avaliação — 12 — Auxílio-invalidez" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O auxílio-invalidez também pode ser suspenso se o militar for julgado apto em inspeção de saúde.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 12 — Auxílio-invalidez.", fonte: "Simulado 2ª Avaliação — 12 — Auxílio-invalidez" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Licença é a autorização para o afastamento total do serviço, em caráter temporário, concedida ao policial-militar.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 13 — Licenças e licença especial (Arts. 64-65).", fonte: "Simulado 2ª Avaliação — 13 — Licenças e licença especial (Arts. 64-65)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "São modalidades: especial, para interesse particular, para saúde de pessoa da família e para saúde própria.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 13 — Licenças e licença especial (Arts. 64-65).", fonte: "Simulado 2ª Avaliação — 13 — Licenças e licença especial (Arts. 64-65)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A Licença Especial tem duração de 6 meses, podendo ser parcelada em 2 ou 3 meses por ano civil, quando conveniente.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 13 — Licenças e licença especial (Arts. 64-65).", fonte: "Simulado 2ª Avaliação — 13 — Licenças e licença especial (Arts. 64-65)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O período de licença especial interrompe a contagem do tempo de efetivo serviço.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 13 — Licenças e licença especial (Arts. 64-65).", fonte: "Simulado 2ª Avaliação — 13 — Licenças e licença especial (Arts. 64-65)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A licença especial pode ser interrompida para cumprimento de punição disciplinar, conforme regulado pela autoridade competente.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 13 — Licenças e licença especial (Arts. 64-65).", fonte: "Simulado 2ª Avaliação — 13 — Licenças e licença especial (Arts. 64-65)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Um militar da ativa que, no desempenho de qualquer serviço, tenha paradeiro desconhecido por mais de 8 dias, é considerado desaparecido.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 14 — Desaparecimento, extravio e desligamento.", fonte: "Simulado 2ª Avaliação — 14 — Desaparecimento, extravio e desligamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Basta que o militar permaneça desaparecido por mais de 15 dias para ser oficialmente declarado extraviado.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 14 — Desaparecimento, extravio e desligamento.", fonte: "Simulado 2ª Avaliação — 14 — Desaparecimento, extravio e desligamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "São motivos de desligamento/exclusão, entre outros: reserva remunerada, reforma, demissão, perda de posto e patente, licenciamento, exclusão a bem da disciplina, deserção, falecimento e extravio.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 14 — Desaparecimento, extravio e desligamento.", fonte: "Simulado 2ª Avaliação — 14 — Desaparecimento, extravio e desligamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Uma vez transferido para a reserva ou reformado, o militar fica automaticamente isento de indenizar prejuízos causados à Fazenda estadual.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 14 — Desaparecimento, extravio e desligamento.", fonte: "Simulado 2ª Avaliação — 14 — Desaparecimento, extravio e desligamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O prazo para o desligamento efetivo da OPM não pode ultrapassar 45 dias, contados da primeira publicação oficial do ato.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 14 — Desaparecimento, extravio e desligamento.", fonte: "Simulado 2ª Avaliação — 14 — Desaparecimento, extravio e desligamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A transferência para a reserva remunerada pode ocorrer a pedido ou ex officio.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 15 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 15 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Para os oficiais, a transferência ex officio por idade ocorre ao atingir 63 anos.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 15 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 15 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A reforma do policial militar pode ocorrer a pedido, desde que preenchidos os requisitos legais.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 15 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 15 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar reformado por incapacidade definitiva que for considerado apto em inspeção de saúde poderá retornar ao serviço ativo, conforme previsão legal.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 15 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 15 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O policial militar desaparecido por mais de 30 dias passa a ser oficialmente considerado extraviado.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 15 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 15 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "multipla", enunciado: "Sobre as gratificações previstas para os militares do Estado de Pernambuco, é correto afirmar que:", alternativas: A("a GLE mantém, atualmente, o valor percentual de 15% do soldo do posto ou graduação.", "a Gratificação de Perigo Laboral é concedida aos militares em razão do risco da profissão.", "a GOEPM é cumulável com a Gratificação por Encargo de Comando (GEC).", "a gratificação de motorista teve seu valor percentual sobre o soldo tacitamente revogado pela LC 32/2001, passando a valor nominal.", "a GAT-4 pode ser cumulada com a GOEPM."), gabarito: "D", explicacao: "Gabarito oficial do simulado da turma (questão 16).", fonte: "Simulado 2ª Avaliação — questão 16" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Na readaptação prospectiva, o militar que incorra em reforma por incapacidade definitiva na atividade-fim, por deficiência, permanece no serviço ativo em atividade administrativa, no mesmo posto/graduação.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 17 — Readaptação do militar.", fonte: "Simulado 2ª Avaliação — 17 — Readaptação do militar" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A readaptação prospectiva independe de o militar ser julgado apto pela Junta Militar de Saúde para a nova função.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 17 — Readaptação do militar.", fonte: "Simulado 2ª Avaliação — 17 — Readaptação do militar" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Na readaptação real, se o tempo reformado não ultrapassar 5 anos, o militar retorna ao serviço ativo.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 17 — Readaptação do militar.", fonte: "Simulado 2ª Avaliação — 17 — Readaptação do militar" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Na readaptação real, se o tempo reformado ultrapassar 5 anos, o militar regride para a reserva remunerada, respeitadas as idades-limite.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 17 — Readaptação do militar.", fonte: "Simulado 2ª Avaliação — 17 — Readaptação do militar" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Aos militares readaptados não são assegurados os mesmos direitos e prerrogativas dos demais integrantes da Corporação.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 17 — Readaptação do militar.", fonte: "Simulado 2ª Avaliação — 17 — Readaptação do militar" },
  { modulo: "12", tipo: "multipla", enunciado: "Segundo o art. 89 da Lei 6.783/74, NÃO será concedida transferência para a reserva remunerada, a pedido, ao policial-militar que:", alternativas: A("contar com menos de 40 anos de idade.", "estiver respondendo inquérito ou processo em qualquer jurisdição, ou estiver cumprindo pena de qualquer natureza.", "for do sexo feminino.", "estiver na ativa há menos de 20 anos, independentemente do tempo de serviço militar.", "estiver em gozo de férias regulamentares."), gabarito: "B", explicacao: "Gabarito oficial do simulado da turma (questão 18).", fonte: "Simulado 2ª Avaliação — questão 18" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Para quem ingressou a partir de 1º/01/2022, a reserva a pedido com proventos integrais só é possível após 35 anos de serviço, sendo no mínimo 30 de efetivo serviço militar em Pernambuco.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 19 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 19 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A transferência de ofício por idade ocorre quando o militar completa 70 anos, seja oficial ou praça.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 19 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 19 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A reforma do militar do Estado é ato que ocorre sempre de ofício, nunca a pedido do interessado.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 19 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 19 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Uma das hipóteses de reforma é o militar atingir a idade limite de 70 anos.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 19 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 19 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar que responde a inquérito/processo em qualquer jurisdição, ou cumpre pena de qualquer natureza, não tem direito à reserva a pedido.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 19 — Reserva remunerada e reforma.", fonte: "Simulado 2ª Avaliação — 19 — Reserva remunerada e reforma" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção é ato administrativo cuja finalidade básica é selecionar policiais militares para funções do grau hierárquico superior.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 20 — Promoção na carreira.", fonte: "Simulado 2ª Avaliação — 20 — Promoção na carreira" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Os critérios ordinários de promoção são antiguidade e bravura.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 20 — Promoção na carreira.", fonte: "Simulado 2ª Avaliação — 20 — Promoção na carreira" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção post mortem constitui um dos critérios extraordinários de promoção.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 20 — Promoção na carreira.", fonte: "Simulado 2ª Avaliação — 20 — Promoção na carreira" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção requerida é considerada um critério ordinário de promoção.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 20 — Promoção na carreira.", fonte: "Simulado 2ª Avaliação — 20 — Promoção na carreira" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção em ressarcimento de preterição pode ocorrer em casos excepcionais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 20 — Promoção na carreira.", fonte: "Simulado 2ª Avaliação — 20 — Promoção na carreira" },
  { modulo: "12", tipo: "multipla", enunciado: "Quanto aos critérios de promoção (LC 470/2021), assinale a alternativa correta:", alternativas: A("para coronel e tenente-coronel, a proporção é de uma promoção por merecimento e uma por antiguidade.", "para o 2º tenente, a promoção se dá apenas por antiguidade, na ordem de classificação intelectual do CFO ou equivalente.", "não há previsão legal de promoção em ressarcimento de preterição.", "a promoção post mortem independe de o militar estar em serviço ou atuando em razão da função no óbito.", "a promoção requerida exige o cumprimento de interstício e habilitação em cursos."), gabarito: "B", explicacao: "Gabarito oficial do simulado da turma (questão 21).", fonte: "Simulado 2ª Avaliação — questão 21" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A servidora gestante tem direito à licença-maternidade de 180 dias, com vencimento integral.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 22 — Licença-maternidade e paternidade.", fonte: "Simulado 2ª Avaliação — 22 — Licença-maternidade e paternidade" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Em caso de nascimento prematuro, a licença-maternidade terá início a partir do parto.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 22 — Licença-maternidade e paternidade.", fonte: "Simulado 2ª Avaliação — 22 — Licença-maternidade e paternidade" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Pela adoção ou guarda de criança de até 1 ano, a servidora tem direito a apenas 90 dias de licença-maternidade.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 22 — Licença-maternidade e paternidade.", fonte: "Simulado 2ª Avaliação — 22 — Licença-maternidade e paternidade" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O servidor, pelo nascimento ou adoção de filhos, tem direito à licença-paternidade de 20 dias consecutivos.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 22 — Licença-maternidade e paternidade.", fonte: "Simulado 2ª Avaliação — 22 — Licença-maternidade e paternidade" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Em caso de falecimento da genitora, é assegurada a ampliação da licença-paternidade por até 180 dias consecutivos, exceto no falecimento do filho.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 22 — Licença-maternidade e paternidade.", fonte: "Simulado 2ª Avaliação — 22 — Licença-maternidade e paternidade" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção por invalidez permanente independe de vaga, interstício ou habilitação em cursos, e o militar passa automaticamente a excedente.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 23 — Critérios extraordinários e competências.", fonte: "Simulado 2ª Avaliação — 23 — Critérios extraordinários e competências" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Para major, capitão e 1º tenente, e para subtenente, 1º e 2º sargento, a proporção é de uma por merecimento e uma por antiguidade.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 23 — Critérios extraordinários e competências.", fonte: "Simulado 2ª Avaliação — 23 — Critérios extraordinários e competências" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção requerida somente pode ser solicitada por quem ingressou até 31/12/2021 e possua o tempo de serviço exigido para a reserva.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 23 — Critérios extraordinários e competências.", fonte: "Simulado 2ª Avaliação — 23 — Critérios extraordinários e competências" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção por merecimento dos oficiais é de competência do Comandante Geral, por portaria, por delegação do Governador.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 23 — Critérios extraordinários e competências.", fonte: "Simulado 2ª Avaliação — 23 — Critérios extraordinários e competências" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Não será promovido post mortem o militar se configurado que na ação houve ofensa à honra, ao pundonor, ao dever ou ao decoro militar.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 23 — Critérios extraordinários e competências.", fonte: "Simulado 2ª Avaliação — 23 — Critérios extraordinários e competências" },
  { modulo: "12", tipo: "multipla", enunciado: "De acordo com a Lei 6.783/74, considera-se excedente o policial militar que:", alternativas: A("permanecer agregado por mais de dois anos.", "for promovido por bravura sem existir vaga.", "estiver afastado por licença para tratamento de saúde.", "for transferido para a reserva remunerada.", "permanecer desaparecido por mais de trinta dias."), gabarito: "B", explicacao: "Gabarito oficial do simulado da turma (questão 24).", fonte: "Simulado 2ª Avaliação — questão 24" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A demissão, como forma de desligamento da PM, aplica-se exclusivamente aos oficiais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 25 — Demissão, perda de posto e licenciamento.", fonte: "Simulado 2ª Avaliação — 25 — Demissão, perda de posto e licenciamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Se o oficial contar mais de 5 anos de oficialato, a demissão a pedido pode ser concedida sem indenizar os cofres públicos.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 25 — Demissão, perda de posto e licenciamento.", fonte: "Simulado 2ª Avaliação — 25 — Demissão, perda de posto e licenciamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O licenciamento do serviço ativo é instituto voltado exclusivamente às praças, não se aplicando aos oficiais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 25 — Demissão, perda de posto e licenciamento.", fonte: "Simulado 2ª Avaliação — 25 — Demissão, perda de posto e licenciamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Mesmo demissionário a pedido, o oficial mantém o direito a remuneração proporcional ao tempo de serviço prestado.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 25 — Demissão, perda de posto e licenciamento.", fonte: "Simulado 2ª Avaliação — 25 — Demissão, perda de posto e licenciamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Um oficial pode perder o posto e a patente se declarado indigno do oficialato, ou incompatível, por decisão do TJPE.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 25 — Demissão, perda de posto e licenciamento.", fonte: "Simulado 2ª Avaliação — 25 — Demissão, perda de posto e licenciamento" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar readaptado terá seu quadro clínico acompanhado anualmente pela Junta Militar de Saúde.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 26 — Acompanhamento do militar readaptado.", fonte: "Simulado 2ª Avaliação — 26 — Acompanhamento do militar readaptado" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Constatada cura ou melhora expressiva, a Junta pode atestar que o readaptado reúne condições de retornar à atividade-fim, sem restrições.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 26 — Acompanhamento do militar readaptado.", fonte: "Simulado 2ª Avaliação — 26 — Acompanhamento do militar readaptado" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Havendo agravamento na saúde do readaptado, a Junta pode atestar que ele reúne condições para a reforma.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 26 — Acompanhamento do militar readaptado.", fonte: "Simulado 2ª Avaliação — 26 — Acompanhamento do militar readaptado" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O acompanhamento anual da Junta é facultativo, podendo o readaptado dispensar a avaliação.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 26 — Acompanhamento do militar readaptado.", fonte: "Simulado 2ª Avaliação — 26 — Acompanhamento do militar readaptado" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Ao readaptado não é assegurada a participação em cursos nem a possibilidade de ministrar instruções/aulas.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 26 — Acompanhamento do militar readaptado.", fonte: "Simulado 2ª Avaliação — 26 — Acompanhamento do militar readaptado" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Para ingressar no Quadro de Acesso, exclusivamente para merecimento, o militar deve estar entre os 40% mais antigos do posto/graduação.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 27 — Quadro de Acesso (LC 470/2021).", fonte: "Simulado 2ª Avaliação — 27 — Quadro de Acesso (LC 470/2021)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O interstício mínimo para promoção ao posto de Capitão, no QOPM/Bombeiro Militar, é de 3 anos.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 27 — Quadro de Acesso (LC 470/2021).", fonte: "Simulado 2ª Avaliação — 27 — Quadro de Acesso (LC 470/2021)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar não poderá constar do Quadro de Acesso quando preso temporariamente, preventivamente ou em flagrante, enquanto não revogada a prisão.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 27 — Quadro de Acesso (LC 470/2021).", fonte: "Simulado 2ª Avaliação — 27 — Quadro de Acesso (LC 470/2021)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Será excluído de qualquer Quadro de Acesso o militar promovido, falecido ou que passar à inatividade.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 27 — Quadro de Acesso (LC 470/2021).", fonte: "Simulado 2ª Avaliação — 27 — Quadro de Acesso (LC 470/2021)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O militar em gozo de licença para tratar de interesse particular poderá normalmente constar do Quadro de Acesso.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 27 — Quadro de Acesso (LC 470/2021).", fonte: "Simulado 2ª Avaliação — 27 — Quadro de Acesso (LC 470/2021)" },
  { modulo: "12", tipo: "multipla", enunciado: "Para o militar ingresso a partir de 1º/01/2022, a transferência para a reserva remunerada, a pedido, exige:", alternativas: A("30 anos de serviço, independentemente do tempo de atividade militar.", "35 anos de serviço, sendo, no mínimo, 30 anos de atividade de natureza militar em Pernambuco.", "35 anos exclusivamente de efetivo serviço militar.", "apenas idade mínima de 60 anos.", "30 anos de efetivo serviço militar e idade mínima de 55 anos."), gabarito: "B", explicacao: "Gabarito oficial do simulado da turma (questão 28).", fonte: "Simulado 2ª Avaliação — questão 28" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O soldo é irredutível e, como regra, não pode ser objeto de penhora, sequestro ou arresto, salvo hipóteses legais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 29 — Remuneração e promoção.", fonte: "Simulado 2ª Avaliação — 29 — Remuneração e promoção" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O valor do soldo deve ser o mesmo para ativa, reserva ou reformado de mesmo grau hierárquico, ressalvadas exceções legais.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 29 — Remuneração e promoção.", fonte: "Simulado 2ª Avaliação — 29 — Remuneração e promoção" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Antiguidade e merecimento são critérios ordinários; bravura, post mortem, invalidez permanente, decenal e requerida são extraordinários.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 29 — Remuneração e promoção.", fonte: "Simulado 2ª Avaliação — 29 — Remuneração e promoção" },
  { modulo: "12", tipo: "certo_errado", enunciado: "A promoção por invalidez permanente depende de vaga, interstício e habilitação em cursos, como as demais.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 29 — Remuneração e promoção.", fonte: "Simulado 2ª Avaliação — 29 — Remuneração e promoção" },
  { modulo: "12", tipo: "certo_errado", enunciado: "No posto de 2º tenente, a promoção segue exclusivamente o critério de antiguidade, na ordem de classificação intelectual do CFO.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 29 — Remuneração e promoção.", fonte: "Simulado 2ª Avaliação — 29 — Remuneração e promoção" },
  { modulo: "12", tipo: "certo_errado", enunciado: "É direito do oficial, em serviço ativo ou na inatividade, o porte de arma, ressalvados os casos de inatividade por alienação mental ou condenação por crimes contra a segurança nacional.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto).", fonte: "Simulado 2ª Avaliação — 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O CRAF emitido pela PMPE confere ao proprietário o direito ao porte da arma nele registrada.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto).", fonte: "Simulado 2ª Avaliação — 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O CRAF do policial militar é válido por prazo indeterminado.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto).", fonte: "Simulado 2ª Avaliação — 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "Perderá o direito ao porte o policial militar sob recomendação médica ou psicológica para não portar arma de fogo.", gabarito: "certo", explicacao: "Gabarito oficial do simulado da turma. Bloco: 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto).", fonte: "Simulado 2ª Avaliação — 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto)" },
  { modulo: "12", tipo: "certo_errado", enunciado: "O procedimento de cassação do CRAF somente pode ser instaurado mediante denúncia, não de ofício.", gabarito: "errado", explicacao: "Gabarito oficial do simulado da turma. Bloco: 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto).", fonte: "Simulado 2ª Avaliação — 30 — Porte de arma de fogo (INCG 612/2024 e Estatuto)" },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)

  const hashDe = (q: Q) => createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
  const novos = new Set(QS.map(hashDe))

  // remove o que sobrou do conteúdo antigo dos módulos 6-9 (e reimportações parciais)
  const antigas = await prisma.questao.findMany({ where: { materia: MAT, modulo: { in: MODULOS } }, select: { id: true, hash: true } })
  const remover = antigas.filter(a => !novos.has(a.hash)).map(a => a.id)
  if (remover.length) await prisma.questao.deleteMany({ where: { id: { in: remover } } })

  let c = 0, u = 0
  for (const q of QS) {
    const hash = hashDe(q)
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash, fonte: q.fonte ?? null }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }

  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`LPMO assunto 2 (mods 6-12): ${c} criadas, ${u} atualizadas, ${remover.length} removidas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
