import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "LPMO"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ════════ MÓDULO 1 — Lei Orgânica Nacional ════════
  { modulo: "1", tipo: "certo_errado", enunciado: "A Lei Orgânica Nacional das Polícias Militares e Corpos de Bombeiros Militares é a Lei nº 14.751, de 12 de dezembro de 2023.", gabarito: "certo", explicacao: "Correto. A Lei nº 14.751/2023 é a Lei Orgânica Nacional das PM e CBM." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Compete privativamente à União legislar sobre normas gerais de organização das polícias militares (art. 22, XXI, da CF).", gabarito: "certo", explicacao: "Correto. O art. 22, XXI, da CF (redação da EC 103/2019) fixa a competência privativa da União." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A competência para editar normas gerais das polícias militares é concorrente entre União, Estados e Municípios.", gabarito: "errado", explicacao: "Errado. É competência PRIVATIVA da União (art. 22, XXI, da CF), e não concorrente; os Municípios sequer integram esse rol." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Segundo o art. 5º da Lei 14.751/2023, os membros das PM são autoridades de polícia administrativa, ostensiva, de preservação da ordem pública e judiciária militar.", gabarito: "certo", explicacao: "Correto. O §2º do art. 5º define essas quatro qualidades." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A polícia administrativa atua após o delito e é regida por normas de Direito Processual Penal.", gabarito: "errado", explicacao: "Errado. A polícia administrativa atua ANTES do delito (Direito Administrativo); a judiciária é que tem o delito como fato central (Direito Processual Penal)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A função de polícia judiciária militar abrange as atividades previstas no Código Penal Militar e no Código de Processo Penal Militar.", gabarito: "certo", explicacao: "Correto. O §4º do art. 5º remete ao CPM e ao CPPM (art. 8º do CPPM)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A estrutura básica dos órgãos (art. 10) compreende: direção, assessoramento, apoio, execução e correição.", gabarito: "certo", explicacao: "Correto. São os cinco tipos de órgãos do art. 10 (rol preferencial)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os órgãos de execução destinam-se à realização das atividades-meio da instituição.", gabarito: "errado", explicacao: "Errado. Os órgãos de execução realizam as atividades-FIM; os de apoio é que cuidam das atividades-meio." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os órgãos de correição exercem as funções de corregedoria-geral, com atuação desconcentrada.", gabarito: "certo", explicacao: "Correto. É o §5º do art. 10 da Lei 14.751/2023." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A Lei Orgânica Nacional tem eficácia imediata, salvo nos dispositivos que ela própria indique a necessidade de regulamentação.", gabarito: "certo", explicacao: "Correto. A apostila aponta a eficácia imediata, ressalvados os dispositivos que exijam regulamentação." },
  { modulo: "1", tipo: "certo_errado", enunciado: "As funções constitucionais das polícias militares podem ser exercidas por qualquer servidor público estadual.", gabarito: "errado", explicacao: "Errado. Só podem ser exercidas pelos militares que integram as corporações, salvo casos autorizados por lei (convênio/cooperação)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "O fundamento constitucional da Lei Orgânica Nacional foi reeditado pela Emenda Constitucional nº 103/2019.", gabarito: "certo", explicacao: "Correto. A EC 103/2019 deu nova redação ao art. 22, XXI, da CF." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Em Pernambuco, a Lei de Organização Básica da PMPE é a Lei nº 11.328/1996.", gabarito: "certo", explicacao: "Correto. A LOB da PMPE é a Lei nº 11.328/1996." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A polícia preventiva tem por finalidade perseguir o crime já ocorrido (persecutio criminis).", gabarito: "errado", explicacao: "Errado. A preventiva visa EVITAR o crime; a repressiva é que persegue o crime (persecutio criminis)." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Os órgãos de assessoramento prestam consultoria e orientação técnica para auxiliar as decisões dos órgãos de direção.", gabarito: "certo", explicacao: "Correto. É o §2º do art. 10 (órgãos de assessoramento)." },

  { modulo: "1", tipo: "multipla", enunciado: "A Lei Orgânica Nacional das PM e CBM é a:", alternativas: A("Lei nº 14.751/2023", "Lei nº 6.783/1974", "Lei nº 11.817/2000", "Lei nº 14.133/2021", "Lei nº 11.328/1996"), gabarito: "A", explicacao: "A Lei nº 14.751, de 12/12/2023, é a Lei Orgânica Nacional." },
  { modulo: "1", tipo: "multipla", enunciado: "Segundo o art. 5º, os membros das PM são autoridades de polícia:", alternativas: A("administrativa, ostensiva, de preservação da ordem pública e judiciária militar", "civil, federal, rodoviária e militar", "apenas judiciária militar", "administrativa e tributária", "preventiva e eleitoral"), gabarito: "A", explicacao: "São as quatro qualidades do §2º do art. 5º." },
  { modulo: "1", tipo: "multipla", enunciado: "A estrutura básica de órgãos prevista no art. 10 NÃO inclui:", alternativas: A("órgãos de tributação", "órgãos de direção", "órgãos de assessoramento", "órgãos de apoio", "órgãos de correição"), gabarito: "A", explicacao: "Os cinco tipos são direção, assessoramento, apoio, execução e correição. 'Tributação' não consta." },
  { modulo: "1", tipo: "multipla", enunciado: "O fundamento constitucional da Lei Orgânica Nacional é a competência:", alternativas: A("privativa da União (art. 22, XXI, CF)", "concorrente da União e Estados", "exclusiva dos Estados", "comum aos entes federativos", "privativa dos Municípios"), gabarito: "A", explicacao: "É competência privativa da União (art. 22, XXI, da CF)." },
  { modulo: "1", tipo: "multipla", enunciado: "Os órgãos responsáveis pelas atividades-FIM da instituição são os de:", alternativas: A("execução", "apoio", "assessoramento", "direção", "correição"), gabarito: "A", explicacao: "Os órgãos de execução realizam as atividades-fim; os de apoio, as atividades-meio." },

  { modulo: "1", tipo: "dissertativa", enunciado: "Discorra sobre o fundamento constitucional e a eficácia da Lei Orgânica Nacional (Lei 14.751/2023).", modelo: { estrutura: "Fundamento (art. 22, XXI) → competência privativa → eficácia imediata → adequação estadual.", criterios: ["Citar o art. 22, XXI, da CF (EC 103/2019)", "Explicar a competência privativa da União", "Apontar a eficácia imediata (salvo regulamentação)", "Mencionar a necessidade de simetria das leis estaduais"], resposta: "A Lei Orgânica Nacional (Lei nº 14.751/2023) fundamenta-se no art. 22, XXI, da CF (com redação da EC 103/2019), que atribui privativamente à União a competência para legislar sobre normas gerais de organização, garantias, inatividades e pensões das PM e CBM. Por se tratar de competência privativa, inibe-se a ingerência dos demais entes. A lei tem eficácia imediata, salvo nos dispositivos que ela própria indique a necessidade de regulamentação; ainda assim, os Estados devem atualizar suas Leis de Organização Básica para manter simetria com a norma federal." } },
  { modulo: "1", tipo: "dissertativa", enunciado: "Explique as quatro qualidades de autoridade dos membros das PM (art. 5º) e diferencie polícia administrativa de judiciária.", modelo: { estrutura: "As 4 qualidades → administrativa × judiciária → preventiva × repressiva.", criterios: ["Listar as 4 (administrativa, ostensiva, ordem pública, judiciária militar)", "Diferenciar administrativa (antes do delito) e judiciária (delito como fato central)", "Mencionar preventiva × repressiva"], resposta: "Pelo art. 5º, §2º, da Lei 14.751/2023, os membros das PM são autoridades de polícia administrativa, ostensiva, de preservação da ordem pública e judiciária militar. A polícia administrativa atua antes do delito e é regida por normas de Direito Administrativo; a polícia judiciária tem o delito como fato central e é regida por normas de Direito Processual (Penal Militar). De forma complementar, a polícia preventiva busca evitar o crime, enquanto a repressiva persegue o crime já ocorrido (persecutio criminis)." } },

  // ════════ MÓDULO 2 — Hierarquia ════════
  { modulo: "2", tipo: "certo_errado", enunciado: "São oficiais superiores: o coronel, o tenente-coronel e o major.", gabarito: "certo", explicacao: "Correto. O art. 12 da Lei 14.751/2023 classifica coronel, tenente-coronel e major como oficiais superiores." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O capitão é classificado como oficial subalterno.", gabarito: "errado", explicacao: "Errado. O capitão é o oficial intermediário; subalternos são o 1º e o 2º tenente." },
  { modulo: "2", tipo: "certo_errado", enunciado: "São oficiais subalternos o primeiro-tenente e o segundo-tenente.", gabarito: "certo", explicacao: "Correto. 1º e 2º tenente são oficiais subalternos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Aspirante a oficial, cadete e aluno-oficial são classificados como praças especiais.", gabarito: "certo", explicacao: "Correto. São as praças especiais do art. 12." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O subtenente e os sargentos são classificados como oficiais subalternos.", gabarito: "errado", explicacao: "Errado. Subtenente e sargentos são PRAÇAS, não oficiais subalternos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A todos os postos e graduações acresce-se a designação 'PM' ou 'BM'.", gabarito: "certo", explicacao: "Correto. É o parágrafo único do art. 12." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O rol de postos e graduações do art. 12 é meramente exemplificativo, podendo o Estado criar novos postos.", gabarito: "errado", explicacao: "Errado. O art. 12 é taxativo; não se pode criar ou suprimir postos/graduações além do rol." },
  { modulo: "2", tipo: "certo_errado", enunciado: "São graduações de praças: subtenente, primeiro/segundo/terceiro-sargento, aluno-sargento, cabo, soldado e aluno-soldado.", gabarito: "certo", explicacao: "Correto. É o rol de praças do art. 12, III." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O cadete é o discente do Curso de Formação de Oficiais (CFO).", gabarito: "certo", explicacao: "Correto. A apostila identifica o cadete como discente do CFO." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Diferentemente do art. 10, o art. 12 (hierarquia) traz rol taxativo.", gabarito: "certo", explicacao: "Correto. O art. 10 é preferencial; o art. 12 é taxativo." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O major é um oficial intermediário.", gabarito: "errado", explicacao: "Errado. O major é oficial SUPERIOR; o oficial intermediário é o capitão." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A hierarquia das PM observa, por força do regime jurídico constitucional militar, os fundamentos das Forças Armadas.", gabarito: "certo", explicacao: "Correto. É o caput do art. 12, que invoca o regime militar e os fundamentos das FFAA." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Aluno-soldado e aluno-sargento foram inseridos como graduações pela Lei Orgânica Nacional.", gabarito: "certo", explicacao: "Correto. A apostila destaca a inserção de aluno-soldado, aluno-sargento, aluno-oficial e cadete." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O aspirante a oficial é classificado como oficial superior.", gabarito: "errado", explicacao: "Errado. O aspirante a oficial é PRAÇA ESPECIAL, não oficial superior." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O coronel é o posto mais elevado da hierarquia das polícias militares no rol do art. 12.", gabarito: "certo", explicacao: "Correto. O coronel encabeça os oficiais superiores no rol do art. 12." },

  { modulo: "2", tipo: "multipla", enunciado: "Quais são os oficiais superiores, segundo o art. 12?", alternativas: A("coronel, tenente-coronel e major", "coronel, major e capitão", "tenente-coronel, capitão e 1º tenente", "major, capitão e 2º tenente", "coronel e capitão"), gabarito: "A", explicacao: "Oficiais superiores: coronel, tenente-coronel e major." },
  { modulo: "2", tipo: "multipla", enunciado: "O capitão é classificado como oficial:", alternativas: A("intermediário", "superior", "subalterno", "especial", "praça"), gabarito: "A", explicacao: "O capitão é o oficial intermediário." },
  { modulo: "2", tipo: "multipla", enunciado: "Aspirante a oficial, cadete e aluno-oficial são:", alternativas: A("praças especiais", "oficiais subalternos", "oficiais superiores", "praças", "oficiais intermediários"), gabarito: "A", explicacao: "São as praças especiais do art. 12." },
  { modulo: "2", tipo: "multipla", enunciado: "Assinale a designação acrescida a todos os postos e graduações:", alternativas: A("'PM' ou 'BM'", "'EB'", "'PF'", "'GM'", "'FA'"), gabarito: "A", explicacao: "Acresce-se 'PM' ou 'BM' (parágrafo único do art. 12)." },
  { modulo: "2", tipo: "multipla", enunciado: "Sobre o rol de postos e graduações do art. 12, é correto afirmar:", alternativas: A("é taxativo, não cabendo criar ou suprimir postos", "é exemplificativo", "pode ser ampliado por decreto estadual", "admite supressão do posto de capitão", "não inclui as praças especiais"), gabarito: "A", explicacao: "O art. 12 é taxativo (diferente do rol preferencial do art. 10)." },

  { modulo: "2", tipo: "dissertativa", enunciado: "Apresente a estrutura hierárquica das polícias militares conforme o art. 12 da Lei 14.751/2023.", modelo: { estrutura: "Oficiais (superiores/intermediário/subalternos) → praças especiais → praças → designação PM/BM.", criterios: ["Oficiais superiores: coronel, tenente-coronel, major", "Oficial intermediário: capitão", "Oficiais subalternos: 1º e 2º tenente", "Praças especiais: aspirante, cadete, aluno-oficial", "Praças: subtenente, sargentos, cabo, soldado e alunos", "Designação PM/BM"], resposta: "Pelo art. 12, a hierarquia divide-se em: oficiais — superiores (coronel, tenente-coronel e major), intermediário (capitão) e subalternos (1º e 2º tenente); praças especiais — aspirante a oficial, cadete e aluno-oficial; e praças — subtenente, 1º/2º/3º sargento, aluno-sargento, cabo, soldado e aluno-soldado. A todos acresce-se a designação 'PM' ou 'BM'. Trata-se de rol taxativo, não cabendo criar ou suprimir postos e graduações." } },
  { modulo: "2", tipo: "dissertativa", enunciado: "Diferencie o caráter do rol do art. 10 (órgãos) do caráter do rol do art. 12 (postos e graduações).", modelo: { estrutura: "Art. 10 (preferencial) → art. 12 (taxativo) → consequência.", criterios: ["Apontar o art. 10 como rol preferencial/não taxativo", "Apontar o art. 12 como taxativo", "Indicar a impossibilidade de criar/suprimir postos"], resposta: "O art. 10, ao tratar da estrutura básica de órgãos, usa a expressão 'preferencialmente', conferindo um modelo NÃO taxativo, que admite adequação pelas corporações. Já o art. 12, ao definir os postos e graduações, traz rol TAXATIVO: não é possível às corporações criar postos/graduações além dos previstos nem suprimi-los, garantindo padronização hierárquica nacional." } },

  // ════════ MÓDULO 3 — Deveres ════════
  { modulo: "3", tipo: "certo_errado", enunciado: "Os deveres policiais-militares emanam de vínculos racionais e morais que ligam o militar à comunidade e à sua segurança.", gabarito: "certo", explicacao: "Correto. É o caput do art. 30 da Lei 6.783/1974." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A dedicação integral ao serviço, mesmo com o sacrifício da própria vida, é um dever policial-militar.", gabarito: "certo", explicacao: "Correto. É o inciso I do art. 30." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A probidade e a lealdade são exigidas do militar apenas em serviço, não fora dele.", gabarito: "errado", explicacao: "Errado. O dever de probidade e lealdade vale 'em todas as circunstâncias' (art. 30, III)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A disciplina e o respeito à hierarquia constituem dever policial-militar.", gabarito: "certo", explicacao: "Correto. É o inciso IV do art. 30." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Tratar o subordinado dignamente e com urbanidade é um dever policial-militar.", gabarito: "certo", explicacao: "Correto. É o inciso VI do art. 30." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O culto aos símbolos nacionais não figura entre os deveres policiais-militares.", gabarito: "errado", explicacao: "Errado. O culto aos símbolos nacionais é o inciso II do art. 30." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Segundo o legislador estadual, as obrigações ligam-se aos valores e à ética, transcendendo a individualidade do militar.", gabarito: "certo", explicacao: "Correto. As obrigações relacionam-se a valores (seção I) e ética (seção II)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Os deveres decorrem do vínculo individual de cada policial militar ao envergar a farda.", gabarito: "certo", explicacao: "Correto. Os deveres decorrem dos vínculos racionais e morais individuais." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O rigoroso cumprimento das obrigações e ordens é um dever policial-militar.", gabarito: "certo", explicacao: "Correto. É o inciso V do art. 30." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A fidelidade à instituição é incompatível com o conceito de dever policial-militar.", gabarito: "errado", explicacao: "Errado. A fidelidade à instituição integra o inciso I do art. 30 (dedicação integral e fidelidade)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Obrigações e deveres, no tratamento dado pelo legislador estadual, possuem fundamentos distintos.", gabarito: "certo", explicacao: "Correto. As obrigações ligam-se a valores/ética; os deveres, ao vínculo racional e moral individual." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O respeito à hierarquia é dispensável para os oficiais superiores.", gabarito: "errado", explicacao: "Errado. A disciplina e o respeito à hierarquia são deveres de todos os militares (art. 30, IV)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A lealdade exigida do militar deve estar presente em todas as circunstâncias.", gabarito: "certo", explicacao: "Correto. O inciso III do art. 30 fala em probidade e lealdade 'em todas as circunstâncias'." },
  { modulo: "3", tipo: "certo_errado", enunciado: "O dever de urbanidade aplica-se ao trato com o subordinado.", gabarito: "certo", explicacao: "Correto. O inciso VI do art. 30 impõe tratar o subordinado dignamente e com urbanidade." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Os deveres policiais-militares estão previstos no Código de Processo Penal Militar.", gabarito: "errado", explicacao: "Errado. Os deveres estão no Estatuto dos Militares de PE (Lei 6.783/1974, art. 30), não no CPPM." },

  { modulo: "3", tipo: "multipla", enunciado: "Assinale o que NÃO é dever policial-militar do art. 30:", alternativas: A("a busca pelo lucro pessoal", "a dedicação integral ao serviço", "o culto aos símbolos nacionais", "a probidade e a lealdade", "a disciplina e o respeito à hierarquia"), gabarito: "A", explicacao: "A 'busca pelo lucro pessoal' não é dever; os demais constam do art. 30." },
  { modulo: "3", tipo: "multipla", enunciado: "A dedicação integral ao serviço, mesmo com o sacrifício da própria vida, está prevista em qual inciso do art. 30?", alternativas: A("inciso I", "inciso II", "inciso III", "inciso IV", "inciso VI"), gabarito: "A", explicacao: "É o inciso I do art. 30 (dedicação integral e fidelidade à instituição)." },
  { modulo: "3", tipo: "multipla", enunciado: "Segundo o legislador estadual, os deveres policiais-militares decorrem de:", alternativas: A("vínculos racionais e morais individuais", "normas tributárias", "contrato de trabalho privado", "regulamento de trânsito", "convenção coletiva"), gabarito: "A", explicacao: "Os deveres emanam de vínculos racionais e morais (art. 30)." },
  { modulo: "3", tipo: "multipla", enunciado: "Tratar o subordinado dignamente e com urbanidade é dever previsto no:", alternativas: A("inciso VI do art. 30", "inciso I do art. 30", "art. 49", "art. 68", "art. 75"), gabarito: "A", explicacao: "É o inciso VI do art. 30." },
  { modulo: "3", tipo: "multipla", enunciado: "A diferença, para o legislador estadual, entre obrigações e deveres é que:", alternativas: A("obrigações ligam-se a valores/ética; deveres, ao vínculo individual do militar", "são exatamente sinônimos", "deveres só valem em serviço", "obrigações são facultativas", "deveres não admitem sanção"), gabarito: "A", explicacao: "Obrigações relacionam-se a valores e ética; os deveres decorrem do vínculo racional e moral individual." },

  { modulo: "3", tipo: "dissertativa", enunciado: "Enumere e comente os deveres policiais-militares do art. 30 da Lei 6.783/1974.", modelo: { estrutura: "Caput (vínculos racionais e morais) → incisos I a VI.", criterios: ["Citar o caput (vínculos racionais e morais)", "Listar os seis deveres (I a VI)"], resposta: "Os deveres policiais-militares (art. 30) emanam de vínculos racionais e morais que ligam o militar à comunidade e à sua segurança, e compreendem: I – a dedicação integral ao serviço e a fidelidade à instituição, mesmo com o sacrifício da própria vida; II – o culto aos símbolos nacionais; III – a probidade e a lealdade em todas as circunstâncias; IV – a disciplina e o respeito à hierarquia; V – o rigoroso cumprimento das obrigações e ordens; e VI – a obrigação de tratar o subordinado dignamente e com urbanidade." } },
  { modulo: "3", tipo: "dissertativa", enunciado: "Diferencie 'obrigações' de 'deveres' policiais-militares, conforme o tratamento do legislador estadual.", modelo: { estrutura: "Obrigações → deveres → fundamento de cada → conclusão.", criterios: ["Obrigações: valores e ética, transcendem a individualidade", "Deveres: vínculo racional e moral individual", "Concluir pela distinção de fundamento"], resposta: "Para o legislador estadual, as obrigações estão voltadas a aspectos morais, comportamentais e sociais, ligadas ao campo dos valores e da ética, transcendendo a individualidade de cada militar. Já os deveres decorrem dos vínculos racionais e morais que ligam individualmente cada policial militar ao envergar a farda, tendo caráter moral, mas sem possibilidade de valoração. A distinção, portanto, está no fundamento: as obrigações são coletivas/axiológicas e os deveres, individuais." } },

  // ════════ MÓDULO 4 — Direitos, Recursos e Elegibilidade ════════
  { modulo: "4", tipo: "certo_errado", enunciado: "A garantia da patente, em toda a sua plenitude, é um direito do oficial.", gabarito: "certo", explicacao: "Correto. É o inciso I do art. 49 da Lei 6.783/1974." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A estabilidade é assegurada à praça com 10 anos de tempo de efetivo serviço.", gabarito: "certo", explicacao: "Correto. A estabilidade da praça ocorre com 10 anos de efetivo serviço (art. 49)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O direito de recorrer na esfera administrativa prescreve sempre em 30 dias.", gabarito: "errado", explicacao: "Errado. O art. 50 prevê 15 dias (quota compulsória/quadro de acesso) ou 120 dias (demais casos)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O pedido de reconsideração, a queixa e a representação não podem ser feitos coletivamente.", gabarito: "certo", explicacao: "Correto. É o §2º do art. 50." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A promoção é um dos direitos do policial-militar previstos no art. 49.", gabarito: "certo", explicacao: "Correto. A promoção figura entre os direitos do art. 49." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O porte de arma, quando oficial, em serviço ativo ou na inatividade, é um direito, salvo exceções legais.", gabarito: "certo", explicacao: "Correto. É o direito previsto no art. 49 (salvo inatividade por alienação mental ou condenações específicas)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O prazo de 15 dias para recorrer aplica-se aos casos de inclusão em quota compulsória ou composição de Quadro de Acesso.", gabarito: "certo", explicacao: "Correto. É a alínea 'a' do §1º do art. 50." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O militar com menos de 5 anos de efetivo serviço, ao se candidatar a cargo eletivo, permanece no serviço ativo normalmente.", gabarito: "errado", explicacao: "Errado. Com menos de 5 anos, ao se candidatar, é excluído do serviço ativo (demissão/licenciamento ex-officio)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O militar com 5 anos ou mais de serviço, ao se candidatar, é afastado e agregado; se eleito, é transferido para a reserva na diplomação.", gabarito: "certo", explicacao: "Correto. É a alínea 'b' do parágrafo único do art. 51." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Nos demais casos (que não quota compulsória/quadro de acesso), o prazo para recorrer é de 120 dias corridos.", gabarito: "certo", explicacao: "Correto. É a alínea 'b' do §1º do art. 50." },
  { modulo: "4", tipo: "certo_errado", enunciado: "São direitos do policial-militar as férias, os afastamentos temporários e as licenças.", gabarito: "certo", explicacao: "Correto. Constam do rol do art. 49." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O policial-militar da ativa que se dirigir ao Poder Judiciário não precisa comunicar a iniciativa à autoridade a que está subordinado.", gabarito: "errado", explicacao: "Errado. O §3º do art. 50 exige que participe antecipadamente a iniciativa à autoridade a quem estiver subordinado." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A constituição de pensão policial-militar é um dos direitos do art. 49.", gabarito: "certo", explicacao: "Correto. A constituição de pensão figura entre os direitos do art. 49." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Os recursos administrativos previstos no art. 50 são apelação e agravo.", gabarito: "errado", explicacao: "Errado. São pedido de reconsideração, queixa e representação (art. 50) — não apelação/agravo (que são judiciais)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A estabilidade é assegurada à praça já no momento do ingresso na corporação.", gabarito: "errado", explicacao: "Errado. A estabilidade da praça depende de 10 anos de efetivo serviço." },

  { modulo: "4", tipo: "multipla", enunciado: "A estabilidade da praça é assegurada com:", alternativas: A("10 anos de tempo de efetivo serviço", "5 anos de serviço", "3 anos de serviço", "o ingresso na corporação", "15 anos de serviço"), gabarito: "A", explicacao: "A praça adquire estabilidade com 10 anos de efetivo serviço (art. 49)." },
  { modulo: "4", tipo: "multipla", enunciado: "O direito de recorrer na esfera administrativa prescreve em:", alternativas: A("15 dias (quota compulsória/quadro de acesso) ou 120 dias (demais casos)", "30 dias em qualquer caso", "5 dias úteis", "60 dias", "10 dias corridos"), gabarito: "A", explicacao: "O §1º do art. 50 prevê 15 dias e 120 dias, conforme o caso." },
  { modulo: "4", tipo: "multipla", enunciado: "São instrumentos de recurso administrativo do art. 50:", alternativas: A("pedido de reconsideração, queixa e representação", "apelação e agravo", "habeas corpus e mandado de segurança", "embargos e recurso especial", "advertência e repreensão"), gabarito: "A", explicacao: "O art. 50 prevê reconsideração, queixa e representação." },
  { modulo: "4", tipo: "multipla", enunciado: "O militar com 5 ou mais anos de serviço que se candidata a cargo eletivo é:", alternativas: A("afastado e agregado; se eleito, transferido para a reserva na diplomação", "imediatamente demitido", "mantido em atividade sem qualquer alteração", "reformado de ofício", "excluído a bem da disciplina"), gabarito: "A", explicacao: "Alínea 'b' do parágrafo único do art. 51." },
  { modulo: "4", tipo: "multipla", enunciado: "Assinale um direito previsto no art. 49:", alternativas: A("promoção", "isenção total de deveres", "porte ilimitado sem qualquer restrição às praças", "imunidade penal", "vitaliciedade"), gabarito: "A", explicacao: "A promoção é direito do art. 49 (o porte das praças tem restrições do Comando-Geral)." },

  { modulo: "4", tipo: "dissertativa", enunciado: "Discorra sobre os recursos administrativos do art. 50 do Estatuto (instrumentos, prazos e vedação de coletividade).", modelo: { estrutura: "Instrumentos → prazos (15/120 dias) → vedação coletiva → comunicação ao Judiciário.", criterios: ["Citar reconsideração, queixa e representação", "Indicar os prazos de 15 e 120 dias", "Mencionar a vedação de pleito coletivo", "Citar o dever de comunicar a ida ao Judiciário"], resposta: "Pelo art. 50, o policial-militar que se julgar prejudicado ou ofendido por ato administrativo/disciplinar pode interpor pedido de reconsideração, queixa ou representação. O direito de recorrer prescreve em 15 dias corridos quanto a ato decorrente de inclusão em quota compulsória ou composição de Quadro de Acesso, e em 120 dias nos demais casos. Tais pedidos não podem ser feitos coletivamente. O militar da ativa que se dirigir ao Judiciário deve participar antecipadamente a iniciativa à autoridade a que está subordinado." } },
  { modulo: "4", tipo: "dissertativa", enunciado: "Explique as regras de elegibilidade do militar (art. 51), conforme o tempo de efetivo serviço.", modelo: { estrutura: "Regra de alistabilidade → menos de 5 anos → 5 anos ou mais → conclusão.", criterios: ["Apontar quem é alistável/elegível", "Menos de 5 anos: exclusão do serviço ativo", "5 anos ou mais: afastado/agregado; se eleito, reserva na diplomação"], resposta: "Pelo art. 51, os policiais-militares são alistáveis (oficiais, aspirantes, subtenentes, sargentos e alunos de curso superior de formação de oficiais) e, sendo alistáveis, elegíveis. Ao se candidatar a cargo eletivo: o militar com menos de 5 anos de efetivo serviço é excluído do serviço ativo (demissão ou licenciamento ex-officio); o militar com 5 anos ou mais é afastado temporariamente e agregado (em licença para tratar de interesse particular) e, se eleito, é transferido para a reserva remunerada no ato da diplomação." } },

  // ════════ MÓDULO 5 — Prerrogativas ════════
  { modulo: "5", tipo: "certo_errado", enunciado: "As prerrogativas dos policiais-militares são constituídas pelas honras, dignidades e distinções devidas aos graus hierárquicos e cargos.", gabarito: "certo", explicacao: "Correto. É o caput do art. 68." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O cumprimento de pena de prisão/detenção pode ocorrer em qualquer estabelecimento prisional comum, sem prerrogativa especial.", gabarito: "errado", explicacao: "Errado. É prerrogativa o cumprimento somente em OPM cujo comandante tenha precedência hierárquica sobre o preso (art. 68)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O julgamento em foro especial nos crimes militares é uma prerrogativa do policial-militar.", gabarito: "certo", explicacao: "Correto. É prerrogativa prevista no art. 68." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O policial-militar pode ser preso por autoridade policial em qualquer hipótese, independentemente de flagrante.", gabarito: "errado", explicacao: "Errado. Somente em flagrante delito (art. 69), devendo ser entregue imediatamente à autoridade PM mais próxima." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Em caso de flagrante, a autoridade policial deve entregar o militar preso imediatamente à autoridade policial-militar mais próxima.", gabarito: "certo", explicacao: "Correto. É o art. 69 (só pode retê-lo o tempo necessário à lavratura do flagrante)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Os policiais-militares da ativa, no exercício de funções, são dispensados do serviço de júri e do serviço na justiça eleitoral.", gabarito: "certo", explicacao: "Correto. É o art. 70." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O uso de títulos, uniformes, distintivos e insígnias correspondentes ao posto/graduação é prerrogativa do policial-militar.", gabarito: "certo", explicacao: "Correto. É a alínea 'a' do parágrafo único do art. 68." },
  { modulo: "5", tipo: "certo_errado", enunciado: "As honras, o tratamento e os sinais de respeito assegurados em lei/regulamento são prerrogativas.", gabarito: "certo", explicacao: "Correto. É a alínea 'b' do parágrafo único do art. 68." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O comandante da OME onde o militar é preso pode ter precedência hierárquica inferior à do preso.", gabarito: "errado", explicacao: "Errado. A prerrogativa exige que o comandante tenha PRECEDÊNCIA hierárquica sobre o preso (art. 68)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Cabe ao Comandante-Geral a iniciativa de responsabilizar a autoridade policial que maltratar preso policial-militar.", gabarito: "certo", explicacao: "Correto. É o §1º do art. 69." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A autoridade policial pode reter o militar preso em flagrante pelo tempo que entender conveniente.", gabarito: "errado", explicacao: "Errado. Só pode retê-lo o tempo necessário à lavratura do flagrante (art. 69)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "As prerrogativas vinculam-se aos graus hierárquicos e aos cargos.", gabarito: "certo", explicacao: "Correto. O art. 68 vincula as prerrogativas aos graus hierárquicos e cargos." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Havendo perigo de vida para preso policial-militar durante processo no foro comum, o Comandante-Geral providencia a guarda por força policial-militar.", gabarito: "certo", explicacao: "Correto. É o §2º do art. 69." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O julgamento em foro especial é prerrogativa restrita aos crimes comuns praticados por militares.", gabarito: "errado", explicacao: "Errado. A prerrogativa de foro especial refere-se aos CRIMES MILITARES." },
  { modulo: "5", tipo: "certo_errado", enunciado: "As prerrogativas dos militares incluem o uso de insígnias e emblemas correspondentes ao posto ou graduação.", gabarito: "certo", explicacao: "Correto. Integra a alínea 'a' do parágrafo único do art. 68." },

  { modulo: "5", tipo: "multipla", enunciado: "É prerrogativa do policial-militar:", alternativas: A("julgamento em foro especial nos crimes militares", "imunidade penal absoluta", "isenção de prestar contas", "vitaliciedade no cargo", "dispensa de cumprir ordens"), gabarito: "A", explicacao: "O julgamento em foro especial nos crimes militares é prerrogativa (art. 68)." },
  { modulo: "5", tipo: "multipla", enunciado: "O policial-militar somente pode ser preso por autoridade policial:", alternativas: A("em flagrante delito, devendo ser entregue à autoridade PM mais próxima", "por simples suspeita", "mediante ordem verbal de qualquer delegado", "em qualquer hipótese", "após condenação definitiva apenas"), gabarito: "A", explicacao: "Art. 69: prisão pela autoridade policial só em flagrante, com entrega imediata à autoridade PM." },
  { modulo: "5", tipo: "multipla", enunciado: "Quanto ao serviço de júri e à justiça eleitoral, os policiais-militares da ativa em função são:", alternativas: A("dispensados de ambos", "obrigados a ambos", "dispensados só do júri", "dispensados só da justiça eleitoral", "convocados compulsoriamente"), gabarito: "A", explicacao: "O art. 70 dispensa os PM da ativa, em função, do júri e da justiça eleitoral." },
  { modulo: "5", tipo: "multipla", enunciado: "O cumprimento de prisão/detenção do militar deve ocorrer:", alternativas: A("em OPM cujo comandante tenha precedência hierárquica sobre o preso", "em presídio comum", "em cadeia pública", "na delegacia que efetuou a prisão", "em qualquer quartel federal"), gabarito: "A", explicacao: "É prerrogativa do art. 68 (OPM com comandante de precedência hierárquica)." },
  { modulo: "5", tipo: "multipla", enunciado: "As prerrogativas dos policiais-militares são constituídas por:", alternativas: A("honras, dignidades e distinções devidas aos graus hierárquicos e cargos", "benefícios tributários", "imunidades parlamentares", "vantagens contratuais privadas", "isenções previdenciárias"), gabarito: "A", explicacao: "É o conceito do caput do art. 68." },

  { modulo: "5", tipo: "dissertativa", enunciado: "Apresente as principais prerrogativas dos policiais-militares (arts. 68 a 70).", modelo: { estrutura: "Conceito (art. 68) → rol → prisão (art. 69) → dispensas (art. 70).", criterios: ["Definir prerrogativas (honras/dignidades/distinções)", "Citar uso de títulos/uniformes, prisão só em OPM e foro especial", "Mencionar prisão só em flagrante (art. 69)", "Citar dispensa do júri e da justiça eleitoral (art. 70)"], resposta: "As prerrogativas (art. 68) são as honras, dignidades e distinções devidas aos graus hierárquicos e cargos, abrangendo: o uso de títulos, uniformes, distintivos, insígnias e emblemas; as honras e sinais de respeito; o cumprimento de prisão/detenção somente em OPM cujo comandante tenha precedência hierárquica sobre o preso; e o julgamento em foro especial nos crimes militares. Pelo art. 69, o militar só pode ser preso por autoridade policial em flagrante delito, sendo entregue de imediato à autoridade PM mais próxima. Pelo art. 70, os PM da ativa, no exercício de funções, são dispensados do serviço de júri e do serviço na justiça eleitoral." } },
  { modulo: "5", tipo: "dissertativa", enunciado: "Explique a prerrogativa relativa à prisão do policial-militar (art. 69) e o papel do Comandante-Geral.", modelo: { estrutura: "Prisão só em flagrante → entrega à autoridade PM → tempo de retenção → papel do CG.", criterios: ["Apontar a prisão só em flagrante delito", "Entrega imediata à autoridade PM mais próxima", "Retenção apenas pelo tempo da lavratura", "Iniciativa do CG para responsabilizar abusos e garantir a guarda"], resposta: "Pelo art. 69, somente em flagrante delito o policial-militar pode ser preso por autoridade policial, que fica obrigada a entregá-lo imediatamente à autoridade policial-militar mais próxima, só podendo retê-lo na delegacia pelo tempo necessário à lavratura do flagrante. Cabe ao Comandante-Geral a iniciativa de responsabilizar a autoridade que descumprir essa regra ou maltratar preso policial-militar; e, havendo perigo de vida para preso PM em processo no foro comum, o Comandante-Geral providencia a guarda dos tribunais por força policial-militar." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tot = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`LPMO (mods 1-5): ${c} criadas, ${u} atualizadas. Total ${MAT}: ${tot}.`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
