import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "SSP"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

// Complemento para atingir ~22 questões/módulo (padrão DADM/GRAPP/ACE).
const QS: Q[] = [
  // ════ MÓDULO 1 — Conceitos fundamentais ════
  { modulo: "1", tipo: "certo_errado", enunciado: "O termo 'público', do latim publicus, designa aquilo que é relativo ao povo e à coletividade, em oposição ao privado.", gabarito: "certo", explicacao: "Correto. Publicus deriva de populus (povo): o que é de uso de todos." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A palavra 'ordem', do latim ordo, refere-se à correta disposição/arrumação das coisas no seu devido lugar.", gabarito: "certo", explicacao: "Correto. Ordo: colocação das coisas em seu devido lugar e na correta disposição entre si." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Segurança, derivada do latim securus, exprime a ação de tornar a coisa livre de perigos e incertezas.", gabarito: "certo", explicacao: "Correto. Securus: tornar seguro, assegurar e garantir." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A ordem pública restringe-se exclusivamente à ausência de crimes, não envolvendo o funcionamento dos serviços públicos.", gabarito: "errado", explicacao: "Errado. A ordem pública abrange direitos individuais, estabilidade das instituições, regular funcionamento dos serviços públicos e moralidade pública." },
  { modulo: "1", tipo: "certo_errado", enunciado: "A salubridade pública integra a tríade da ordem pública, ao lado da segurança e da tranquilidade públicas.", gabarito: "certo", explicacao: "Correto. Ordem pública = segurança pública + tranquilidade pública + salubridade pública." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Tranquilidade pública e ordem pública são conceitos idênticos e intercambiáveis.", gabarito: "errado", explicacao: "Errado. A tranquilidade pública é apenas um dos elementos (ao lado de segurança e salubridade) que compõem a ordem pública." },
  { modulo: "1", tipo: "multipla", enunciado: "A 'incolumidade das pessoas e do patrimônio', citada no art. 144, refere-se a:", alternativas: A("preservação da integridade física das pessoas e dos bens", "apenas à proteção do patrimônio público", "exclusivamente à saúde coletiva", "somente à ordem econômica", "ao controle de fronteiras"), gabarito: "A", explicacao: "Incolumidade = estado de quem/que está livre de dano; integridade das pessoas e do patrimônio." },
  { modulo: "1", tipo: "multipla", enunciado: "Sobre a ordem pública, assinale a alternativa correta:", alternativas: A("é a situação de tranquilidade e normalidade assegurada pelo Estado conforme as normas jurídicas", "é a mera repressão policial ao crime", "independe das normas jurídicas vigentes", "é responsabilidade exclusiva da União", "limita-se às vias públicas"), gabarito: "A", explicacao: "É a situação de tranquilidade/normalidade que o Estado assegura às instituições e a todos, conforme as normas jurídicas." },
  { modulo: "1", tipo: "multipla", enunciado: "A segurança pública, segundo a doutrina, é espécie do gênero:", alternativas: A("ordem pública", "ordem econômica", "ordem tributária", "poder de polícia administrativa apenas", "defesa nacional"), gabarito: "A", explicacao: "A segurança pública é um dos componentes (espécie) da ordem pública, junto com tranquilidade e salubridade." },
  { modulo: "1", tipo: "multipla", enunciado: "Assinale a opção que melhor define 'defesa social':", alternativas: A("conjunto de ações integradas do Estado para proteção da sociedade, incluindo segurança pública, defesa civil e sistema prisional", "apenas a atuação das Forças Armadas", "o mesmo que defesa nacional", "a competência exclusiva dos municípios", "a proteção apenas do patrimônio da União"), gabarito: "A", explicacao: "Defesa social é mais ampla que segurança pública: integra segurança, defesa civil, sistema prisional e políticas correlatas." },
  { modulo: "1", tipo: "dissertativa", enunciado: "Conceitue ordem pública e explique sua composição (tríade).", modelo: { estrutura: "Conceito → tríade → papel do Estado → conclusão.", criterios: ["Definir ordem pública como situação de tranquilidade/normalidade segundo as normas jurídicas", "Citar a tríade: segurança, tranquilidade e salubridade públicas", "Relacionar com a garantia de direitos e o funcionamento das instituições"], resposta: "Ordem pública é a situação de tranquilidade e normalidade que o Estado deve assegurar às instituições e a todos os membros da sociedade, conforme as normas jurídicas. Ela se compõe de uma tríade: segurança pública (proteção contra a violência), tranquilidade pública (paz social) e salubridade pública (condições de saúde do meio). Existe quando estão garantidos os direitos individuais, a estabilidade das instituições, o regular funcionamento dos serviços públicos e a moralidade pública." } },

  // ════ MÓDULO 2 — Art. 144: os órgãos ════
  { modulo: "2", tipo: "certo_errado", enunciado: "O art. 144 da CF estabelece que a segurança pública é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio.", gabarito: "certo", explicacao: "Correto. É a finalidade prevista no caput do art. 144." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A Polícia Ferroviária Federal é um dos órgãos de segurança pública previstos no art. 144 da CF.", gabarito: "certo", explicacao: "Correto. É o inciso III do art. 144." },
  { modulo: "2", tipo: "certo_errado", enunciado: "As Forças Armadas constam expressamente entre os órgãos de segurança pública dos incisos do art. 144.", gabarito: "errado", explicacao: "Errado. As Forças Armadas não integram o rol do art. 144; atuam excepcionalmente em GLO (art. 142)." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O rol de órgãos de segurança pública do art. 144 é exemplificativo, podendo Estados criar livremente novos órgãos policiais.", gabarito: "errado", explicacao: "Errado. O rol é taxativo; o STF firmou que os Estados não podem criar órgãos policiais fora do art. 144." },
  { modulo: "2", tipo: "certo_errado", enunciado: "A segurança pública, além de dever do Estado, é direito e responsabilidade de todos.", gabarito: "certo", explicacao: "Correto. O caput do art. 144 consagra a responsabilidade compartilhada com a sociedade." },
  { modulo: "2", tipo: "certo_errado", enunciado: "As polícias penais foram previstas no art. 144 desde a redação originária da CF de 1988.", gabarito: "errado", explicacao: "Errado. As polícias penais foram inseridas pela EC nº 104/2019 (inciso VI e §5º-A)." },
  { modulo: "2", tipo: "multipla", enunciado: "Os órgãos de segurança pública do art. 144 da CF, na ordem dos incisos, são:", alternativas: A("PF, PRF, PFF, polícias civis, PM/CBM e polícias penais", "PM, PC, PF, Guarda Municipal, Exército e PRF", "PF, PC, PM, MP, Judiciário e CBM", "PRF, PF, Guarda Municipal, PM, PC e CBM", "PF, PC, PM, PRF, agentes de trânsito e penal"), gabarito: "A", explicacao: "Incisos I a VI: Polícia Federal; PRF; PFF; polícias civis; PM e CBM; polícias penais." },
  { modulo: "2", tipo: "multipla", enunciado: "A inclusão das polícias penais no art. 144 deu-se pela:", alternativas: A("Emenda Constitucional nº 104/2019", "Emenda Constitucional nº 19/1998", "Lei nº 13.675/2018", "Emenda Constitucional nº 82/2014", "Lei nº 13.022/2014"), gabarito: "A", explicacao: "A EC 104/2019 criou as polícias penais federal, estaduais e distrital." },
  { modulo: "2", tipo: "multipla", enunciado: "A guarda municipal, no texto constitucional, está prevista:", alternativas: A("no §8º do art. 144, fora do rol dos incisos I a VI", "no inciso VII do art. 144", "no art. 142 (Forças Armadas)", "apenas em lei estadual", "no inciso V do art. 144"), gabarito: "A", explicacao: "O §8º faculta aos Municípios constituir guardas municipais; elas não integram os incisos I a VI." },
  { modulo: "2", tipo: "multipla", enunciado: "A frase 'dever do Estado, direito e responsabilidade de todos' está contida:", alternativas: A("no caput do art. 144 da CF", "no preâmbulo da Constituição", "no art. 5º da CF", "na Lei 13.675/2018 apenas", "no art. 142 da CF"), gabarito: "A", explicacao: "É o caput do art. 144 da Constituição." },
  { modulo: "2", tipo: "dissertativa", enunciado: "Enumere os órgãos de segurança pública do art. 144 da CF e explique por que o rol é considerado taxativo.", modelo: { estrutura: "Lista dos 6 órgãos → taxatividade → consequência → conclusão.", criterios: ["Listar os seis órgãos (incisos I a VI)", "Afirmar a taxatividade do rol", "Apontar que Estados não podem criar órgãos fora dele (jurisprudência do STF)"], resposta: "O art. 144 enumera seis órgãos: Polícia Federal (I), Polícia Rodoviária Federal (II), Polícia Ferroviária Federal (III), polícias civis (IV), polícias militares e corpos de bombeiros militares (V) e polícias penais (VI, incluídas pela EC 104/2019). O rol é taxativo: conforme entendimento do STF, os entes federativos não podem criar órgãos de segurança pública diversos dos previstos na Constituição, sob pena de inconstitucionalidade — daí a guarda municipal estar prevista em parágrafo próprio (§8º) e não entre os incisos." } },

  // ════ MÓDULO 3 — Competências ════
  { modulo: "3", tipo: "certo_errado", enunciado: "Compete à Polícia Federal prevenir e reprimir o tráfico ilícito de entorpecentes com repercussão interestadual ou internacional.", gabarito: "certo", explicacao: "Correto. É atribuição da PF (art. 144, §1º, II)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "À Polícia Rodoviária Federal cabe o patrulhamento ostensivo das rodovias federais.", gabarito: "certo", explicacao: "Correto. Art. 144, §2º." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Cabe às polícias militares a apuração de infrações penais comuns e a função de polícia judiciária.", gabarito: "errado", explicacao: "Errado. À PM cabem a polícia ostensiva e a preservação da ordem; a polícia judiciária e a apuração penal são das polícias civis (e PF, na esfera federal)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Aos corpos de bombeiros militares incumbe, além das atribuições definidas em lei, a execução de atividades de defesa civil.", gabarito: "certo", explicacao: "Correto. Art. 144, §5º, parte final." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As polícias civis são dirigidas por delegados de polícia de carreira.", gabarito: "certo", explicacao: "Correto. Art. 144, §4º." },
  { modulo: "3", tipo: "certo_errado", enunciado: "As polícias penais estão vinculadas ao órgão administrador do sistema penal e respondem pela segurança dos estabelecimentos penais.", gabarito: "certo", explicacao: "Correto. Art. 144, §5º-A (EC 104/2019)." },
  { modulo: "3", tipo: "certo_errado", enunciado: "A função de polícia judiciária da União é exercida concorrentemente pela Polícia Federal e pela Polícia Rodoviária Federal.", gabarito: "errado", explicacao: "Errado. A polícia judiciária da União é exercida com EXCLUSIVIDADE pela Polícia Federal (§1º, IV)." },
  { modulo: "3", tipo: "multipla", enunciado: "A polícia ostensiva e a preservação da ordem pública cabem:", alternativas: A("às polícias militares", "às polícias civis", "à Polícia Federal", "às guardas municipais", "à Polícia Rodoviária Federal"), gabarito: "A", explicacao: "Art. 144, §5º: às PM cabem a polícia ostensiva e a preservação da ordem pública." },
  { modulo: "3", tipo: "multipla", enunciado: "As funções de polícia marítima, aeroportuária e de fronteiras competem à:", alternativas: A("Polícia Federal", "Polícia Rodoviária Federal", "Marinha do Brasil", "Polícia Civil", "Guarda Municipal"), gabarito: "A", explicacao: "Art. 144, §1º, III: são funções da Polícia Federal." },
  { modulo: "3", tipo: "multipla", enunciado: "Segundo o §6º do art. 144, as PM e os CBM são forças auxiliares e reserva do:", alternativas: A("Exército, subordinando-se aos Governadores", "Ministério da Defesa, subordinando-se ao Presidente", "Ministério da Justiça", "Senado Federal", "STF"), gabarito: "A", explicacao: "São forças auxiliares e reserva do Exército, subordinadas aos Governadores (com as polícias civis e penais)." },
  { modulo: "3", tipo: "multipla", enunciado: "A apuração de infrações penais militares NÃO compete às polícias civis porque:", alternativas: A("o §4º do art. 144 ressalva expressamente as infrações militares", "as infrações militares não existem", "compete apenas à Polícia Federal", "compete às guardas municipais", "compete aos agentes de trânsito"), gabarito: "A", explicacao: "O §4º atribui às PC a apuração de infrações penais 'exceto as militares'." },

  // ════ MÓDULO 4 — Outros atores ════
  { modulo: "4", tipo: "certo_errado", enunciado: "A Lei nº 13.022/2014 dispõe sobre o Estatuto Geral das Guardas Municipais.", gabarito: "certo", explicacao: "Correto. Regulamenta as guardas municipais previstas no §8º do art. 144." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A segurança viária foi inserida no art. 144 pela Emenda Constitucional nº 82/2014.", gabarito: "certo", explicacao: "Correto. O §10 (EC 82/2014) trata da segurança viária e dos agentes de trânsito." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A atuação das Forças Armadas na segurança pública interna é regra geral e permanente.", gabarito: "errado", explicacao: "Errado. É excepcional, por meio de operações de Garantia da Lei e da Ordem (GLO)." },
  { modulo: "4", tipo: "certo_errado", enunciado: "Os Municípios são obrigados a constituir guardas municipais.", gabarito: "errado", explicacao: "Errado. O §8º diz que os Municípios 'poderão' constituí-las — é faculdade, não obrigação." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A segurança viária compreende a educação, a engenharia e a fiscalização de trânsito.", gabarito: "certo", explicacao: "Correto. É o conteúdo do §10, I, do art. 144." },
  { modulo: "4", tipo: "multipla", enunciado: "As guardas municipais destinam-se, conforme o §8º do art. 144, à proteção:", alternativas: A("dos bens, serviços e instalações dos Municípios", "exclusivamente das rodovias municipais", "do patrimônio da União", "apenas das escolas estaduais", "das fronteiras nacionais"), gabarito: "A", explicacao: "§8º: proteção dos bens, serviços e instalações municipais, conforme dispuser a lei (13.022/2014)." },
  { modulo: "4", tipo: "multipla", enunciado: "A atuação das Forças Armadas em apoio à segurança pública interna ocorre por meio de:", alternativas: A("operações de Garantia da Lei e da Ordem (GLO)", "convênios com guardas municipais", "delegação da Polícia Civil", "requisição do Ministério Público", "ordem do prefeito"), gabarito: "A", explicacao: "As FFAA atuam excepcionalmente em GLO, autorizadas pelo Presidente da República." },
  { modulo: "4", tipo: "multipla", enunciado: "O sistema penitenciário, no quadro da segurança/defesa social, é responsável por:", alternativas: A("executar as penas impostas pelo Judiciário", "investigar crimes federais", "patrulhar rodovias", "fiscalizar o trânsito urbano", "julgar ações penais"), gabarito: "A", explicacao: "O sistema penitenciário executa as penas; enfrenta desafios como superlotação e ressocialização." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A segurança viária é exercida para a preservação da ordem pública e da incolumidade das pessoas e do patrimônio nas vias públicas.", gabarito: "certo", explicacao: "Correto. É a redação do §10 do art. 144 (EC 82/2014)." },
  { modulo: "4", tipo: "multipla", enunciado: "Assinale a alternativa correta sobre os atores complementares da segurança pública:", alternativas: A("guardas municipais e agentes de trânsito atuam de forma cooperada, mas não substituem as polícias dos incisos do art. 144", "as guardas municipais exercem polícia judiciária", "os agentes de trânsito podem investigar homicídios", "o sistema penitenciário julga as penas", "as Forças Armadas atuam ordinariamente no policiamento ostensivo"), gabarito: "A", explicacao: "Atores complementares cooperam, dentro de suas competências, sem substituir os órgãos do art. 144." },

  // ════ MÓDULO 5 — SUSP/PNSPDS ════
  { modulo: "5", tipo: "certo_errado", enunciado: "A Lei nº 13.675/2018 regulamenta o §7º do art. 144 da CF, disciplinando a organização e o funcionamento dos órgãos de segurança pública.", gabarito: "certo", explicacao: "Correto. A lei do SUSP/PNSPDS dá concretude ao §7º do art. 144." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A PNSPDS adota o respeito ao Estado Democrático de Direito e aos direitos humanos entre seus princípios.", gabarito: "certo", explicacao: "Correto. São princípios expressos da Política Nacional (art. 4º da Lei 13.675/2018)." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O SUSP transfere a competência da segurança pública exclusivamente para a União.", gabarito: "errado", explicacao: "Errado. O SUSP integra e coordena os órgãos das três esferas (federalismo cooperativo), sem retirar competências dos entes." },
  { modulo: "5", tipo: "certo_errado", enunciado: "Guardas municipais e agentes de trânsito podem integrar operacionalmente o SUSP, nos limites de suas competências.", gabarito: "certo", explicacao: "Correto. O art. 9º da Lei 13.675/2018 os inclui como integrantes operacionais." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A governança do SUSP dispensa planejamento, metas e avaliação de resultados.", gabarito: "errado", explicacao: "Errado. A governança do SUSP estrutura-se justamente em planejamento, execução, monitoramento e avaliação, com planos e metas." },
  { modulo: "5", tipo: "multipla", enunciado: "A sigla PNSPDS corresponde a:", alternativas: A("Política Nacional de Segurança Pública e Defesa Social", "Plano Nacional de Segurança Pública e Defesa Social", "Programa Nacional de Saúde Pública e Defesa Social", "Política Nacional de Segurança Penitenciária e Defesa Social", "Plano Nacional de Sistema Prisional e Defesa Social"), gabarito: "A", explicacao: "PNSPDS = Política Nacional de Segurança Pública e Defesa Social (Lei 13.675/2018)." },
  { modulo: "5", tipo: "multipla", enunciado: "São objetivos/princípios da PNSPDS, EXCETO:", alternativas: A("uso ilimitado e discricionário da força policial", "respeito aos direitos humanos", "eficiência e transparência", "resolução pacífica de conflitos", "participação social"), gabarito: "A", explicacao: "A PNSPDS preconiza o uso COMEDIDO e PROPORCIONAL da força — não o uso ilimitado." },
  { modulo: "5", tipo: "multipla", enunciado: "A lógica de articulação do SUSP entre União, Estados e Municípios é a de:", alternativas: A("federalismo cooperativo", "centralismo federal", "autonomia absoluta dos municípios", "subordinação das polícias à União", "competência privativa estadual"), gabarito: "A", explicacao: "O SUSP baseia-se no federalismo cooperativo, com atribuições próprias e conexas exercidas de forma coordenada." },
  { modulo: "5", tipo: "multipla", enunciado: "O ciclo de governança do SUSP compreende, tipicamente:", alternativas: A("planejamento, execução, monitoramento e avaliação", "inquérito, denúncia, processo e sentença", "prevenção, repressão e absolvição", "edital, licitação e contrato", "alistamento, seleção e formação"), gabarito: "A", explicacao: "A governança do SUSP segue o ciclo planejar → executar → monitorar → avaliar, com planos alinhados à PNSPDS." },
  { modulo: "5", tipo: "certo_errado", enunciado: "O SUSP e o SUS possuem a mesma base legal e tratam da mesma matéria.", gabarito: "errado", explicacao: "Errado. SUSP (segurança pública, Lei 13.675/2018) e SUS (saúde) são sistemas distintos, com bases legais próprias." },

  // ════ MÓDULO 6 — Justiça criminal ════
  { modulo: "6", tipo: "certo_errado", enunciado: "No sistema de justiça criminal, ao Poder Judiciário compete aplicar o direito ao caso concreto, com autonomia administrativa e financeira.", gabarito: "certo", explicacao: "Correto. O Judiciário julga, com independência e autonomia." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A responsabilidade pela segurança pública é exclusiva da União, não cabendo cooperação dos Estados e Municípios.", gabarito: "errado", explicacao: "Errado. A segurança pública é de responsabilidade compartilhada e cooperada entre União, Estados e Municípios." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A ENASP (2010) teve como foco inicial os crimes de homicídio doloso.", gabarito: "certo", explicacao: "Correto. A Estratégia Nacional de Justiça e Segurança Pública priorizou inicialmente os homicídios dolosos." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O FUNPEN é o Fundo Penitenciário Nacional, gerido no âmbito do Ministério da Justiça.", gabarito: "certo", explicacao: "Correto. Discute-se sua transformação em fundo de segurança pública e a vedação ao contingenciamento." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Os poderes da União — Legislativo, Executivo e Judiciário — são independentes e harmônicos entre si.", gabarito: "certo", explicacao: "Correto. É o princípio da separação dos poderes (art. 2º da CF)." },
  { modulo: "6", tipo: "multipla", enunciado: "No sistema de justiça criminal, o órgão titular da ação penal pública é:", alternativas: A("o Ministério Público", "o delegado de polícia", "o juiz de direito", "a Defensoria Pública", "o Tribunal de Contas"), gabarito: "A", explicacao: "O MP é o titular privativo da ação penal pública (art. 129, I, da CF)." },
  { modulo: "6", tipo: "multipla", enunciado: "Estudos citados na apostila (IPEA, Defensoria) sobre a atuação penal evidenciam:", alternativas: A("viés racial e socioeconômico em prisões e ingressos em domicílios", "ausência total de desigualdade no sistema", "que apenas bairros ricos são alvo de operações", "que o reconhecimento fotográfico é infalível", "que não há relação entre cidadania e direito penal"), gabarito: "A", explicacao: "Os dados apontam desproporção racial e social (ex.: maioria de pretos/pardos em prisões por reconhecimento e ingressos em domicílios de bairros pobres)." },
  { modulo: "6", tipo: "multipla", enunciado: "A cooperação federativa em segurança pública pode ser descrita como um modelo de:", alternativas: A("federalismo cooperativo, com atribuições próprias e conexas", "centralização total na União", "independência absoluta entre os entes", "competência exclusiva municipal", "delegação integral ao Judiciário"), gabarito: "A", explicacao: "União, Estados e Municípios têm atribuições próprias e conexas, exercidas de forma coordenada (federalismo cooperativo)." },
  { modulo: "6", tipo: "multipla", enunciado: "A série 'Faces da Cidadania' e os precedentes do STJ citados tratam, sobretudo, do conflito entre:", alternativas: A("direitos fundamentais e atuação dos órgãos de persecução penal", "competências da União e dos Estados", "poderes Executivo e Legislativo", "tributos federais e estaduais", "polícia militar e bombeiros"), gabarito: "A", explicacao: "Discutem a tensão entre os direitos fundamentais do cidadão e a atuação dos órgãos de persecução penal." },
  { modulo: "6", tipo: "certo_errado", enunciado: "O respeito aos direitos fundamentais é incompatível com a atividade de segurança pública e deve ser afastado nas operações policiais.", gabarito: "errado", explicacao: "Errado. O respeito aos direitos fundamentais é parte integrante e legitimadora da segurança pública, não um obstáculo." },
]

type Card = { modulo: string; frente: string; verso: string }
const CARDS: Card[] = [
  { modulo: "1", frente: "Público, ordem, segurança (etimologia)", verso: `• Público (publicus): relativo ao povo/coletividade.\n• Ordem (ordo): correta disposição das coisas.\n• Segurança (securus): tornar livre de perigos e incertezas.` },
  { modulo: "1", frente: "Segurança pública × defesa social", verso: `• Segurança pública: espécie da ordem pública (proteção contra a violência).\n• Defesa social: mais ampla — integra segurança pública, defesa civil e sistema prisional.` },
  { modulo: "2", frente: "Art. 144 — taxatividade do rol", verso: `• Rol dos incisos I-VI é TAXATIVO (STF): Estados não criam órgãos fora dele.\n• Guarda municipal está no §8º (fora dos incisos).` },
  { modulo: "3", frente: "Polícia ostensiva × judiciária", verso: `• PM (§5º): ostensiva + ordem pública (prevenção, fardada).\n• PC (§4º)/PF (§1º): judiciária + investigação (após o delito).\n• PF tem exclusividade na polícia judiciária da União.` },
  { modulo: "4", frente: "EC 82/2014 e Lei 13.022/2014", verso: `• EC 82/2014: segurança viária (§10) — educação, engenharia e fiscalização de trânsito.\n• Lei 13.022/2014: Estatuto Geral das Guardas Municipais (§8º).` },
  { modulo: "5", frente: "PNSPDS — princípios", verso: `• Respeito ao Estado Democrático de Direito e aos direitos humanos; eficiência; transparência; participação social; resolução pacífica de conflitos; uso comedido e proporcional da força.` },
  { modulo: "5", frente: "SUSP — governança", verso: `• Ciclo: planejamento → execução → monitoramento → avaliação.\n• Planos nacional/estaduais/municipais alinhados à PNSPDS; federalismo cooperativo.` },
  { modulo: "6", frente: "ENASP e FUNPEN", verso: `• ENASP (2010, CNJ+CNMP+MJ): foco inicial em homicídios dolosos.\n• FUNPEN: Fundo Penitenciário Nacional (MJ); debate sobre vedar contingenciamento.` },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  let fc = 0
  const fcBase = await prisma.flashcard.count({ where: { materia: MAT } })
  for (const card of CARDS) {
    const hash = createHash("sha1").update(`${MAT}|${card.modulo}|${card.frente}`).digest("hex")
    await prisma.flashcard.upsert({ where: { hash }, update: { verso: card.verso }, create: { materia: MAT, modulo: card.modulo, frente: card.frente, verso: card.verso, ordem: fcBase + fc, hash } })
    fc++
  }
  const [tq, tc] = await Promise.all([prisma.questao.count({ where: { materia: MAT } }), prisma.flashcard.count({ where: { materia: MAT } })])
  console.log(`SSP +complemento: questoes ${c} criadas/${u} atualizadas (total ${tq}); flashcards +${fc} (total ${tc}).`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
