import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "TCEM"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ── Módulo 1 — Comando, Chefia e Liderança ──
  { modulo: "1", tipo: "certo_errado", enunciado: "A liderança militar permite ao comandante mover seus subordinados não apenas pela força de leis e regulamentos, mas pela sua qualificação profissional e pelo exemplo pessoal.", gabarito: "certo", explicacao: "Correto. A liderança militar conduz pelo envolvimento, fazendo da missão uma causa comum, e não mero cumprimento de ordem." },
  { modulo: "1", tipo: "certo_errado", enunciado: "Assim como no meio civil 'liderança' é por vezes confundida com 'gerência', na caserna o termo liderança militar é frequentemente empregado, de forma inadequada, como sinônimo de comando.", gabarito: "certo", explicacao: "Correto. A apostila alerta para essa confusão: comando é o exercício do cargo; liderança é elemento informal e desejável do comando." },
  { modulo: "1", tipo: "multipla", enunciado: "A relação entre liderança e comando pode ser caracterizada da seguinte forma:", alternativas: A("a liderança é um elemento informal, mas desejável, do comando", "a liderança substitui integralmente a autoridade legal do cargo", "o comando é um elemento informal da liderança", "liderança e comando são incompatíveis entre si", "a liderança dispensa a administração"), gabarito: "A", explicacao: "A liderança é o componente informal (desejável) do comando, ao lado da autoridade legal e da administração." },

  // ── Módulo 2 — Liderança Militar, competências e inteligências ──
  { modulo: "2", tipo: "multipla", enunciado: "A Teoria das Inteligências Múltiplas, que propõe que o ser humano possui diferentes capacidades (lógico-matemática, linguística, espacial, musical, corporal-cinestésica, interpessoal e intrapessoal), foi proposta por:", alternativas: A("Howard Gardner", "Daniel Goleman", "Peter Salovey", "Abraham Maslow", "Frederick Taylor"), gabarito: "A", explicacao: "Howard Gardner propôs, no início dos anos 1980, a teoria das inteligências múltiplas (inicialmente sete inteligências)." },
  { modulo: "2", tipo: "certo_errado", enunciado: "Segundo Gardner, cada tipo de inteligência desenvolve-se de forma independente das demais, de modo que o alto desempenho em uma das formas não implica o mesmo desempenho em outra.", gabarito: "certo", explicacao: "Correto. As inteligências são relativamente autônomas entre si." },
  { modulo: "2", tipo: "multipla", enunciado: "A inteligência associada à capacidade de conhecer a si mesmo, controlar os próprios sentimentos e usar as informações pessoais para alcançar objetivos, considerada por Gardner a mais rara, é a:", alternativas: A("intrapessoal", "interpessoal", "linguística", "lógico-matemática", "naturalista"), gabarito: "A", explicacao: "A inteligência intrapessoal liga-se ao autoconhecimento e ao autocontrole; a interpessoal, à relação com os outros." },
  { modulo: "2", tipo: "multipla", enunciado: "A Teoria da Inteligência Emocional, relacionada às inteligências intrapessoal e interpessoal, é proposta por:", alternativas: A("Peter Salovey e Daniel Goleman", "Howard Gardner e Henri Fayol", "Elton Mayo e Max Weber", "Sun Tzu e Clausewitz", "Maslow e Herzberg"), gabarito: "A", explicacao: "A inteligência emocional, no campo social, é atribuída a Peter Salovey e Daniel Goleman; é central para a liderança." },
  { modulo: "2", tipo: "multipla", enunciado: "As quatro habilidades fundamentais da inteligência emocional, segundo a apostila, são:", alternativas: A("autoconhecimento, autocontrole, empatia e administração dos relacionamentos", "memória, atenção, percepção e motivação", "planejar, organizar, dirigir e controlar", "prever, comandar, coordenar e fiscalizar", "observação, sentimento, necessidade e pedido"), gabarito: "A", explicacao: "São: (1) conhecer as próprias emoções (autoconhecimento); (2) controlá-las (autocontrole); (3) reconhecer as emoções nos outros (empatia); (4) administrar relacionamentos." },
  { modulo: "2", tipo: "certo_errado", enunciado: "O autoconhecimento, primeira habilidade da inteligência emocional, é a diferença entre um mero 'ataque de raiva' e o reconhecimento desse ataque (saber que 'estou com raiva agora').", gabarito: "certo", explicacao: "Correto. É a chamada 'consciência paralela' — base para o controle das emoções." },
  { modulo: "2", tipo: "certo_errado", enunciado: "É a inteligência emocional que permitirá ao comandante, em qualquer escalão, agir com sereno rigor, conseguindo persuadir os seus subordinados.", gabarito: "certo", explicacao: "Correto. A apostila destaca a inteligência emocional como diferencial da liderança em todos os escalões." },
  { modulo: "2", tipo: "multipla", enunciado: "As competências do líder militar resultam da transformação, em comportamentos com resultados práticos, de recursos:", alternativas: A("cognitivos, psicomotores e afetivos", "financeiros, materiais e humanos", "legais, morais e disciplinares", "táticos, técnicos e logísticos", "físicos, mentais e espirituais"), gabarito: "A", explicacao: "Competência = transformação de recursos cognitivos, psicomotores e afetivos em comportamentos que geram resultados." },
  { modulo: "2", tipo: "certo_errado", enunciado: "As competências afetivas do líder podem ser pessoais (no âmbito individual) ou interpessoais (que exigem interação com outras pessoas para serem externadas).", gabarito: "certo", explicacao: "Correto. A apostila distingue competências afetivas pessoais e interpessoais." },

  // ── Módulo 3 — Estilos de Comando e níveis ──
  { modulo: "3", tipo: "certo_errado", enunciado: "O uso indiscriminado e prolongado do estilo de comando autocrático tende a desgastar os vínculos afetivos entre o comandante e os comandados.", gabarito: "certo", explicacao: "Correto. Apesar de útil em emergências, o autocrático em excesso desgasta a relação." },
  { modulo: "3", tipo: "certo_errado", enunciado: "Em um grupo composto por indivíduos competentes e com elevada iniciativa, o estilo de comando autocrático tende a potencializar os resultados.", gabarito: "errado", explicacao: "Errado. Nesse perfil de grupo, o autocrático pode restringir a capacidade dos subordinados e gerar resultados negativos." },
  { modulo: "3", tipo: "multipla", enunciado: "O estilo de comando participativo caracteriza-se por:", alternativas: A("o comandante ouvir e aproveitar as sugestões do grupo antes de decidir, mantendo a decisão final", "o comandante transferir integralmente a decisão ao grupo", "a ausência de autoridade do comandante", "decisões tomadas sem qualquer consulta", "a exclusividade em ambientes de combate"), gabarito: "A", explicacao: "No participativo o comandante atua sintonizado com o grupo, mas a decisão final é dele." },
  { modulo: "3", tipo: "multipla", enunciado: "O estilo de comando delegativo é bastante empregado:", alternativas: A("nos níveis intermediários e superiores e nas operações de execução descentralizada", "apenas no nível de pequenos escalões", "somente em situações de combate", "exclusivamente em tempo de paz", "apenas no comando de recrutas"), gabarito: "A", explicacao: "O delegativo predomina nos níveis intermediário/superior e na execução descentralizada, em que se delega o poder de decisão a comandantes subordinados." },

  // ── Módulo 4 — Estrutura do Estado-Maior ──
  { modulo: "4", tipo: "multipla", enunciado: "O órgão de planejamento e coordenação de mais alto nível, responsável por desenvolver planos estratégicos e operacionais, é o:", alternativas: A("Estado-Maior Geral (EMG)", "Estado-Maior de OME", "Conselho de Disciplina", "Comando de Policiamento da Capital", "Corregedoria-Geral"), gabarito: "A", explicacao: "O EMG é o EM de mais alto nível; o EM de OME planeja e coordena no âmbito de uma Organização Militar Estadual." },
  { modulo: "4", tipo: "certo_errado", enunciado: "A descentralização habilita o comandante a dirigir e supervisionar a execução de seu plano sem se envolver nos detalhes do planejamento, da direção e do controle de cada elemento subordinado.", gabarito: "certo", explicacao: "Correto. Ao descentralizar, o comandante delega competência e responsabiliza os subordinados, poupando tempo e energia." },
  { modulo: "4", tipo: "certo_errado", enunciado: "O Estado-Maior de uma OME é o órgão de planejamento e coordenação responsável por desenvolver planos operacionais e táticos para as operações em campo.", gabarito: "certo", explicacao: "Correto. O EM de OME elabora os planos operacionais/táticos da unidade." },
  { modulo: "4", tipo: "multipla", enunciado: "Cabe ao Subchefe do Estado-Maior:", alternativas: A("assessorar o Chefe do EM e coordenar a elaboração de diretrizes, planos e ordens, apto a assumir a Chefia em impedimentos", "comandar operacionalmente todos os batalhões", "substituir o Comandante-Geral em qualquer situação", "exercer a função de corregedor", "presidir o Conselho de Justificação"), gabarito: "A", explicacao: "O Subchefe assessora o Chefe do EM e o substitui em impedimentos, sem quebra da sequência lógica do comando." },

  // ── Módulo 5 — Seções do EM ──
  { modulo: "5", tipo: "multipla", enunciado: "A Seção do Estado-Maior encarregada dos assuntos de informação e contrainformação (inteligência) é a:", alternativas: A("PM/2", "PM/1", "PM/3", "PM/5", "PM/7"), gabarito: "A", explicacao: "A PM/2 trata de informação e contrainformação (inteligência), assessorando a tomada de decisão." },
  { modulo: "5", tipo: "multipla", enunciado: "O assessoramento do Comandante-Geral na área de logística (suprimento, transporte, manutenção e serviços) compete à:", alternativas: A("PM/4", "PM/3", "PM/6", "PM/8", "PM/1"), gabarito: "A", explicacao: "A 4ª Seção (PM/4) cuida do apoio logístico da Corporação." },
  { modulo: "5", tipo: "multipla", enunciado: "A 5ª Seção do EM (PM/5), também denominada Assessoria de Comunicação Social (ASCOM), é encarregada:", alternativas: A("dos assuntos civis, da comunicação social e do cerimonial de solenidades e eventos", "do orçamento e das finanças da Corporação", "da doutrina institucional", "exclusivamente da inteligência policial", "da formação e do ensino"), gabarito: "A", explicacao: "A PM/5 trata de assuntos civis, comunicação social (ASCOM) e cerimonial; integra o CICOM/SDS." },
  { modulo: "5", tipo: "multipla", enunciado: "A Seção do EM responsável pelos projetos estruturadores e pela captação de recursos extraorçamentários, instituída pela Lei nº 15.186/2013, é a:", alternativas: A("PM/7", "PM/6", "PM/8", "PM/3", "PM/2"), gabarito: "A", explicacao: "A PM/7 trata de projetos estruturadores e capta recursos extraorçamentários (Lei nº 15.186/2013); a PM/6 cuida do orçamento." },
  { modulo: "5", tipo: "certo_errado", enunciado: "A 6ª Seção do Estado-Maior (PM/6) é encarregada do planejamento administrativo e orçamentário, gerindo o orçamento e as finanças da Corporação.", gabarito: "certo", explicacao: "Correto. A PM/6 planeja e executa o orçamento e as finanças, otimizando os recursos da instituição." },

  // ── Módulo 6 — Atividades do EM ──
  { modulo: "6", tipo: "certo_errado", enunciado: "Na produção de informações, cabe ao Estado-Maior coletar, consolidar e interpretar os dados de interesse do comando, fornecendo ao comandante informações já interpretadas e prontas para utilização.", gabarito: "certo", explicacao: "Correto. É a 1ª atividade do EM: transformar dados em informações úteis e oportunas." },
  { modulo: "6", tipo: "certo_errado", enunciado: "Falhas na elaboração dos estudos de situação podem gerar erros e omissões de consequências desastrosas, caso não sejam consideradas as contingências e os obstáculos à linha de ação adotada.", gabarito: "certo", explicacao: "Correto. A adequação dos planos depende de estudos de situação prévios e continuados." },
  { modulo: "6", tipo: "multipla", enunciado: "A atividade do Estado-Maior que consiste em transformar as decisões e diretrizes do comandante em documentos de execução é a:", alternativas: A("produção de planos e ordens", "produção de informações", "elaboração de estudos de situação", "supervisão da execução", "apresentação de propostas"), gabarito: "A", explicacao: "Na produção de planos e ordens, o EM converte as decisões do comandante em planos/ordens (podendo ter competência delegada para expedi-los)." },
  { modulo: "6", tipo: "certo_errado", enunciado: "A supervisão da execução dos planos e ordens libera o comandante do trato de detalhes e fornece ao Estado-Maior as informações necessárias para elaborar os relatórios de situação.", gabarito: "certo", explicacao: "Correto. É a 5ª atividade do EM; assegura a correta execução e realimenta o comando." },

  // ── Módulo 7 — Organização Básica da PMPE ──
  { modulo: "7", tipo: "certo_errado", enunciado: "A Lei nº 11.328/1996 foi sancionada em 11 de janeiro de 1996 e dispõe sobre a Organização Básica da Polícia Militar de Pernambuco.", gabarito: "certo", explicacao: "Correto. É a norma estruturante da organização da PMPE, da qual decorrem o organograma e os Quadros de Organização." },
  { modulo: "7", tipo: "multipla", enunciado: "Manter atualizada a distribuição do efetivo da Corporação conforme os Quadros de Organização (Q.O.) é atribuição típica da:", alternativas: A("PM/1 (pessoal e legislação)", "PM/3 (operações)", "PM/4 (logística)", "PM/6 (orçamento)", "PM/8 (doutrina)"), gabarito: "A", explicacao: "A PM/1 responde pela Organização Básica (Lei 11.328/96), efetivo, Q.O. e legislação." },

  // ── Módulo 8 — Trabalho de Comando ──
  { modulo: "8", tipo: "multipla", enunciado: "O documento de planejamento que organiza projetos com o mesmo objetivo, ampliando ações de uma política pública e sendo gerido de forma coordenada, é o:", alternativas: A("programa", "plano", "projeto", "diagnóstico", "relatório"), gabarito: "A", explicacao: "Programa = conjunto coordenado de projetos com objetivo comum; projeto = ação específica com início/fim; plano = documento diretor." },
  { modulo: "8", tipo: "multipla", enunciado: "Caracteriza-se por ser um instrumento técnico-administrativo para ações específicas, com início e fim definidos:", alternativas: A("o projeto", "o programa", "o plano", "a diretriz", "a política"), gabarito: "A", explicacao: "O projeto é a ação específica, com início e fim definidos e equipe própria." },
  { modulo: "8", tipo: "certo_errado", enunciado: "A sequência do Trabalho de Comando relaciona-se ao conteúdo de Teoria Geral da Administração e envolve planejamento, organização, execução, controle, coordenação e avaliação.", gabarito: "certo", explicacao: "Correto. A apostila vincula o Trabalho de Comando ao ciclo administrativo (PODC ampliado com coordenação e avaliação/lições aprendidas)." },
  { modulo: "8", tipo: "certo_errado", enunciado: "O diagnóstico em segurança pública serve apenas para registrar ocorrências passadas, não tendo utilidade para a alocação de recursos nem para a avaliação de eficácia das ações.", gabarito: "errado", explicacao: "Errado. O diagnóstico identifica problemas e necessidades, orienta a alocação de recursos, embasa planos/programas/projetos e permite avaliar a eficácia." },
  { modulo: "8", tipo: "dissertativa", enunciado: "Conceitue Estado-Maior e diferencie plano, programa e projeto no contexto do Trabalho de Comando.", modelo: { estrutura: "Conceito de EM → plano → programa → projeto → conclusão.", criterios: ["Conceituar o EM como órgão de assessoramento/planejamento/coordenação", "Diferenciar plano, programa e projeto pelo nível de agregação/escopo", "Relacionar os instrumentos ao Trabalho de Comando"], resposta: "O Estado-Maior é o órgão de assessoramento, planejamento e coordenação que auxilia o comandante, atuando mediante diretrizes por ele baixadas e liberando-o do trato de detalhes. No planejamento do Trabalho de Comando, três instrumentos se complementam, diferenciando-se pelo nível de agregação de decisões e detalhamento: o plano é o documento mais amplo, que reúne objetivos, estratégias, diretrizes e políticas; o programa é um conjunto de projetos com o mesmo objetivo, geridos de forma coordenada para ampliar uma política pública; e o projeto é o instrumento técnico-administrativo de ação específica, com início e fim definidos. Esses documentos, apoiados em um bom diagnóstico, orientam a atuação do Estado-Maior na construção do Trabalho de Comando." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tq = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`TCEM (lote 2): questoes ${c} criadas/${u} atualizadas (total ${tq}).`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
