import "dotenv/config"
import { createHash } from "crypto"
import { PrismaClient } from "../lib/generated/prisma/client"
import { PrismaNeon } from "@prisma/adapter-neon"
import { neonConfig } from "@neondatabase/serverless"
import ws from "ws"

neonConfig.webSocketConstructor = ws
const prisma = new PrismaClient({ adapter: new PrismaNeon({ connectionString: process.env.DATABASE_URL! }) })
const MAT = "TCEM"

type Alt = { id: string; texto: string }
type Q =
  | { modulo: string; tipo: "certo_errado"; enunciado: string; gabarito: "certo" | "errado"; explicacao: string }
  | { modulo: string; tipo: "multipla"; enunciado: string; alternativas: Alt[]; gabarito: string; explicacao: string }
  | { modulo: string; tipo: "dissertativa"; enunciado: string; modelo: { estrutura: string; criterios: string[]; resposta: string } }
const A = (...t: string[]): Alt[] => t.map((texto, i) => ({ id: "ABCDE"[i], texto }))

const QS: Q[] = [
  // ── Módulo 9 — Documentos de Estado-Maior ──
  { modulo: "9", tipo: "multipla", enunciado: "As Instruções Provisórias que conceituam os Documentos de Estado-Maior na PMPE foram aprovadas pela:", alternativas: A("Portaria do Comando-Geral nº 582, de 14 de dezembro de 1981", "Lei nº 11.328, de 11 de janeiro de 1996", "Decreto nº 17.589, de 16 de junho de 1994", "Lei nº 11.817, de 24 de julho de 2000", "Portaria GM-MD nº 1.143, de 2022"), gabarito: "A", explicacao: "A Portaria CG nº 582/1981 aprovou as Instruções Provisórias de Estado-Maior (conceituação dos documentos de EM)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "Os documentos de Estado-Maior são, em geral, escritos com concisão e clareza, obedecendo a mementos preestabelecidos, e destinam-se a viabilizar as atividades da Corporação.", gabarito: "certo", explicacao: "Correto. É a definição geral dos documentos de EM nas Instruções Provisórias." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O Plano baseia-se em hipóteses, enquanto a Ordem baseia-se em fatos.", gabarito: "certo", explicacao: "Correto. Distinção clássica: o plano dá forma ao planejamento (hipóteses); a ordem determina a execução de um serviço (fatos)." },
  { modulo: "9", tipo: "multipla", enunciado: "O documento de Estado-Maior em que se aprecia, isolada ou conjuntamente, problema complexo e controvertido de natureza administrativa, ensejando parecer conclusivo sobre a solução a ser adotada, é o:", alternativas: A("Estudo de Estado-Maior", "Estudo", "Diretriz", "Ordem de Serviço", "Nota de Serviço"), gabarito: "A", explicacao: "O Estudo de EM trata de problemas complexos/controvertidos, com parecer conclusivo; o Estudo simples trata de problemas administrativos simples." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior que estabelece orientação, por meio de normas objetivas, para a realização de um trabalho administrativo, operacional ou de planejamento:", alternativas: A("Diretriz", "Ordem", "Plano", "Relatório", "Anexo"), gabarito: "A", explicacao: "A Diretriz estabelece orientação por normas; subdivide-se em de Planejamento, de Operações e Administrativa." },
  { modulo: "9", tipo: "multipla", enunciado: "A Diretriz que estabelece orientação para a elaboração de estudos, planos, ordens e notas de qualquer natureza é a Diretriz de:", alternativas: A("Planejamento", "Operações", "Administração", "Serviço", "Segurança"), gabarito: "A", explicacao: "A Diretriz de Planejamento orienta o planejamento (estudos, planos, ordens e notas)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O Plano de Operações é o documento de EM que contém o esquema imaginado por um comandante para a execução, com êxito, de uma missão operacional, baseando-se normalmente em estudos de situação realizados pelas seções de EM.", gabarito: "certo", explicacao: "Correto. O Plano de Operações apoia-se nos estudos de situação das seções do EM." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior que fornece às unidades subordinadas informações antecipadas de uma ação prevista, proporcionando-lhes mais tempo para os preparativos:", alternativas: A("Ordem Preparatória", "Ordem Fragmentada", "Ordem de Serviço", "Nota de Instrução", "Relatório de Situação"), gabarito: "A", explicacao: "A Ordem Preparatória antecipa informações de uma ação prevista, dando tempo para os preparativos." },
  { modulo: "9", tipo: "multipla", enunciado: "A Ordem de Operação caracteriza-se por:", alternativas: A("determinar a realização de missão operacional de envergadura, envolvendo uma ou mais OME, definindo a SITUAÇÃO e a MISSÃO", "regular cerimônias e solenidades", "criar ou alterar rotinas e a organização da PM", "complementar uma ordem já expedida com dados que faltavam", "prestar informações ao escalão superior"), gabarito: "A", explicacao: "A Ordem de Operação, expedida por Comandante-Geral/Grande Comando, determina missão operacional de envergadura, definindo situação, missão e pormenores da execução coordenada." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior que determina, sob a forma de procedimento, a realização de serviço que requeira emprego de elemento PM em caráter rotineiro, preventivo ou repressivo:", alternativas: A("Ordem de Serviço", "Ordem de Operação", "Nota de Serviço", "Diretriz de Operações", "Plano Administrativo"), gabarito: "A", explicacao: "A Ordem de Serviço regula o serviço PM rotineiro/preventivo/repressivo, envolvendo uma ou mais unidades." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Ordem Fragmentada (ou Complementar) destina-se a proporcionar instruções básicas, específicas e oportunas, complementando uma ordem preparatória, de operações ou administrativa já expedida.", gabarito: "certo", explicacao: "Correto. A Ordem Fragmentada traz elementos que faltavam, omitindo o que já consta da ordem completa e não foi alterado." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior que regula o procedimento em casos de cerimônias, exibições, formaturas, desfiles e solenidades — eventos NÃO considerados operacionais:", alternativas: A("Nota de Serviço", "Ordem de Serviço", "Nota de Instrução", "Nota de Segurança", "Diretriz Administrativa"), gabarito: "A", explicacao: "A Nota de Serviço regula cerimônias e solenidades (eventos não operacionais). NÃO confundir com a Ordem de Serviço (serviço operacional rotineiro)." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Nota de Serviço e a Ordem de Serviço são documentos idênticos, ambos destinados a regular o policiamento ostensivo de rotina.", gabarito: "errado", explicacao: "Errado. A Nota de Serviço regula cerimônias/solenidades (não operacionais); a Ordem de Serviço regula o serviço PM operacional rotineiro." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior destinado a criar, modificar, adaptar ou ajustar a organização da PM (ou de OME) ou a estabelecer/alterar rotinas, preparado a partir do escalão Batalhão:", alternativas: A("Nota de Instrução (NI)", "Nota de Serviço", "Nota de Segurança", "Nota Complementar", "Relatório Periódico"), gabarito: "A", explicacao: "A Nota de Instrução cria/altera organização e rotinas; é preparada a partir do escalão Batalhão e pode consolidar-se em Normas Gerais de Ação." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento elaborado pelas 2ªs Seções de EM, destinado a regular missões de segurança reservada relativas a determinado evento:", alternativas: A("Nota de Segurança", "Nota de Serviço", "Nota de Instrução", "Ordem Preparatória", "Diretriz de Operações"), gabarito: "A", explicacao: "A Nota de Segurança é elaborada pela 2ª Seção (inteligência) para missões de segurança reservada." },
  { modulo: "9", tipo: "certo_errado", enunciado: "A Nota Complementar (NC) destina-se a suprir omissões ou retificar erros verificados em Nota de Serviço, Nota de Instrução ou Nota de Segurança anteriormente expedidas.", gabarito: "certo", explicacao: "Correto. A NC complementa a Nota a que se refere, sem repetir o que nela já consta, e assume a nomenclatura correspondente." },
  { modulo: "9", tipo: "multipla", enunciado: "Na cadeia de detalhamento dos documentos de Estado-Maior, a sequência correta — do que detalha o documento básico ao mais específico — é:", alternativas: A("Anexo → Apêndice → Adendo → Aditamento", "Aditamento → Adendo → Apêndice → Anexo", "Apêndice → Anexo → Aditamento → Adendo", "Anexo → Adendo → Apêndice → Aditamento", "Adendo → Apêndice → Anexo → Aditamento"), gabarito: "A", explicacao: "O Anexo detalha o documento básico; o Apêndice explicita o anexo; o Adendo complementa o apêndice; o Aditamento complementa o adendo." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O Estudo de Situação de Informações é elaborado pela 2ª Seção do EM (PM/2), apreciando a influência dos fatores de informações no cumprimento da missão operacional.", gabarito: "certo", explicacao: "Correto. Cada estudo de situação é feito pela seção correspondente; o de informações/contrainformações cabe à PM/2." },
  { modulo: "9", tipo: "multipla", enunciado: "O Estudo de Situação de Logística, que determina a influência dos fatores de apoio administrativo no cumprimento da missão, é elaborado pela:", alternativas: A("4ª Seção do EM (PM/4)", "1ª Seção do EM (PM/1)", "3ª Seção do EM (PM/3)", "5ª Seção do EM (PM/5)", "6ª Seção do EM (PM/6)"), gabarito: "A", explicacao: "O Estudo de Situação de Logística cabe à PM/4 (apoio administrativo/logística)." },
  { modulo: "9", tipo: "multipla", enunciado: "Documento de Estado-Maior por meio do qual os comandos subordinados prestam informações aos escalões superiores sobre a situação geral ou determinado assunto, difundindo informações:", alternativas: A("Relatório", "Diretriz", "Ordem", "Nota de Instrução", "Plano"), gabarito: "A", explicacao: "O Relatório difunde informações dos comandos subordinados aos superiores; deve restringir-se ao indispensável." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O Relatório de Situação de Operações difunde informações referentes à situação de uma operação em curso, abrangendo dados de um único momento (e não de todo um período).", gabarito: "certo", explicacao: "Correto. Por abranger um único momento, distingue-se do Relatório Periódico de Operações." },
  { modulo: "9", tipo: "multipla", enunciado: "Genericamente, a Ordem é o documento pelo qual uma autoridade determina a um subordinado a execução de um serviço. São tipos de ordem previstos, EXCETO:", alternativas: A("Ordem de Diagnóstico", "Ordem de Operação", "Ordem Administrativa", "Ordem Preparatória", "Ordem Fragmentária"), gabarito: "A", explicacao: "Os tipos previstos são: de Operação, Administrativa, Preparatória e Fragmentária. 'Ordem de Diagnóstico' não existe." },
  { modulo: "9", tipo: "certo_errado", enunciado: "O Estudo aprecia problemas administrativos simples e suas possíveis soluções, ao passo que o Estudo de Estado-Maior trata de problemas complexos e controvertidos com parecer conclusivo.", gabarito: "certo", explicacao: "Correto. É a diferença entre o Estudo (simples) e o Estudo de EM (complexo, com parecer conclusivo)." },
  { modulo: "9", tipo: "multipla", enunciado: "O Plano que contém o esquema imaginado por comandantes, diretores ou chefes de OME para o equacionamento e solução de problemas de natureza administrativa, podendo resultar de um Estudo de EM, é o:", alternativas: A("Plano Administrativo", "Plano de Operações", "Plano Estratégico", "Plano Diretor", "Plano de Carreira"), gabarito: "A", explicacao: "O Plano Administrativo soluciona problemas administrativos e pode decorrer de um Estudo de EM ou de um Estudo." },
  { modulo: "9", tipo: "dissertativa", enunciado: "Diferencie Diretriz, Plano e Ordem como documentos de Estado-Maior, destacando em que cada um se baseia.", modelo: { estrutura: "Diretriz → Plano → Ordem → distinção (normas/hipóteses/fatos).", criterios: ["Conceituar a Diretriz como orientação por normas", "Conceituar o Plano (hipóteses) e a Ordem (fatos)", "Destacar a base de cada documento"], resposta: "A Diretriz é o documento de Estado-Maior que estabelece orientação, por meio de normas objetivas, para a realização de um trabalho administrativo, operacional ou de planejamento, sendo baixada por comandantes, diretores ou chefes. O Plano dá forma ao trabalho de planejamento, viabilizando, mediante um esquema imaginado, a solução de problemas, e baseia-se em hipóteses (espécies: Plano de Operações e Plano Administrativo). A Ordem é o documento pelo qual uma autoridade determina a um subordinado a execução de um serviço e baseia-se em fatos (espécies: de Operação, Administrativa, Preparatória e Fragmentada). Em síntese: a diretriz orienta por normas, o plano apoia-se em hipóteses e a ordem, em fatos." } },
  { modulo: "9", tipo: "dissertativa", enunciado: "Conceitue Nota de Instrução, Nota de Serviço e Nota de Segurança como documentos de Estado-Maior.", modelo: { estrutura: "NI → Nota de Serviço → Nota de Segurança → conclusão.", criterios: ["Conceituar a Nota de Instrução (organização/rotinas, a partir do Batalhão)", "Conceituar a Nota de Serviço (cerimônias/solenidades não operacionais)", "Conceituar a Nota de Segurança (2ª Seção, segurança reservada)"], resposta: "A Nota de Instrução (NI) é o documento de Estado-Maior destinado a criar, modificar, adaptar ou ajustar a organização total ou parcial da PM ou de OME, bem como a estabelecer ou alterar rotinas operacionais e/ou administrativas, sendo preparada a partir do escalão Batalhão e podendo consolidar-se em Normas Gerais de Ação. A Nota de Serviço regula o procedimento em casos de cerimônias, exibições, formaturas, desfiles e solenidades, ou seja, eventos não considerados operacionais. A Nota de Segurança é elaborada pelas 2ªs Seções de EM e destina-se a regular missões de segurança reservada relativas a determinado evento. Eventuais omissões ou erros nessas notas são supridos por Nota Complementar." } },
]

async function main() {
  const disc = await prisma.disciplina.findUnique({ where: { sigla: MAT } })
  if (!disc) throw new Error(`Disciplina ${MAT} não existe.`)
  let c = 0, u = 0
  for (const q of QS) {
    const hash = createHash("sha1").update(`${MAT}|${q.modulo}|${q.enunciado}`).digest("hex")
    const base: any = { materia: MAT, modulo: q.modulo, tipo: q.tipo, enunciado: q.enunciado, hash }
    if (q.tipo === "multipla") { base.alternativas = q.alternativas; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else if (q.tipo === "certo_errado") { base.alternativas = []; base.gabarito = q.gabarito; base.explicacao = q.explicacao }
    else { base.alternativas = []; base.gabarito = ""; base.modelo = q.modelo }
    const exists = await prisma.questao.findUnique({ where: { hash } })
    await prisma.questao.upsert({ where: { hash }, update: base, create: base })
    exists ? u++ : c++
  }
  const tq = await prisma.questao.count({ where: { materia: MAT } })
  console.log(`TCEM (lote 3 - documentos): questoes ${c} criadas/${u} atualizadas (total ${tq}).`)
}
main().catch(e => { console.error(e); process.exit(1) }).finally(() => prisma.$disconnect())
